"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { ArrowLeft, Send } from "lucide-react";

const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:8006/api/v1";
type Contact={email:string;name:string};
async function wm(path:string,init?:RequestInit){return fetch(`${API}/webmail${path}`,{credentials:"include",...init,headers:{"Content-Type":"application/json",...(init?.headers||{})}})}
function addresses(value:string){return value.split(",").map(v=>v.trim()).filter(Boolean)}

export default function RichCompose(){
 const[contacts,setContacts]=useState<Contact[]>([]);const[signature,setSignature]=useState("");const[status,setStatus]=useState("");const[sending,setSending]=useState(false);
 useEffect(()=>{void(async()=>{const[c,s]=await Promise.all([wm("/contacts"),wm("/signature")]);if(c.ok)setContacts((await c.json()).items||[]);if(s.ok)setSignature((await s.json()).html||"")})()},[]);
 async function send(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setSending(true);setStatus("");const bodyText=String(f.get("body")||"");const bodyHtml=bodyText.split("\n").map(line=>`<p>${line.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")||"<br>"}</p>`).join("");const r=await wm("/send-rich",{method:"POST",body:JSON.stringify({to:addresses(String(f.get("to")||"")),cc:addresses(String(f.get("cc")||"")),bcc:addresses(String(f.get("bcc")||"")),subject:String(f.get("subject")||""),body_text:bodyText,body_html:bodyHtml,signature_html:signature})});setSending(false);setStatus(r.ok?"Message sent with sanitized HTML and signature.":((await r.json().catch(()=>({}))).detail||"Unable to send message."));if(r.ok)e.currentTarget.reset()}
 return <main className="min-h-screen bg-[#eef3f1] p-4 sm:p-8"><div className="mx-auto max-w-4xl"><div className="flex items-center justify-between"><Link href="/webmail" className="inline-flex items-center gap-2 text-xs font-black text-[#285b55]"><ArrowLeft size={14}/>Back to webmail</Link><Link href="/webmail/settings" className="text-xs font-black text-[#285b55]">Signature & contacts</Link></div><div className="mt-5 rounded-2xl border border-[#dce5e0] bg-white shadow-sm"><div className="border-b border-[#e4eae7] p-5"><h1 className="text-2xl font-black text-[#20372d]">Rich compose</h1><p className="mt-1 text-xs text-[#74857d]">Compose safely formatted mail with your saved signature and contact autocomplete.</p></div><form onSubmit={send} className="p-5"><datalist id="webmail-contacts">{contacts.map(c=><option key={c.email} value={c.email}>{c.name}</option>)}</datalist><div className="grid gap-3"><input list="webmail-contacts" name="to" required className="rounded-xl border border-[#dce5e0] p-3 text-sm" placeholder="To (comma-separated)"/><input list="webmail-contacts" name="cc" className="rounded-xl border border-[#dce5e0] p-3 text-sm" placeholder="Cc"/><input list="webmail-contacts" name="bcc" className="rounded-xl border border-[#dce5e0] p-3 text-sm" placeholder="Bcc"/><input name="subject" className="rounded-xl border border-[#dce5e0] p-3 text-sm font-bold" placeholder="Subject"/><textarea name="body" className="min-h-[360px] rounded-xl border border-[#dce5e0] p-4 text-sm leading-6" placeholder="Write your message..."/></div>{signature?<div className="mt-4 rounded-xl border border-dashed border-[#cfdad5] bg-[#f8faf9] p-3"><p className="mb-2 text-[9px] font-black uppercase tracking-[.12em] text-[#87968f]">Saved signature preview</p><div className="text-xs" dangerouslySetInnerHTML={{__html:signature}}/></div>:null}{status?<div className="mt-4 rounded-xl bg-[#f2f6f4] p-3 text-xs font-bold">{status}</div>:null}<div className="mt-4 flex justify-end"><button disabled={sending} className="inline-flex items-center gap-2 rounded-xl bg-[#123a38] px-5 py-3 text-xs font-black text-white disabled:opacity-50"><Send size={14}/>{sending?"Sending...":"Send message"}</button></div></form></div></div></main>
}
