"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import styles from "../../workforce/workforce.module.css";

type Row = Record<string, unknown>;
type Policy = { minimum_bids: number; low_value_bid_waiver: string | number; default_retention_pct: string | number; max_retention_pct: string | number; certificate_requires_document: boolean; performance_alert_score: string | number };
const API = "/api/v1";
function text(row: Row | null | undefined, key: string) { return String(row?.[key] ?? ""); }
function number(row: Row | null | undefined, key: string) { return Number(row?.[key] ?? 0); }
function cash(value: unknown) { return "M " + Number(value ?? 0).toLocaleString("en-LS", { minimumFractionDigits: 2, maximumFractionDigits: 2 }); }
async function api<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(API + path, { ...init, credentials: "include", headers: { "Content-Type": "application/json", ...(init?.headers ?? {}) }, cache: "no-store" });
  if (response.status === 401) { window.location.href = "/login?returnTo=" + encodeURIComponent("/subcontracts/control"); throw new Error("Session expired"); }
  const payload = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(typeof payload?.detail === "string" ? payload.detail : JSON.stringify(payload?.detail ?? payload));
  return payload as T;
}

export default function SubcontractControl() {
  const [packages, setPackages] = useState<Row[]>([]);
  const [contracts, setContracts] = useState<Row[]>([]);
  const [certificates, setCertificates] = useState<Row[]>([]);
  const [alerts, setAlerts] = useState<Row[]>([]);
  const [audit, setAudit] = useState<Row[]>([]);
  const [policy, setPolicy] = useState<Policy>({ minimum_bids: 3, low_value_bid_waiver: 5000, default_retention_pct: 5, max_retention_pct: 15, certificate_requires_document: true, performance_alert_score: 2.5 });
  const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [loading, setLoading] = useState(true);
  const refresh = useCallback(async () => {
    setLoading(true); setError("");
    try {
      const values = await Promise.all([api<Row[]>("/subcontracts/packages"), api<Row[]>("/subcontracts/contracts"), api<Row[]>("/subcontracts/certificates"), api<Row[]>("/subcontracts/dashboard/alerts"), api<Row[]>("/subcontracts/audit/events?limit=200"), api<Policy>("/subcontracts/policy/current")]);
      setPackages(values[0]); setContracts(values[1]); setCertificates(values[2]); setAlerts(values[3]); setAudit(values[4]); setPolicy(values[5]);
    } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not load Subcontract Control"); } finally { setLoading(false); }
  }, []);
  useEffect(() => { void refresh(); }, [refresh]);
  function success(message: string) { setNotice(message); setError(""); setTimeout(() => setNotice(""), 3500); void refresh(); }
  async function decision(id: number, outcome: "approve" | "reject") { try { await api("/subcontracts/approvals/" + id + "/decision", { method: "POST", body: JSON.stringify({ decision: outcome, comment: outcome === "approve" ? "Approved in Subcontract Control" : "Rejected in Subcontract Control" }) }); success("Subcontract approval " + outcome + "d."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Approval failed"); } }
  async function savePolicy(event: FormEvent) { event.preventDefault(); try { await api("/subcontracts/policy/current", { method: "PUT", body: JSON.stringify({ minimum_bids: Number(policy.minimum_bids), low_value_bid_waiver: Number(policy.low_value_bid_waiver), default_retention_pct: Number(policy.default_retention_pct), max_retention_pct: Number(policy.max_retention_pct), certificate_requires_document: policy.certificate_requires_document, performance_alert_score: Number(policy.performance_alert_score) }) }); success("Subcontract governance policy saved."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not save policy"); } }
  if (loading) return <main className={styles.page}><div className={styles.loading}><strong>Loading Subcontract Control…</strong></div></main>;
  const awards = packages.filter(row => text(row, "status") === "award_submitted" && number(row, "award_approval_request_id") > 0);
  const contractQueue = contracts.filter(row => text(row, "status") === "submitted" && number(row, "approval_request_id") > 0);
  const certificateQueue = certificates.filter(row => text(row, "status") === "submitted" && number(row, "approval_request_id") > 0);
  return <main className={styles.page}><header className={styles.header}><div className={styles.brand}><div className={styles.brandMark}>BT</div><div><small>Phase 9 Governance</small><h1>Subcontract Control</h1><p>Awards · contracts · certificates · retention · commercial audit.</p></div></div><div className={styles.headerActions}><Link className={styles.link} href="/subcontracts">Subcontract Management</Link><Link className={styles.link} href="/projects">Projects</Link></div></header><div className={styles.shell}>{error && <div className={styles.error}>{error}</div>}{notice && <div className={styles.notice}>{notice}</div>}
    <section className={styles.metrics}><Metric label="Awards" value={awards.length} note="awaiting approval"/><Metric label="Contracts" value={contractQueue.length} note="awaiting approval"/><Metric label="Certificates" value={certificateQueue.length} note="awaiting approval"/><Metric label="Alerts" value={alerts.length} note="commercial follow-up"/></section>
    <section className={styles.grid2}><Queue title="Award approval queue" description="An evaluated, invited active subcontractor must be approved before contract drafting." rows={awards} reference="package_number" amount="budget_amount" onDecision={decision}/><Queue title="Contract approval queue" description="Authorise only controlled contract documents linked to an approved award." rows={contractQueue} reference="contract_number" amount="original_contract_sum" onDecision={decision}/></section>
    <section className={styles.panel}><div className={styles.panelHead}><div><h3>Certificate approval queue</h3><p>Certificate approval freezes certified gross, retention and net payable before any payment evidence is accepted.</p></div></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Certificate</th><th>Period end</th><th>Gross</th><th>Retention</th><th>Net payable</th><th>Action</th></tr></thead><tbody>{certificateQueue.map(row => <tr key={String(row.id)}><td>{text(row, "certificate_number")}</td><td>{text(row, "period_end")}</td><td>{cash(row.gross_value)}</td><td>{cash(row.retention_deduction)}</td><td>{cash(row.net_payable)}</td><td><Actions requestId={number(row, "approval_request_id")} onDecision={decision}/></td></tr>)}</tbody></table></div></section>
    <section className={styles.grid2}><form className={styles.panel} onSubmit={savePolicy}><div className={styles.panelHead}><div><h3>Subcontract governance policy</h3><p>Controls bid competition, retention limits, measurement evidence and performance follow-up.</p></div></div><div className={styles.form}><label>Minimum bids<input type="number" min="1" max="10" value={policy.minimum_bids} onChange={event => setPolicy({ ...policy, minimum_bids: Number(event.target.value) })}/></label><label>Low-value waiver M<input type="number" min="0" step=".01" value={String(policy.low_value_bid_waiver)} onChange={event => setPolicy({ ...policy, low_value_bid_waiver: event.target.value })}/></label><label>Default retention %<input type="number" min="0" max="100" step=".001" value={String(policy.default_retention_pct)} onChange={event => setPolicy({ ...policy, default_retention_pct: event.target.value })}/></label><label>Maximum retention %<input type="number" min="0" max="100" step=".001" value={String(policy.max_retention_pct)} onChange={event => setPolicy({ ...policy, max_retention_pct: event.target.value })}/></label><label>Certificate evidence<select value={policy.certificate_requires_document ? "yes" : "no"} onChange={event => setPolicy({ ...policy, certificate_requires_document: event.target.value === "yes" })}><option value="yes">Required</option><option value="no">Optional</option></select></label><label>Performance alert score<input type="number" min="0" max="5" step=".01" value={String(policy.performance_alert_score)} onChange={event => setPolicy({ ...policy, performance_alert_score: event.target.value })}/></label><div className={styles.formActions}><button className={styles.button} type="submit">Save policy</button></div></div></form>
      <div className={styles.panel}><div className={styles.panelHead}><div><h3>Commercial alerts &amp; performance watch</h3><p>BuildTrack never invents tender returns, completion claims, measurements, tax or bank payments.</p></div></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Severity</th><th>Type</th><th>Reference</th><th>Message</th></tr></thead><tbody>{alerts.map((row, index) => <tr key={String(row.reference ?? index)}><td>{text(row, "severity")}</td><td>{text(row, "type")}</td><td>{text(row, "reference")}</td><td>{text(row, "message")}</td></tr>)}</tbody></table></div></div></section>
    <section className={styles.panel}><div className={styles.panelHead}><div><h3>Immutable commercial audit</h3><p>Subcontract package, bid, award, contract, certificate and payment activity is retained for accountable review.</p></div><div className={styles.toolbar}><a className={styles.button} href="/api/v1/subcontracts/exports/contracts.csv">Contract CSV</a><a className={styles.button} href="/api/v1/subcontracts/exports/certificates.csv">Certificate CSV</a></div></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Time</th><th>Actor</th><th>Action</th><th>Entity</th></tr></thead><tbody>{audit.slice(0, 100).map(row => <tr key={String(row.id)}><td>{text(row, "occurred_at")}</td><td>{text(row, "actor")}</td><td>{text(row, "action")}</td><td>{text(row, "entity_type")} #{text(row, "entity_id")}</td></tr>)}</tbody></table></div></section>
  </div></main>;
}
function Metric({ label, value, note }: { label: string; value: number; note: string }) { return <div className={styles.metric}><small>{label}</small><strong>{value}</strong><span>{note}</span></div>; }
function Actions({ requestId, onDecision }: { requestId: number; onDecision: (id: number, outcome: "approve" | "reject") => Promise<void> }) { return <div className={styles.actions}><button className={styles.mini} onClick={() => void onDecision(requestId, "approve")}>Approve</button><button className={styles.mini} onClick={() => void onDecision(requestId, "reject")}>Reject</button></div>; }
function Queue({ title, description, rows, reference, amount, onDecision }: { title: string; description: string; rows: Row[]; reference: string; amount: string; onDecision: (id: number, outcome: "approve" | "reject") => Promise<void> }) { return <div className={styles.panel}><div className={styles.panelHead}><div><h3>{title}</h3><p>{description}</p></div></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Reference</th><th>Value</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.map(row => <tr key={String(row.id)}><td>{text(row, reference)}</td><td>{cash(row[amount])}</td><td>{text(row, "status")}</td><td><Actions requestId={number(row, reference === "package_number" ? "award_approval_request_id" : "approval_request_id")} onDecision={onDecision}/></td></tr>)}</tbody></table></div></div>; }
