"use client";

import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, Download, FileCheck2, Mail, SendHorizontal, ShieldCheck, XCircle } from "lucide-react";
import { ControlShell } from "@/components/control-shell";
import { financeRoleRank, useFinanceAccess } from "../_components/use-finance-access";

const API = process.env.NEXT_PUBLIC_API_URL || "/api/v1";
const money = (minor = 0) => `M ${(minor / 100).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
async function api(path: string, init?: RequestInit) { return fetch(`${API}${path}`, { credentials: "include", ...init, headers: { "Content-Type": "application/json", ...(init?.headers || {}) } }); }

type Settings = { approval_enabled: boolean; invoice_approval_threshold_minor: number };
type InvoiceMini = { id: string; invoice_number: string; client_name: string; recipient_email: string; total_minor: number; status: string; due_date: string };
type Approval = { id: string; status: string; request_note: string; decision_note: string; requested_at: string; invoice?: InvoiceMini };
type Candidate = { invoice: InvoiceMini; approval: Approval | null };
type Client = { id: string; name: string; email: string };
type Behaviour = { client_id: string; client_name: string; invoice_count: number; settled_invoice_count: number; on_time_invoice_count: number; late_invoice_count: number; on_time_percent: number | null; average_days_to_pay: number | null; open_overdue_invoice_count: number; max_days_overdue: number; current_exposure_minor: number };

function today() { return new Date().toISOString().slice(0, 10); }

export default function FinanceGovernancePage() {
  const { email, allowed, role, loading: accessLoading } = useFinanceAccess();
  const canApprove = financeRoleRank(role) >= 3;
  const canAdmin = financeRoleRank(role) >= 4;
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const [settings, setSettings] = useState<Settings>({ approval_enabled: true, invoice_approval_threshold_minor: 500000 });
  const [threshold, setThreshold] = useState("5000"); const [approvals, setApprovals] = useState<Approval[]>([]); const [candidates, setCandidates] = useState<Candidate[]>([]); const [clients, setClients] = useState<Client[]>([]); const [behaviour, setBehaviour] = useState<Behaviour[]>([]);
  const [asOf, setAsOf] = useState(today()); const [onlyBalance, setOnlyBalance] = useState(true); const [selectedClients, setSelectedClients] = useState<Record<string, boolean>>({});

  const selectedIds = useMemo(() => Object.entries(selectedClients).filter(([, checked]) => checked).map(([id]) => id), [selectedClients]);
  const pending = useMemo(() => approvals.filter((row) => row.status === "pending"), [approvals]);

  async function load() {
    const [s, a, cand, c] = await Promise.all([api("/finance/governance/settings"), api("/finance/governance/approvals"), api("/finance/governance/approval-candidates"), api("/finance/clients?active=true")]);
    if (s.ok) { const body = await s.json(); setSettings(body); setThreshold(String((body.invoice_approval_threshold_minor || 0) / 100)); }
    if (a.ok) setApprovals((await a.json()).items || []); if (cand.ok) setCandidates((await cand.json()).items || []);
    if (c.ok) { const list = (await c.json()).items || []; setClients(list); const metrics = await Promise.all(list.slice(0, 100).map(async (client: Client) => { const r = await api(`/finance/governance/clients/${client.id}/behaviour`); return r.ok ? await r.json() : null; })); setBehaviour(metrics.filter(Boolean)); }
  }

  useEffect(() => { if (allowed && canApprove) void load(); }, [allowed, canApprove]);

  async function saveSettings() { if (!canAdmin) return setMessage("Finance Admin access is required to change approval policy."); setBusy(true); setMessage(""); try { const r = await api("/finance/governance/settings", { method: "PUT", body: JSON.stringify({ approval_enabled: settings.approval_enabled, invoice_approval_threshold_minor: Math.max(0, Math.round(Number(threshold || 0) * 100)) }) }); const data = await r.json().catch(() => ({})); if (!r.ok) throw new Error(String(data.detail || "Unable to save governance settings")); setSettings(data); setMessage("Approval controls updated."); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : "Unable to save governance settings"); } finally { setBusy(false); } }

  async function requestApproval(invoice: InvoiceMini) { const note = window.prompt(`Request approval for ${invoice.invoice_number}. Note (optional):`, "") ?? ""; setBusy(true); setMessage(""); try { const r = await api(`/finance/governance/invoices/${invoice.id}/approval`, { method: "POST", body: JSON.stringify({ note }) }); const data = await r.json().catch(() => ({})); if (!r.ok) throw new Error(String(data.detail || "Unable to request approval")); setMessage(`${invoice.invoice_number} added to the approval queue.`); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : "Unable to request approval"); } finally { setBusy(false); } }

  async function decide(id: string, approved: boolean) { const note = window.prompt(approved ? "Approval note (optional)" : "Reason for rejection", "") ?? ""; if (!approved && !note.trim()) return; setBusy(true); setMessage(""); try { const r = await api(`/finance/governance/approvals/${id}/decision`, { method: "POST", body: JSON.stringify({ approved, note }) }); const data = await r.json().catch(() => ({})); if (!r.ok) throw new Error(String(data.detail || "Unable to record decision")); setMessage(approved ? "Invoice approved." : "Invoice rejected."); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : "Unable to record decision"); } finally { setBusy(false); } }

  function downloadPack() { window.location.href = `${API}/finance/governance/statement-pack.zip?as_of=${asOf}&only_with_balance=${onlyBalance ? "true" : "false"}`; }

  async function sendStatements() { const countLabel = selectedIds.length ? `${selectedIds.length} selected client(s)` : "all active clients"; if (!window.confirm(`Send statements to ${countLabel}${onlyBalance ? " with outstanding balances" : ""}?`)) return; setBusy(true); setMessage(""); try { const r = await api("/finance/governance/statements/send", { method: "POST", body: JSON.stringify({ client_ids: selectedIds.length ? selectedIds : null, as_of: asOf, only_with_balance: onlyBalance }) }); const data = await r.json().catch(() => ({})); if (!r.ok) throw new Error(String(data.detail || "Unable to send statements")); setMessage(`Statements: ${data.sent?.length || 0} sent, ${data.skipped?.length || 0} skipped, ${data.failed?.length || 0} failed.`); } catch (e) { setMessage(e instanceof Error ? e.message : "Unable to send statements"); } finally { setBusy(false); } }

  return <ControlShell title="Finance governance" subtitle="Approval thresholds, statement packs and factual client payment behaviour" userEmail={email}>
    {accessLoading ? <section className="surface-card p-6">Checking Finance access…</section> : !allowed || !canApprove ? <section className="surface-card p-6">Finance Approver access or higher is required.</section> : <div className="space-y-4 pb-24">
      {message ? <div className="surface-card px-4 py-3 text-xs font-bold">{message}</div> : null}

      <section className="surface-card p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><ShieldCheck size={18} /><h1 className="text-lg font-black">Invoice approval control</h1></div><p className="mt-1 max-w-2xl text-xs text-[var(--admin-muted)]">Invoices at or above the configured threshold cannot be emailed until approved.</p></div><label className="flex items-center gap-2 text-xs font-bold"><input type="checkbox" disabled={!canAdmin} checked={settings.approval_enabled} onChange={(e) => setSettings({ ...settings, approval_enabled: e.target.checked })} />Approval enforcement enabled</label></div><div className="mt-4 flex flex-wrap items-end gap-2"><label className="text-[10px] font-black uppercase">Approval threshold (M)<input className="input mt-1 w-48" disabled={!canAdmin} type="number" min="0" step="0.01" value={threshold} onChange={(e) => setThreshold(e.target.value)} /></label>{canAdmin ? <button disabled={busy} onClick={() => void saveSettings()} className="btn-primary">Save approval policy</button> : <span className="pb-2 text-[10px] text-[var(--admin-muted)]">Only Finance Admin can change policy.</span>}</div></section>

      <section className="surface-card overflow-hidden"><div className="border-b p-4"><h2 className="font-black">Invoices requiring approval</h2><p className="mt-1 text-xs text-[var(--admin-muted)]">Invoices above the threshold appear here before they can be sent.</p></div><div className="overflow-auto"><table className="w-full text-left text-xs"><thead><tr><th className="p-3">Invoice</th><th className="p-3">Client</th><th className="p-3 text-right">Amount</th><th className="p-3">Approval</th><th className="p-3 text-right">Action</th></tr></thead><tbody>{candidates.map((row) => <tr key={row.invoice.id} className="border-t"><td className="p-3 font-black">{row.invoice.invoice_number}</td><td className="p-3">{row.invoice.client_name}</td><td className="p-3 text-right font-black">{money(row.invoice.total_minor)}</td><td className="p-3 uppercase">{row.approval?.status || "not requested"}</td><td className="p-3 text-right">{!row.approval || row.approval.status === "rejected" ? <button disabled={busy} onClick={() => void requestApproval(row.invoice)} className="btn-secondary inline-flex items-center gap-1"><SendHorizontal size={13} />Request approval</button> : <span className="text-[10px] text-[var(--admin-muted)]">{row.approval.status}</span>}</td></tr>)}</tbody></table></div></section>

      <section className="surface-card overflow-hidden"><div className="border-b p-4"><div className="flex items-center gap-2"><FileCheck2 size={17} /><h2 className="font-black">Approval queue</h2></div><p className="mt-1 text-xs text-[var(--admin-muted)]">{pending.length} pending approval request(s).</p></div><div className="overflow-auto"><table className="w-full text-left text-xs"><thead><tr><th className="p-3">Invoice</th><th className="p-3">Client</th><th className="p-3 text-right">Amount</th><th className="p-3">Requested</th><th className="p-3">Status</th><th className="p-3 text-right">Actions</th></tr></thead><tbody>{approvals.map((row) => <tr key={row.id} className="border-t"><td className="p-3 font-black">{row.invoice?.invoice_number || "—"}</td><td className="p-3">{row.invoice?.client_name || "—"}</td><td className="p-3 text-right font-black">{money(row.invoice?.total_minor || 0)}</td><td className="p-3">{row.requested_at?.slice(0, 10) || "—"}</td><td className="p-3 uppercase">{row.status}</td><td className="p-3"><div className="flex justify-end gap-2">{row.status === "pending" ? <><button disabled={busy} onClick={() => void decide(row.id, true)} className="btn-secondary inline-flex items-center gap-1"><CheckCircle2 size={13} />Approve</button><button disabled={busy} onClick={() => void decide(row.id, false)} className="btn-secondary inline-flex items-center gap-1"><XCircle size={13} />Reject</button></> : <span className="text-[10px] text-[var(--admin-muted)]">Decision recorded</span>}</div></td></tr>)}</tbody></table></div></section>

      <section className="surface-card p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="font-black">Statement run</h2><p className="mt-1 text-xs text-[var(--admin-muted)]">Generate one ZIP pack or email branded PDF statements through the verified Finance sender.</p></div><div className="flex flex-wrap items-end gap-2"><label className="text-[10px] font-black uppercase">As at<input className="input mt-1" type="date" value={asOf} onChange={(e) => setAsOf(e.target.value)} /></label><label className="flex items-center gap-2 pb-2 text-xs font-bold"><input type="checkbox" checked={onlyBalance} onChange={(e) => setOnlyBalance(e.target.checked)} />Only clients with balances</label><button onClick={downloadPack} className="btn-secondary inline-flex items-center gap-2"><Download size={14} />Download ZIP pack</button><button disabled={busy} onClick={() => void sendStatements()} className="btn-primary inline-flex items-center gap-2"><Mail size={14} />Send statements</button></div></div><p className="mt-3 text-[10px] font-bold text-[var(--admin-muted)]">Select clients below to restrict the email run. With none selected, the run considers all active clients.</p></section>

      <section className="surface-card overflow-hidden"><div className="border-b p-4"><h2 className="font-black">Client payment behaviour</h2><p className="mt-1 text-xs text-[var(--admin-muted)]">Factual payment history only: average days to pay, on-time history, overdue count and current exposure. This is not a credit score.</p></div><div className="max-h-[520px] overflow-auto"><table className="w-full text-left text-xs"><thead className="sticky top-0 bg-white"><tr><th className="p-3">Select</th><th className="p-3">Client</th><th className="p-3 text-right">Invoices</th><th className="p-3 text-right">Avg days to pay</th><th className="p-3 text-right">On time</th><th className="p-3 text-right">Open overdue</th><th className="p-3 text-right">Exposure</th><th className="p-3">Statement</th></tr></thead><tbody>{behaviour.map((row) => <tr key={row.client_id} className="border-t"><td className="p-3"><input type="checkbox" checked={Boolean(selectedClients[row.client_id])} onChange={(e) => setSelectedClients({ ...selectedClients, [row.client_id]: e.target.checked })} /></td><td className="p-3 font-black">{row.client_name}</td><td className="p-3 text-right">{row.invoice_count}</td><td className="p-3 text-right">{row.average_days_to_pay == null ? "—" : row.average_days_to_pay}</td><td className="p-3 text-right">{row.on_time_percent == null ? "—" : `${row.on_time_percent}%`}</td><td className="p-3 text-right">{row.open_overdue_invoice_count}</td><td className="p-3 text-right font-black">{money(row.current_exposure_minor)}</td><td className="p-3"><a className="font-black underline" href={`${API}/finance/governance/clients/${row.client_id}/statement.pdf?as_of=${asOf}`}>PDF</a></td></tr>)}</tbody></table></div></section>
    </div>}
  </ControlShell>;
}
