"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import styles from "../workforce/workforce.module.css";

type Row = Record<string, unknown>;
type Catalog = { branches: Row[]; projects: Row[]; packages: Row[]; subcontractors: Row[]; documents: Row[]; permissions: string[] };
type Summary = { packages: number; packages_pending_award: number; contracts: number; contracts_pending: number; commitments: string; certified: string; payable: string };
type Tab = "dashboard" | "subcontractors" | "packages" | "bids" | "contracts" | "certificates" | "audit";
const API = "/api/v1";
const TABS: Array<[Tab, string]> = [["dashboard", "Dashboard"], ["subcontractors", "Subcontractors"], ["packages", "Packages"], ["bids", "Bids & award"], ["contracts", "Contracts"], ["certificates", "Certificates"], ["audit", "Audit"]];
function text(row: Row | null | undefined, key: string) { return String(row?.[key] ?? ""); }
function number(row: Row | null | undefined, key: string) { return Number(row?.[key] ?? 0); }
function list(value: unknown): Row[] { return Array.isArray(value) ? value as Row[] : []; }
function cash(value: unknown) { return "M " + Number(value ?? 0).toLocaleString("en-LS", { minimumFractionDigits: 2, maximumFractionDigits: 2 }); }
function today() { return new Date().toISOString().slice(0, 10); }
function daysFromNow(days: number) { const date = new Date(); date.setDate(date.getDate() + days); return date.toISOString().slice(0, 10); }
async function api<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(API + path, { ...init, credentials: "include", headers: { "Content-Type": "application/json", ...(init?.headers ?? {}) }, cache: "no-store" });
  if (response.status === 401) { window.location.href = "/login?returnTo=" + encodeURIComponent("/subcontracts"); throw new Error("Session expired"); }
  const payload = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(typeof payload?.detail === "string" ? payload.detail : JSON.stringify(payload?.detail ?? payload));
  return payload as T;
}
function Table({ data, columns }: { data: Row[]; columns: string[] }) {
  if (!data.length) return <div className={styles.empty}>No records yet.</div>;
  return <div className={styles.tableWrap}><table className={styles.table}><thead><tr>{columns.map(column => <th key={column}>{column.replaceAll("_", " ")}</th>)}</tr></thead><tbody>{data.map((row, index) => <tr key={String(row.id ?? index)}>{columns.map(column => <td key={column}>{/(amount|value|sum|payable|certified|paid|retention)/.test(column) ? cash(row[column]) : String(row[column] ?? "")}</td>)}</tr>)}</tbody></table></div>;
}

export default function SubcontractsPage() {
  const [initialized, setInitialized] = useState<boolean | null>(null);
  const [catalog, setCatalog] = useState<Catalog>({ branches: [], projects: [], packages: [], subcontractors: [], documents: [], permissions: [] });
  const [summary, setSummary] = useState<Summary | null>(null);
  const [alerts, setAlerts] = useState<Row[]>([]);
  const [packages, setPackages] = useState<Row[]>([]);
  const [contracts, setContracts] = useState<Row[]>([]);
  const [certificates, setCertificates] = useState<Row[]>([]);
  const [audit, setAudit] = useState<Row[]>([]);
  const [tab, setTab] = useState<Tab>("dashboard");
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [loading, setLoading] = useState(true);
  const [packageId, setPackageId] = useState("");
  const [packageDetail, setPackageDetail] = useState<Row | null>(null);
  const [contractId, setContractId] = useState("");
  const [contractDetail, setContractDetail] = useState<Row | null>(null);
  const [vendor, setVendor] = useState({ legal_name: "", contact_name: "", phone: "", trade_categories: "civil works", status: "pending" });
  const [pkg, setPkg] = useState({ branch_id: "", project_id: "", package_code: "", title: "", trade_category: "", planned_start_date: today(), planned_completion_date: daysFromNow(30), budget_amount: "0" });
  const [scope, setScope] = useState({ description: "", quantity: "1", unit: "item", budget_rate: "0" });
  const [invite, setInvite] = useState({ subcontractor_id: "", due_date: daysFromNow(14) });
  const [bid, setBid] = useState({ subcontractor_id: "", bid_reference: "", bid_date: today(), valid_until: daysFromNow(30), tax_amount: "0" });
  const [awardDocumentId, setAwardDocumentId] = useState("");
  const [contract, setContract] = useState({ package_id: "", title: "", start_date: today(), completion_date: daysFromNow(60), retention_pct: "5", contract_document_id: "" });
  const [certificate, setCertificate] = useState({ certificate_type: "interim", period_start: today(), period_end: today(), gross_value: "0", evidence_document_id: "" });
  const permissions = useMemo(() => new Set(catalog.permissions), [catalog.permissions]);
  const can = (permission: string) => permissions.has(permission);
  const refresh = useCallback(async () => {
    setLoading(true); setError("");
    try {
      const status = await api<{ initialized: boolean }>("/subcontracts/status");
      setInitialized(status.initialized);
      if (!status.initialized) return;
      const values = await Promise.all([
        api<Catalog>("/subcontracts/catalog"), api<Summary>("/subcontracts/dashboard/summary"), api<Row[]>("/subcontracts/dashboard/alerts"),
        api<Row[]>("/subcontracts/packages"), api<Row[]>("/subcontracts/contracts"), api<Row[]>("/subcontracts/certificates"), api<Row[]>("/subcontracts/audit/events?limit=200"),
      ]);
      setCatalog(values[0]); setSummary(values[1]); setAlerts(values[2]); setPackages(values[3]); setContracts(values[4]); setCertificates(values[5]); setAudit(values[6]);
    } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not load Subcontract Management"); } finally { setLoading(false); }
  }, []);
  useEffect(() => { void refresh(); }, [refresh]);
  function success(message: string) { setNotice(message); setError(""); setTimeout(() => setNotice(""), 3500); void refresh(); }
  async function submit(path: string, body: unknown, message: string) { try { await api(path, { method: "POST", body: JSON.stringify(body) }); success(message); } catch (reason) { setError(reason instanceof Error ? reason.message : "Operation failed"); } }
  async function selectPackage(id: string) { setPackageId(id); try { setPackageDetail(id ? await api<Row>("/subcontracts/packages/" + id) : null); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not load package"); } }
  async function selectContract(id: string) { setContractId(id); try { setContractDetail(id ? await api<Row>("/subcontracts/contracts/" + id) : null); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not load contract"); } }
  async function initialise() { await submit("/subcontracts/bootstrap", {}, "Phase 9 Subcontract Management initialised."); setInitialized(true); }
  async function addVendor(event: FormEvent) { event.preventDefault(); await submit("/subcontracts/subcontractors", { ...vendor, contact_name: vendor.contact_name || null, phone: vendor.phone || null, trade_categories: vendor.trade_categories.split(",").map(value => value.trim()).filter(Boolean) }, "Subcontractor recorded."); }
  async function addPackage(event: FormEvent) { event.preventDefault(); await submit("/subcontracts/packages", { ...pkg, branch_id: Number(pkg.branch_id), project_id: Number(pkg.project_id), budget_amount: Number(pkg.budget_amount), trade_category: pkg.trade_category || null }, "Project subcontract package created."); }
  async function addScope(event: FormEvent) { event.preventDefault(); if (!packageId) return; await submit("/subcontracts/packages/" + packageId + "/lines", { ...scope, quantity: Number(scope.quantity), budget_rate: Number(scope.budget_rate) }, "Scope line added."); await selectPackage(packageId); }
  async function addInvitation(event: FormEvent) { event.preventDefault(); if (!packageId) return; await submit("/subcontracts/packages/" + packageId + "/invite", { subcontractor_id: Number(invite.subcontractor_id), due_date: invite.due_date || null }, "Controlled subcontractor invitation created."); await selectPackage(packageId); }
  async function addBid(event: FormEvent) {
    event.preventDefault(); if (!packageId || !packageDetail) return;
    const lines = list(packageDetail.lines).map(row => ({ package_line_id: number(row, "id"), quantity: Number(row.quantity ?? 0), unit_rate: Number(row.budget_rate ?? 0), notes: null }));
    await submit("/subcontracts/packages/" + packageId + "/bids", { ...bid, subcontractor_id: Number(bid.subcontractor_id), tax_amount: Number(bid.tax_amount), lines }, "Subcontract bid recorded against every scope line.");
    await selectPackage(packageId);
  }
  async function evaluateBid(bidId: number) { await submit("/subcontracts/bids/" + bidId + "/evaluation", { technical_score: 80, commercial_score: 80, hse_score: 80, programme_score: 80, recommendation: "recommended", notes: "Detailed evaluation evidence to be recorded." }, "Bid evaluation saved."); if (packageId) await selectPackage(packageId); }
  async function awardBid(bidId: number) { if (!packageId) return; await submit("/subcontracts/packages/" + packageId + "/award", { bid_id: bidId, award_document_id: awardDocumentId ? Number(awardDocumentId) : null }, "Award submitted for Branch and Head Office approval."); await selectPackage(packageId); }
  async function addContract(event: FormEvent) { event.preventDefault(); await submit("/subcontracts/contracts", { ...contract, package_id: Number(contract.package_id), retention_pct: Number(contract.retention_pct), contract_document_id: contract.contract_document_id ? Number(contract.contract_document_id) : null }, "Subcontract contract drafted."); }
  async function submitContract() { if (contractId) { await submit("/subcontracts/contracts/" + contractId + "/submit", {}, "Contract submitted for maker/checker approval."); await selectContract(contractId); } }
  async function addCertificate(event: FormEvent) { event.preventDefault(); if (!contractId) return; await submit("/subcontracts/contracts/" + contractId + "/certificates", { ...certificate, gross_value: Number(certificate.gross_value), evidence_document_id: certificate.evidence_document_id ? Number(certificate.evidence_document_id) : null }, "Work certificate prepared."); await selectContract(contractId); }
  async function submitCertificate(certificateId: number) { await submit("/subcontracts/certificates/" + certificateId + "/submit", {}, "Certificate submitted for maker/checker approval."); }
  if (loading && initialized === null) return <main className={styles.page}><div className={styles.loading}><strong>Loading Subcontract Management…</strong></div></main>;
  if (initialized === false) return <main className={styles.page}><Header/><div className={styles.shell}><section className={styles.initialise}><span className={styles.phase}>Phase 9 · Subcontract Management</span><h2>Control subcontract packages from bid to retention.</h2><p>Subcontractors, scope, bids, contracts, certificates, payment evidence, retention and performance are held in the shared BuildTrack control plane.</p>{error && <div className={styles.error}>{error}</div>}<button className={styles.button} onClick={() => void initialise()}>Initialise Phase 9</button></section></div></main>;
  const bids = list(packageDetail?.bids); const evaluations = new Set(list(packageDetail?.evaluations).map(row => number(row, "bid_id")));
  return <main className={styles.page}><Header/><div className={styles.shell}>{error && <div className={styles.error}>{error}</div>}{notice && <div className={styles.notice}>{notice}</div>}
    <div className={styles.tabs}>{TABS.map(([id, label]) => <button key={id} className={tab === id ? styles.active : ""} onClick={() => setTab(id)}>{label}</button>)}</div>
    {summary && <section className={styles.metrics}><Metric label="Packages" value={summary.packages} note={summary.packages_pending_award + " awaiting award"}/><Metric label="Contracts" value={summary.contracts} note={summary.contracts_pending + " in approval"}/><Metric label="Commitments" value={cash(summary.commitments)} note="active & submitted"/><Metric label="Certified" value={cash(summary.certified)} note="approved work"/><Metric label="Payable" value={cash(summary.payable)} note="approved balance"/></section>}
    {tab === "dashboard" && <><section className={styles.hero}><div className={styles.heroCard}><span className={styles.phase}>Phase 9 · Subcontract Management</span><h2>From real trade scope to controlled payment.</h2><p>Bid evaluation, contract evidence, certified work and retention are linked to the right Nthane Brothers project, branch and site.</p></div><div className={styles.heroCard}><small>Commercial alerts</small><h2>{alerts.length}</h2><p>bid dates · contract completion · performance</p></div></section><section className={styles.panel}><div className={styles.panelHead}><div><h3>Commercial alerts</h3><p>Resolve deadlines, completion and performance actions.</p></div><Link className={styles.button} href="/subcontracts/control">Open Subcontract Control</Link></div><Table data={alerts} columns={["severity", "type", "reference", "message"]}/></section></>}
    {tab === "subcontractors" && <section className={styles.grid2}><div className={styles.panel}><h3>Subcontractor register</h3><Table data={catalog.subcontractors} columns={["subcontractor_code", "legal_name", "trade_categories", "safety_rating", "performance_rating", "status"]}/></div>{can("subcontracts.manage") && <form className={styles.panel} onSubmit={addVendor}><h3>Add subcontractor</h3><div className={styles.form}><label className={styles.wide}>Legal name<input required value={vendor.legal_name} onChange={event => setVendor({ ...vendor, legal_name: event.target.value })}/></label><label>Contact<input value={vendor.contact_name} onChange={event => setVendor({ ...vendor, contact_name: event.target.value })}/></label><label>Phone<input value={vendor.phone} onChange={event => setVendor({ ...vendor, phone: event.target.value })}/></label><label className={styles.wide}>Trade categories<input value={vendor.trade_categories} onChange={event => setVendor({ ...vendor, trade_categories: event.target.value })}/></label><label>Status<select value={vendor.status} onChange={event => setVendor({ ...vendor, status: event.target.value })}><option value="pending">Pending evidence</option><option value="active">Active / approved</option><option value="suspended">Suspended</option></select></label><div className={styles.formActions}><button className={styles.button} type="submit">Save subcontractor</button></div></div></form>}</section>}
    {tab === "packages" && <section className={styles.grid2}><form className={styles.panel} onSubmit={addPackage}><h3>Create project subcontract package</h3><div className={styles.form}><label>Branch<select required value={pkg.branch_id} onChange={event => setPkg({ ...pkg, branch_id: event.target.value, project_id: "" })}><option value="">Select</option>{catalog.branches.map(row => <option key={String(row.id)} value={String(row.id)}>{text(row, "name")}</option>)}</select></label><label>Project<select required value={pkg.project_id} onChange={event => setPkg({ ...pkg, project_id: event.target.value })}><option value="">Select</option>{catalog.projects.filter(row => String(row.branch_id) === pkg.branch_id).map(row => <option key={String(row.id)} value={String(row.id)}>{text(row, "project_number")} · {text(row, "name")}</option>)}</select></label><label>Package code<input required value={pkg.package_code} onChange={event => setPkg({ ...pkg, package_code: event.target.value.toUpperCase() })}/></label><label>Trade<input value={pkg.trade_category} onChange={event => setPkg({ ...pkg, trade_category: event.target.value })}/></label><label className={styles.wide}>Title<input required value={pkg.title} onChange={event => setPkg({ ...pkg, title: event.target.value })}/></label><label>Budget M<input required type="number" min="0" step=".01" value={pkg.budget_amount} onChange={event => setPkg({ ...pkg, budget_amount: event.target.value })}/></label><label>Completion<input required type="date" value={pkg.planned_completion_date} onChange={event => setPkg({ ...pkg, planned_completion_date: event.target.value })}/></label><div className={styles.formActions}><button className={styles.button} type="submit">Create package</button></div></div></form><div className={styles.panel}><h3>Project packages</h3><Table data={packages} columns={["package_number", "package_code", "title", "project_id", "budget_amount", "status"]}/></div></section>}
    {tab === "bids" && <section className={styles.grid2}><div className={styles.panel}><h3>Scope, invitations &amp; bids</h3><label>Select package<select value={packageId} onChange={event => void selectPackage(event.target.value)}><option value="">Select</option>{packages.map(row => <option key={String(row.id)} value={String(row.id)}>{text(row, "package_number")} · {text(row, "title")}</option>)}</select></label>{packageDetail && <><h4>Scope lines</h4><Table data={list(packageDetail.lines)} columns={["line_number", "description", "quantity", "unit", "budget_rate", "budget_amount"]}/><label>Award evaluation evidence<select value={awardDocumentId} onChange={event => setAwardDocumentId(event.target.value)}><option value="">Attach before contract approval</option>{catalog.documents.map(row => <option key={String(row.id)} value={String(row.id)}>{text(row, "title")}</option>)}</select></label><h4>Recorded bids</h4><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Bid</th><th>Vendor</th><th>Total</th><th>Status</th><th>Action</th></tr></thead><tbody>{bids.map(row => <tr key={String(row.id)}><td>{text(row, "bid_number")}</td><td>{text(row, "subcontractor_id")}</td><td>{cash(row.total_amount)}</td><td>{text(row, "status")}</td><td><div className={styles.actions}>{!evaluations.has(number(row, "id")) && <button className={styles.mini} onClick={() => void evaluateBid(number(row, "id"))}>Evaluate</button>}<button className={styles.mini} onClick={() => void awardBid(number(row, "id"))}>Submit award</button></div></td></tr>)}</tbody></table></div></>}</div>
      {packageId && can("subcontracts.manage") && <div className={styles.panel}><form onSubmit={addScope}><h3>Add scope line</h3><div className={styles.form}><label className={styles.wide}>Description<input required value={scope.description} onChange={event => setScope({ ...scope, description: event.target.value })}/></label><label>Quantity<input required type="number" min=".001" step=".001" value={scope.quantity} onChange={event => setScope({ ...scope, quantity: event.target.value })}/></label><label>Budget rate M<input required type="number" min="0" step=".0001" value={scope.budget_rate} onChange={event => setScope({ ...scope, budget_rate: event.target.value })}/></label><div className={styles.formActions}><button className={styles.button} type="submit">Add scope</button></div></div></form><form onSubmit={addInvitation}><h3>Invite approved subcontractor</h3><div className={styles.form}><label>Subcontractor<select required value={invite.subcontractor_id} onChange={event => setInvite({ ...invite, subcontractor_id: event.target.value })}><option value="">Select</option>{catalog.subcontractors.filter(row => text(row, "status") === "active").map(row => <option key={String(row.id)} value={String(row.id)}>{text(row, "legal_name")}</option>)}</select></label><label>Bid due<input type="date" value={invite.due_date} onChange={event => setInvite({ ...invite, due_date: event.target.value })}/></label><div className={styles.formActions}><button className={styles.button} type="submit">Create invitation</button></div></div></form><form onSubmit={addBid}><h3>Record every-line bid</h3><div className={styles.form}><label>Subcontractor<select required value={bid.subcontractor_id} onChange={event => setBid({ ...bid, subcontractor_id: event.target.value })}><option value="">Select</option>{catalog.subcontractors.filter(row => text(row, "status") === "active").map(row => <option key={String(row.id)} value={String(row.id)}>{text(row, "legal_name")}</option>)}</select></label><label>Bid reference<input required value={bid.bid_reference} onChange={event => setBid({ ...bid, bid_reference: event.target.value })}/></label><label>Tax M<input type="number" min="0" step=".01" value={bid.tax_amount} onChange={event => setBid({ ...bid, tax_amount: event.target.value })}/></label><div className={styles.formActions}><button className={styles.button} type="submit">Record bid</button></div></div></form></div>}</section>}
    {tab === "contracts" && <section className={styles.grid2}><form className={styles.panel} onSubmit={addContract}><h3>Draft awarded-package contract</h3><div className={styles.form}><label>Package<select required value={contract.package_id} onChange={event => setContract({ ...contract, package_id: event.target.value })}><option value="">Select awarded package</option>{packages.filter(row => text(row, "status") === "awarded").map(row => <option key={String(row.id)} value={String(row.id)}>{text(row, "package_number")} · {text(row, "title")}</option>)}</select></label><label>Retention %<input required type="number" min="0" max="100" step=".001" value={contract.retention_pct} onChange={event => setContract({ ...contract, retention_pct: event.target.value })}/></label><label className={styles.wide}>Title<input required value={contract.title} onChange={event => setContract({ ...contract, title: event.target.value })}/></label><label>Start<input required type="date" value={contract.start_date} onChange={event => setContract({ ...contract, start_date: event.target.value })}/></label><label>Completion<input required type="date" value={contract.completion_date} onChange={event => setContract({ ...contract, completion_date: event.target.value })}/></label><label className={styles.wide}>Controlled contract document<select value={contract.contract_document_id} onChange={event => setContract({ ...contract, contract_document_id: event.target.value })}><option value="">Required before approval</option>{catalog.documents.map(row => <option key={String(row.id)} value={String(row.id)}>{text(row, "title")}</option>)}</select></label><div className={styles.formActions}><button className={styles.button} type="submit">Draft contract</button></div></div></form><div className={styles.panel}><h3>Contracts &amp; position</h3><label>Open contract<select value={contractId} onChange={event => void selectContract(event.target.value)}><option value="">Select</option>{contracts.map(row => <option key={String(row.id)} value={String(row.id)}>{text(row, "contract_number")} · {text(row, "status")}</option>)}</select></label><Table data={contracts} columns={["contract_number", "project_id", "original_contract_sum", "certified_amount", "paid_amount", "retention_held", "status"]}/>{contractDetail && <button className={styles.button} onClick={() => void submitContract()}>Submit contract approval</button>}</div></section>}
    {tab === "certificates" && <section className={styles.grid2}><div className={styles.panel}><h3>Certified subcontract work</h3><Table data={certificates} columns={["certificate_number", "contract_number", "period_end", "gross_value", "retention_deduction", "net_payable", "status"]}/>{can("subcontracts.certify") && certificates.filter(row => ["draft", "rejected"].includes(text(row, "status"))).map(row => <button key={String(row.id)} className={styles.mini} onClick={() => void submitCertificate(number(row, "id"))}>Submit {text(row, "certificate_number")}</button>)}<a className={styles.button} href="/api/v1/subcontracts/exports/certificates.csv">Export certificates CSV</a></div>{contractId && <form className={styles.panel} onSubmit={addCertificate}><h3>Prepare work certificate</h3><div className={styles.form}><label>Type<select value={certificate.certificate_type} onChange={event => setCertificate({ ...certificate, certificate_type: event.target.value })}><option value="interim">Interim</option><option value="final">Final</option><option value="retention_release">Retention release</option></select></label><label>Gross certified M<input required type="number" min="0" step=".01" value={certificate.gross_value} onChange={event => setCertificate({ ...certificate, gross_value: event.target.value })}/></label><label>Period start<input required type="date" value={certificate.period_start} onChange={event => setCertificate({ ...certificate, period_start: event.target.value })}/></label><label>Period end<input required type="date" value={certificate.period_end} onChange={event => setCertificate({ ...certificate, period_end: event.target.value })}/></label><label className={styles.wide}>Measurement/certificate evidence<select required value={certificate.evidence_document_id} onChange={event => setCertificate({ ...certificate, evidence_document_id: event.target.value })}><option value="">Required by policy</option>{catalog.documents.map(row => <option key={String(row.id)} value={String(row.id)}>{text(row, "title")}</option>)}</select></label><div className={styles.formActions}><button className={styles.button} type="submit">Prepare certificate</button></div></div></form>}</section>}
    {tab === "audit" && <section className={styles.panel}><div className={styles.panelHead}><div><h3>Subcontract commercial audit</h3><p>Package, bid, award, contract, certificate and payment actions remain attributable to their actor and scope.</p></div><a className={styles.button} href="/api/v1/subcontracts/exports/contracts.csv">Export contracts CSV</a></div><Table data={audit} columns={["occurred_at", "actor", "action", "entity_type", "entity_id"]}/></section>}
  </div></main>;
}

function Metric({ label, value, note }: { label: string; value: string | number; note: string }) { return <div className={styles.metric}><small>{label}</small><strong>{value}</strong><span>{note}</span></div>; }
function Header() { return <header className={styles.header}><div className={styles.brand}><div className={styles.brandMark}>BT</div><div><small>Phase 9 Commercial Control</small><h1>Subcontract Management</h1><p>Subcontractors · packages · awards · contracts · certificates.</p></div></div><div className={styles.headerActions}><Link className={styles.link} href="/subcontracts/control">Subcontract Control</Link><Link className={styles.link} href="/projects">Projects</Link></div></header>; }
