"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import styles from "../workforce/workforce.module.css";

type Row = Record<string, unknown>;
const API = "/api/v1";
const text = (row: Row | null | undefined, key: string) => String(row?.[key] ?? "");
const amount = (value: unknown) => `M ${Number(value ?? 0).toLocaleString("en-LS", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
async function api<T>(path: string): Promise<T> { const response = await fetch(API + path, { credentials: "include", cache: "no-store" }); if (response.status === 401) { window.location.href = "/login?returnTo=" + encodeURIComponent("/intelligence"); throw new Error("Session expired"); } const body: unknown = await response.json().catch(() => ({})); if (!response.ok) { const detail = typeof body === "object" && body !== null ? (body as Row).detail : ""; throw new Error(typeof detail === "string" ? detail : "Could not load intelligence."); } return body as T; }
function Table({ title, children }: { title: string; children: React.ReactNode }) { return <section className={styles.panel}><div className={styles.panelHead}><h3>{title}</h3></div><div className={styles.tableWrap}>{children}</div></section>; }

export default function IntelligencePage() {
  const [dashboard, setDashboard] = useState<Row>({}), [branches, setBranches] = useState<Row[]>([]), [projects, setProjects] = useState<Row[]>([]), [exceptions, setExceptions] = useState<Row[]>([]), [error, setError] = useState(""), [loading, setLoading] = useState(true);
  const refresh = useCallback(async () => { setLoading(true); try { const [d, b, p, e] = await Promise.all([api<Row>("/intelligence/director-dashboard"), api<Row[]>("/intelligence/branches"), api<Row[]>("/intelligence/projects/health"), api<Row[]>("/intelligence/exceptions")]); setDashboard(d); setBranches(b); setProjects(p); setExceptions(e); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not load Management Intelligence. Initialise Phase 12 with an administrator first."); } finally { setLoading(false); } }, []);
  useEffect(() => { void refresh(); }, [refresh]);
  if (loading) return <main className={styles.page}><div className={styles.loading}><strong>Loading Management Intelligence…</strong></div></main>;
  const health = (dashboard.project_health && typeof dashboard.project_health === "object" ? dashboard.project_health as Row : {});
  const fleet = (dashboard.fleet && typeof dashboard.fleet === "object" ? dashboard.fleet as Row : {});
  const materials = (dashboard.materials && typeof dashboard.materials === "object" ? dashboard.materials as Row : {});
  const pipeline = (dashboard.tender_pipeline && typeof dashboard.tender_pipeline === "object" ? dashboard.tender_pipeline as Row : {});
  return <main className={styles.page}><header className={styles.header}><div className={styles.brand}><div className={styles.brandMark}>MI</div><div><small>BuildTrack · Phase 12</small><h1>Management Intelligence</h1><p>Director, branch, project, tender, fleet and materials information from controlled BuildTrack records.</p></div></div><div className={styles.headerActions}><button className={styles.button} onClick={() => void refresh()}>Refresh</button><Link className={styles.link} href="/commercial">Commercial</Link><Link className={styles.link} href="/projects">Projects</Link></div></header><div className={styles.shell}>{error && <div className={styles.error}>{error}</div>}
    <section className={styles.hero}><div className={styles.heroCard}><span className={styles.phase}>Company portfolio</span><h2>{amount(dashboard.portfolio_revenue)} revenue</h2><p>{amount(dashboard.portfolio_exposure)} cost exposure · {amount(dashboard.portfolio_forecast_margin)} forecast margin</p></div><div className={styles.heroCard}><small>Project health</small><h2>{text(health, "critical")} critical · {text(health, "watch")} watch</h2><p>{text(health, "healthy")} healthy projects</p></div><div className={styles.heroCard}><small>Client receivable</small><h2>{amount(dashboard.client_receivable)}</h2><p>Evidence-led invoices and recorded receipts only</p></div></section>
    <section className={styles.grid2}><Table title="Branch comparison"><table className={styles.table}><thead><tr><th>Branch</th><th>Projects</th><th>Revenue</th><th>Exposure</th><th>Margin</th><th>Critical</th></tr></thead><tbody>{branches.map(row => <tr key={text(row, "branch_id")}><td>{text(row, "code")} · {text(row, "name")}</td><td>{text(row, "projects")}</td><td>{amount(row.revenue)}</td><td>{amount(row.exposure)}</td><td>{amount(row.forecast_margin)}</td><td>{text(row, "critical_projects")}</td></tr>)}</tbody></table></Table><Table title="Tender pipeline"><div className={styles.detail}><div><small>Open</small><strong>{text(pipeline, "open")}</strong></div><div><small>Awarded</small><strong>{text(pipeline, "awarded")}</strong></div><div><small>Won value</small><strong>{amount(pipeline.won_value)}</strong></div><div><small>Closing in 30 days</small><strong>{text(pipeline, "closing_next_30_days")}</strong></div></div></Table></section>
    <section className={styles.grid2}><Table title="Fleet performance"><div className={styles.detail}><div><small>Assets</small><strong>{text(fleet, "assets")}</strong></div><div><small>Serviceable</small><strong>{text(fleet, "serviceable")}</strong></div><div><small>Fuel cost</small><strong>{amount(fleet.fuel_cost)}</strong></div><div><small>Maintenance cost</small><strong>{amount(fleet.maintenance_cost)}</strong></div></div></Table><Table title="Materials intelligence"><div className={styles.detail}><div><small>Stock value</small><strong>{amount(materials.stock_value)}</strong></div><div><small>Low stock items</small><strong>{text(materials, "low_stock_count")}</strong></div><div><small>Reserved quantities</small><strong>Controlled in Stores</strong></div><div><small>Reorder levels</small><strong>Monitored</strong></div></div></Table></section>
    <Table title="Project health"><table className={styles.table}><thead><tr><th>Project</th><th>Health</th><th>Budget</th><th>Exposure</th><th>Revenue</th><th>Margin</th><th>Risks</th><th>Completion</th></tr></thead><tbody>{projects.map(row => <tr key={text(row, "project_id")}><td>{text(row, "project_number")} · {text(row, "name")}</td><td>{text(row, "status")}</td><td>{amount(row.budget)}</td><td>{amount(row.exposure)}</td><td>{amount(row.revenue)}</td><td>{amount(row.forecast_margin)}</td><td>{text(row, "critical_risks")}</td><td>{text(row, "completion_date")}</td></tr>)}</tbody></table></Table>
    <Table title="Exceptions requiring attention"><table className={styles.table}><thead><tr><th>Category</th><th>Severity</th><th>Reference</th><th>Message</th></tr></thead><tbody>{exceptions.map((row, index) => <tr key={`${text(row, "reference")}-${index}`}><td>{text(row, "category")}</td><td>{text(row, "severity")}</td><td>{text(row, "reference")}</td><td>{text(row, "message")}</td></tr>)}</tbody></table></Table>
  </div></main>;
}
