export type ManualForm = {
  label: string;
  purpose: string;
};

export type ManualEntry = {
  route: string;
  title: string;
  group: string;
  summary: string;
  find: string[];
  steps: string[];
  roles: string;
  forms?: ManualForm[];
  public?: boolean;
  directRoute?: boolean;
  dynamicRoute?: boolean;
};

export const ROLE_GUIDE = [
  ["System Administrator", "Full platform administration, company setup and technical control."],
  ["Access Administrator", "Users, roles, scopes, sessions and password/security administration."],
  ["Head Office Executive", "Company-wide oversight, intelligence and executive approvals."],
  ["Branch Manager", "Branch-level operational oversight and approvals."],
  ["Site Manager", "Site-level operational control and approvals."],
  ["Approver", "Independent maker/checker approval where assigned."],
  ["Auditor / Read Only", "Read-only review of controlled records and evidence."],
  ["Human Resources Manager", "Employee, contract, leave and workforce administration."],
  ["Payroll Officer", "Timesheet and payroll preparation."],
  ["Fleet Manager", "Fleet governance, maintenance, compliance and cost oversight."],
  ["Fleet Officer", "Fleet records, assignments, fuel and operating transactions."],
  ["Fleet Inspector", "Inspections, defects and condition evidence."],
  ["Tender Manager", "Tender pipeline, gates, approvals and submission readiness."],
  ["Estimator / Quantity Surveyor", "BOQ, estimates and commercial tender preparation."],
  ["Tender Coordinator", "Tender documents, checklists, securities and clarifications."],
  ["Project Manager", "Project mobilisation, delivery control and readiness."],
  ["Project Controls", "Programme, progress, cost and control information."],
  ["Site Supervisor", "Daily site reports, labour, plant, materials and progress capture."],
  ["HSE Officer", "Health, safety and environmental assurance records."],
  ["Quality Officer", "Quality inspections, findings and evidence."],
  ["Procurement Manager", "Procurement approvals, suppliers, purchase control and stores oversight."],
  ["Procurement Officer", "Requisitions, quotations, purchase orders and receiving workflows."],
  ["Storekeeper", "Stores, stock movements, receiving and transfers."],
  ["Subcontract Manager", "Subcontract packages, awards, contracts and certificates."],
  ["Subcontract Officer", "Subcontractor records, bids, documents and package administration."],
  ["Site Commercial Officer", "Site-level subcontract and commercial evidence."],
  ["Commercial Manager", "Client contracts, valuations, claims and commercial oversight."],
  ["Quantity Surveyor", "Measurement, valuation, cost and claim preparation."],
  ["Project Commercial Officer", "Project-level cost/commercial records."],
  ["Finance Manager", "Finance control, approvals, periods and cash oversight."],
  ["Finance Officer", "Journals, invoices, payment requests and evidence capture."],
  ["Finance Reviewer", "Independent finance review and maker/checker control."],
] as const;

export const MANUAL_ENTRIES: ManualEntry[] = [
  { route: "/", title: "Command Centre", group: "Overview", summary: "Your operational home page for company, branch and site status.", find: ["dashboard", "overview", "alerts", "what needs attention", "company status"], steps: ["Open the Command Centre after signing in.", "Use the cards and alerts to identify items requiring attention.", "Follow a module link to correct data in the owning workspace rather than editing summary figures here."], roles: "All authenticated users; visibility follows role and scope." },
  { route: "/intelligence", title: "Management Intelligence", group: "Overview", summary: "Executive and management reporting across projects, tenders, fleet, materials and branches.", find: ["reports", "KPI", "management dashboard", "branch performance", "project performance", "fleet report"], steps: ["Choose the management view relevant to your responsibility.", "Filter by the available company, branch, project or period scope.", "Use intelligence to investigate; make corrections in the source module."], roles: "Executives, managers, auditors and authorised operational leaders." },
  { route: "/projects", title: "Project Mobilisation", group: "Projects & sites", summary: "Turn awarded work into a controlled project and prepare it for delivery.", find: ["new project", "project setup", "award", "mobilisation", "project team", "project plant", "readiness", "budget baseline"], steps: ["Create or select the project.", "Complete project identity, branch/site and award information.", "Build mobilisation readiness, team, plant, budget and programme information.", "Resolve readiness gaps before full site execution."], roles: "Project Manager, Project Controls, Branch/Site Managers and authorised administrators.", forms: [{label:"Create / mobilise project",purpose:"Create project identity and mobilisation record."},{label:"Project team",purpose:"Assign people to project responsibilities."},{label:"Project plant",purpose:"Plan or assign plant to the project."},{label:"Readiness item",purpose:"Record mobilisation requirements and evidence."}] },
  { route: "/projects/control", title: "Project Control", group: "Projects & sites", summary: "Controlled project oversight for delivery, milestones and management checkpoints.", find: ["project control", "project status", "milestone", "delivery control"], steps: ["Select the project under control.", "Review control indicators and exceptions.", "Record or review the required control information.", "Escalate exceptions to the responsible project or branch manager."], roles: "Project Manager, Project Controls, managers and approvers." },
  { route: "/projects/risks", title: "Project Risks", group: "Projects & sites", summary: "Project risk register, mitigation and ownership.", find: ["risk register", "project risk", "mitigation", "risk owner"], steps: ["Select the project.", "Create a risk with cause, event, consequence and rating.", "Assign an owner and mitigation.", "Review status until the risk is closed or accepted."], roles: "Project Manager, Project Controls, Site Manager and authorised reviewers.", forms: [{label:"Project risk",purpose:"Add a risk, rating, owner and mitigation."}] },
  { route: "/planning", title: "Programme Control", group: "Projects & sites", summary: "Baselines, activities, progress, look-ahead planning and delays.", find: ["programme", "schedule", "baseline", "activity", "lookahead", "delay", "progress update"], steps: ["Select the project programme.", "Create or review the approved baseline.", "Maintain activities and progress updates.", "Use look-ahead planning for near-term execution.", "Record delay events as internal control evidence; contractual notices belong in Contract Control."], roles: "Project Controls, Project Manager, Site Manager and authorised planners.", forms: [{label:"Programme baseline",purpose:"Create or maintain a programme baseline."},{label:"Activity",purpose:"Add programme activities and dates."},{label:"Progress update",purpose:"Record actual progress against plan."},{label:"Look-ahead item",purpose:"Plan near-term work."},{label:"Delay record",purpose:"Capture a delivery delay event for internal control."}] },
  { route: "/resources", title: "Resource Capacity", group: "Projects & sites", summary: "Plan labour, plant and resource demand across work.", find: ["resource plan", "capacity", "resource conflict", "resource request", "labour demand", "plant demand"], steps: ["Create or review a resource plan.", "Record demand by project/site and period.", "Review conflicts and shortages.", "Raise and fulfil resource requests using controlled assignments."], roles: "Project Managers, Project Controls, HR/Fleet managers and branch management.", forms: [{label:"Resource plan",purpose:"Plan resource capacity for a project or period."},{label:"Resource demand",purpose:"Record required people/plant/resources."},{label:"Resource request",purpose:"Request resources to close a capacity gap."},{label:"Resource fulfilment",purpose:"Record how a request was fulfilled."}] },
  { route: "/communications", title: "Communications", group: "Projects & sites", summary: "Stakeholders, correspondence, meetings and action tracking.", find: ["letter", "correspondence", "meeting", "minutes", "stakeholder", "action item", "communication"], steps: ["Select the relevant project or scope.", "Maintain the stakeholder register.", "Record incoming/outgoing correspondence and evidence.", "Capture meetings and assign actions.", "Track actions to closure."], roles: "Project Managers, Commercial/Contract staff, Site Managers and authorised users.", forms: [{label:"Stakeholder",purpose:"Register a project stakeholder and contact context."},{label:"Correspondence",purpose:"Record a letter, email or other communication and evidence."},{label:"Meeting",purpose:"Capture meeting details and minutes reference."},{label:"Action item",purpose:"Assign and track a communication action."}] },
  { route: "/compliance", title: "Compliance Control", group: "Projects & sites", summary: "Policies, obligations, reviews and compliance evidence.", find: ["policy", "compliance", "obligation", "legal requirement", "review"], steps: ["Identify the applicable policy or obligation.", "Assign scope, owner and due date.", "Record review evidence and status.", "Escalate overdue or failed obligations."], roles: "Compliance users, managers, auditors and authorised operational owners.", forms: [{label:"Policy / obligation",purpose:"Register a controlled compliance requirement."},{label:"Compliance review",purpose:"Record review result and evidence."}] },
  { route: "/data-quality", title: "Data Quality", group: "Projects & sites", summary: "Readiness snapshots, findings and verified remediation.", find: ["data quality", "missing data", "readiness finding", "remediation", "snapshot"], steps: ["Create or review a data-quality snapshot.", "Inspect findings by module and severity.", "Assign remediation to the data owner.", "Verify remediation before closing a finding."], roles: "Project Controls, data stewards, managers, auditors and system administrators.", forms: [{label:"Quality snapshot",purpose:"Freeze a readiness/data-quality view for review."},{label:"Finding",purpose:"Record a data-quality issue."},{label:"Remediation",purpose:"Record and verify corrective action."}] },
  { route: "/authority", title: "Approval Authority", group: "Projects & sites", summary: "Effective-dated Maloti approval limits by role, branch, module and transaction.", find: ["approval limit", "delegation", "authority", "Maloti limit", "who can approve"], steps: ["Choose the transaction/module requiring an authority rule.", "Set role, scope, value limit and effective dates.", "Use non-overlapping effective periods.", "Review authority before operational approvals are attempted."], roles: "System/Access Administrators, executives and authorised governance managers.", forms: [{label:"Authority rule",purpose:"Set a controlled approval/delegation limit."}] },
  { route: "/changes", title: "Change Control", group: "Projects & sites", summary: "System change requests, release control and implementation evidence.", find: ["change request", "release", "system change", "deployment approval"], steps: ["Register the proposed change and reason.", "Assess impact, testing and approval requirements.", "Record release evidence.", "Close only after implementation and verification are documented."], roles: "System Administrators, change/release owners, approvers and auditors.", forms: [{label:"Change request",purpose:"Register a controlled system change."},{label:"Release record",purpose:"Document implementation and verification evidence."}] },
  { route: "/site-operations", title: "Site Operations", group: "Projects & sites", summary: "Daily site reporting for labour, plant, materials, progress, incidents and quality.", find: ["daily report", "site diary", "labour on site", "plant on site", "material use", "site progress", "incident", "quality issue"], steps: ["Select the site/project and reporting date.", "Open or create the daily report.", "Capture labour, plant, materials, progress and evidence.", "Record incidents and quality items where applicable.", "Submit for independent review/approval; approved snapshots remain auditable."], roles: "Site Supervisor, Site Manager, HSE/Quality staff, Project Manager and approvers.", forms: [{label:"Daily site report",purpose:"Create the site diary for a reporting date."},{label:"Labour entry",purpose:"Capture labour deployed on site."},{label:"Plant entry",purpose:"Capture plant used on site."},{label:"Material usage",purpose:"Capture material consumed/used on site."},{label:"Progress entry",purpose:"Capture work progress and evidence."},{label:"Incident / quality item",purpose:"Capture site incident or quality information."}] },
  { route: "/site-operations/control", title: "Site Operations Control", group: "Projects & sites", summary: "Review and control daily site reports and exceptions.", find: ["approve daily report", "site report review", "site control"], steps: ["Select the relevant site/reporting period.", "Review submitted daily records and evidence.", "Return incomplete records or approve independently where authorised.", "Use exceptions to follow up with the site team."], roles: "Site Manager, Project Manager, approvers and auditors." },
  { route: "/closeout", title: "Project Closeout", group: "Projects & sites", summary: "Close projects with handover, outstanding items and controlled evidence packs.", find: ["project closeout", "handover", "snag", "completion", "close project"], steps: ["Select a project approaching completion.", "Review required closeout items and evidence.", "Resolve outstanding actions/snags and commercial/operational dependencies.", "Complete handover and closure approval."], roles: "Project Manager, Commercial Manager, Site Manager, Project Controls and approvers.", forms: [{label:"Closeout item",purpose:"Record a closure requirement, owner and evidence."},{label:"Handover / completion record",purpose:"Document controlled project completion."}] },
  { route: "/mobile", title: "Field Capture", group: "Projects & sites", summary: "Offline-capable field capture queue with controlled sync.", find: ["offline", "mobile", "field capture", "sync queue"], steps: ["Open Field Capture while connected before going offline where possible.", "Capture supported field records locally.", "Review the queue before synchronising.", "Sync when connectivity returns; queued items do not silently auto-post."], roles: "Authorised field users, supervisors and site teams." },
  { route: "/tenders", title: "Tender Management", group: "Commercial", summary: "Tender pipeline, checklist, BOQ/estimate, securities, clarifications, approvals and submission evidence.", find: ["tender", "bid", "BOQ", "estimate", "tender security", "clarification", "submission"], steps: ["Create or select the tender opportunity.", "Complete checklist and document requirements.", "Prepare estimate/BOQ and commercial inputs.", "Track securities and clarifications.", "Complete maker/checker approvals before submission.", "Record submission evidence; the system does not pretend an external submission happened."], roles: "Tender Manager, Estimator/Quantity Surveyor, Tender Coordinator and approvers.", forms: [{label:"Tender",purpose:"Create and maintain a tender opportunity."},{label:"Tender checklist",purpose:"Track mandatory bid requirements."},{label:"BOQ / estimate",purpose:"Prepare priced tender information."},{label:"Tender security",purpose:"Track bid bonds/securities and expiry."},{label:"Clarification",purpose:"Record tender clarification questions/responses."},{label:"Submission evidence",purpose:"Record proof of tender submission."}] },
  { route: "/tenders/control", title: "Tender Control", group: "Commercial", summary: "Tender gate review, readiness and independent approval controls.", find: ["approve tender", "tender gate", "bid readiness", "tender review"], steps: ["Select the tender awaiting control review.", "Review completeness, estimate, securities and required evidence.", "Return deficiencies to the preparer or approve within authority.", "Confirm submission readiness independently."], roles: "Tender Manager, executives, approvers and authorised commercial reviewers." },
  { route: "/procurement", title: "Procurement & Stores", group: "Commercial", summary: "Suppliers, requisitions, quotations, purchase orders, receiving, stores and stock movements.", find: ["supplier", "requisition", "RFQ", "quotation", "purchase order", "PO", "goods received", "GRN", "stock", "stores", "transfer"], steps: ["Maintain approved supplier and item/store records.", "Raise a requisition for the required goods/services.", "Collect and compare quotations where required.", "Create/approve the purchase order under authority rules.", "Receive goods and record evidence.", "Use stock transfers/ledger movements for store control."], roles: "Procurement Manager, Procurement Officer, Storekeeper, managers and approvers.", forms: [{label:"Supplier",purpose:"Create/maintain supplier information."},{label:"Requisition",purpose:"Request goods or services."},{label:"Quotation / RFQ",purpose:"Record sourcing and supplier quotations."},{label:"Purchase order",purpose:"Create a controlled supplier order."},{label:"Goods receipt",purpose:"Record delivery/receiving evidence."},{label:"Stock transfer",purpose:"Move controlled stock between stores/sites."}] },
  { route: "/procurement/control", title: "Procurement Control", group: "Commercial", summary: "Review procurement exceptions, approvals and control gates.", find: ["approve requisition", "approve PO", "procurement approval", "purchase control"], steps: ["Choose the procurement item awaiting review.", "Confirm sourcing, value, authority and supporting evidence.", "Approve independently or return for correction.", "Monitor outstanding procurement exceptions."], roles: "Procurement Manager, approvers, finance/commercial reviewers and auditors." },
  { route: "/subcontracts", title: "Subcontract Management", group: "Commercial", summary: "Subcontractors, work packages, bids, contracts, certificates, retention and evidence.", find: ["subcontractor", "subcontract", "package", "subcontract bid", "certificate", "retention"], steps: ["Maintain the subcontractor register.", "Create the work package and scope.", "Record/compare subcontract bids.", "Complete award and contract control.", "Prepare certificates and supporting evidence through approval."], roles: "Subcontract Manager, Subcontract Officer, Site Commercial Officer, QS and approvers.", forms: [{label:"Subcontractor",purpose:"Register a subcontractor."},{label:"Work package",purpose:"Define subcontract scope and package."},{label:"Subcontract bid",purpose:"Record bidder offer and comparison information."},{label:"Subcontract contract",purpose:"Record award/contract information."},{label:"Certificate",purpose:"Prepare subcontract payment/certification evidence."}] },
  { route: "/subcontracts/control", title: "Subcontract Control", group: "Commercial", summary: "Independent subcontract approvals and commercial control review.", find: ["approve subcontract", "subcontract control", "certificate approval"], steps: ["Select the package, award or certificate awaiting review.", "Check scope, evidence, value and authority.", "Approve independently or return to the preparer.", "Track unresolved exceptions."], roles: "Subcontract Manager, Commercial Manager, approvers and auditors." },
  { route: "/commercial", title: "Cost & Commercial", group: "Commercial", summary: "Client contract, cost, valuation, claim and cash-flow control.", find: ["client contract", "cost", "valuation", "claim", "cash flow", "commercial report"], steps: ["Select the project/client contract.", "Maintain contract and cost information.", "Prepare valuations and claims with evidence.", "Review cash-flow position and commercial exposure.", "Use Contract Control for formal contractual notices and variation events."], roles: "Commercial Manager, Quantity Surveyor, Project Commercial Officer, Project Manager and approvers.", forms: [{label:"Client contract",purpose:"Maintain client-side commercial contract information."},{label:"Cost record",purpose:"Capture/organise project cost information."},{label:"Valuation",purpose:"Prepare a client valuation."},{label:"Claim",purpose:"Record a commercial claim and evidence."},{label:"Cash-flow entry",purpose:"Maintain project cash-flow information."}] },
  { route: "/finance", title: "Finance & Cash Control", group: "Commercial", summary: "Periods, chart of accounts, journals, invoices, payment requests and payment evidence.", find: ["finance", "journal", "invoice", "payment request", "payment evidence", "chart of accounts", "financial period"], steps: ["Confirm the financial period is open and appropriate accounts exist.", "Capture journals/invoices with supporting evidence.", "Prepare payment requests where applicable.", "Obtain independent review/approval.", "Record payment evidence supplied by the real payment process; this system does not move money."], roles: "Finance Manager, Finance Officer, Finance Reviewer and authorised approvers.", forms: [{label:"Financial period",purpose:"Open/maintain controlled accounting periods."},{label:"Chart account",purpose:"Maintain chart-of-accounts records."},{label:"Journal",purpose:"Prepare a controlled journal entry."},{label:"Invoice",purpose:"Record supplier/client invoice information."},{label:"Payment request",purpose:"Prepare a request for payment."},{label:"Payment evidence",purpose:"Attach/record proof supplied after real payment activity."}] },
  { route: "/assistants", title: "Algorithmic Assistants", group: "Commercial", summary: "Explainable decision support for tendering and procurement without autonomous approval.", find: ["assistant", "recommendation", "tender assistant", "procurement assistant", "algorithm"], steps: ["Choose the available assistant for the decision you are reviewing.", "Provide/select the controlled source information.", "Review the explanation and recommendation.", "Make the final human decision in the owning operational module."], roles: "Authorised tender, procurement, commercial and management users." },
  { route: "/contract-control", title: "Contract Control", group: "Commercial", summary: "Contractual notices, extension events and variation/instruction control.", find: ["contract notice", "notice", "extension of time", "EOT", "variation", "instruction", "contract deadline"], steps: ["Open the direct Contract Control route.", "Select branch/site and the relevant contract.", "Prepare the notice with event date, notice type, subject, due date and contractual detail.", "Use independent issue/review controls; preparers cannot self-issue where maker/checker is enforced."], roles: "Commercial/contract managers, Quantity Surveyors, Project Managers and authorised approvers.", forms: [{label:"Contract notice",purpose:"Prepare a contractual notice for independent issue."}], directRoute: true },
  { route: "/workforce", title: "Workforce", group: "People & control", summary: "Employees, contracts, leave, attendance, timesheets and payroll preparation.", find: ["employee", "staff", "contract", "leave", "attendance", "timesheet", "payroll", "employee bank"], steps: ["Create/select the employee record.", "Maintain employment contract and required employee information.", "Record leave and attendance using the applicable workflow.", "Prepare/approve timesheets.", "Prepare payroll data; actual salary payment occurs outside the system."], roles: "HR Manager, Payroll Officer, managers and authorised administrators.", forms: [{label:"Employee",purpose:"Create/maintain employee personal and employment information."},{label:"Employment contract",purpose:"Record contract terms and dates."},{label:"Leave request",purpose:"Record employee leave."},{label:"Attendance",purpose:"Record attendance information."},{label:"Timesheet",purpose:"Prepare time worked for review/payroll."},{label:"Payroll batch",purpose:"Prepare payroll information for approval/export."}] },
  { route: "/workforce/setup", title: "Workforce Setup", group: "People & control", summary: "Reference/configuration data used by workforce and payroll processes.", find: ["HR setup", "leave type", "workforce configuration", "payroll setup"], steps: ["Open Workforce Setup before large-scale employee processing.", "Maintain the controlled workforce reference/configuration values.", "Verify setup before using dependent workforce forms."], roles: "HR Manager, Payroll Officer and System Administrator.", forms: [{label:"Workforce configuration",purpose:"Maintain reference values used by HR/payroll workflows."}] },
  { route: "/development", title: "HR Development", group: "People & control", summary: "Training, development and credential/competency control.", find: ["training", "skills", "credential", "certificate", "employee development"], steps: ["Select the employee/development context.", "Record training, competency or credential information.", "Attach evidence and expiry where applicable.", "Review upcoming expiry or capability gaps."], roles: "HR Manager, managers and authorised training/competency owners.", forms: [{label:"Training / development record",purpose:"Record employee development activity."},{label:"Credential",purpose:"Record competency/certification evidence and validity."}] },
  { route: "/fleet", title: "Fleet & Plant", group: "People & control", summary: "Assets, assignments, fuel, inspections, defects, compliance, maintenance and cost.", find: ["vehicle", "plant", "fleet", "fuel", "inspection", "defect", "maintenance", "service", "license", "fleet cost"], steps: ["Register/select the vehicle or plant asset.", "Maintain assignment and operating status.", "Capture fuel transactions with quantity, cost and evidence.", "Perform inspections and raise defects.", "Plan/record maintenance and compliance items.", "Review asset cost/history before deployment decisions."], roles: "Fleet Manager, Fleet Officer, Fleet Inspector, managers and approvers.", forms: [{label:"Fleet / plant asset",purpose:"Register vehicle or plant master data."},{label:"Asset assignment",purpose:"Assign fleet/plant to branch, site or project."},{label:"Fuel transaction",purpose:"Record fuel quantity, amount and operating evidence."},{label:"Inspection",purpose:"Capture condition/safety inspection."},{label:"Defect",purpose:"Raise a fleet/plant defect."},{label:"Maintenance",purpose:"Plan or record service/repair activity."},{label:"Compliance item",purpose:"Track licences, certificates or other validity requirements."}] },
  { route: "/fleet/control", title: "Fleet Control", group: "People & control", summary: "Fleet governance, compliance exceptions, cost and readiness review.", find: ["fleet control", "vehicle compliance", "maintenance approval", "fleet readiness"], steps: ["Review the fleet control view for exceptions.", "Open the affected asset.", "Resolve overdue inspection, maintenance, defect or compliance items in Fleet & Plant.", "Use independent approval where required."], roles: "Fleet Manager, Branch Manager, approvers and auditors." },
  { route: "/assurance", title: "HSE & Quality", group: "People & control", summary: "Health, safety, quality, inspection and assurance evidence.", find: ["HSE", "safety", "quality", "inspection", "RFI", "nonconformance", "incident assurance"], steps: ["Select the project/site and assurance type.", "Create the inspection, finding or assurance record.", "Attach evidence and assign corrective actions.", "Verify closeout independently where required."], roles: "HSE Officer, Quality Officer, Site/Project Managers and authorised reviewers.", forms: [{label:"HSE / quality inspection",purpose:"Record an assurance inspection."},{label:"Finding / nonconformance",purpose:"Record an issue requiring corrective action."},{label:"Corrective action",purpose:"Assign and verify remediation."}] },
  { route: "/support", title: "Support Centre", group: "People & control", summary: "Operational support requests and knowledge/SOP support.", find: ["help", "support ticket", "system problem", "SOP", "knowledge"], steps: ["Search available knowledge/SOP guidance first.", "Create a support request when assistance is still required.", "Describe the affected screen, action and error clearly.", "Track the request to resolution."], roles: "All authorised users; support administration for designated support staff.", forms: [{label:"Support request",purpose:"Request operational/system assistance."},{label:"Knowledge / SOP entry",purpose:"Maintain controlled user guidance."}] },
  { route: "/environment", title: "Environment & Sustainability", group: "People & control", summary: "Environmental and sustainability controls/evidence.", find: ["environment", "sustainability", "waste", "environmental record"], steps: ["Select the project/site context.", "Record the environmental/sustainability item and evidence.", "Assign ownership and follow-up where required.", "Review status through closure."], roles: "HSE/environmental staff, Site/Project Managers and authorised reviewers.", forms: [{label:"Environmental record",purpose:"Capture an environmental or sustainability control item."}] },
  { route: "/tools", title: "Tools & Calibration", group: "People & control", summary: "Tool register, issue/return and calibration/validity control.", find: ["tool", "equipment", "calibration", "tool issue", "tool return"], steps: ["Register/select the tool or controlled equipment.", "Maintain assignment/issue information.", "Track calibration or validity dates where applicable.", "Do not deploy expired/unverified controlled tools."], roles: "Store/tool custodians, quality staff, site managers and authorised users.", forms: [{label:"Tool / equipment",purpose:"Register controlled tools/equipment."},{label:"Issue / return",purpose:"Track custody of a tool."},{label:"Calibration",purpose:"Record calibration/validity evidence."}] },
  { route: "/client-portal", title: "Client Portal", group: "People & control", summary: "Internal control of documents/evidence deliberately shared with clients.", find: ["client portal", "share with client", "client documents", "client evidence"], steps: ["Select the project/client context.", "Choose only approved evidence intended for external sharing.", "Create/manage the controlled share/link as supported.", "Review expiry/access and revoke when no longer required."], roles: "Project/Commercial managers and authorised client-sharing users.", forms: [{label:"Client share",purpose:"Publish selected approved evidence for controlled client access."}] },
  { route: "/vendor-portal", title: "Vendor Portal", group: "People & control", summary: "Internal control of supplier/subcontractor evidence requests and public submission links.", find: ["vendor portal", "supplier documents", "subcontractor upload", "evidence request"], steps: ["Create/select the vendor evidence request.", "Define the evidence required and validity/expiry as applicable.", "Issue the generated public submission link through the real communication channel.", "Review submitted evidence before accepting it into internal control."], roles: "Procurement/Subcontract managers and authorised vendor administrators.", forms: [{label:"Vendor evidence request",purpose:"Request documents/evidence from an external supplier/subcontractor."}] },
  { route: "/business-development", title: "Business Development", group: "People & control", summary: "Opportunity pipeline before work becomes a formal tender.", find: ["opportunity", "lead", "business development", "pipeline", "prospect"], steps: ["Register a new opportunity/lead.", "Record client, value, stage, owner and next action.", "Maintain pipeline status and evidence.", "Convert/hand over qualifying opportunities into tender control when appropriate."], roles: "Business development staff, executives and authorised commercial users.", forms: [{label:"Opportunity",purpose:"Create and track a business-development opportunity."}] },
  { route: "/client-accounts", title: "Client Accounts", group: "People & control", summary: "Client/account relationship information and interaction history.", find: ["client account", "customer", "client contact", "relationship", "client history"], steps: ["Create/select the client account.", "Maintain account/contact information.", "Record relationship interactions and relevant notes/evidence.", "Use linked opportunities/projects/contracts for operational work."], roles: "Business development, commercial/account managers and authorised executives.", forms: [{label:"Client account",purpose:"Create/maintain client organisation information."},{label:"Client interaction",purpose:"Record relationship activity and follow-up."}] },
  { route: "/access", title: "Access & Security", group: "People & control", summary: "Users, role assignments, scope, sessions, password resets and security administration.", find: ["user", "account", "permission", "role", "branch access", "site access", "password reset", "session", "security"], steps: ["Create/select the user account.", "Assign only required roles and company/branch/site scope.", "Use reset/session controls when access must be recovered or revoked.", "Review security events and avoid excessive privilege."], roles: "System Administrator and Access Administrator.", forms: [{label:"User account",purpose:"Create or update an internal user."},{label:"Role / scope assignment",purpose:"Grant a role at company, branch or site scope."},{label:"Password reset",purpose:"Issue a controlled one-time reset token."},{label:"Session control",purpose:"Review/revoke active access sessions."}] },
  { route: "/rollout", title: "Professional Rollout", group: "People & control", summary: "Migration, UAT, training, security and recovery readiness evidence.", find: ["rollout", "UAT", "migration", "training evidence", "go live", "recovery test"], steps: ["Choose the rollout/control area.", "Record required readiness item and evidence.", "Assign owner/status and complete independent verification where required.", "Use the evidence set for go-live/readiness decisions."], roles: "System Administrators, project sponsors, implementation leads and auditors.", forms: [{label:"Rollout readiness item",purpose:"Record migration/UAT/training/security/recovery evidence."}] },
  { route: "/automation", title: "Operational Automation", group: "People & control", summary: "Auditable operational alert rules and delivery channels.", find: ["automation", "alert", "notification rule", "deadline alert"], steps: ["Open the direct Operational Automation route.", "Create a named rule.", "Specify the trigger and delivery channel.", "Review status; automation must not silently alter operational records."], roles: "System Administrators and authorised operational managers.", forms: [{label:"Automation rule",purpose:"Create an auditable alert/delivery rule."}], directRoute: true },
  { route: "/login", title: "Sign In", group: "Authentication & external", summary: "Authenticate with your username/email and password.", find: ["login", "sign in"], steps: ["Enter the username/email supplied by an administrator.", "Enter your password and sign in.", "If a return screen was requested, the system returns you there after authentication."], roles: "All internal users.", public: true },
  { route: "/reset-password", title: "Reset Password", group: "Authentication & external", summary: "Use a one-time reset token from an authorised access administrator.", find: ["forgot password", "reset password", "reset token"], steps: ["Obtain a valid reset token from an authorised Access Administrator.", "Paste the token and enter a compliant new password twice.", "After success, return to Sign In."], roles: "Users with a valid reset token.", public: true },
  { route: "/setup", title: "First-Time Setup", group: "Authentication & external", summary: "Initial company and first System Administrator bootstrap.", find: ["first setup", "bootstrap", "initial admin", "company setup"], steps: ["Create the company foundation and Head Office if not already bootstrapped.", "Create the first System Administrator account.", "Continue into Access & Security for controlled user provisioning."], roles: "Installation owner during first-time bootstrap only.", public: true },
  { route: "/vendor-submissions/[token]", title: "Vendor Evidence Submission", group: "Authentication & external", summary: "Public tokenised page used by a supplier/subcontractor to submit requested evidence.", find: ["vendor upload", "supplier upload link", "submission token"], steps: ["Open the exact secure link issued for the evidence request.", "Review the requested evidence.", "Submit the required information/documents before expiry.", "Internal staff review the submission in Vendor Portal."], roles: "External vendor holding a valid issued token.", public: true, dynamicRoute: true },
];

export const SYSTEM_FORMS = MANUAL_ENTRIES.flatMap((entry) =>
  (entry.forms ?? []).map((form) => ({ ...form, route: entry.route, module: entry.title, group: entry.group }))
);

export const MANUAL_GROUPS = Array.from(new Set(MANUAL_ENTRIES.map((entry) => entry.group)));
