import Link from "next/link";
import { redirect } from "next/navigation";
import { createInventoryItemAction, recordInventoryMovementAction } from "./actions";
import { ApiError, nbrosApi } from "@/lib/backend";

type InventoryItem = { id: string; sku: string; name: string; category: string; quantity_on_hand: number; reorder_level: number; unit: string; stock_level: string };
type Movement = { id: string; item_id: string; quantity_delta: number; movement_type: string; reference_type: string | null; reference_id: string | null; notes: string | null; created_at: string };
type KitStock = { rule_id: string; make: string; model: string; service_type: string; level: "green" | "orange" | "red"; label: string; detail: string; kit_name: string | null; sku: string | null; quantity_on_hand: number; reorder_level?: number; unit?: string };
type InventoryResponse = { items: InventoryItem[]; recent_movements: Movement[] };

function itemLevel(label: string): "green" | "orange" | "red" { if (label === "AVAILABLE") return "green"; if (label === "LOW STOCK") return "orange"; return "red"; }

export default async function InventoryPage({ searchParams }: { searchParams: Promise<{ branch?: string }> }) {
  const { branch } = await searchParams;
  if (!branch) redirect("/fleet");
  let inventory: InventoryResponse; let kits: KitStock[];
  try { [inventory, kits] = await Promise.all([nbrosApi<InventoryResponse>(`/api/v1/fleet/inventory?branch_id=${branch}`), nbrosApi<KitStock[]>(`/api/v1/fleet/inventory/service-kits?branch_id=${branch}`)]); }
  catch (error) { if (error instanceof ApiError && error.status === 401) redirect("/api/auth/login"); throw error; }
  const names = new Map(inventory.items.map((item) => [item.id, item.name]));

  return <div className="app-shell">
    <aside className="sidebar"><div className="sidebar-brand"><span className="mini-mark">NB</span><strong>NBros</strong></div><nav><span className="nav-section">Fleet</span><Link className="nav-item" href={`/fleet?branch=${branch}`}>Dashboard</Link><Link className="nav-item" href={`/fleet/drivers?branch=${branch}`}>Drivers</Link><Link className="nav-item" href={`/fleet/requests?branch=${branch}`}>Vehicle requests</Link><Link className="nav-item" href={`/fleet/operations?branch=${branch}`}>Operations</Link><Link className="nav-item active" href={`/fleet/inventory?branch=${branch}`}>Service-kit stock</Link><Link className="nav-item" href={`/fleet/reports?branch=${branch}`}>Reports</Link><Link className="nav-item" href={`/fleet/advisor?branch=${branch}`}>Fleet advisor</Link><Link className="nav-item" href={`/fleet/settings?branch=${branch}`}>Settings</Link></nav></aside>
    <main className="workspace">
      <header className="workspace-header"><div><span className="eyebrow">Fleet Management</span><h1>Service-kit inventory</h1><p className="muted">Branch-scoped stock used by the Fleet service decision engine.</p></div><Link className="ghost-button" href={`/fleet?branch=${branch}`}>Back to fleet</Link></header>

      <section className="two-column">
        <article className="panel"><div className="panel-heading"><div><span className="eyebrow">Inventory</span><h2>Add stock item</h2></div></div><form action={createInventoryItemAction} className="form-grid compact-form"><input type="hidden" name="branch_id" value={branch}/><label>SKU<input name="sku" required placeholder="KIT-HILUX-10K"/></label><label>Item / kit name<input name="name" required placeholder="Hilux 10 000 km Service Kit"/></label><label>Category<input name="category" defaultValue="service_kit"/></label><label>Unit<input name="unit" defaultValue="unit"/></label><label>Opening quantity<input name="opening_quantity" type="number" step="0.01" min="0" defaultValue="0"/></label><label>Reorder level<input name="reorder_level" type="number" step="0.01" min="0" defaultValue="1"/></label><div className="form-span"><button className="primary-button">Save stock item</button></div></form></article>
        <article className="panel"><div className="panel-heading"><div><span className="eyebrow">Stock movement</span><h2>Receive / issue / adjust</h2></div></div>{inventory.items.length === 0 ? <div className="empty-state"><strong>No inventory items yet.</strong><span>Create the first service-kit item before recording movements.</span></div> : <form action={recordInventoryMovementAction} className="form-grid compact-form"><input type="hidden" name="branch_id" value={branch}/><label>Item<select name="item_id" required>{inventory.items.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.sku}</option>)}</select></label><label>Movement<select name="movement_type" defaultValue="receipt"><option value="receipt">Receipt</option><option value="issue">Issue</option><option value="service_use">Service use</option><option value="adjustment">Adjustment</option></select></label><label>Quantity change<input name="quantity_delta" type="number" step="0.01" required placeholder="5 or -1"/></label><label>Reference type<input name="reference_type" placeholder="service_record / purchase"/></label><label>Reference ID<input name="reference_id"/></label><label>Notes<input name="notes"/></label><div className="form-span"><button className="primary-button">Record movement</button></div></form>}</article>
      </section>

      <section className="panel"><div className="panel-heading"><div><span className="eyebrow">Current stock</span><h2>Branch inventory</h2></div><span className="count-badge">{inventory.items.length}</span></div>{inventory.items.length === 0 ? <div className="empty-state"><strong>No Fleet stock recorded.</strong><span>Service-kit checks will report STOCK REQUIRED until matching stock is recorded.</span></div> : <div className="table-wrap"><table><thead><tr><th>SKU</th><th>Item</th><th>Category</th><th>On hand</th><th>Reorder</th><th>Status</th></tr></thead><tbody>{inventory.items.map((item) => <tr key={item.id}><td>{item.sku}</td><td><strong>{item.name}</strong></td><td>{item.category}</td><td>{item.quantity_on_hand} {item.unit}</td><td>{item.reorder_level} {item.unit}</td><td><span className={`status-pill status-${itemLevel(item.stock_level)}`}>{item.stock_level}</span></td></tr>)}</tbody></table></div>}</section>

      <section className="panel"><div className="panel-heading"><div><span className="eyebrow">Service readiness</span><h2>Configured service kits</h2></div><span className="count-badge">{kits.length}</span></div>{kits.length === 0 ? <div className="empty-state"><strong>No service-kit rules configured.</strong><span>Create make/model/service-type rules in Fleet Settings.</span></div> : <div className="table-wrap"><table><thead><tr><th>Vehicle</th><th>Service</th><th>Kit</th><th>Stock</th><th>Status</th></tr></thead><tbody>{kits.map((kit) => <tr key={kit.rule_id}><td><strong>{kit.make} {kit.model}</strong></td><td>{kit.service_type}</td><td>{kit.kit_name ?? "Not configured"}</td><td>{kit.quantity_on_hand}{kit.unit ? ` ${kit.unit}` : ""}</td><td><span className={`status-pill status-${kit.level}`}>{kit.label}</span><small className="muted"> {kit.detail}</small></td></tr>)}</tbody></table></div>}</section>

      <section className="panel"><div className="panel-heading"><div><span className="eyebrow">Audit trail</span><h2>Recent stock movements</h2></div></div>{inventory.recent_movements.length === 0 ? <div className="empty-state"><strong>No stock movements.</strong><span>Receipts, issues and adjustments are retained here for traceability.</span></div> : <div className="table-wrap"><table><thead><tr><th>Time</th><th>Item</th><th>Movement</th><th>Quantity</th><th>Reference</th><th>Notes</th></tr></thead><tbody>{inventory.recent_movements.map((row) => <tr key={row.id}><td>{new Date(row.created_at).toLocaleString()}</td><td>{names.get(row.item_id) ?? row.item_id}</td><td>{row.movement_type}</td><td>{row.quantity_delta > 0 ? "+" : ""}{row.quantity_delta}</td><td>{row.reference_type ? `${row.reference_type}${row.reference_id ? ` · ${row.reference_id}` : ""}` : "—"}</td><td>{row.notes ?? "—"}</td></tr>)}</tbody></table></div>}</section>
    </main>
  </div>;
}
