export type LegacyCashoutCaptureInput = {
  branch_id?: string | null;
  folio_number: string;
  cashout_book_number?: string | null;
  page_number?: string | null;
  entry_number?: string | null;
  loan_date: string;
  first_names?: string | null;
  surname?: string | null;
  identity_number?: string | null;
  passport_expiry_date?: string | null;
  residential_address?: string | null;
  postal_address?: string | null;
  employer?: string | null;
  occupation?: string | null;
  net_salary?: number | null;
  cell_phone?: string | null;
  home_phone?: string | null;
  work_phone?: string | null;
  emergency_name?: string | null;
  emergency_cell_phone?: string | null;
  emergency_work_phone?: string | null;
  emergency_relationship?: string | null;
  bank_name: string;
  bank_account_holder: string;
  bank_account_number: string;
  bank_branch_name?: string | null;
  bank_branch_code?: string | null;
  bank_account_type?: string;
  amount_taken: number;
  total_repayable: number;
  amount_paid: number;
  installment_count: number;
  installment_amount: number;
  repayment_type: "daily" | "weekly" | "monthly" | "custom";
  calculator_method?: string | null;
  calculator_snapshot?: Record<string, unknown>;
  capture_notes?: string | null;
};

export type LegacyCashoutCapture = {
  id: string;
  folio_number: string;
  cashout_book_number: string | null;
  page_number: string | null;
  entry_number: string | null;
  loan_date: string | null;
  borrower_name: string;
  first_names: string | null;
  surname: string | null;
  identity_number: string | null;
  identity_type: "national_id" | "passport" | null;
  passport_expiry_date: string | null;
  residential_address: string | null;
  postal_address: string | null;
  employer: string | null;
  occupation: string | null;
  net_salary: number | null;
  cell_phone: string | null;
  home_phone: string | null;
  work_phone: string | null;
  emergency_name: string | null;
  emergency_cell_phone: string | null;
  emergency_work_phone: string | null;
  emergency_relationship: string | null;
  bank_name: string | null;
  bank_account_holder: string | null;
  bank_branch_name: string | null;
  bank_branch_code: string | null;
  bank_account_type: string | null;
  bank_account_last4: string | null;
  has_bank_account_number: boolean;
  amount_taken: number;
  total_repayable: number;
  amount_paid: number;
  balance: number;
  installment_count: number;
  installment_amount: number;
  repayment_type: string;
  calculator_method: string | null;
  calculator_snapshot: Record<string, unknown>;
  capture_notes: string | null;
  status: "draft" | "reviewed" | "returned" | "posted";
  review_notes: string | null;
  loan_reference: string | null;
  borrower_profile_ready: boolean;
  created_at: string;
  reviewed_at: string | null;
  converted_at: string | null;
};
