"use client";

import { useCallback, useEffect, useState } from "react";
import { Activity, BellRing, KeyRound, RefreshCw, ShieldCheck, UsersRound } from "lucide-react";
import { ControlShell } from "@/components/control-shell";
import { apiJson, apiMutation, PLATFORM_API_URL } from "@/lib/platform-api";

type Status = { platform_owner: boolean; linked: boolean; elevated: boolean; bootstrap_link_available?: boolean; central_admin?: { email?: string } };
type Overview = {
  auth: { users: { total:number;active:number;platform_admins:number;mfa_enabled:number;locked:number }; sessions:{active:number;revoked:number}; applications:{total:number;active:number}; security:{audit_events:number;pending_push_events:number} };
  push: { endpoints:{total:number;active:number}; messages:{total:number;last_24h:number;queued:number;no_endpoints:number}; deliveries:{queued:number;failed:number;delivered:number;opened:number}; identity_projection:{lifecycle_events:number;revoked_sessions:number;disabled_users:number;disabled_applications:number} };
};
type AuthUser={id:string;email?:string|null;phone?:string|null;display_name:string;is_active:boolean;is_platform_admin:boolean;mfa_enabled:boolean;failed_login_attempts:number;locked_until?:string|null;last_login_at?:string|null};
type AuthApp={client_id:string;name:string;is_active:boolean};
type PushApp={client_id:string;active:boolean;endpoints:number;active_endpoints:number;messages:number};
type PushMessage={id:string;source_client_id:string;recipient_sub:string;status:string;created_at:string;delivery_count:number};

function Metric({label,value,note}:{label:string;value:number|string;note?:string}){return <div className="surface-card p-4"><p className="text-[9px] font-black uppercase tracking-[.13em] text-[var(--admin-muted)]">{label}</p><p className="mt-2 text-2xl font-black">{value}</p>{note?<p className="mt-1 text-[9px] text-[var(--admin-muted)]">{note}</p>:null}</div>}
function Pill({good,children}:{good:boolean;children:React.ReactNode}){return <span className={`rounded-full px-2 py-1 text-[9px] font-black ${good?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700"}`}>{children}</span>}

export default function IthutePlatformPage(){
  const[status,setStatus]=useState<Status|null>(null);const[overview,setOverview]=useState<Overview|null>(null);const[users,setUsers]=useState<AuthUser[]>([]);const[authApps,setAuthApps]=useState<AuthApp[]>([]);const[pushApps,setPushApps]=useState<PushApp[]>([]);const[messages,setMessages]=useState<PushMessage[]>([]);const[search,setSearch]=useState("");const[notice,setNotice]=useState("");const[busy,setBusy]=useState(false);
  const loadStatus=useCallback(async()=>{try{setStatus(await apiJson<Status>("/platform/ithute/admin/status",{ttlMs:0,force:true}))}catch{setStatus({platform_owner:false,linked:false,elevated:false})}},[]);
  const load=useCallback(async(q="")=>{setBusy(true);try{const[o,u,a,p,m]=await Promise.all([apiJson<Overview>("/platform/ithute/overview",{ttlMs:0,force:true}),apiJson<AuthUser[]>(`/platform/ithute/auth/users?limit=25${q?`&q=${encodeURIComponent(q)}`:""}`,{ttlMs:0,force:true}),apiJson<AuthApp[]>("/platform/ithute/auth/applications",{ttlMs:0,force:true}),apiJson<PushApp[]>("/platform/ithute/push/applications",{ttlMs:0,force:true}),apiJson<PushMessage[]>("/platform/ithute/push/messages?limit=20",{ttlMs:0,force:true})]);setOverview(o);setUsers(u);setAuthApps(a);setPushApps(p);setMessages(m)}catch{setNotice("Central admin elevation expired or a platform service is unavailable.");await loadStatus()}finally{setBusy(false)}},[loadStatus]);
  useEffect(()=>{void loadStatus()},[loadStatus]);useEffect(()=>{if(status?.elevated)void load()},[status?.elevated,load]);
  async function updateUser(user:AuthUser,body:{is_active?:boolean;unlock?:boolean}){try{await apiMutation(`/platform/ithute/auth/users/${user.id}`,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});setNotice("Central user security updated.");await load(search)}catch{setNotice("Unable to update central user.")}}
  async function revoke(user:AuthUser){try{await apiMutation(`/platform/ithute/auth/users/${user.id}/revoke-sessions`,{method:"POST",credentials:"include"});setNotice("Sessions revoked; Push lifecycle projection will follow Auth.");await load(search)}catch{setNotice("Unable to revoke sessions.")}}
  async function toggle(app:AuthApp){try{await apiMutation(`/platform/ithute/auth/applications/${encodeURIComponent(app.client_id)}`,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({is_active:!app.is_active})});setNotice(`Application ${app.is_active?"disabled":"enabled"}; Push will follow Auth lifecycle state.`);await load(search)}catch{setNotice("Unable to change application state.")}}
  async function endElevation(){await fetch(`${PLATFORM_API_URL}/platform/ithute/admin/logout`,{method:"POST",credentials:"include"});setOverview(null);setUsers([]);await loadStatus()}

  if(!status)return <ControlShell title="!thute Auth & Push" subtitle="Central identity and notification control"><div className="surface-card p-6">Checking privileged access…</div></ControlShell>;
  if(!status.platform_owner)return <ControlShell title="!thute Auth & Push"><div className="surface-card p-6"><ShieldCheck size={24}/><h2 className="mt-3 text-lg font-black">Platform owner access required</h2><p className="mt-2 text-sm text-[var(--admin-muted)]">Only the Mailbox DNS platform owner can enter this console, and central !thute platform-admin authorization is required after that.</p></div></ControlShell>;
  if(!status.elevated)return <ControlShell title="!thute Auth & Push" subtitle="Central identity and notification control"><div className="mx-auto max-w-2xl pt-8"><div className="surface-card p-6 sm:p-8"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-[#eef4f1] text-[var(--admin-pine)]"><KeyRound size={22}/></div><h1 className="mt-5 text-xl font-black">Central admin step-up required</h1><p className="mt-2 text-sm leading-6 text-[var(--admin-muted)]">A normal panel session cannot administer !thute Auth or Push. Authenticate with the central !thute platform-admin account. The elevated session is short-lived and Push receives only a two-minute human-bound delegation.</p>{!status.linked?<div className="mt-4 rounded-xl bg-amber-50 p-4 text-xs font-bold text-amber-800">This legacy platform owner is not linked yet. The first successful central platform-admin step-up will securely bind the two identities after both sides authenticate, and the binding will be audited.</div>:null}<button className="btn-primary mt-5" onClick={()=>{window.location.href=`${PLATFORM_API_URL}/platform/ithute/admin/login`}}><ShieldCheck size={14}/>Authenticate with !thute</button></div></div></ControlShell>;

  const pushByClient=new Map(pushApps.map(x=>[x.client_id,x]));
  return <ControlShell title="!thute Auth & Push" subtitle="Central identity, sessions, applications and push delivery" userEmail={status.central_admin?.email}>
    <div className="space-y-5">
      <section className="surface-card p-4 sm:p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[9px] font-black uppercase tracking-[.13em] text-[var(--admin-muted)]">Privileged control plane</p><h1 className="mt-1 text-xl font-black">Auth & Push superadmin</h1><p className="mt-1 text-[10px] text-[var(--admin-muted)]">Dual-gated as panel owner + central platform admin. Provider credentials and endpoint tokens never leave Push.</p></div><div className="flex gap-2"><button className="btn-secondary" disabled={busy} onClick={()=>void load(search)}><RefreshCw size={14}/>Refresh</button><button className="btn-secondary" onClick={()=>void endElevation()}>End admin session</button></div></div>{notice?<div className="mt-3 rounded-xl border border-[var(--admin-line)] bg-[#f8faf8] p-3 text-[10px] font-bold">{notice}</div>:null}</section>
      {overview?<><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Auth users" value={overview.auth.users.total} note={`${overview.auth.users.active} active · ${overview.auth.users.platform_admins} admins`}/><Metric label="Active sessions" value={overview.auth.sessions.active} note={`${overview.auth.sessions.revoked} revoked`}/><Metric label="Push endpoints" value={overview.push.endpoints.active} note={`${overview.push.endpoints.total} total`}/><Metric label="Messages / 24h" value={overview.push.messages.last_24h} note={`${overview.push.deliveries.failed} failed deliveries`}/><Metric label="Lifecycle backlog" value={overview.auth.security.pending_push_events} note={`${overview.push.identity_projection.lifecycle_events} projected`}/></section><section className="grid gap-4 xl:grid-cols-2"><div className="surface-card p-5"><div className="flex items-center gap-2"><UsersRound size={17}/><p className="text-sm font-black">Identity security</p></div><div className="mt-4 grid grid-cols-2 gap-3"><Metric label="MFA users" value={overview.auth.users.mfa_enabled}/><Metric label="Locked" value={overview.auth.users.locked}/><Metric label="Applications" value={`${overview.auth.applications.active}/${overview.auth.applications.total}`}/><Metric label="Audit events" value={overview.auth.security.audit_events}/></div></div><div className="surface-card p-5"><div className="flex items-center gap-2"><BellRing size={17}/><p className="text-sm font-black">Push security & delivery</p></div><div className="mt-4 grid grid-cols-2 gap-3"><Metric label="Delivered" value={overview.push.deliveries.delivered}/><Metric label="Opened" value={overview.push.deliveries.opened}/><Metric label="Revoked sessions" value={overview.push.identity_projection.revoked_sessions}/><Metric label="Disabled users" value={overview.push.identity_projection.disabled_users}/></div></div></section></>:null}
      <section className="surface-card p-4 sm:p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-black">Central users</p><p className="text-[10px] text-[var(--admin-muted)]">Security changes are audited and session revocation projects into Push.</p></div><form className="flex gap-2" onSubmit={e=>{e.preventDefault();void load(search)}}><input className="input min-w-[220px]" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search user"/><button className="btn-secondary">Search</button></form></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[820px] text-left text-[10px]"><thead><tr className="border-b border-[var(--admin-line)] text-[9px] uppercase text-[var(--admin-muted)]"><th className="p-2">User</th><th className="p-2">Status</th><th className="p-2">Security</th><th className="p-2">Last login</th><th className="p-2 text-right">Actions</th></tr></thead><tbody>{users.map(u=><tr key={u.id} className="border-b border-[var(--admin-line)]"><td className="p-2"><p className="font-black">{u.display_name}</p><p className="text-[var(--admin-muted)]">{u.email||u.phone||u.id}</p></td><td className="p-2"><Pill good={u.is_active}>{u.is_active?"Active":"Disabled"}</Pill>{u.is_platform_admin?<span className="ml-2 text-[9px] font-black">ADMIN</span>:null}</td><td className="p-2">MFA {u.mfa_enabled?"on":"off"} · failures {u.failed_login_attempts}</td><td className="p-2 text-[var(--admin-muted)]">{u.last_login_at?new Date(u.last_login_at).toLocaleString():"Never"}</td><td className="p-2"><div className="flex justify-end gap-1"><button className="btn-secondary" onClick={()=>void updateUser(u,{is_active:!u.is_active})}>{u.is_active?"Disable":"Enable"}</button>{u.failed_login_attempts||u.locked_until?<button className="btn-secondary" onClick={()=>void updateUser(u,{unlock:true})}>Unlock</button>:null}<button className="btn-secondary" onClick={()=>void revoke(u)}>Revoke sessions</button></div></td></tr>)}</tbody></table></div></section>
      <section className="surface-card p-4 sm:p-5"><div className="flex items-center gap-2"><Activity size={17}/><div><p className="text-sm font-black">First-party applications</p><p className="text-[10px] text-[var(--admin-muted)]">Auth remains authoritative; Push follows lifecycle state.</p></div></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[650px] text-left text-[10px]"><thead><tr className="border-b border-[var(--admin-line)] text-[9px] uppercase text-[var(--admin-muted)]"><th className="p-2">Application</th><th className="p-2">Auth</th><th className="p-2">Push endpoints</th><th className="p-2">Messages</th><th className="p-2 text-right">Action</th></tr></thead><tbody>{authApps.map(a=>{const p=pushByClient.get(a.client_id);return <tr key={a.client_id} className="border-b border-[var(--admin-line)]"><td className="p-2"><p className="font-black">{a.name}</p><code className="text-[9px]">{a.client_id}</code></td><td className="p-2"><Pill good={a.is_active}>{a.is_active?"Enabled":"Disabled"}</Pill></td><td className="p-2">{p?`${p.active_endpoints}/${p.endpoints}`:"0/0"}</td><td className="p-2">{p?.messages||0}</td><td className="p-2 text-right"><button className="btn-secondary" onClick={()=>void toggle(a)}>{a.is_active?"Disable":"Enable"}</button></td></tr>})}</tbody></table></div></section>
      <section className="surface-card p-4 sm:p-5"><div><p className="text-sm font-black">Recent Push messages</p><p className="text-[10px] text-[var(--admin-muted)]">Metadata only; encrypted provider endpoints are never exposed.</p></div><div className="mt-4 space-y-2">{messages.map(m=><div key={m.id} className="grid gap-2 rounded-xl border border-[var(--admin-line)] p-3 sm:grid-cols-[1fr_auto_auto]"><div><p className="text-[10px] font-black">{m.source_client_id}</p><p className="font-mono text-[9px] text-[var(--admin-muted)]">recipient {m.recipient_sub}</p></div><div className="text-[9px] text-[var(--admin-muted)]">{new Date(m.created_at).toLocaleString()} · {m.delivery_count} deliveries</div><Pill good={m.status!=="no_endpoints"}>{m.status}</Pill></div>)}</div></section>
    </div>
  </ControlShell>
}
