#!/usr/bin/env python3
"""Ithute managed-hosting node runtime and database agent.

This process is the only component allowed to activate hosted customer images or
provision shared database credentials on an Ithute hosting node. The public API
never receives Docker or database-admin access. Customer database jobs contain
only project-scoped names and passwords generated by the control plane.
"""

from __future__ import annotations

import hashlib
import ipaddress
import json
import os
import re
import signal
import subprocess
import time
import urllib.error
import urllib.request
from typing import Any

AGENT_VERSION = "ithute-hosting-agent/2"
ENV_KEY_RE = re.compile(r"^[A-Z_][A-Z0-9_]{0,127}$")
DIGEST_RE = re.compile(r"^sha256:[0-9a-f]{64}$")
DB_IDENT_RE = re.compile(r"^[a-z][a-z0-9_]{1,62}$")
DB_USER_RE = re.compile(r"^[A-Za-z][A-Za-z0-9_]{1,62}$")
STOP = False


def required_env(name: str, default: str | None = None) -> str:
    value = os.getenv(name, default)
    if value is None or not value.strip():
        raise RuntimeError(f"Missing required environment variable: {name}")
    return value.strip()


API_URL = required_env("ITHUTE_API_URL").rstrip("/")
AGENT_TOKEN = required_env("ITHUTE_HOSTING_AGENT_TOKEN")
POLL_SECONDS = max(5, int(os.getenv("ITHUTE_HOSTING_POLL_SECONDS", "15")))
HEARTBEAT_SECONDS = max(15, int(os.getenv("ITHUTE_HOSTING_HEARTBEAT_SECONDS", "60")))
DOCKER = os.getenv("ITHUTE_HOSTING_DOCKER", "docker")
IMAGE_PREFIX = os.getenv("ITHUTE_HOSTING_IMAGE_PREFIX", "ghcr.io/ithute-stak/hosted-").strip().lower()
ALLOW_HTTP = os.getenv("ITHUTE_HOSTING_ALLOW_HTTP", "false").lower() == "true"
PSQL = os.getenv("ITHUTE_HOSTING_PSQL", "psql")
CREATEDB = os.getenv("ITHUTE_HOSTING_CREATEDB", "createdb")
DROPDB = os.getenv("ITHUTE_HOSTING_DROPDB", "dropdb")
MYSQL = os.getenv("ITHUTE_HOSTING_MYSQL", "mysql")
POSTGRES_ADMIN_HOST = os.getenv("ITHUTE_HOSTING_POSTGRES_ADMIN_HOST", "127.0.0.1").strip()
POSTGRES_ADMIN_PORT = int(os.getenv("ITHUTE_HOSTING_POSTGRES_ADMIN_PORT", "5432"))
POSTGRES_ADMIN_USER = os.getenv("ITHUTE_HOSTING_POSTGRES_ADMIN_USER", "").strip()
POSTGRES_ADMIN_PASSWORD = os.getenv("ITHUTE_HOSTING_POSTGRES_ADMIN_PASSWORD", "")
POSTGRES_ADMIN_DATABASE = os.getenv("ITHUTE_HOSTING_POSTGRES_ADMIN_DATABASE", "postgres").strip()
POSTGRES_APP_HOST = os.getenv("ITHUTE_HOSTING_POSTGRES_HOST", "ithute-db-gateway").strip()
POSTGRES_APP_PORT = int(os.getenv("ITHUTE_HOSTING_POSTGRES_PORT", "5432"))
MYSQL_ADMIN_HOST = os.getenv("ITHUTE_HOSTING_MYSQL_ADMIN_HOST", "127.0.0.1").strip()
MYSQL_ADMIN_PORT = int(os.getenv("ITHUTE_HOSTING_MYSQL_ADMIN_PORT", "3306"))
MYSQL_ADMIN_USER = os.getenv("ITHUTE_HOSTING_MYSQL_ADMIN_USER", "").strip()
MYSQL_ADMIN_PASSWORD = os.getenv("ITHUTE_HOSTING_MYSQL_ADMIN_PASSWORD", "")
MYSQL_APP_HOST = os.getenv("ITHUTE_HOSTING_MYSQL_HOST", "ithute-db-gateway").strip()
MYSQL_APP_PORT = int(os.getenv("ITHUTE_HOSTING_MYSQL_PORT", "3306"))
ORIGIN_BIND_IP = os.getenv("ITHUTE_HOSTING_ORIGIN_BIND_IP", "").strip()
ORIGIN_PORT_START = int(os.getenv("ITHUTE_HOSTING_ORIGIN_PORT_START", "22000"))
ORIGIN_PORT_END = int(os.getenv("ITHUTE_HOSTING_ORIGIN_PORT_END", "29999"))

if not API_URL.startswith("https://") and not ALLOW_HTTP:
    raise RuntimeError("ITHUTE_API_URL must use HTTPS unless ITHUTE_HOSTING_ALLOW_HTTP=true")
if not AGENT_TOKEN.startswith("ith_host_"):
    raise RuntimeError("ITHUTE_HOSTING_AGENT_TOKEN is not a hosting-node credential")
if not IMAGE_PREFIX:
    raise RuntimeError("ITHUTE_HOSTING_IMAGE_PREFIX cannot be empty")
if ORIGIN_BIND_IP:
    try:
        origin_address = ipaddress.ip_address(ORIGIN_BIND_IP)
    except ValueError as exc:
        raise RuntimeError("ITHUTE_HOSTING_ORIGIN_BIND_IP must be a literal private/VPN IP address") from exc
    if not isinstance(origin_address, ipaddress.IPv4Address) or not origin_address.is_private or origin_address.is_unspecified or origin_address.is_multicast or origin_address.is_link_local:
        raise RuntimeError("ITHUTE_HOSTING_ORIGIN_BIND_IP must be a private/VPN IPv4 address, never a public or wildcard address")
    if not (1024 <= ORIGIN_PORT_START <= ORIGIN_PORT_END <= 65535):
        raise RuntimeError("ITHUTE_HOSTING_ORIGIN_PORT_START/END must define a valid non-privileged port range")
for port_name, port in (
    ("ITHUTE_HOSTING_POSTGRES_ADMIN_PORT", POSTGRES_ADMIN_PORT),
    ("ITHUTE_HOSTING_POSTGRES_PORT", POSTGRES_APP_PORT),
    ("ITHUTE_HOSTING_MYSQL_ADMIN_PORT", MYSQL_ADMIN_PORT),
    ("ITHUTE_HOSTING_MYSQL_PORT", MYSQL_APP_PORT),
):
    if not 1 <= port <= 65535:
        raise RuntimeError(f"{port_name} must be a valid TCP port")


def log(message: str) -> None:
    print(f"[hosting-agent] {message}", flush=True)


def api(path: str, payload: dict[str, Any] | None = None) -> dict[str, Any]:
    data = None if payload is None else json.dumps(payload).encode("utf-8")
    request = urllib.request.Request(
        f"{API_URL}/api/v1{path}",
        data=data,
        method="POST",
        headers={
            "Accept": "application/json",
            "Content-Type": "application/json",
            "X-Ithute-Hosting-Agent": AGENT_TOKEN,
            "User-Agent": AGENT_VERSION,
        },
    )
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            raw = response.read().decode("utf-8")
            return json.loads(raw) if raw else {}
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")[:2000]
        raise RuntimeError(f"Control-plane HTTP {exc.code}: {detail}") from exc


def command(args: list[str], *, check: bool = True, timeout: int = 120, extra_env: dict[str, str] | None = None) -> subprocess.CompletedProcess[str]:
    process_env = os.environ.copy()
    if extra_env:
        process_env.update(extra_env)
    result = subprocess.run(args, check=False, capture_output=True, text=True, timeout=timeout, env=process_env)
    if check and result.returncode != 0:
        detail = (result.stderr or result.stdout).strip()[-2000:]
        raise RuntimeError(f"command {os.path.basename(args[0])} failed: {detail}")
    return result


def docker(*args: str, check: bool = True, timeout: int = 120, extra_env: dict[str, str] | None = None) -> subprocess.CompletedProcess[str]:
    return command([DOCKER, *args], check=check, timeout=timeout, extra_env=extra_env)


def exists(kind: str, name: str) -> bool:
    return docker(kind, "inspect", name, check=False).returncode == 0


def validate_manifest(work: dict[str, Any]) -> tuple[dict[str, Any], dict[str, str]]:
    image_ref = str(work.get("image_ref") or "").strip().lower()
    digest = str(work.get("image_digest") or "").strip().lower()
    if not image_ref.startswith(IMAGE_PREFIX) or "@sha256:" not in image_ref:
        raise RuntimeError("Refusing image outside the approved digest-pinned Ithute hosting namespace")
    actual_digest = "sha256:" + image_ref.rsplit("@sha256:", 1)[1]
    if not DIGEST_RE.fullmatch(actual_digest) or actual_digest != digest:
        raise RuntimeError("Runtime manifest image digest does not match the immutable image reference")

    project = work.get("project")
    if not isinstance(project, dict):
        raise RuntimeError("Runtime manifest is missing project settings")
    security = project.get("security")
    if not isinstance(security, dict):
        raise RuntimeError("Runtime manifest is missing the security contract")
    if security.get("privileged") is not False:
        raise RuntimeError("Refusing privileged hosted workload")
    if security.get("docker_socket") is not False:
        raise RuntimeError("Refusing hosted workload with Docker socket access")
    if security.get("host_ports") != []:
        raise RuntimeError("Refusing hosted workload that requests public host ports")
    if security.get("no_new_privileges") is not True:
        raise RuntimeError("Runtime manifest must require no-new-privileges")
    if security.get("read_only_root") is not True:
        raise RuntimeError("Runtime manifest must require a read-only root filesystem")
    if "ALL" not in list(security.get("cap_drop") or []):
        raise RuntimeError("Runtime manifest must drop all Linux capabilities")
    if security.get("persistent_mount") != "/data":
        raise RuntimeError("Runtime manifest persistent mount must be /data")

    resources = project.get("resources")
    if not isinstance(resources, dict):
        raise RuntimeError("Runtime manifest is missing resource limits")
    for key in ("storage_mb", "memory_mb", "cpu_millicores", "pid_limit"):
        if int(resources.get(key) or 0) <= 0:
            raise RuntimeError(f"Runtime manifest has an invalid {key} limit")

    environment = project.get("environment") or {}
    if not isinstance(environment, dict):
        raise RuntimeError("Runtime environment must be an object")
    clean_environment: dict[str, str] = {}
    for key, value in environment.items():
        if not ENV_KEY_RE.fullmatch(str(key)):
            raise RuntimeError("Runtime environment contains an invalid key")
        if not isinstance(value, str) or "\x00" in value:
            raise RuntimeError(f"Runtime environment value for {key} is invalid")
        clean_environment[str(key)] = value

    if docker("image", "inspect", image_ref, check=False).returncode != 0:
        raise RuntimeError("Approved image is not preloaded on this node; the isolated builder/transfer stage must load it first")
    image_user = docker("image", "inspect", "--format", "{{.Config.User}}", image_ref).stdout.strip().lower()
    if not image_user or image_user in {"0", "root", "0:0", "root:root"}:
        raise RuntimeError("Hosted image must declare a non-root USER")
    return project, clean_environment


def ensure_network(name: str, project_id: str) -> None:
    if not exists("network", name):
        docker("network", "create", "--driver", "bridge", "--label", "ithute.hosted=true", "--label", f"ithute.project={project_id}", name)


def ensure_volume(name: str, project_id: str) -> None:
    if not exists("volume", name):
        docker("volume", "create", "--label", "ithute.hosted=true", "--label", f"ithute.project={project_id}", name)


def private_ip(container: str, network: str) -> str:
    template = "{{(index .NetworkSettings.Networks \"" + network + "\").IPAddress}}"
    ip = docker("inspect", "--format", template, container).stdout.strip()
    if not ip:
        raise RuntimeError("Candidate container has no private network address")
    return ip


def wait_healthy(ip: str, port: int, path: str) -> None:
    if not path.startswith("/"):
        raise RuntimeError("Health path must start with /")
    url = f"http://{ip}:{port}{path}"
    last_error = "health endpoint did not respond"
    for _ in range(30):
        if STOP:
            raise RuntimeError("Agent is stopping")
        try:
            with urllib.request.urlopen(url, timeout=3) as response:
                if 200 <= response.status < 400:
                    return
                last_error = f"HTTP {response.status}"
        except Exception as exc:
            last_error = str(exc)
        time.sleep(2)
    raise RuntimeError(f"Candidate failed private health check: {last_error}")


def report(deployment_id: str, status: str, message: str | None = None, *, origin_url: str | None = None) -> dict[str, Any]:
    payload: dict[str, Any] = {"status": status, "message": message}
    if origin_url:
        payload["origin_url"] = origin_url
    return api(f"/hosting/agent/deployments/{deployment_id}/status", payload)


def _existing_origin_port(container: str, container_port: int) -> int | None:
    if not exists("container", container):
        return None
    template = "{{(index (index .HostConfig.PortBindings \"" + str(container_port) + "/tcp\") 0).HostPort}}"
    result = docker("inspect", "--format", template, container, check=False)
    if result.returncode != 0:
        return None
    try:
        port = int(result.stdout.strip())
    except ValueError:
        return None
    return port if ORIGIN_PORT_START <= port <= ORIGIN_PORT_END else None


def _origin_candidates(project_id: str) -> list[int]:
    size = ORIGIN_PORT_END - ORIGIN_PORT_START + 1
    seed = int(hashlib.sha256(project_id.encode("ascii")).hexdigest()[:8], 16)
    start = ORIGIN_PORT_START + (seed % size)
    return [ORIGIN_PORT_START + ((start - ORIGIN_PORT_START + offset) % size) for offset in range(min(size, 128))]


def _run_candidate(
    *,
    current: str,
    network: str,
    image_ref: str,
    environment: dict[str, str],
    resources: dict[str, Any],
    project_id: str,
    deployment_id: str,
    volume: str,
    container_port: int,
    preferred_origin_port: int | None,
) -> int | None:
    cpus = max(0.1, int(resources["cpu_millicores"]) / 1000.0)
    env_args: list[str] = []
    for key in sorted(environment):
        env_args.extend(["--env", key])
    base_args = [
        "run", "-d", "--name", current, "--network", network, "--restart", "unless-stopped",
        "--add-host", "ithute-db-gateway:host-gateway",
        "--memory", f"{int(resources['memory_mb'])}m", "--cpus", f"{cpus:.3f}", "--pids-limit", str(int(resources["pid_limit"])),
        "--read-only", "--security-opt", "no-new-privileges:true", "--cap-drop", "ALL",
        "--tmpfs", "/tmp:rw,nosuid,nodev,noexec,size=64m", "--mount", f"type=volume,source={volume},target=/data",
        "--label", "ithute.hosted=true", "--label", f"ithute.project={project_id}", "--label", f"ithute.deployment={deployment_id}",
    ]
    if not ORIGIN_BIND_IP:
        docker(*base_args, *env_args, image_ref, timeout=180, extra_env=environment)
        return None

    candidates = []
    if preferred_origin_port is not None:
        candidates.append(preferred_origin_port)
    candidates.extend(port for port in _origin_candidates(project_id) if port not in candidates)
    last_error = "no private origin port is available"
    for host_port in candidates:
        result = docker(
            *base_args,
            "--publish", f"{ORIGIN_BIND_IP}:{host_port}:{container_port}",
            *env_args, image_ref, timeout=180, extra_env=environment, check=False,
        )
        if result.returncode == 0:
            return host_port
        docker("rm", "-f", current, check=False)
        last_error = (result.stderr or result.stdout or last_error).strip()[-1200:]
        if "port is already allocated" not in last_error.lower() and "address already in use" not in last_error.lower():
            raise RuntimeError(f"could not start hosted workload with private origin binding: {last_error}")
    raise RuntimeError(f"private origin port range is exhausted: {last_error}")


def restore_previous(current: str, backup: str) -> None:
    if exists("container", current):
        docker("rm", "-f", current, check=False)
    if exists("container", backup):
        docker("rename", backup, current, check=False)
        docker("start", current, check=False)


def activate(work: dict[str, Any]) -> None:
    deployment_id = str(work["id"])
    project, environment = validate_manifest(work)
    project_id = str(project["id"])
    project_key = project_id.replace("-", "")
    current = f"ithute-hosted-{project_key}"
    backup = f"{current}-previous-{deployment_id.replace('-', '')[:8]}"
    network = f"ithute-project-{project_key[:16]}"
    volume = f"ithute-project-{project_key}-data"
    image_ref = str(work["image_ref"])
    resources = project["resources"]
    previous_exists = exists("container", current)
    previous_origin_port = _existing_origin_port(current, int(project["container_port"])) if previous_exists and ORIGIN_BIND_IP else None

    try:
        ensure_network(network, project_id)
        ensure_volume(volume, project_id)
        if exists("container", backup):
            docker("rm", "-f", backup)
        if previous_exists:
            docker("stop", "--time", "20", current, timeout=45)
            docker("rename", current, backup)

        container_port = int(project["container_port"])
        origin_port = _run_candidate(
            current=current,
            network=network,
            image_ref=image_ref,
            environment=environment,
            resources=resources,
            project_id=project_id,
            deployment_id=deployment_id,
            volume=volume,
            container_port=container_port,
            preferred_origin_port=previous_origin_port,
        )
        report(deployment_id, "running", "Candidate container started on its private project network")
        ip = private_ip(current, network)
        wait_healthy(ip, container_port, str(project["health_path"]))
        origin_url = f"http://{ORIGIN_BIND_IP}:{origin_port}" if ORIGIN_BIND_IP and origin_port else None
        report(deployment_id, "healthy", "Private health check passed; release promoted", origin_url=origin_url)
        if exists("container", backup):
            docker("rm", "-f", backup)
        log(f"deployment {deployment_id} healthy")
    except Exception as exc:
        error = str(exc)[:1900]
        log(f"deployment {deployment_id} failed: {error}")
        restore_previous(current, backup)
        try:
            report(deployment_id, "failed", error)
        except Exception as report_exc:
            log(f"could not report deployment failure: {report_exc}")


def heartbeat() -> None:
    api("/hosting/agent/heartbeat", {"version": AGENT_VERSION})


def claim() -> dict[str, Any] | None:
    result = api("/hosting/agent/deployments/claim")
    work = result.get("deployment")
    return work if isinstance(work, dict) else None


def sql_literal(value: str) -> str:
    if "\x00" in value:
        raise RuntimeError("Database credential contains an invalid NUL character")
    return "'" + value.replace("'", "''") + "'"


def validate_database_work(work: dict[str, Any]) -> tuple[str, str, str, str, str]:
    database_id = str(work.get("id") or "")
    operation = str(work.get("operation") or "")
    engine = str(work.get("engine") or "")
    database_name = str(work.get("database_name") or "")
    username = str(work.get("username") or "")
    password = str(work.get("password") or "")
    if not database_id:
        raise RuntimeError("Database job is missing its id")
    if operation not in {"provision", "rotate", "suspend", "resume", "delete"}:
        raise RuntimeError("Unknown database operation")
    if engine not in {"postgresql", "mysql"}:
        raise RuntimeError("Unknown database engine")
    if not DB_IDENT_RE.fullmatch(database_name) or not DB_USER_RE.fullmatch(username):
        raise RuntimeError("Database job contains an invalid identifier")
    if len(password) < 20 or len(password) > 256:
        raise RuntimeError("Database job contains an invalid generated password")
    return database_id, operation, engine, database_name, username


def postgres_environment() -> dict[str, str]:
    if not POSTGRES_ADMIN_HOST or not POSTGRES_ADMIN_USER or not POSTGRES_ADMIN_PASSWORD or not POSTGRES_ADMIN_DATABASE:
        raise RuntimeError("PostgreSQL provisioning is not configured on this hosting node")
    return {"PGPASSWORD": POSTGRES_ADMIN_PASSWORD}


def postgres_connection_args() -> list[str]:
    postgres_environment()
    return ["--host", POSTGRES_ADMIN_HOST, "--port", str(POSTGRES_ADMIN_PORT), "--username", POSTGRES_ADMIN_USER]


def psql(sql: str) -> str:
    args = [PSQL, *postgres_connection_args(), "--dbname", POSTGRES_ADMIN_DATABASE, "-v", "ON_ERROR_STOP=1", "-Atqc", sql]
    return command(args, timeout=60, extra_env=postgres_environment()).stdout.strip()


def postgres_database_exists(name: str) -> bool:
    return psql(f"SELECT 1 FROM pg_database WHERE datname={sql_literal(name)}") == "1"


def postgres_role_exists(name: str) -> bool:
    return psql(f"SELECT 1 FROM pg_roles WHERE rolname={sql_literal(name)}") == "1"


def postgres_operation(work: dict[str, Any]) -> tuple[str, int, str | None]:
    _, operation, _, database_name, username = validate_database_work(work)
    password = str(work["password"])
    if operation == "provision":
        if postgres_role_exists(username):
            psql(f"ALTER ROLE {username} LOGIN PASSWORD {sql_literal(password)}")
        else:
            psql(f"CREATE ROLE {username} LOGIN PASSWORD {sql_literal(password)}")
        if not postgres_database_exists(database_name):
            command([CREATEDB, *postgres_connection_args(), f"--maintenance-db={POSTGRES_ADMIN_DATABASE}", f"--owner={username}", database_name], timeout=120, extra_env=postgres_environment())
        psql(f"GRANT CONNECT ON DATABASE {database_name} TO {username}")
    elif operation == "rotate":
        if not postgres_role_exists(username):
            raise RuntimeError("PostgreSQL role no longer exists")
        psql(f"ALTER ROLE {username} LOGIN PASSWORD {sql_literal(password)}")
    elif operation == "suspend":
        psql(f"ALTER ROLE {username} NOLOGIN")
    elif operation == "resume":
        psql(f"ALTER ROLE {username} LOGIN")
    elif operation == "delete":
        command([DROPDB, *postgres_connection_args(), f"--maintenance-db={POSTGRES_ADMIN_DATABASE}", "--if-exists", database_name], timeout=120, extra_env=postgres_environment())
        psql(f"DROP ROLE IF EXISTS {username}")
    version = psql("SHOW server_version") if operation != "delete" else None
    return POSTGRES_APP_HOST, POSTGRES_APP_PORT, version


def mysql_exec(sql: str) -> str:
    if not MYSQL_ADMIN_HOST or not MYSQL_ADMIN_USER or not MYSQL_ADMIN_PASSWORD:
        raise RuntimeError("MySQL provisioning is not configured on this hosting node")
    args = [MYSQL, "--batch", "--skip-column-names", "--host", MYSQL_ADMIN_HOST, "--port", str(MYSQL_ADMIN_PORT), "--user", MYSQL_ADMIN_USER, "--execute", sql]
    return command(args, timeout=60, extra_env={"MYSQL_PWD": MYSQL_ADMIN_PASSWORD}).stdout.strip()


def mysql_operation(work: dict[str, Any]) -> tuple[str, int, str | None]:
    _, operation, _, database_name, username = validate_database_work(work)
    password = str(work["password"])
    quoted_user = sql_literal(username)
    quoted_password = sql_literal(password)
    if operation == "provision":
        mysql_exec(
            f"CREATE DATABASE IF NOT EXISTS `{database_name}`; "
            f"CREATE USER IF NOT EXISTS {quoted_user}@'%' IDENTIFIED BY {quoted_password}; "
            f"ALTER USER {quoted_user}@'%' IDENTIFIED BY {quoted_password} ACCOUNT UNLOCK; "
            f"GRANT ALL PRIVILEGES ON `{database_name}`.* TO {quoted_user}@'%'; FLUSH PRIVILEGES;"
        )
    elif operation == "rotate":
        mysql_exec(f"ALTER USER {quoted_user}@'%' IDENTIFIED BY {quoted_password};")
    elif operation == "suspend":
        mysql_exec(f"ALTER USER {quoted_user}@'%' ACCOUNT LOCK;")
    elif operation == "resume":
        mysql_exec(f"ALTER USER {quoted_user}@'%' ACCOUNT UNLOCK;")
    elif operation == "delete":
        mysql_exec(f"DROP DATABASE IF EXISTS `{database_name}`; DROP USER IF EXISTS {quoted_user}@'%';")
    version = mysql_exec("SELECT VERSION();") if operation != "delete" else None
    return MYSQL_APP_HOST, MYSQL_APP_PORT, version


def report_database(database_id: str, success: bool, *, host: str | None = None, port: int | None = None, engine_version: str | None = None, message: str | None = None) -> dict[str, Any]:
    return api(f"/hosting/agent/databases/{database_id}/status", {"success": success, "host": host, "port": port, "engine_version": engine_version, "message": message})


def claim_database() -> dict[str, Any] | None:
    result = api("/hosting/agent/databases/claim")
    work = result.get("database")
    return work if isinstance(work, dict) else None


def process_database(work: dict[str, Any]) -> None:
    database_id = str(work.get("id") or "")
    try:
        _, _, engine, _, _ = validate_database_work(work)
        if engine == "postgresql":
            host, port, version = postgres_operation(work)
        else:
            host, port, version = mysql_operation(work)
        report_database(database_id, True, host=host, port=port, engine_version=version)
        log(f"database {database_id} operation {work.get('operation')} complete")
    except Exception as exc:
        error = str(exc)[:1900]
        log(f"database {database_id} operation failed: {error}")
        try:
            report_database(database_id, False, message=error)
        except Exception as report_exc:
            log(f"could not report database failure: {report_exc}")


def handle_signal(signum: int, _frame: Any) -> None:
    global STOP
    log(f"received signal {signum}; stopping after current operation")
    STOP = True


def main() -> int:
    signal.signal(signal.SIGTERM, handle_signal)
    signal.signal(signal.SIGINT, handle_signal)
    docker("version", "--format", "{{.Server.Version}}")
    log(f"starting {AGENT_VERSION}")
    last_heartbeat = 0.0
    while not STOP:
        now = time.monotonic()
        try:
            if now - last_heartbeat >= HEARTBEAT_SECONDS:
                heartbeat()
                last_heartbeat = now
            database_work = claim_database()
            if database_work:
                process_database(database_work)
                continue
            work = claim()
            if work:
                activate(work)
                continue
        except Exception as exc:
            log(f"poll failed: {exc}")
        for _ in range(POLL_SECONDS):
            if STOP:
                break
            time.sleep(1)
    log("stopped")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
