"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import styles from "../workforce/workforce.module.css";

type Row=Record<string,unknown>;
type Catalog={activations:Row[];projects:Row[];employees:Row[];assets:Row[];documents:Row[];permissions:string[]};
type Summary={active_sites:number;approved_reports:number;reports_pending:number;approved_labour_hours:string;approved_plant_hours:string;approved_material_cost:string;open_incidents:number;open_quality_actions:number};
type Tab="dashboard"|"activate"|"diary"|"labour"|"plant"|"materials"|"progress"|"evidence"|"incidents"|"quality"|"audit";
const API="/api/v1";
const tabs:Array<[Tab,string]>=[["dashboard","Dashboard"],["activate","Activate site"],["diary","Daily diary"],["labour","Labour"],["plant","Plant"],["materials","Materials"],["progress","Progress"],["evidence","Evidence"],["incidents","Incidents"],["quality","Quality"],["audit","Audit"]];
function text(r:Row|null|undefined,k:string){return String(r?.[k]??"")}
function num(r:Row|null|undefined,k:string){return Number(r?.[k]??0)}
function list(v:unknown):Row[]{return Array.isArray(v)?v as Row[]:[]}
function cash(v:unknown){return `M ${Number(v??0).toLocaleString("en-LS",{minimumFractionDigits:2,maximumFractionDigits:2})}`}
function today(){return new Date().toISOString().slice(0,10)}
function localNow(){const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16)}
function badge(v:string){if(["approved","active","closed","accepted","pass"].includes(v))return styles.green;if(["submitted","draft","investigating","conditional","action_required"].includes(v))return styles.amber;if(["rejected","fail","critical","fatal","serious","open"].includes(v))return styles.red;return styles.blue}
async function api<T>(path:string,init?:RequestInit):Promise<T>{const response=await fetch(`${API}${path}`,{...init,credentials:"include",headers:{"Content-Type":"application/json",...(init?.headers??{})},cache:"no-store"});if(response.status===401){window.location.href=`/login?returnTo=${encodeURIComponent("/site-operations")}`;throw new Error("Session expired")};const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(typeof payload?.detail==="string"?payload.detail:JSON.stringify(payload?.detail??payload));return payload as T}
function Field({label,children,wide=false}:{label:string;children:React.ReactNode;wide?:boolean}){return <div className={`${styles.field} ${wide?styles.wide:""}`}><label>{label}</label>{children}</div>}
function Btn({children,variant="",...props}:React.ButtonHTMLAttributes<HTMLButtonElement>&{variant?:"secondary"|"danger"|""}){return <button {...props} className={`${styles.button} ${variant?styles[variant]:""}`}>{children}</button>}
function Data({rows,cols}:{rows:Row[];cols:string[]}){return rows.length?<div className={styles.tableWrap}><table className={styles.table}><thead><tr>{cols.map(c=><th key={c}>{c.replaceAll("_"," ")}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={String(r.id??i)}>{cols.map(c=><td key={c}>{c.includes("cost")||c.includes("amount")?cash(r[c]):String(r[c]??"")}</td>)}</tr>)}</tbody></table></div>:<div className={styles.empty}>No records yet.</div>}

export default function SiteOperationsPage(){
 const [initialized,setInitialized]=useState<boolean|null>(null),[catalog,setCatalog]=useState<Catalog>({activations:[],projects:[],employees:[],assets:[],documents:[],permissions:[]}),[summary,setSummary]=useState<Summary|null>(null),[reports,setReports]=useState<Row[]>([]),[alerts,setAlerts]=useState<Row[]>([]),[auditRows,setAuditRows]=useState<Row[]>([]),[selectedActivation,setSelectedActivation]=useState(""),[selectedReport,setSelectedReport]=useState(""),[detail,setDetail]=useState<Row|null>(null),[tab,setTab]=useState<Tab>("dashboard"),[error,setError]=useState(""),[notice,setNotice]=useState(""),[loading,setLoading]=useState(true);
 const [activation,setActivation]=useState({project_id:"",site_id:"",notes:""});
 const [diary,setDiary]=useState({report_date:today(),shift:"day",weather_summary:"",rain_hours:"0",work_summary:"",planned_work:"",blockers:"",safety_summary:"",visitor_summary:"",no_work_reason:""});
 const [labour,setLabour]=useState({employee_id:"",crew_name:"",worker_count:"1",regular_hours:"8",overtime_hours:"0",activity:"",work_area:"",notes:""});
 const [plant,setPlant]=useState({asset_id:"",operator_employee_id:"",usage_hours:"8",idle_hours:"0",start_odometer_km:"",end_odometer_km:"",start_engine_hours:"",end_engine_hours:"",activity:"",breakdown:false,notes:""});
 const [material,setMaterial]=useState({movement_type:"received",material_code:"",description:"",unit:"item",quantity:"1",unit_cost:"0",supplier_or_source:"",source_reference:"",work_area:"",waste_reason:"",document_id:"",notes:""});
 const [progress,setProgress]=useState({milestone_id:"",work_item:"",unit:"",planned_quantity:"",period_quantity:"",cumulative_quantity:"",progress_pct:"0",measurement_date:today(),narrative:"",document_id:""});
 const [evidence,setEvidence]=useState({document_id:"",evidence_type:"photo",caption:"",work_area:"",captured_at:localNow()});
 const [incident,setIncident]=useState({incident_type:"safety",occurred_at:localNow(),severity:"minor",description:"",employee_id:"",persons_involved:"",lost_time:false,immediate_action:"",root_cause:"",corrective_action:"",owner_employee_id:"",due_date:"",status:"open",document_id:""});
 const [quality,setQuality]=useState({check_type:"inspection",work_item:"",specification_reference:"",inspected_at:localNow(),inspector_employee_id:"",result:"pass",nonconformance_number:"",corrective_action:"",owner_employee_id:"",due_date:"",status:"open",document_id:"",notes:""});
 const permissions=useMemo(()=>new Set(catalog.permissions),[catalog.permissions]);const can=(p:string)=>permissions.has(p);
 const refresh=useCallback(async()=>{setLoading(true);setError("");try{const s=await api<{initialized:boolean}>("/site-ops/status");setInitialized(s.initialized);if(!s.initialized)return;const [c,sm,r,a,au]=await Promise.all([api<Catalog>("/site-ops/catalog"),api<Summary>("/site-ops/dashboard/summary"),api<Row[]>("/site-ops/reports"),api<Row[]>("/site-ops/dashboard/alerts"),api<Row[]>("/site-ops/audit/events?limit=150")]);setCatalog(c);setSummary(sm);setReports(r);setAlerts(a);setAuditRows(au);if(selectedReport)setDetail(await api<Row>(`/site-ops/reports/${selectedReport}`).catch(()=>null));}catch(e){setError(e instanceof Error?e.message:"Could not load Site Operations")}finally{setLoading(false)}},[selectedReport]);
 useEffect(()=>{void refresh()},[]);
 function success(message:string){setNotice(message);setError("");setTimeout(()=>setNotice(""),3500);void refresh()}
 async function initialize(){try{await api("/site-ops/bootstrap",{method:"POST"});setInitialized(true);success("Phase 7 Site Operations initialised.")}catch(e){setError(e instanceof Error?e.message:"Could not initialise Phase 7")}}
 async function chooseReport(id:string){setSelectedReport(id);setDetail(id?await api<Row>(`/site-ops/reports/${id}`):null);const row=reports.find(r=>String(r.id)===id);if(row)setSelectedActivation(String(row.activation_id??""))}
 async function activate(e:FormEvent){e.preventDefault();try{const row=await api<Row>(`/site-ops/activations/${activation.project_id}`,{method:"POST",body:JSON.stringify({site_id:activation.site_id?Number(activation.site_id):null,notes:activation.notes||null})});setSelectedActivation(String(row.id));success("Approved project/site activated for Site Operations.")}catch(e){setError(e instanceof Error?e.message:"Could not activate site")}}
 async function createDiary(e:FormEvent){e.preventDefault();if(!selectedActivation){setError("Select an active site first.");return}try{const row=await api<Row>(`/site-ops/activations/${selectedActivation}/reports`,{method:"POST",body:JSON.stringify({...diary,rain_hours:Number(diary.rain_hours),weather_summary:diary.weather_summary||null,work_summary:diary.work_summary||null,planned_work:diary.planned_work||null,blockers:diary.blockers||null,safety_summary:diary.safety_summary||null,visitor_summary:diary.visitor_summary||null,no_work_reason:diary.no_work_reason||null})});setSelectedReport(String(row.id));setDetail(await api<Row>(`/site-ops/reports/${row.id}`));success("Daily site report created.")}catch(e){setError(e instanceof Error?e.message:"Could not create daily report")}}
 async function addLabour(e:FormEvent){e.preventDefault();try{await api(`/site-ops/reports/${selectedReport}/labour`,{method:"POST",body:JSON.stringify({employee_id:labour.employee_id?Number(labour.employee_id):null,crew_name:labour.crew_name||null,worker_count:Number(labour.worker_count),regular_hours:Number(labour.regular_hours),overtime_hours:Number(labour.overtime_hours),activity:labour.activity,work_area:labour.work_area||null,cost_centre_id:null,timesheet_entry_id:null,notes:labour.notes||null})});setLabour({...labour,activity:"",notes:""});success("Labour deployment added.")}catch(e){setError(e instanceof Error?e.message:"Could not add labour")}}
 async function addPlant(e:FormEvent){e.preventDefault();const nullable=(v:string)=>v===""?null:Number(v);try{await api(`/site-ops/reports/${selectedReport}/plant`,{method:"POST",body:JSON.stringify({asset_id:Number(plant.asset_id),operator_employee_id:plant.operator_employee_id?Number(plant.operator_employee_id):null,usage_hours:Number(plant.usage_hours),idle_hours:Number(plant.idle_hours),start_odometer_km:nullable(plant.start_odometer_km),end_odometer_km:nullable(plant.end_odometer_km),start_engine_hours:nullable(plant.start_engine_hours),end_engine_hours:nullable(plant.end_engine_hours),activity:plant.activity,breakdown:plant.breakdown,notes:plant.notes||null})});setPlant({...plant,activity:"",notes:""});success("Project plant usage added.")}catch(e){setError(e instanceof Error?e.message:"Could not add plant usage")}}
 async function addMaterial(e:FormEvent){e.preventDefault();try{await api(`/site-ops/reports/${selectedReport}/materials`,{method:"POST",body:JSON.stringify({...material,quantity:Number(material.quantity),unit_cost:Number(material.unit_cost),material_code:material.material_code||null,supplier_or_source:material.supplier_or_source||null,source_reference:material.source_reference||null,work_area:material.work_area||null,waste_reason:material.waste_reason||null,document_id:material.document_id?Number(material.document_id):null,notes:material.notes||null})});setMaterial({...material,description:"",quantity:"1",source_reference:"",notes:""});success("Material evidence added.")}catch(e){setError(e instanceof Error?e.message:"Could not add material")}}
 async function addProgress(e:FormEvent){e.preventDefault();const nullable=(v:string)=>v===""?null:Number(v);try{await api(`/site-ops/reports/${selectedReport}/progress`,{method:"POST",body:JSON.stringify({milestone_id:progress.milestone_id?Number(progress.milestone_id):null,work_item:progress.work_item,unit:progress.unit||null,planned_quantity:nullable(progress.planned_quantity),period_quantity:nullable(progress.period_quantity),cumulative_quantity:nullable(progress.cumulative_quantity),progress_pct:Number(progress.progress_pct),measurement_date:progress.measurement_date,narrative:progress.narrative||null,document_id:progress.document_id?Number(progress.document_id):null})});setProgress({...progress,work_item:"",period_quantity:"",narrative:""});success("Measured progress added.")}catch(e){setError(e instanceof Error?e.message:"Could not add progress")}}
 async function addEvidence(e:FormEvent){e.preventDefault();try{await api(`/site-ops/reports/${selectedReport}/evidence`,{method:"POST",body:JSON.stringify({document_id:Number(evidence.document_id),evidence_type:evidence.evidence_type,caption:evidence.caption||null,work_area:evidence.work_area||null,captured_at:evidence.captured_at?new Date(evidence.captured_at).toISOString():null})});setEvidence({...evidence,document_id:"",caption:""});success("Site evidence linked.")}catch(e){setError(e instanceof Error?e.message:"Could not link evidence")}}
 async function addIncident(e:FormEvent){e.preventDefault();if(!selectedActivation){setError("Select an active site first.");return}try{await api(`/site-ops/activations/${selectedActivation}/incidents`,{method:"POST",body:JSON.stringify({...incident,daily_report_id:selectedReport?Number(selectedReport):null,occurred_at:new Date(incident.occurred_at).toISOString(),employee_id:incident.employee_id?Number(incident.employee_id):null,owner_employee_id:incident.owner_employee_id?Number(incident.owner_employee_id):null,due_date:incident.due_date||null,document_id:incident.document_id?Number(incident.document_id):null,persons_involved:incident.persons_involved||null,immediate_action:incident.immediate_action||null,root_cause:incident.root_cause||null,corrective_action:incident.corrective_action||null})});setIncident({...incident,description:"",persons_involved:"",immediate_action:"",root_cause:"",corrective_action:""});success("Site incident recorded.")}catch(e){setError(e instanceof Error?e.message:"Could not record incident")}}
 async function addQuality(e:FormEvent){e.preventDefault();if(!selectedActivation){setError("Select an active site first.");return}try{await api(`/site-ops/activations/${selectedActivation}/quality`,{method:"POST",body:JSON.stringify({...quality,daily_report_id:selectedReport?Number(selectedReport):null,inspected_at:new Date(quality.inspected_at).toISOString(),inspector_employee_id:quality.inspector_employee_id?Number(quality.inspector_employee_id):null,owner_employee_id:quality.owner_employee_id?Number(quality.owner_employee_id):null,due_date:quality.due_date||null,document_id:quality.document_id?Number(quality.document_id):null,specification_reference:quality.specification_reference||null,nonconformance_number:quality.nonconformance_number||null,corrective_action:quality.corrective_action||null,notes:quality.notes||null})});setQuality({...quality,work_item:"",nonconformance_number:"",corrective_action:"",notes:""});success("Quality inspection recorded.")}catch(e){setError(e instanceof Error?e.message:"Could not record quality inspection")}}
 async function submit(){try{await api(`/site-ops/reports/${selectedReport}/submit`,{method:"POST"});success("Daily report submitted for maker/checker approval.")}catch(e){setError(e instanceof Error?e.message:"Daily report is not ready")}}
 if(loading&&initialized===null)return <main className={styles.page}><div className={styles.loading}><strong>Loading Site Operations…</strong></div></main>;
 if(initialized===false)return <main className={styles.page}><Header/><div className={styles.shell}><section className={styles.initialise}><span className={styles.phase}>Phase 7 · Site Operations</span><h2>Activate controlled daily construction-site operations.</h2><p>Initialisation adds site roles, scoped permissions, incident/quality numbering, daily-report maker/checker workflow and governance policy.</p>{error&&<div className={styles.error}>{error}</div>}<Btn onClick={()=>void initialize()}>Initialise Phase 7</Btn></section></div></main>;
 const labourRows=list(detail?.labour),plantRows=list(detail?.plant),materialRows=list(detail?.materials),progressRows=list(detail?.progress),evidenceRows=list(detail?.evidence),incidentRows=list(detail?.incidents),qualityRows=list(detail?.quality),blockers=Array.isArray(detail?.submission_blockers)?detail?.submission_blockers as unknown[]:[];
 const activationRow=catalog.activations.find(r=>String(r.id)===selectedActivation);const activeProject=activationRow?catalog.projects.find(r=>String(r.id)===String(activationRow.project_id)):null;const projectAssets=catalog.assets.filter(r=>!activeProject||String(r.project_id)===String(activeProject.id));
 return <main className={styles.page}><Header/><div className={styles.shell}>{error&&<div className={styles.error}>{error}</div>}{notice&&<div className={styles.notice}>{notice}</div>}<div className={styles.tabs}>{tabs.map(([id,label])=><button key={id} className={tab===id?styles.active:""} onClick={()=>setTab(id)}>{label}</button>)}</div>
 {summary&&<section className={styles.metrics}><div className={styles.metric}><small>Active sites</small><strong>{summary.active_sites}</strong><span>Phase 6-ready operations</span></div><div className={styles.metric}><small>Approved reports</small><strong>{summary.approved_reports}</strong><span>{summary.reports_pending} pending approval</span></div><div className={styles.metric}><small>Labour hours</small><strong>{Number(summary.approved_labour_hours).toLocaleString()}</strong><span>approved evidence</span></div><div className={styles.metric}><small>Plant hours</small><strong>{Number(summary.approved_plant_hours).toLocaleString()}</strong><span>approved utilisation</span></div><div className={styles.metric}><small>Material cost</small><strong>{cash(summary.approved_material_cost)}</strong><span>{summary.open_incidents} incidents · {summary.open_quality_actions} quality actions</span></div></section>}
 {tab==="dashboard"&&<><section className={styles.hero}><div className={styles.heroCard}><span className={styles.phase}>Phase 7 · Site Operations</span><h2>Daily construction evidence in one controlled report.</h2><p>Labour, plant, materials, progress, safety, quality and site evidence remain tied to the exact project/site/day and become immutable after approval.</p></div><div className={styles.heroCard}><small>Operational alerts</small><h2>{alerts.length}</h2><p>missing reports · approvals · incidents · quality</p></div></section><section className={styles.panel}><div className={styles.panelHead}><div><h3>Daily report register</h3><p>Select a report to work across the evidence tabs.</p></div><a className={styles.button} href="/api/v1/site-ops/exports/daily-reports.csv">Export approved CSV</a></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Date</th><th>Project</th><th>Site</th><th>Shift</th><th>Status</th><th>Summary</th></tr></thead><tbody>{reports.map(r=><tr key={num(r,"id")} className={styles.clickable} onClick={()=>void chooseReport(String(r.id))}><td>{text(r,"report_date")}</td><td>{text(r,"project_id")}</td><td>{text(r,"site_id")}</td><td>{text(r,"shift")}</td><td><span className={`${styles.badge} ${badge(text(r,"status"))}`}>{text(r,"status")}</span></td><td>{text(r,"work_summary")||text(r,"no_work_reason")}</td></tr>)}</tbody></table></div></section><section className={styles.panel}><div className={styles.panelHead}><div><h3>Site Operations alerts</h3><p>Items requiring action before clean daily control.</p></div></div><Data rows={alerts} cols={["severity","type","project_id","site_id","message"]}/></section></>}
 {tab==="activate"&&<section className={styles.panel}><div className={styles.panelHead}><div><h3>Phase 6 → Site Operations activation</h3><p>Only projects with approved mobilisation readiness snapshots can activate.</p></div></div><form className={styles.form} onSubmit={activate}><Field label="Ready project"><select required value={activation.project_id} onChange={e=>setActivation({...activation,project_id:e.target.value})}><option value="">Select project</option>{catalog.projects.map(r=><option key={String(r.id)} value={String(r.id)}>{text(r,"project_number")} · {text(r,"name")}</option>)}</select></Field><Field label="Site ID (optional)"><input value={activation.site_id} onChange={e=>setActivation({...activation,site_id:e.target.value})}/></Field><Field label="Notes" wide><input value={activation.notes} onChange={e=>setActivation({...activation,notes:e.target.value})}/></Field><div className={styles.formActions}><Btn type="submit" disabled={!can("siteops.manage")}>Activate Site Operations</Btn></div></form><Data rows={catalog.activations} cols={["id","project_id","site_id","status","activated_by","activated_at"]}/></section>}
 {tab==="diary"&&<><section className={styles.panel}><div className={styles.panelHead}><div><h3>Daily site diary</h3><p>Select activation and create one controlled report per site/date/shift.</p></div></div><div className={styles.toolbar}><select value={selectedActivation} onChange={e=>setSelectedActivation(e.target.value)}><option value="">Select active site</option>{catalog.activations.filter(r=>text(r,"status")==="active").map(r=><option key={String(r.id)} value={String(r.id)}>Activation {String(r.id)} · Project {text(r,"project_id")} · Site {text(r,"site_id")}</option>)}</select><select value={selectedReport} onChange={e=>void chooseReport(e.target.value)}><option value="">Select report</option>{reports.map(r=><option key={String(r.id)} value={String(r.id)}>{text(r,"report_date")} · {text(r,"shift")} · {text(r,"status")}</option>)}</select></div><form className={styles.form} onSubmit={createDiary}><Field label="Report date"><input type="date" required value={diary.report_date} onChange={e=>setDiary({...diary,report_date:e.target.value})}/></Field><Field label="Shift"><select value={diary.shift} onChange={e=>setDiary({...diary,shift:e.target.value})}><option>day</option><option>night</option><option>other</option></select></Field><Field label="Weather"><input value={diary.weather_summary} onChange={e=>setDiary({...diary,weather_summary:e.target.value})}/></Field><Field label="Rain hours"><input type="number" min="0" max="24" step="0.25" value={diary.rain_hours} onChange={e=>setDiary({...diary,rain_hours:e.target.value})}/></Field><Field label="Work summary" wide><textarea value={diary.work_summary} onChange={e=>setDiary({...diary,work_summary:e.target.value})}/></Field><Field label="Planned work" wide><textarea value={diary.planned_work} onChange={e=>setDiary({...diary,planned_work:e.target.value})}/></Field><Field label="Blockers" wide><textarea value={diary.blockers} onChange={e=>setDiary({...diary,blockers:e.target.value})}/></Field><Field label="Safety summary" wide><textarea value={diary.safety_summary} onChange={e=>setDiary({...diary,safety_summary:e.target.value})}/></Field><Field label="No-work reason" wide><textarea value={diary.no_work_reason} onChange={e=>setDiary({...diary,no_work_reason:e.target.value})}/></Field><div className={styles.formActions}><Btn type="submit">Create daily report</Btn>{selectedReport&&<Btn type="button" onClick={()=>void submit()}>Submit for approval</Btn>}</div></form>{blockers.length>0&&<div className={styles.warning}><strong>Submission blockers:</strong> {blockers.map(String).join(" · ")}</div>}</section></>}
 {tab==="labour"&&<section className={styles.panel}><div className={styles.panelHead}><div><h3>Labour deployment</h3><p>Individual employees or named crews; operational evidence does not silently replace payroll timesheets.</p></div></div><form className={styles.form} onSubmit={addLabour}><Field label="Employee"><select value={labour.employee_id} onChange={e=>setLabour({...labour,employee_id:e.target.value})}><option value="">Named crew instead</option>{catalog.employees.map(r=><option key={String(r.id)} value={String(r.id)}>{text(r,"employee_number")} · {text(r,"name")}</option>)}</select></Field><Field label="Crew name"><input value={labour.crew_name} onChange={e=>setLabour({...labour,crew_name:e.target.value})}/></Field><Field label="Workers"><input type="number" min="1" value={labour.worker_count} onChange={e=>setLabour({...labour,worker_count:e.target.value})}/></Field><Field label="Regular hours"><input type="number" min="0" max="24" step="0.25" value={labour.regular_hours} onChange={e=>setLabour({...labour,regular_hours:e.target.value})}/></Field><Field label="Overtime"><input type="number" min="0" max="24" step="0.25" value={labour.overtime_hours} onChange={e=>setLabour({...labour,overtime_hours:e.target.value})}/></Field><Field label="Activity" wide><input required value={labour.activity} onChange={e=>setLabour({...labour,activity:e.target.value})}/></Field><Field label="Work area"><input value={labour.work_area} onChange={e=>setLabour({...labour,work_area:e.target.value})}/></Field><div className={styles.formActions}><Btn type="submit" disabled={!selectedReport}>Add labour</Btn></div></form><Data rows={labourRows} cols={["employee_id","crew_name","worker_count","regular_hours","overtime_hours","activity","work_area"]}/></section>}
 {tab==="plant"&&<section className={styles.panel}><div className={styles.panelHead}><div><h3>Plant / equipment usage</h3><p>Only serviceable plant confirmed to this Phase 6 project/site can be used.</p></div></div><form className={styles.form} onSubmit={addPlant}><Field label="Allocated plant"><select required value={plant.asset_id} onChange={e=>setPlant({...plant,asset_id:e.target.value})}><option value="">Select plant</option>{projectAssets.map(r=><option key={String(r.asset_id)} value={String(r.asset_id)}>{text(r,"asset_number")} · {text(r,"name")}</option>)}</select></Field><Field label="Operator"><select value={plant.operator_employee_id} onChange={e=>setPlant({...plant,operator_employee_id:e.target.value})}><option value="">Not recorded</option>{catalog.employees.map(r=><option key={String(r.id)} value={String(r.id)}>{text(r,"name")}</option>)}</select></Field><Field label="Usage hours"><input type="number" min="0" max="24" step="0.25" value={plant.usage_hours} onChange={e=>setPlant({...plant,usage_hours:e.target.value})}/></Field><Field label="Idle hours"><input type="number" min="0" max="24" step="0.25" value={plant.idle_hours} onChange={e=>setPlant({...plant,idle_hours:e.target.value})}/></Field><Field label="Activity" wide><input required value={plant.activity} onChange={e=>setPlant({...plant,activity:e.target.value})}/></Field><Field label="Breakdown"><select value={plant.breakdown?"yes":"no"} onChange={e=>setPlant({...plant,breakdown:e.target.value==="yes"})}><option value="no">No</option><option value="yes">Yes</option></select></Field><div className={styles.formActions}><Btn type="submit" disabled={!selectedReport}>Add plant usage</Btn></div></form><Data rows={plantRows} cols={["asset_id","operator_employee_id","usage_hours","idle_hours","activity","breakdown"]}/></section>}
 {tab==="materials"&&<section className={styles.panel}><div className={styles.panelHead}><div><h3>Material movement evidence</h3><p>Phase 7 records site evidence; Phase 8 will own procurement/stores inventory ledgers.</p></div></div><form className={styles.form} onSubmit={addMaterial}><Field label="Movement"><select value={material.movement_type} onChange={e=>setMaterial({...material,movement_type:e.target.value})}><option>received</option><option>used</option><option>returned</option><option>waste</option></select></Field><Field label="Description" wide><input required value={material.description} onChange={e=>setMaterial({...material,description:e.target.value})}/></Field><Field label="Unit"><input required value={material.unit} onChange={e=>setMaterial({...material,unit:e.target.value})}/></Field><Field label="Quantity"><input type="number" min="0.0001" step="0.0001" value={material.quantity} onChange={e=>setMaterial({...material,quantity:e.target.value})}/></Field><Field label="Unit cost"><input type="number" min="0" step="0.01" value={material.unit_cost} onChange={e=>setMaterial({...material,unit_cost:e.target.value})}/></Field><Field label="Reference"><input value={material.source_reference} onChange={e=>setMaterial({...material,source_reference:e.target.value})}/></Field><Field label="Waste reason" wide><input value={material.waste_reason} onChange={e=>setMaterial({...material,waste_reason:e.target.value})}/></Field><div className={styles.formActions}><Btn type="submit" disabled={!selectedReport}>Add material evidence</Btn></div></form><Data rows={materialRows} cols={["movement_type","description","unit","quantity","unit_cost","total_cost","source_reference"]}/></section>}
 {tab==="progress"&&<section className={styles.panel}><div className={styles.panelHead}><div><h3>Measured progress</h3><p>Progress can reference Phase 6 milestones and supporting documents.</p></div></div><form className={styles.form} onSubmit={addProgress}><Field label="Work item" wide><input required value={progress.work_item} onChange={e=>setProgress({...progress,work_item:e.target.value})}/></Field><Field label="Progress %"><input type="number" min="0" max="100" step="0.001" value={progress.progress_pct} onChange={e=>setProgress({...progress,progress_pct:e.target.value})}/></Field><Field label="Measurement date"><input type="date" value={progress.measurement_date} onChange={e=>setProgress({...progress,measurement_date:e.target.value})}/></Field><Field label="Period quantity"><input type="number" min="0" step="0.0001" value={progress.period_quantity} onChange={e=>setProgress({...progress,period_quantity:e.target.value})}/></Field><Field label="Cumulative quantity"><input type="number" min="0" step="0.0001" value={progress.cumulative_quantity} onChange={e=>setProgress({...progress,cumulative_quantity:e.target.value})}/></Field><Field label="Narrative" wide><textarea value={progress.narrative} onChange={e=>setProgress({...progress,narrative:e.target.value})}/></Field><div className={styles.formActions}><Btn type="submit" disabled={!selectedReport}>Add measured progress</Btn></div></form><Data rows={progressRows} cols={["work_item","measurement_date","period_quantity","cumulative_quantity","progress_pct","milestone_id"]}/></section>}
 {tab==="evidence"&&<section className={styles.panel}><div className={styles.panelHead}><div><h3>Photos & document evidence</h3><p>Evidence reuses Phase 1 document control instead of storing uncontrolled attachments.</p></div></div><form className={styles.form} onSubmit={addEvidence}><Field label="Document"><select required value={evidence.document_id} onChange={e=>setEvidence({...evidence,document_id:e.target.value})}><option value="">Select document</option>{catalog.documents.map(r=><option key={String(r.id)} value={String(r.id)}>{text(r,"title")}</option>)}</select></Field><Field label="Evidence type"><select value={evidence.evidence_type} onChange={e=>setEvidence({...evidence,evidence_type:e.target.value})}><option>photo</option><option>video</option><option>drawing</option><option>delivery_note</option><option>measurement</option><option>instruction</option><option>other</option></select></Field><Field label="Caption" wide><input value={evidence.caption} onChange={e=>setEvidence({...evidence,caption:e.target.value})}/></Field><div className={styles.formActions}><Btn type="submit" disabled={!selectedReport}>Link evidence</Btn></div></form><Data rows={evidenceRows} cols={["evidence_type","document_id","caption","work_area","captured_at"]}/></section>}
 {tab==="incidents"&&<section className={styles.panel}><div className={styles.panelHead}><div><h3>Safety / environment / security incidents</h3><p>Serious, critical and fatal records require immediate action evidence.</p></div><Link className={styles.button} href="/site-operations/control">Open control queue</Link></div><form className={styles.form} onSubmit={addIncident}><Field label="Type"><select value={incident.incident_type} onChange={e=>setIncident({...incident,incident_type:e.target.value})}><option>safety</option><option>near_miss</option><option>environment</option><option>security</option><option>equipment</option><option>property</option><option>other</option></select></Field><Field label="Severity"><select value={incident.severity} onChange={e=>setIncident({...incident,severity:e.target.value})}><option>minor</option><option>moderate</option><option>serious</option><option>critical</option><option>fatal</option></select></Field><Field label="Occurred"><input type="datetime-local" value={incident.occurred_at} onChange={e=>setIncident({...incident,occurred_at:e.target.value})}/></Field><Field label="Description" wide><textarea required value={incident.description} onChange={e=>setIncident({...incident,description:e.target.value})}/></Field><Field label="Immediate action" wide><textarea value={incident.immediate_action} onChange={e=>setIncident({...incident,immediate_action:e.target.value})}/></Field><Field label="Corrective action" wide><textarea value={incident.corrective_action} onChange={e=>setIncident({...incident,corrective_action:e.target.value})}/></Field><div className={styles.formActions}><Btn type="submit" disabled={!selectedActivation}>Record incident</Btn></div></form><Data rows={incidentRows} cols={["incident_number","incident_type","severity","description","status","due_date"]}/></section>}
 {tab==="quality"&&<section className={styles.panel}><div className={styles.panelHead}><div><h3>Quality inspections & NCRs</h3><p>Failed checks require corrective action before a linked daily report can be approved.</p></div><Link className={styles.button} href="/site-operations/control">Open control queue</Link></div><form className={styles.form} onSubmit={addQuality}><Field label="Check type"><select value={quality.check_type} onChange={e=>setQuality({...quality,check_type:e.target.value})}><option>inspection</option><option>test</option><option>hold_point</option><option>ncr</option><option>snag</option><option>handover</option><option>other</option></select></Field><Field label="Result"><select value={quality.result} onChange={e=>setQuality({...quality,result:e.target.value})}><option>pass</option><option>conditional</option><option>fail</option></select></Field><Field label="Work item" wide><input required value={quality.work_item} onChange={e=>setQuality({...quality,work_item:e.target.value})}/></Field><Field label="Specification"><input value={quality.specification_reference} onChange={e=>setQuality({...quality,specification_reference:e.target.value})}/></Field><Field label="NCR number"><input value={quality.nonconformance_number} onChange={e=>setQuality({...quality,nonconformance_number:e.target.value})}/></Field><Field label="Corrective action" wide><textarea value={quality.corrective_action} onChange={e=>setQuality({...quality,corrective_action:e.target.value})}/></Field><div className={styles.formActions}><Btn type="submit" disabled={!selectedActivation}>Record quality check</Btn></div></form><Data rows={qualityRows} cols={["inspection_number","check_type","work_item","result","nonconformance_number","status"]}/></section>}
 {tab==="audit"&&<section className={styles.panel}><div className={styles.panelHead}><div><h3>Site Operations audit</h3><p>Scoped operational history for Phase 7.</p></div></div><Data rows={auditRows} cols={["occurred_at","actor","action","entity_type","entity_id","project_id","site_id"]}/></section>}
 </div></main>
}
function Header(){return <header className={styles.header}><div className={styles.brand}><div className={styles.brandMark}>BT</div><div><small>BUILDTRACK · CONSTRUCTION OPERATIONS</small><h1>Site Operations</h1><p>Daily site diary · labour · plant · materials · progress · safety · quality</p></div></div><div className={styles.headerActions}><Link className={styles.link} href="/site-operations/control">Site Operations Control</Link><Link className={styles.link} href="/projects">Project Mobilisation</Link><Link className={styles.link} href="/fleet">Fleet &amp; Plant</Link></div></header>}
