from __future__ import annotations
from datetime import date,datetime,timezone
from decimal import Decimal
from sqlalchemy import Date,DateTime,ForeignKey,Integer,JSON,Numeric,String,Text,UniqueConstraint
from sqlalchemy.orm import Mapped,mapped_column
from app.db.base import Base
def utcnow()->datetime:return datetime.now(timezone.utc)
class AuthorityLimit(Base):
 __tablename__="authority_limits";__table_args__=(UniqueConstraint("company_id","role_id","branch_id","site_id","module","transaction_type","effective_from",name="uq_authority_limit_scope"),)
 id:Mapped[int]=mapped_column(Integer,primary_key=True);company_id:Mapped[int]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),nullable=False,index=True);role_id:Mapped[int]=mapped_column(ForeignKey("roles.id",ondelete="RESTRICT"),nullable=False,index=True);branch_id:Mapped[int]=mapped_column(ForeignKey("branches.id",ondelete="RESTRICT"),nullable=False,index=True);site_id:Mapped[int|None]=mapped_column(ForeignKey("sites.id",ondelete="SET NULL"),index=True);limit_number:Mapped[str]=mapped_column(String(80),nullable=False,index=True);module:Mapped[str]=mapped_column(String(80),nullable=False,index=True);transaction_type:Mapped[str]=mapped_column(String(80),nullable=False,index=True);minimum_amount:Mapped[Decimal]=mapped_column(Numeric(18,2),nullable=False,default=Decimal("0"));maximum_amount:Mapped[Decimal]=mapped_column(Numeric(18,2),nullable=False);currency:Mapped[str]=mapped_column(String(8),nullable=False,default="LSL");effective_from:Mapped[date]=mapped_column(Date,nullable=False,index=True);effective_to:Mapped[date|None]=mapped_column(Date,index=True);status:Mapped[str]=mapped_column(String(24),nullable=False,default="draft",index=True);document_id:Mapped[int|None]=mapped_column(ForeignKey("documents.id",ondelete="SET NULL"),index=True);notes:Mapped[str|None]=mapped_column(Text);prepared_by:Mapped[str]=mapped_column(String(255),nullable=False);submitted_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));approved_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));approved_by:Mapped[str|None]=mapped_column(String(255));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False,default=utcnow)
class AuthorityAuditEvent(Base):
 __tablename__="authority_audit_events"
 id:Mapped[int]=mapped_column(Integer,primary_key=True);company_id:Mapped[int]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),nullable=False,index=True);branch_id:Mapped[int|None]=mapped_column(ForeignKey("branches.id",ondelete="SET NULL"),index=True);site_id:Mapped[int|None]=mapped_column(ForeignKey("sites.id",ondelete="SET NULL"),index=True);actor:Mapped[str]=mapped_column(String(255),nullable=False);action:Mapped[str]=mapped_column(String(120),nullable=False,index=True);entity_type:Mapped[str]=mapped_column(String(80),nullable=False);entity_id:Mapped[str]=mapped_column(String(100),nullable=False);detail:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict);occurred_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False,default=utcnow,index=True)
