from __future__ import annotations
from datetime import date,datetime,timezone
from decimal import Decimal
from sqlalchemy import Date,DateTime,ForeignKey,Integer,JSON,Numeric,String,Text,UniqueConstraint
from sqlalchemy.orm import Mapped,mapped_column
from app.db.base import Base
def utcnow()->datetime:return datetime.now(timezone.utc)
class BusinessOpportunity(Base):
 __tablename__="business_opportunities";__table_args__=(UniqueConstraint("company_id","opportunity_number",name="uq_business_opportunity_number"),)
 id:Mapped[int]=mapped_column(Integer,primary_key=True);company_id:Mapped[int]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),nullable=False,index=True);branch_id:Mapped[int]=mapped_column(ForeignKey("branches.id",ondelete="RESTRICT"),nullable=False,index=True);site_id:Mapped[int|None]=mapped_column(ForeignKey("sites.id",ondelete="SET NULL"),index=True);opportunity_number:Mapped[str]=mapped_column(String(80),nullable=False,index=True);title:Mapped[str]=mapped_column(String(300),nullable=False);client_name:Mapped[str]=mapped_column(String(240),nullable=False,index=True);client_contact:Mapped[str|None]=mapped_column(String(240));sector:Mapped[str|None]=mapped_column(String(120));source:Mapped[str]=mapped_column(String(80),nullable=False,default="referral");estimated_value:Mapped[Decimal|None]=mapped_column(Numeric(18,2));probability:Mapped[int]=mapped_column(Integer,nullable=False,default=0);expected_bid_date:Mapped[date|None]=mapped_column(Date,index=True);scope_summary:Mapped[str|None]=mapped_column(Text);next_action:Mapped[str|None]=mapped_column(String(300));next_action_date:Mapped[date|None]=mapped_column(Date,index=True);status:Mapped[str]=mapped_column(String(24),nullable=False,default="lead",index=True);tender_id:Mapped[int|None]=mapped_column(ForeignKey("tenders.id",ondelete="SET NULL"),index=True);prepared_by:Mapped[str]=mapped_column(String(255),nullable=False);qualified_by:Mapped[str|None]=mapped_column(String(255));qualified_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));closed_by:Mapped[str|None]=mapped_column(String(255));closed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));close_note:Mapped[str|None]=mapped_column(Text);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False,default=utcnow);updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False,default=utcnow,onupdate=utcnow)
class BusinessOpportunityActivity(Base):
 __tablename__="business_opportunity_activities"
 id:Mapped[int]=mapped_column(Integer,primary_key=True);company_id:Mapped[int]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),nullable=False,index=True);opportunity_id:Mapped[int]=mapped_column(ForeignKey("business_opportunities.id",ondelete="CASCADE"),nullable=False,index=True);activity_date:Mapped[date]=mapped_column(Date,nullable=False,index=True);activity_type:Mapped[str]=mapped_column(String(80),nullable=False);note:Mapped[str]=mapped_column(Text,nullable=False);next_action:Mapped[str|None]=mapped_column(String(300));next_action_date:Mapped[date|None]=mapped_column(Date);recorded_by:Mapped[str]=mapped_column(String(255),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False,default=utcnow)
class BusinessDevelopmentAuditEvent(Base):
 __tablename__="business_development_audit_events";id:Mapped[int]=mapped_column(Integer,primary_key=True);company_id:Mapped[int]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),nullable=False,index=True);branch_id:Mapped[int|None]=mapped_column(ForeignKey("branches.id",ondelete="SET NULL"),index=True);site_id:Mapped[int|None]=mapped_column(ForeignKey("sites.id",ondelete="SET NULL"),index=True);actor:Mapped[str]=mapped_column(String(255),nullable=False);action:Mapped[str]=mapped_column(String(120),nullable=False,index=True);entity_type:Mapped[str]=mapped_column(String(80),nullable=False);entity_id:Mapped[str]=mapped_column(String(100),nullable=False);detail:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict);occurred_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False,default=utcnow,index=True)
