from __future__ import annotations
from datetime import date,datetime,timezone
from sqlalchemy import Date,DateTime,ForeignKey,Integer,JSON,String,Text,UniqueConstraint
from sqlalchemy.orm import Mapped,mapped_column
from app.db.base import Base
def utcnow()->datetime:return datetime.now(timezone.utc)
class ChangeRequest(Base):
 __tablename__="change_requests";__table_args__=(UniqueConstraint("company_id","change_number",name="uq_change_request_number"),)
 id:Mapped[int]=mapped_column(Integer,primary_key=True);company_id:Mapped[int]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),nullable=False,index=True);branch_id:Mapped[int]=mapped_column(ForeignKey("branches.id",ondelete="RESTRICT"),nullable=False,index=True);site_id:Mapped[int|None]=mapped_column(ForeignKey("sites.id",ondelete="SET NULL"),index=True);change_number:Mapped[str]=mapped_column(String(80),nullable=False,index=True);title:Mapped[str]=mapped_column(String(300),nullable=False);change_type:Mapped[str]=mapped_column(String(48),nullable=False,index=True);risk_level:Mapped[str]=mapped_column(String(24),nullable=False,index=True);description:Mapped[str]=mapped_column(Text,nullable=False);impact_assessment:Mapped[str|None]=mapped_column(Text);pilot_plan:Mapped[str|None]=mapped_column(Text);planned_release_date:Mapped[date|None]=mapped_column(Date,index=True);status:Mapped[str]=mapped_column(String(24),nullable=False,default="draft",index=True);evidence_document_id:Mapped[int|None]=mapped_column(ForeignKey("documents.id",ondelete="SET NULL"),index=True);uat_document_id:Mapped[int|None]=mapped_column(ForeignKey("documents.id",ondelete="SET NULL"),index=True);release_document_id:Mapped[int|None]=mapped_column(ForeignKey("documents.id",ondelete="SET NULL"),index=True);prepared_by:Mapped[str]=mapped_column(String(255),nullable=False);submitted_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));approved_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));approved_by:Mapped[str|None]=mapped_column(String(255));released_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False,default=utcnow)
class ChangeAuditEvent(Base):
 __tablename__="change_audit_events";id:Mapped[int]=mapped_column(Integer,primary_key=True);company_id:Mapped[int]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),nullable=False,index=True);branch_id:Mapped[int|None]=mapped_column(ForeignKey("branches.id",ondelete="SET NULL"),index=True);site_id:Mapped[int|None]=mapped_column(ForeignKey("sites.id",ondelete="SET NULL"),index=True);actor:Mapped[str]=mapped_column(String(255),nullable=False);action:Mapped[str]=mapped_column(String(120),nullable=False,index=True);entity_type:Mapped[str]=mapped_column(String(80),nullable=False);entity_id:Mapped[str]=mapped_column(String(100),nullable=False);detail:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict);occurred_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False,default=utcnow,index=True)
