from __future__ import annotations
from datetime import date,datetime,timezone
from sqlalchemy import Date,DateTime,ForeignKey,Integer,JSON,String,Text,UniqueConstraint
from sqlalchemy.orm import Mapped,mapped_column
from app.db.base import Base
def utcnow()->datetime:return datetime.now(timezone.utc)
class ClientSharePack(Base):
 __tablename__="client_share_packs";__table_args__=(UniqueConstraint("company_id","pack_number",name="uq_client_share_pack_number"),UniqueConstraint("token_hash",name="uq_client_share_token"))
 id:Mapped[int]=mapped_column(Integer,primary_key=True);company_id:Mapped[int]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),nullable=False,index=True);project_id:Mapped[int]=mapped_column(ForeignKey("projects.id",ondelete="CASCADE"),nullable=False,index=True);branch_id:Mapped[int]=mapped_column(ForeignKey("branches.id",ondelete="RESTRICT"),nullable=False,index=True);site_id:Mapped[int]=mapped_column(ForeignKey("sites.id",ondelete="RESTRICT"),nullable=False,index=True);pack_number:Mapped[str]=mapped_column(String(80),nullable=False,index=True);title:Mapped[str]=mapped_column(String(300),nullable=False);client_name:Mapped[str]=mapped_column(String(240),nullable=False);message:Mapped[str|None]=mapped_column(Text);document_id:Mapped[int]=mapped_column(ForeignKey("documents.id",ondelete="RESTRICT"),nullable=False,index=True);expiry_date:Mapped[date]=mapped_column(Date,nullable=False,index=True);status:Mapped[str]=mapped_column(String(24),nullable=False,default="draft",index=True);token_hash:Mapped[str|None]=mapped_column(String(64),index=True);prepared_by:Mapped[str]=mapped_column(String(255),nullable=False);submitted_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));published_by:Mapped[str|None]=mapped_column(String(255));published_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));revoked_by:Mapped[str|None]=mapped_column(String(255));revoked_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False,default=utcnow)
class ClientPortalAuditEvent(Base):
 __tablename__="client_portal_audit_events";id:Mapped[int]=mapped_column(Integer,primary_key=True);company_id:Mapped[int]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),nullable=False,index=True);branch_id:Mapped[int|None]=mapped_column(ForeignKey("branches.id",ondelete="SET NULL"),index=True);site_id:Mapped[int|None]=mapped_column(ForeignKey("sites.id",ondelete="SET NULL"),index=True);actor:Mapped[str]=mapped_column(String(255),nullable=False);action:Mapped[str]=mapped_column(String(120),nullable=False,index=True);entity_type:Mapped[str]=mapped_column(String(80),nullable=False);entity_id:Mapped[str]=mapped_column(String(100),nullable=False);detail:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict);occurred_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False,default=utcnow,index=True)
