from __future__ import annotations
from datetime import date,datetime,timezone
from sqlalchemy import Date,DateTime,ForeignKey,Integer,JSON,String,Text,UniqueConstraint
from sqlalchemy.orm import Mapped,mapped_column
from app.db.base import Base
def utcnow()->datetime:return datetime.now(timezone.utc)
class ClientAccount(Base):
 __tablename__="client_accounts";__table_args__=(UniqueConstraint("company_id","account_number",name="uq_client_account_number"),)
 id:Mapped[int]=mapped_column(Integer,primary_key=True);company_id:Mapped[int]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),nullable=False,index=True);branch_id:Mapped[int]=mapped_column(ForeignKey("branches.id",ondelete="RESTRICT"),nullable=False,index=True);site_id:Mapped[int|None]=mapped_column(ForeignKey("sites.id",ondelete="SET NULL"),index=True);account_number:Mapped[str]=mapped_column(String(80),nullable=False,index=True);legal_name:Mapped[str]=mapped_column(String(240),nullable=False,index=True);trading_name:Mapped[str|None]=mapped_column(String(240));sector:Mapped[str|None]=mapped_column(String(120));status:Mapped[str]=mapped_column(String(24),nullable=False,default="active",index=True);account_manager:Mapped[str|None]=mapped_column(String(255));notes:Mapped[str|None]=mapped_column(Text);created_by:Mapped[str]=mapped_column(String(255),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False,default=utcnow);updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False,default=utcnow,onupdate=utcnow)
class ClientAccountContact(Base):
 __tablename__="client_account_contacts";__table_args__=(UniqueConstraint("account_id","email",name="uq_client_account_contact_email"),)
 id:Mapped[int]=mapped_column(Integer,primary_key=True);company_id:Mapped[int]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),nullable=False,index=True);account_id:Mapped[int]=mapped_column(ForeignKey("client_accounts.id",ondelete="CASCADE"),nullable=False,index=True);full_name:Mapped[str]=mapped_column(String(240),nullable=False);role:Mapped[str|None]=mapped_column(String(120));email:Mapped[str|None]=mapped_column(String(255));phone:Mapped[str|None]=mapped_column(String(64));is_primary:Mapped[bool]=mapped_column(nullable=False,default=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False,default=utcnow)
class ClientFeedback(Base):
 __tablename__="client_feedback"
 id:Mapped[int]=mapped_column(Integer,primary_key=True);company_id:Mapped[int]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),nullable=False,index=True);account_id:Mapped[int]=mapped_column(ForeignKey("client_accounts.id",ondelete="CASCADE"),nullable=False,index=True);feedback_date:Mapped[date]=mapped_column(Date,nullable=False,index=True);category:Mapped[str]=mapped_column(String(80),nullable=False);score:Mapped[int]=mapped_column(Integer,nullable=False);comment:Mapped[str]=mapped_column(Text,nullable=False);action_plan:Mapped[str|None]=mapped_column(Text);status:Mapped[str]=mapped_column(String(24),nullable=False,default="received",index=True);recorded_by:Mapped[str]=mapped_column(String(255),nullable=False);verified_by:Mapped[str|None]=mapped_column(String(255));verified_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False,default=utcnow)
class ClientAccountAuditEvent(Base):
 __tablename__="client_account_audit_events";id:Mapped[int]=mapped_column(Integer,primary_key=True);company_id:Mapped[int]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),nullable=False,index=True);branch_id:Mapped[int|None]=mapped_column(ForeignKey("branches.id",ondelete="SET NULL"),index=True);site_id:Mapped[int|None]=mapped_column(ForeignKey("sites.id",ondelete="SET NULL"),index=True);actor:Mapped[str]=mapped_column(String(255),nullable=False);action:Mapped[str]=mapped_column(String(120),nullable=False,index=True);entity_type:Mapped[str]=mapped_column(String(80),nullable=False);entity_id:Mapped[str]=mapped_column(String(100),nullable=False);detail:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict);occurred_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False,default=utcnow,index=True)
