from __future__ import annotations
from datetime import date,datetime,timezone
from sqlalchemy import Date,DateTime,ForeignKey,Integer,JSON,Numeric,String,Text
from sqlalchemy.orm import Mapped,mapped_column
from app.db.base import Base
def utcnow()->datetime:return datetime.now(timezone.utc)
class ContractNotice(Base):
 __tablename__="contract_notices";id:Mapped[int]=mapped_column(Integer,primary_key=True);company_id:Mapped[int]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),nullable=False,index=True);branch_id:Mapped[int]=mapped_column(ForeignKey("branches.id",ondelete="RESTRICT"),nullable=False,index=True);site_id:Mapped[int|None]=mapped_column(ForeignKey("sites.id",ondelete="SET NULL"),index=True);contract_id:Mapped[int]=mapped_column(ForeignKey("client_contracts.id",ondelete="CASCADE"),nullable=False,index=True);notice_number:Mapped[str]=mapped_column(String(80),nullable=False,index=True);notice_type:Mapped[str]=mapped_column(String(80),nullable=False);subject:Mapped[str]=mapped_column(String(300),nullable=False);event_date:Mapped[date]=mapped_column(Date,nullable=False);due_date:Mapped[date|None]=mapped_column(Date,index=True);status:Mapped[str]=mapped_column(String(24),nullable=False,default="draft",index=True);prepared_by:Mapped[str]=mapped_column(String(255),nullable=False);issued_by:Mapped[str|None]=mapped_column(String(255));issued_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));detail:Mapped[str]=mapped_column(Text,nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False,default=utcnow)
class ExtensionOfTime(Base):
 __tablename__="contract_extensions_of_time";id:Mapped[int]=mapped_column(Integer,primary_key=True);company_id:Mapped[int]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),nullable=False,index=True);branch_id:Mapped[int]=mapped_column(ForeignKey("branches.id",ondelete="RESTRICT"),nullable=False,index=True);site_id:Mapped[int|None]=mapped_column(ForeignKey("sites.id",ondelete="SET NULL"),index=True);contract_id:Mapped[int]=mapped_column(ForeignKey("client_contracts.id",ondelete="CASCADE"),nullable=False,index=True);notice_id:Mapped[int|None]=mapped_column(ForeignKey("contract_notices.id",ondelete="SET NULL"));reason:Mapped[str]=mapped_column(String(300),nullable=False);days_requested:Mapped[int]=mapped_column(Integer,nullable=False);impact_summary:Mapped[str]=mapped_column(Text,nullable=False);status:Mapped[str]=mapped_column(String(24),nullable=False,default="submitted",index=True);submitted_by:Mapped[str]=mapped_column(String(255),nullable=False);reviewed_by:Mapped[str|None]=mapped_column(String(255));reviewed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));review_note:Mapped[str|None]=mapped_column(Text);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False,default=utcnow)
class ContractVariationInstruction(Base):
 __tablename__="contract_variation_instructions";id:Mapped[int]=mapped_column(Integer,primary_key=True);company_id:Mapped[int]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),nullable=False,index=True);branch_id:Mapped[int]=mapped_column(ForeignKey("branches.id",ondelete="RESTRICT"),nullable=False,index=True);site_id:Mapped[int|None]=mapped_column(ForeignKey("sites.id",ondelete="SET NULL"),index=True);contract_id:Mapped[int]=mapped_column(ForeignKey("client_contracts.id",ondelete="CASCADE"),nullable=False,index=True);instruction_number:Mapped[str]=mapped_column(String(80),nullable=False,index=True);description:Mapped[str]=mapped_column(Text,nullable=False);estimated_value:Mapped[float]=mapped_column(Numeric(18,2),nullable=False);status:Mapped[str]=mapped_column(String(24),nullable=False,default="draft",index=True);prepared_by:Mapped[str]=mapped_column(String(255),nullable=False);approved_by:Mapped[str|None]=mapped_column(String(255));approved_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False,default=utcnow)
class ContractControlAuditEvent(Base):
 __tablename__="contract_control_audit_events";id:Mapped[int]=mapped_column(Integer,primary_key=True);company_id:Mapped[int]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),nullable=False,index=True);branch_id:Mapped[int|None]=mapped_column(ForeignKey("branches.id",ondelete="SET NULL"),index=True);site_id:Mapped[int|None]=mapped_column(ForeignKey("sites.id",ondelete="SET NULL"),index=True);actor:Mapped[str]=mapped_column(String(255),nullable=False);action:Mapped[str]=mapped_column(String(120),nullable=False,index=True);entity_type:Mapped[str]=mapped_column(String(80),nullable=False);entity_id:Mapped[str]=mapped_column(String(100),nullable=False);detail:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict);occurred_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False,default=utcnow,index=True)
