from __future__ import annotations
from datetime import date, datetime, timezone
from sqlalchemy import Date, DateTime, ForeignKey, Integer, JSON, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column
from app.db.base import Base
def utcnow() -> datetime: return datetime.now(timezone.utc)
class DataQualityRun(Base):
    __tablename__="data_quality_runs"
    __table_args__=(UniqueConstraint("project_id","run_date","sequence",name="uq_data_quality_run_day"),)
    id:Mapped[int]=mapped_column(Integer,primary_key=True);company_id:Mapped[int]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),nullable=False,index=True);branch_id:Mapped[int]=mapped_column(ForeignKey("branches.id",ondelete="RESTRICT"),nullable=False,index=True);site_id:Mapped[int|None]=mapped_column(ForeignKey("sites.id",ondelete="SET NULL"),index=True);project_id:Mapped[int]=mapped_column(ForeignKey("projects.id",ondelete="CASCADE"),nullable=False,index=True);run_number:Mapped[str]=mapped_column(String(80),nullable=False,index=True);run_date:Mapped[date]=mapped_column(Date,nullable=False,index=True);sequence:Mapped[int]=mapped_column(Integer,nullable=False);score_pct:Mapped[int]=mapped_column(Integer,nullable=False,default=100);status:Mapped[str]=mapped_column(String(24),nullable=False,index=True);checks:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict);source_activity_count:Mapped[int]=mapped_column(Integer,nullable=False,default=0);run_by:Mapped[str]=mapped_column(String(255),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False,default=utcnow)
class DataQualityFinding(Base):
    __tablename__="data_quality_findings"
    __table_args__=(UniqueConstraint("run_id","check_code",name="uq_data_quality_finding_check"),)
    id:Mapped[int]=mapped_column(Integer,primary_key=True);company_id:Mapped[int]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),nullable=False,index=True);branch_id:Mapped[int]=mapped_column(ForeignKey("branches.id",ondelete="RESTRICT"),nullable=False,index=True);site_id:Mapped[int|None]=mapped_column(ForeignKey("sites.id",ondelete="SET NULL"),index=True);project_id:Mapped[int]=mapped_column(ForeignKey("projects.id",ondelete="CASCADE"),nullable=False,index=True);run_id:Mapped[int]=mapped_column(ForeignKey("data_quality_runs.id",ondelete="CASCADE"),nullable=False,index=True);check_code:Mapped[str]=mapped_column(String(80),nullable=False,index=True);severity:Mapped[str]=mapped_column(String(24),nullable=False,index=True);message:Mapped[str]=mapped_column(Text,nullable=False);status:Mapped[str]=mapped_column(String(24),nullable=False,default="open",index=True);remediation_document_id:Mapped[int|None]=mapped_column(ForeignKey("documents.id",ondelete="SET NULL"),index=True);remediation_note:Mapped[str|None]=mapped_column(Text);remediated_by:Mapped[str|None]=mapped_column(String(255));remediated_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));verified_by:Mapped[str|None]=mapped_column(String(255));verified_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False,default=utcnow)
class DataQualityAuditEvent(Base):
    __tablename__="data_quality_audit_events"
    id:Mapped[int]=mapped_column(Integer,primary_key=True);company_id:Mapped[int]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),nullable=False,index=True);branch_id:Mapped[int|None]=mapped_column(ForeignKey("branches.id",ondelete="SET NULL"),index=True);site_id:Mapped[int|None]=mapped_column(ForeignKey("sites.id",ondelete="SET NULL"),index=True);project_id:Mapped[int|None]=mapped_column(ForeignKey("projects.id",ondelete="SET NULL"),index=True);actor:Mapped[str]=mapped_column(String(255),nullable=False);action:Mapped[str]=mapped_column(String(120),nullable=False,index=True);entity_type:Mapped[str]=mapped_column(String(80),nullable=False);entity_id:Mapped[str]=mapped_column(String(100),nullable=False);detail:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict);occurred_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False,default=utcnow,index=True)
