from __future__ import annotations
from datetime import date, datetime, timezone
from decimal import Decimal
from sqlalchemy import Date, DateTime, ForeignKey, Integer, JSON, Numeric, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column
from app.db.base import Base
def utcnow()->datetime:return datetime.now(timezone.utc)
class RecruitmentCandidate(Base):
 __tablename__="recruitment_candidates"
 __table_args__=(UniqueConstraint("company_id","candidate_number",name="uq_recruitment_candidate_number"),)
 id:Mapped[int]=mapped_column(Integer,primary_key=True);company_id:Mapped[int]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),nullable=False,index=True);branch_id:Mapped[int|None]=mapped_column(ForeignKey("branches.id",ondelete="SET NULL"),index=True);site_id:Mapped[int|None]=mapped_column(ForeignKey("sites.id",ondelete="SET NULL"),index=True);candidate_number:Mapped[str]=mapped_column(String(80),nullable=False,index=True);full_name:Mapped[str]=mapped_column(String(240),nullable=False);phone:Mapped[str|None]=mapped_column(String(64));email:Mapped[str|None]=mapped_column(String(255));position:Mapped[str]=mapped_column(String(160),nullable=False);status:Mapped[str]=mapped_column(String(24),nullable=False,default="applied",index=True);application_date:Mapped[date]=mapped_column(Date,nullable=False,index=True);cv_document_id:Mapped[int|None]=mapped_column(ForeignKey("documents.id",ondelete="SET NULL"));notes:Mapped[str|None]=mapped_column(Text);created_by:Mapped[str]=mapped_column(String(255),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False,default=utcnow)
class EmployeeCredential(Base):
 __tablename__="employee_credentials"
 __table_args__=(UniqueConstraint("employee_id","credential_type","reference_number",name="uq_employee_credential_reference"),)
 id:Mapped[int]=mapped_column(Integer,primary_key=True);company_id:Mapped[int]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),nullable=False,index=True);employee_id:Mapped[int]=mapped_column(ForeignKey("employees.id",ondelete="CASCADE"),nullable=False,index=True);credential_type:Mapped[str]=mapped_column(String(80),nullable=False,index=True);reference_number:Mapped[str|None]=mapped_column(String(120));issuer:Mapped[str|None]=mapped_column(String(180));issue_date:Mapped[date|None]=mapped_column(Date);expiry_date:Mapped[date|None]=mapped_column(Date,index=True);status:Mapped[str]=mapped_column(String(24),nullable=False,default="valid",index=True);document_id:Mapped[int|None]=mapped_column(ForeignKey("documents.id",ondelete="SET NULL"));notes:Mapped[str|None]=mapped_column(Text);recorded_by:Mapped[str]=mapped_column(String(255),nullable=False);recorded_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False,default=utcnow)
class EmployeeTrainingRecord(Base):
 __tablename__="employee_training_records"
 __table_args__=(UniqueConstraint("employee_id","course_name","completion_date",name="uq_employee_training_completion"),)
 id:Mapped[int]=mapped_column(Integer,primary_key=True);company_id:Mapped[int]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),nullable=False,index=True);employee_id:Mapped[int]=mapped_column(ForeignKey("employees.id",ondelete="CASCADE"),nullable=False,index=True);course_name:Mapped[str]=mapped_column(String(240),nullable=False);provider:Mapped[str|None]=mapped_column(String(180));category:Mapped[str]=mapped_column(String(80),nullable=False,default="professional",index=True);start_date:Mapped[date|None]=mapped_column(Date);completion_date:Mapped[date|None]=mapped_column(Date,index=True);expiry_date:Mapped[date|None]=mapped_column(Date,index=True);cost:Mapped[Decimal]=mapped_column(Numeric(18,2),nullable=False,default=Decimal("0"));status:Mapped[str]=mapped_column(String(24),nullable=False,default="planned",index=True);certificate_document_id:Mapped[int|None]=mapped_column(ForeignKey("documents.id",ondelete="SET NULL"));notes:Mapped[str|None]=mapped_column(Text);recorded_by:Mapped[str]=mapped_column(String(255),nullable=False);recorded_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False,default=utcnow)
class EmployeeOnboardingItem(Base):
 __tablename__="employee_onboarding_items"
 __table_args__=(UniqueConstraint("employee_id","title",name="uq_employee_onboarding_title"),)
 id:Mapped[int]=mapped_column(Integer,primary_key=True);company_id:Mapped[int]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),nullable=False,index=True);employee_id:Mapped[int]=mapped_column(ForeignKey("employees.id",ondelete="CASCADE"),nullable=False,index=True);onboarding_type:Mapped[str]=mapped_column(String(80),nullable=False,default="general",index=True);title:Mapped[str]=mapped_column(String(240),nullable=False);due_date:Mapped[date|None]=mapped_column(Date,index=True);status:Mapped[str]=mapped_column(String(24),nullable=False,default="open",index=True);document_id:Mapped[int|None]=mapped_column(ForeignKey("documents.id",ondelete="SET NULL"));notes:Mapped[str|None]=mapped_column(Text);assigned_to:Mapped[str|None]=mapped_column(String(255));completed_by:Mapped[str|None]=mapped_column(String(255));completed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));created_by:Mapped[str]=mapped_column(String(255),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False,default=utcnow)
class EmployeePerformanceReview(Base):
 __tablename__="employee_performance_reviews"
 __table_args__=(UniqueConstraint("employee_id","review_period_end",name="uq_employee_performance_period"),)
 id:Mapped[int]=mapped_column(Integer,primary_key=True);company_id:Mapped[int]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),nullable=False,index=True);employee_id:Mapped[int]=mapped_column(ForeignKey("employees.id",ondelete="CASCADE"),nullable=False,index=True);review_period_start:Mapped[date]=mapped_column(Date,nullable=False);review_period_end:Mapped[date]=mapped_column(Date,nullable=False,index=True);delivery_score:Mapped[Decimal]=mapped_column(Numeric(5,2),nullable=False);quality_score:Mapped[Decimal]=mapped_column(Numeric(5,2),nullable=False);safety_score:Mapped[Decimal]=mapped_column(Numeric(5,2),nullable=False);conduct_score:Mapped[Decimal]=mapped_column(Numeric(5,2),nullable=False);overall_score:Mapped[Decimal]=mapped_column(Numeric(5,2),nullable=False,index=True);development_plan:Mapped[str|None]=mapped_column(Text);status:Mapped[str]=mapped_column(String(24),nullable=False,default="draft",index=True);reviewed_by:Mapped[str]=mapped_column(String(255),nullable=False);reviewed_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False,default=utcnow);acknowledged_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
