from __future__ import annotations
from datetime import date,datetime,timezone
from decimal import Decimal
from sqlalchemy import Boolean,Date,DateTime,ForeignKey,Integer,JSON,Numeric,String,Text,UniqueConstraint
from sqlalchemy.orm import Mapped,mapped_column
from app.db.base import Base
def utcnow()->datetime:return datetime.now(timezone.utc)
class EnvironmentalPlan(Base):
 __tablename__="environmental_plans";__table_args__=(UniqueConstraint("company_id","plan_number",name="uq_environment_plan_number"),UniqueConstraint("project_id","title",name="uq_environment_project_title"))
 id:Mapped[int]=mapped_column(Integer,primary_key=True);company_id:Mapped[int]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),nullable=False,index=True);project_id:Mapped[int]=mapped_column(ForeignKey("projects.id",ondelete="CASCADE"),nullable=False,index=True);branch_id:Mapped[int]=mapped_column(ForeignKey("branches.id",ondelete="RESTRICT"),nullable=False,index=True);site_id:Mapped[int]=mapped_column(ForeignKey("sites.id",ondelete="RESTRICT"),nullable=False,index=True);plan_number:Mapped[str]=mapped_column(String(80),nullable=False,index=True);title:Mapped[str]=mapped_column(String(300),nullable=False);aspects:Mapped[str]=mapped_column(Text,nullable=False);controls:Mapped[str]=mapped_column(Text,nullable=False);review_due_date:Mapped[date|None]=mapped_column(Date,index=True);status:Mapped[str]=mapped_column(String(24),nullable=False,default="draft",index=True);document_id:Mapped[int|None]=mapped_column(ForeignKey("documents.id",ondelete="SET NULL"),index=True);prepared_by:Mapped[str]=mapped_column(String(255),nullable=False);submitted_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));approved_by:Mapped[str|None]=mapped_column(String(255));approved_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False,default=utcnow)
class EnvironmentalWasteRecord(Base):
 __tablename__="environmental_waste_records";__table_args__=(UniqueConstraint("company_id","waste_number",name="uq_environment_waste_number"),)
 id:Mapped[int]=mapped_column(Integer,primary_key=True);company_id:Mapped[int]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),nullable=False,index=True);project_id:Mapped[int]=mapped_column(ForeignKey("projects.id",ondelete="CASCADE"),nullable=False,index=True);branch_id:Mapped[int]=mapped_column(ForeignKey("branches.id",ondelete="RESTRICT"),nullable=False,index=True);site_id:Mapped[int]=mapped_column(ForeignKey("sites.id",ondelete="RESTRICT"),nullable=False,index=True);waste_number:Mapped[str]=mapped_column(String(80),nullable=False,index=True);record_date:Mapped[date]=mapped_column(Date,nullable=False,index=True);waste_stream:Mapped[str]=mapped_column(String(48),nullable=False,index=True);quantity:Mapped[Decimal]=mapped_column(Numeric(14,2),nullable=False);unit:Mapped[str]=mapped_column(String(24),nullable=False);destination:Mapped[str]=mapped_column(String(300),nullable=False);carrier_reference:Mapped[str|None]=mapped_column(String(120));hazardous:Mapped[bool]=mapped_column(Boolean,nullable=False,default=False,index=True);document_id:Mapped[int|None]=mapped_column(ForeignKey("documents.id",ondelete="SET NULL"),index=True);status:Mapped[str]=mapped_column(String(24),nullable=False,default="recorded",index=True);recorded_by:Mapped[str]=mapped_column(String(255),nullable=False);verified_by:Mapped[str|None]=mapped_column(String(255));verified_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False,default=utcnow)
class EnvironmentalInspection(Base):
 __tablename__="environmental_inspections";__table_args__=(UniqueConstraint("company_id","inspection_number",name="uq_environment_inspection_number"),)
 id:Mapped[int]=mapped_column(Integer,primary_key=True);company_id:Mapped[int]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),nullable=False,index=True);project_id:Mapped[int]=mapped_column(ForeignKey("projects.id",ondelete="CASCADE"),nullable=False,index=True);branch_id:Mapped[int]=mapped_column(ForeignKey("branches.id",ondelete="RESTRICT"),nullable=False,index=True);site_id:Mapped[int]=mapped_column(ForeignKey("sites.id",ondelete="RESTRICT"),nullable=False,index=True);inspection_number:Mapped[str]=mapped_column(String(80),nullable=False,index=True);inspection_date:Mapped[date]=mapped_column(Date,nullable=False,index=True);category:Mapped[str]=mapped_column(String(48),nullable=False,index=True);severity:Mapped[str]=mapped_column(String(24),nullable=False,index=True);finding:Mapped[str]=mapped_column(Text,nullable=False);corrective_action:Mapped[str|None]=mapped_column(Text);due_date:Mapped[date|None]=mapped_column(Date,index=True);document_id:Mapped[int|None]=mapped_column(ForeignKey("documents.id",ondelete="SET NULL"),index=True);status:Mapped[str]=mapped_column(String(24),nullable=False,default="open",index=True);created_by:Mapped[str]=mapped_column(String(255),nullable=False);remediated_by:Mapped[str|None]=mapped_column(String(255));remediated_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));verified_by:Mapped[str|None]=mapped_column(String(255));verified_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False,default=utcnow)
class EnvironmentalAuditEvent(Base):
 __tablename__="environmental_audit_events";id:Mapped[int]=mapped_column(Integer,primary_key=True);company_id:Mapped[int]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),nullable=False,index=True);branch_id:Mapped[int|None]=mapped_column(ForeignKey("branches.id",ondelete="SET NULL"),index=True);site_id:Mapped[int|None]=mapped_column(ForeignKey("sites.id",ondelete="SET NULL"),index=True);project_id:Mapped[int|None]=mapped_column(ForeignKey("projects.id",ondelete="SET NULL"),index=True);actor:Mapped[str]=mapped_column(String(255),nullable=False);action:Mapped[str]=mapped_column(String(120),nullable=False,index=True);entity_type:Mapped[str]=mapped_column(String(80),nullable=False);entity_id:Mapped[str]=mapped_column(String(100),nullable=False);detail:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict);occurred_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False,default=utcnow,index=True)
