from __future__ import annotations
from datetime import date, datetime, timezone
from typing import Any
from sqlalchemy import Date, DateTime, ForeignKey, Integer, JSON, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column
from app.db.base import Base
def utcnow()->datetime:return datetime.now(timezone.utc)
class RolloutWave(Base):
 __tablename__="rollout_waves"
 __table_args__=(UniqueConstraint("company_id","wave_number",name="uq_rollout_wave_number"),)
 id:Mapped[int]=mapped_column(Integer,primary_key=True);company_id:Mapped[int]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),nullable=False,index=True);branch_id:Mapped[int]=mapped_column(ForeignKey("branches.id",ondelete="RESTRICT"),nullable=False,index=True);wave_number:Mapped[str]=mapped_column(String(80),nullable=False,index=True);name:Mapped[str]=mapped_column(String(240),nullable=False);planned_go_live_date:Mapped[date]=mapped_column(Date,nullable=False,index=True);actual_go_live_date:Mapped[date|None]=mapped_column(Date,index=True);owner:Mapped[str|None]=mapped_column(String(255));status:Mapped[str]=mapped_column(String(24),nullable=False,default="draft",index=True);created_by:Mapped[str]=mapped_column(String(255),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False,default=utcnow);submitted_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));reviewed_by:Mapped[str|None]=mapped_column(String(255));reviewed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));review_comment:Mapped[str|None]=mapped_column(Text)
class RolloutControlItem(Base):
 __tablename__="rollout_control_items"
 __table_args__=(UniqueConstraint("rollout_wave_id","title",name="uq_rollout_control_title"),)
 id:Mapped[int]=mapped_column(Integer,primary_key=True);company_id:Mapped[int]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),nullable=False,index=True);branch_id:Mapped[int]=mapped_column(ForeignKey("branches.id",ondelete="RESTRICT"),nullable=False,index=True);rollout_wave_id:Mapped[int]=mapped_column(ForeignKey("rollout_waves.id",ondelete="CASCADE"),nullable=False,index=True);control_type:Mapped[str]=mapped_column(String(80),nullable=False,index=True);title:Mapped[str]=mapped_column(String(240),nullable=False);required:Mapped[bool]=mapped_column(nullable=False,default=True);due_date:Mapped[date|None]=mapped_column(Date,index=True);status:Mapped[str]=mapped_column(String(24),nullable=False,default="open",index=True);evidence_document_id:Mapped[int|None]=mapped_column(ForeignKey("documents.id",ondelete="SET NULL"));result_notes:Mapped[str|None]=mapped_column(Text);assigned_to:Mapped[str|None]=mapped_column(String(255));completed_by:Mapped[str|None]=mapped_column(String(255));completed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False,default=utcnow)
class RolloutAuditEvent(Base):
 __tablename__="rollout_audit_events"
 id:Mapped[int]=mapped_column(Integer,primary_key=True);company_id:Mapped[int]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),nullable=False,index=True);branch_id:Mapped[int]=mapped_column(ForeignKey("branches.id",ondelete="RESTRICT"),nullable=False,index=True);rollout_wave_id:Mapped[int|None]=mapped_column(ForeignKey("rollout_waves.id",ondelete="SET NULL"),index=True);actor:Mapped[str]=mapped_column(String(255),nullable=False);action:Mapped[str]=mapped_column(String(120),nullable=False,index=True);entity_type:Mapped[str]=mapped_column(String(80),nullable=False);entity_id:Mapped[str]=mapped_column(String(80),nullable=False);detail:Mapped[dict[str,Any]]=mapped_column(JSON,nullable=False,default=dict);occurred_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False,default=utcnow,index=True)
