from __future__ import annotations
from datetime import date,datetime,timezone
from sqlalchemy import Date,DateTime,ForeignKey,Integer,JSON,String,Text,UniqueConstraint
from sqlalchemy.orm import Mapped,mapped_column
from app.db.base import Base
def utcnow()->datetime:return datetime.now(timezone.utc)
class SupportTicket(Base):
 __tablename__="support_tickets";__table_args__=(UniqueConstraint("company_id","ticket_number",name="uq_support_ticket_number"),)
 id:Mapped[int]=mapped_column(Integer,primary_key=True);company_id:Mapped[int]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),nullable=False,index=True);branch_id:Mapped[int]=mapped_column(ForeignKey("branches.id",ondelete="RESTRICT"),nullable=False,index=True);site_id:Mapped[int|None]=mapped_column(ForeignKey("sites.id",ondelete="SET NULL"),index=True);ticket_number:Mapped[str]=mapped_column(String(80),nullable=False,index=True);category:Mapped[str]=mapped_column(String(48),nullable=False,index=True);priority:Mapped[str]=mapped_column(String(24),nullable=False,index=True);title:Mapped[str]=mapped_column(String(300),nullable=False);description:Mapped[str]=mapped_column(Text,nullable=False);due_date:Mapped[date|None]=mapped_column(Date,index=True);status:Mapped[str]=mapped_column(String(24),nullable=False,default="open",index=True);evidence_document_id:Mapped[int|None]=mapped_column(ForeignKey("documents.id",ondelete="SET NULL"),index=True);resolution_document_id:Mapped[int|None]=mapped_column(ForeignKey("documents.id",ondelete="SET NULL"),index=True);resolution_note:Mapped[str|None]=mapped_column(Text);created_by:Mapped[str]=mapped_column(String(255),nullable=False);assigned_to:Mapped[str|None]=mapped_column(String(255));resolved_by:Mapped[str|None]=mapped_column(String(255));resolved_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));verified_by:Mapped[str|None]=mapped_column(String(255));verified_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False,default=utcnow)
class SupportAuditEvent(Base):
 __tablename__="support_audit_events";id:Mapped[int]=mapped_column(Integer,primary_key=True);company_id:Mapped[int]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),nullable=False,index=True);branch_id:Mapped[int|None]=mapped_column(ForeignKey("branches.id",ondelete="SET NULL"),index=True);site_id:Mapped[int|None]=mapped_column(ForeignKey("sites.id",ondelete="SET NULL"),index=True);actor:Mapped[str]=mapped_column(String(255),nullable=False);action:Mapped[str]=mapped_column(String(120),nullable=False,index=True);entity_type:Mapped[str]=mapped_column(String(80),nullable=False);entity_id:Mapped[str]=mapped_column(String(100),nullable=False);detail:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict);occurred_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False,default=utcnow,index=True)
