from __future__ import annotations
from datetime import date,datetime,timezone
from sqlalchemy import Boolean,Date,DateTime,ForeignKey,Integer,JSON,String,Text,UniqueConstraint
from sqlalchemy.orm import Mapped,mapped_column
from app.db.base import Base
def utcnow()->datetime:return datetime.now(timezone.utc)
class ToolAsset(Base):
 __tablename__="tool_assets";__table_args__=(UniqueConstraint("company_id","tool_number",name="uq_tool_asset_number"),)
 id:Mapped[int]=mapped_column(Integer,primary_key=True);company_id:Mapped[int]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),nullable=False,index=True);branch_id:Mapped[int]=mapped_column(ForeignKey("branches.id",ondelete="RESTRICT"),nullable=False,index=True);site_id:Mapped[int|None]=mapped_column(ForeignKey("sites.id",ondelete="SET NULL"),index=True);tool_number:Mapped[str]=mapped_column(String(80),nullable=False,index=True);name:Mapped[str]=mapped_column(String(240),nullable=False);tool_type:Mapped[str]=mapped_column(String(48),nullable=False,index=True);manufacturer:Mapped[str|None]=mapped_column(String(160));serial_number:Mapped[str|None]=mapped_column(String(160),index=True);status:Mapped[str]=mapped_column(String(24),nullable=False,default="available",index=True);calibration_required:Mapped[bool]=mapped_column(Boolean,nullable=False,default=False,index=True);calibration_due_date:Mapped[date|None]=mapped_column(Date,index=True);document_id:Mapped[int|None]=mapped_column(ForeignKey("documents.id",ondelete="SET NULL"),index=True);created_by:Mapped[str]=mapped_column(String(255),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False,default=utcnow)
class ToolIssue(Base):
 __tablename__="tool_issues";__table_args__=(UniqueConstraint("tool_id","returned_at",name="uq_tool_open_issue"),)
 id:Mapped[int]=mapped_column(Integer,primary_key=True);company_id:Mapped[int]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),nullable=False,index=True);tool_id:Mapped[int]=mapped_column(ForeignKey("tool_assets.id",ondelete="CASCADE"),nullable=False,index=True);employee_id:Mapped[int|None]=mapped_column(ForeignKey("employees.id",ondelete="SET NULL"),index=True);project_id:Mapped[int|None]=mapped_column(ForeignKey("projects.id",ondelete="SET NULL"),index=True);branch_id:Mapped[int]=mapped_column(ForeignKey("branches.id",ondelete="RESTRICT"),nullable=False,index=True);site_id:Mapped[int|None]=mapped_column(ForeignKey("sites.id",ondelete="SET NULL"),index=True);issued_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False,default=utcnow);due_date:Mapped[date|None]=mapped_column(Date,index=True);condition_out:Mapped[str]=mapped_column(String(48),nullable=False);condition_in:Mapped[str|None]=mapped_column(String(48));return_note:Mapped[str|None]=mapped_column(Text);issued_by:Mapped[str]=mapped_column(String(255),nullable=False);returned_by:Mapped[str|None]=mapped_column(String(255));returned_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
class ToolCalibration(Base):
 __tablename__="tool_calibrations";__table_args__=(UniqueConstraint("tool_id","calibration_date",name="uq_tool_calibration_date"),)
 id:Mapped[int]=mapped_column(Integer,primary_key=True);company_id:Mapped[int]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),nullable=False,index=True);tool_id:Mapped[int]=mapped_column(ForeignKey("tool_assets.id",ondelete="CASCADE"),nullable=False,index=True);branch_id:Mapped[int]=mapped_column(ForeignKey("branches.id",ondelete="RESTRICT"),nullable=False,index=True);site_id:Mapped[int|None]=mapped_column(ForeignKey("sites.id",ondelete="SET NULL"),index=True);calibration_date:Mapped[date]=mapped_column(Date,nullable=False);due_date:Mapped[date]=mapped_column(Date,nullable=False,index=True);provider:Mapped[str]=mapped_column(String(200),nullable=False);certificate_document_id:Mapped[int]=mapped_column(ForeignKey("documents.id",ondelete="RESTRICT"),nullable=False,index=True);status:Mapped[str]=mapped_column(String(24),nullable=False,default="recorded",index=True);recorded_by:Mapped[str]=mapped_column(String(255),nullable=False);verified_by:Mapped[str|None]=mapped_column(String(255));verified_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False,default=utcnow)
class ToolAuditEvent(Base):
 __tablename__="tool_audit_events";id:Mapped[int]=mapped_column(Integer,primary_key=True);company_id:Mapped[int]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),nullable=False,index=True);branch_id:Mapped[int|None]=mapped_column(ForeignKey("branches.id",ondelete="SET NULL"),index=True);site_id:Mapped[int|None]=mapped_column(ForeignKey("sites.id",ondelete="SET NULL"),index=True);actor:Mapped[str]=mapped_column(String(255),nullable=False);action:Mapped[str]=mapped_column(String(120),nullable=False,index=True);entity_type:Mapped[str]=mapped_column(String(80),nullable=False);entity_id:Mapped[str]=mapped_column(String(100),nullable=False);detail:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict);occurred_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False,default=utcnow,index=True)
