"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { useBuildTrackUi } from "../components/ui";
import styles from "../workforce/workforce.module.css";

type Row = Record<string, unknown>;
type Mode = "contract" | "cost" | "valuation" | "claim" | "cashflow";
const API = "/api/v1";
const txt = (row: Row | null | undefined, key: string) => String(row?.[key] ?? "");
const num = (row: Row | null | undefined, key: string) => Number(row?.[key] ?? 0);
const money = (value: unknown) => `M ${Number(value ?? 0).toLocaleString("en-LS", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

async function api<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(API + path, { ...init, credentials: "include", cache: "no-store", headers: { "Content-Type": "application/json", ...(init?.headers ?? {}) } });
  if (response.status === 401) { window.location.href = "/login?returnTo=" + encodeURIComponent("/commercial"); throw new Error("Session expired"); }
  const payload: unknown = await response.json().catch(() => ({}));
  if (!response.ok) {
    const detail = typeof payload === "object" && payload !== null ? (payload as Row).detail : null;
    throw new Error(typeof detail === "string" ? detail : "Commercial action could not be completed.");
  }
  return payload as T;
}

function Field({ label, children, wide = false }: { label: string; children: React.ReactNode; wide?: boolean }) { return <div className={`${styles.field} ${wide ? styles.wide : ""}`}><label>{label}</label>{children}</div>; }
function Button({ children, variant = "", ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & { variant?: "secondary" | "danger" | "" }) { return <button {...props} className={`${styles.button} ${variant ? styles[variant] : ""}`}>{children}</button>; }

export default function CommercialPage() {
  const { confirm } = useBuildTrackUi();
  const [projects, setProjects] = useState<Row[]>([]), [contracts, setContracts] = useState<Row[]>([]), [costs, setCosts] = useState<Row[]>([]), [claims, setClaims] = useState<Row[]>([]), [cashflows, setCashflows] = useState<Row[]>([]);
  const [summary, setSummary] = useState<Row>({}), [alerts, setAlerts] = useState<Row[]>([]), [dashboard, setDashboard] = useState<Row | null>(null);
  const [projectId, setProjectId] = useState(""), [contractId, setContractId] = useState(""), [mode, setMode] = useState<Mode>("contract"), [error, setError] = useState(""), [notice, setNotice] = useState(""), [loading, setLoading] = useState(true);
  const [contract, setContract] = useState({ title: "", client_name: "", client_reference: "", start_date: "", completion_date: "", original_contract_sum: "0", retention_pct: "5", contract_document_id: "", notes: "" });
  const [cost, setCost] = useState({ transaction_date: new Date().toISOString().slice(0, 10), transaction_type: "actual", cost_type: "materials", cost_code: "", description: "", amount: "0", source_type: "", source_reference: "", document_id: "", notes: "" });
  const [valuation, setValuation] = useState({ period_start: "", period_end: "", gross_value: "0", other_deductions: "0", evidence_document_id: "", notes: "" });
  const [claim, setClaim] = useState({ claim_type: "extension_of_time", title: "", basis: "", claimed_amount: "0", notice_date: "", response_due_date: "", document_id: "", notes: "" });
  const [cashflow, setCashflow] = useState({ forecast_month: "", expected_inflow: "0", expected_outflow: "0", source: "manual", notes: "" });
  const selectedProject = useMemo(() => projects.find(row => String(row.id) === projectId) ?? null, [projects, projectId]);

  const refresh = useCallback(async () => {
    setLoading(true); setError("");
    try {
      const [projectRows, contractRows, costRows, claimRows, cashRows, report, alertRows] = await Promise.all([api<Row[]>("/commercial/projects"), api<Row[]>("/commercial/contracts"), api<Row[]>("/commercial/costs"), api<Row[]>("/commercial/claims"), api<Row[]>("/commercial/cash-flow"), api<Row>("/commercial/dashboard/summary"), api<Row[]>("/commercial/dashboard/alerts")]);
      setProjects(projectRows); setContracts(contractRows); setCosts(costRows); setClaims(claimRows); setCashflows(cashRows); setSummary(report); setAlerts(alertRows);
      if (projectId) setDashboard(await api<Row>(`/commercial/dashboard/projects/${projectId}`));
    } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not load Commercial Control. Initialise the phase from an administrator account first."); }
    finally { setLoading(false); }
  }, [projectId]);
  useEffect(() => { void refresh(); }, [refresh]);
  function success(message: string) { setNotice(message); setError(""); setTimeout(() => setNotice(""), 4000); void refresh(); }
  async function run(action: () => Promise<unknown>, message: string) { try { await action(); success(message); } catch (reason) { setError(reason instanceof Error ? reason.message : "Commercial action failed."); } }
  async function chooseProject(id: string) { setProjectId(id); setDashboard(id ? await api<Row>(`/commercial/dashboard/projects/${id}`) : null); }
  function projectContracts() { return contracts.filter(row => txt(row, "project_id") === projectId); }

  async function createContract(event: FormEvent) { event.preventDefault(); if (!projectId) return; await run(() => api("/commercial/contracts", { method: "POST", body: JSON.stringify({ project_id: Number(projectId), title: contract.title, client_name: contract.client_name, client_reference: contract.client_reference || null, start_date: contract.start_date, completion_date: contract.completion_date, original_contract_sum: Number(contract.original_contract_sum), retention_pct: Number(contract.retention_pct), contract_document_id: contract.contract_document_id ? Number(contract.contract_document_id) : null, notes: contract.notes || null }) }), "Client contract created. Attach a controlled document before submitting it for approval."); }
  async function createCost(event: FormEvent) { event.preventDefault(); if (!projectId) return; await run(() => api("/commercial/costs", { method: "POST", body: JSON.stringify({ project_id: Number(projectId), transaction_date: cost.transaction_date, transaction_type: cost.transaction_type, cost_type: cost.cost_type, cost_code: cost.cost_code || null, description: cost.description, amount: Number(cost.amount), source_type: cost.source_type || null, source_reference: cost.source_reference || null, document_id: cost.document_id ? Number(cost.document_id) : null, notes: cost.notes || null }) }), "Immutable project cost entry posted."); }
  async function createValuation(event: FormEvent) { event.preventDefault(); if (!contractId) return; await run(() => api(`/commercial/contracts/${contractId}/valuations`, { method: "POST", body: JSON.stringify({ period_start: valuation.period_start, period_end: valuation.period_end, gross_value: Number(valuation.gross_value), other_deductions: Number(valuation.other_deductions), evidence_document_id: valuation.evidence_document_id ? Number(valuation.evidence_document_id) : null, notes: valuation.notes || null }) }), "Client valuation created. Submit it through the controlled approval flow when evidence is ready."); }
  async function createClaim(event: FormEvent) { event.preventDefault(); if (!projectId) return; await run(() => api("/commercial/claims", { method: "POST", body: JSON.stringify({ project_id: Number(projectId), contract_id: contractId ? Number(contractId) : null, claim_type: claim.claim_type, title: claim.title, basis: claim.basis, claimed_amount: Number(claim.claimed_amount), notice_date: claim.notice_date || null, response_due_date: claim.response_due_date || null, document_id: claim.document_id ? Number(claim.document_id) : null, notes: claim.notes || null }) }), "Client claim recorded. It remains a draft until controlled submission."); }
  async function createCashflow(event: FormEvent) { event.preventDefault(); if (!projectId) return; await run(() => api("/commercial/cash-flow", { method: "POST", body: JSON.stringify({ project_id: Number(projectId), forecast_month: cashflow.forecast_month, expected_inflow: Number(cashflow.expected_inflow), expected_outflow: Number(cashflow.expected_outflow), source: cashflow.source, notes: cashflow.notes || null }) }), "Monthly cash-flow forecast saved."); }
  async function submitContract(id: number) { await run(() => api(`/commercial/contracts/${id}/submit`, { method: "POST" }), "Client contract sent to the maker/checker approval queue."); }
  async function submitClaim(id: number) { await run(() => api(`/commercial/claims/${id}/submit`, { method: "POST" }), "Client claim sent to the maker/checker approval queue."); }
  async function reverseCost(id: number) {
    const approved = await confirm({ title: "Reverse controlled cost?", description: "This posts a controlled reversal. The original immutable cost entry remains in the audit history.", confirmLabel: "Post reversal", destructive: true });
    if (approved) await run(() => api(`/commercial/costs/${id}/reverse`, { method: "POST" }), "Controlled reversal posted.");
  }

  if (loading) return <main className={styles.page}><div className={styles.loading}><strong>Loading Commercial Control…</strong></div></main>;
  return <main className={styles.page}><header className={styles.header}><div className={styles.brand}><div className={styles.brandMark}>CC</div><div><small>BuildTrack · Phase 11</small><h1>Cost &amp; Commercial Control</h1><p>Controlled project costs, client contracts, valuations, invoices, cash flow and claims in Maloti.</p></div></div><div className={styles.headerActions}><Link className={styles.link} href="/projects">Projects</Link><Link className={styles.link} href="/procurement">Procurement</Link><Link className={styles.link} href="/subcontracts">Subcontracts</Link></div></header><div className={styles.shell}>
    {error && <div className={styles.error}>{error}</div>}{notice && <div className={styles.notice}>{notice}</div>}
    <section className={styles.hero}><div className={styles.heroCard}><span className={styles.phase}>Commercial source of truth</span><h2>Revenue, cost exposure and cash in one controlled view.</h2><p>Purchase-order and subcontract commitments remain linked to their originating approvals. This workspace never sends invoices or moves money.</p></div><div className={styles.heroCard}><small>Portfolio actual cost</small><h2>{money(summary.actual_cost)}</h2><p>{num(summary, "open_claims")} open claims · {money(summary.commitments)} commitments</p></div></section>
    <section className={styles.panel}><div className={styles.panelHead}><div><h3>Project commercial dashboard</h3><p>Select a project to see budget, commitments, revenue, receivables, forecast margin and cash-flow evidence.</p></div><select value={projectId} onChange={event => void chooseProject(event.target.value)}><option value="">Select project</option>{projects.map(row => <option key={String(row.id)} value={String(row.id)}>{txt(row, "project_number")} · {txt(row, "name")}</option>)}</select></div>{dashboard ? <div className={styles.detail}><div><small>Budget</small><strong>{money(dashboard.budget)}</strong></div><div><small>Actual cost</small><strong>{money(dashboard.actual_cost)}</strong></div><div><small>Total commitments</small><strong>{money(dashboard.total_commitment)}</strong></div><div><small>Revenue</small><strong>{money(dashboard.current_revenue)}</strong></div><div><small>Receivable</small><strong>{money(dashboard.receivable)}</strong></div><div><small>Forecast margin</small><strong>{money(dashboard.forecast_gross_margin)}</strong></div></div> : <div className={styles.empty}>Choose a project to work with its commercial controls.</div>}</section>
    <section className={styles.panel}><div className={styles.tabs}><button className={mode === "contract" ? styles.active : ""} onClick={() => setMode("contract")}>Client contract</button><button className={mode === "cost" ? styles.active : ""} onClick={() => setMode("cost")}>Actual cost</button><button className={mode === "valuation" ? styles.active : ""} onClick={() => setMode("valuation")}>Valuation</button><button className={mode === "claim" ? styles.active : ""} onClick={() => setMode("claim")}>Claim</button><button className={mode === "cashflow" ? styles.active : ""} onClick={() => setMode("cashflow")}>Cash flow</button></div>
      {mode === "contract" && <form className={styles.form} onSubmit={createContract}><Field label="Contract title" wide><input required value={contract.title} onChange={e => setContract({ ...contract, title: e.target.value })} disabled={!projectId}/></Field><Field label="Client name"><input required value={contract.client_name} onChange={e => setContract({ ...contract, client_name: e.target.value })} disabled={!projectId}/></Field><Field label="Client reference"><input value={contract.client_reference} onChange={e => setContract({ ...contract, client_reference: e.target.value })} disabled={!projectId}/></Field><Field label="Start date"><input required type="date" value={contract.start_date} onChange={e => setContract({ ...contract, start_date: e.target.value })} disabled={!projectId}/></Field><Field label="Completion date"><input required type="date" value={contract.completion_date} onChange={e => setContract({ ...contract, completion_date: e.target.value })} disabled={!projectId}/></Field><Field label="Original sum (M)"><input required type="number" min="0" step="0.01" value={contract.original_contract_sum} onChange={e => setContract({ ...contract, original_contract_sum: e.target.value })} disabled={!projectId}/></Field><Field label="Retention %"><input required type="number" min="0" max="100" step="0.001" value={contract.retention_pct} onChange={e => setContract({ ...contract, retention_pct: e.target.value })} disabled={!projectId}/></Field><Field label="Controlled contract document ID"><input type="number" value={contract.contract_document_id} onChange={e => setContract({ ...contract, contract_document_id: e.target.value })} disabled={!projectId}/></Field><Field label="Notes" wide><textarea value={contract.notes} onChange={e => setContract({ ...contract, notes: e.target.value })} disabled={!projectId}/></Field><div className={styles.formActions}><Button type="submit" disabled={!projectId}>Create client contract</Button></div></form>}
      {mode === "cost" && <form className={styles.form} onSubmit={createCost}><Field label="Cost date"><input required type="date" value={cost.transaction_date} onChange={e => setCost({ ...cost, transaction_date: e.target.value })} disabled={!projectId}/></Field><Field label="Entry type"><select value={cost.transaction_type} onChange={e => setCost({ ...cost, transaction_type: e.target.value })} disabled={!projectId}><option value="actual">Actual</option><option value="accrual">Accrual</option><option value="adjustment">Adjustment</option></select></Field><Field label="Cost type"><select value={cost.cost_type} onChange={e => setCost({ ...cost, cost_type: e.target.value })} disabled={!projectId}><option value="labour">Labour</option><option value="materials">Materials</option><option value="plant">Plant</option><option value="subcontract">Subcontract</option><option value="overhead">Overhead</option><option value="professional">Professional</option><option value="other">Other</option></select></Field><Field label="Cost code"><input value={cost.cost_code} onChange={e => setCost({ ...cost, cost_code: e.target.value })} disabled={!projectId}/></Field><Field label="Amount (M)"><input required type="number" step="0.01" value={cost.amount} onChange={e => setCost({ ...cost, amount: e.target.value })} disabled={!projectId}/></Field><Field label="Source type"><input placeholder="supplier_invoice" value={cost.source_type} onChange={e => setCost({ ...cost, source_type: e.target.value })} disabled={!projectId}/></Field><Field label="Source reference"><input value={cost.source_reference} onChange={e => setCost({ ...cost, source_reference: e.target.value })} disabled={!projectId}/></Field><Field label="Document ID"><input type="number" value={cost.document_id} onChange={e => setCost({ ...cost, document_id: e.target.value })} disabled={!projectId}/></Field><Field label="Description" wide><input required value={cost.description} onChange={e => setCost({ ...cost, description: e.target.value })} disabled={!projectId}/></Field><Field label="Notes" wide><textarea value={cost.notes} onChange={e => setCost({ ...cost, notes: e.target.value })} disabled={!projectId}/></Field><div className={styles.formActions}><Button type="submit" disabled={!projectId}>Post controlled cost</Button></div></form>}
      {mode === "valuation" && <form className={styles.form} onSubmit={createValuation}><Field label="Client contract"><select required value={contractId} onChange={e => setContractId(e.target.value)} disabled={!projectId}><option value="">Select active contract</option>{projectContracts().map(row => <option key={String(row.id)} value={String(row.id)}>{txt(row, "contract_number")} · {txt(row, "status")}</option>)}</select></Field><Field label="Period start"><input required type="date" value={valuation.period_start} onChange={e => setValuation({ ...valuation, period_start: e.target.value })} disabled={!contractId}/></Field><Field label="Period end"><input required type="date" value={valuation.period_end} onChange={e => setValuation({ ...valuation, period_end: e.target.value })} disabled={!contractId}/></Field><Field label="Gross value (M)"><input required type="number" min="0" step="0.01" value={valuation.gross_value} onChange={e => setValuation({ ...valuation, gross_value: e.target.value })} disabled={!contractId}/></Field><Field label="Other deductions (M)"><input required type="number" min="0" step="0.01" value={valuation.other_deductions} onChange={e => setValuation({ ...valuation, other_deductions: e.target.value })} disabled={!contractId}/></Field><Field label="Controlled evidence document ID"><input type="number" value={valuation.evidence_document_id} onChange={e => setValuation({ ...valuation, evidence_document_id: e.target.value })} disabled={!contractId}/></Field><Field label="Notes" wide><textarea value={valuation.notes} onChange={e => setValuation({ ...valuation, notes: e.target.value })} disabled={!contractId}/></Field><div className={styles.formActions}><Button type="submit" disabled={!contractId}>Create valuation</Button></div></form>}
      {mode === "claim" && <form className={styles.form} onSubmit={createClaim}><Field label="Claim type"><select value={claim.claim_type} onChange={e => setClaim({ ...claim, claim_type: e.target.value })} disabled={!projectId}><option value="extension_of_time">Extension of time</option><option value="prolongation">Prolongation</option><option value="disruption">Disruption</option><option value="payment">Payment</option><option value="variation">Variation</option><option value="other">Other</option></select></Field><Field label="Client contract"><select value={contractId} onChange={e => setContractId(e.target.value)} disabled={!projectId}><option value="">Not linked</option>{projectContracts().map(row => <option key={String(row.id)} value={String(row.id)}>{txt(row, "contract_number")}</option>)}</select></Field><Field label="Claim title" wide><input required value={claim.title} onChange={e => setClaim({ ...claim, title: e.target.value })} disabled={!projectId}/></Field><Field label="Basis" wide><textarea required value={claim.basis} onChange={e => setClaim({ ...claim, basis: e.target.value })} disabled={!projectId}/></Field><Field label="Claimed amount (M)"><input required type="number" min="0" step="0.01" value={claim.claimed_amount} onChange={e => setClaim({ ...claim, claimed_amount: e.target.value })} disabled={!projectId}/></Field><Field label="Notice date"><input type="date" value={claim.notice_date} onChange={e => setClaim({ ...claim, notice_date: e.target.value })} disabled={!projectId}/></Field><Field label="Response due"><input type="date" value={claim.response_due_date} onChange={e => setClaim({ ...claim, response_due_date: e.target.value })} disabled={!projectId}/></Field><Field label="Controlled evidence ID"><input type="number" value={claim.document_id} onChange={e => setClaim({ ...claim, document_id: e.target.value })} disabled={!projectId}/></Field><Field label="Notes" wide><textarea value={claim.notes} onChange={e => setClaim({ ...claim, notes: e.target.value })} disabled={!projectId}/></Field><div className={styles.formActions}><Button type="submit" disabled={!projectId}>Create client claim</Button></div></form>}
      {mode === "cashflow" && <form className={styles.form} onSubmit={createCashflow}><Field label="Forecast month"><input required type="date" value={cashflow.forecast_month} onChange={e => setCashflow({ ...cashflow, forecast_month: e.target.value })} disabled={!projectId}/></Field><Field label="Expected inflow (M)"><input required type="number" min="0" step="0.01" value={cashflow.expected_inflow} onChange={e => setCashflow({ ...cashflow, expected_inflow: e.target.value })} disabled={!projectId}/></Field><Field label="Expected outflow (M)"><input required type="number" min="0" step="0.01" value={cashflow.expected_outflow} onChange={e => setCashflow({ ...cashflow, expected_outflow: e.target.value })} disabled={!projectId}/></Field><Field label="Source"><select value={cashflow.source} onChange={e => setCashflow({ ...cashflow, source: e.target.value })} disabled={!projectId}><option value="manual">Manual forecast</option><option value="valuation">Valuation-based</option><option value="commercial_review">Commercial review</option></select></Field><Field label="Notes" wide><textarea value={cashflow.notes} onChange={e => setCashflow({ ...cashflow, notes: e.target.value })} disabled={!projectId}/></Field><div className={styles.formActions}><Button type="submit" disabled={!projectId}>Save cash-flow month</Button></div></form>}
    </section>
    <section className={styles.grid2}><section className={styles.panel}><div className={styles.panelHead}><div><h3>Client contracts</h3><p>Draft records remain unissued until maker/checker approval.</p></div></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Contract</th><th>Client</th><th>Value</th><th>Status</th><th>Action</th></tr></thead><tbody>{contracts.filter(row => !projectId || txt(row, "project_id") === projectId).map(row => <tr key={String(row.id)}><td>{txt(row, "contract_number")}</td><td>{txt(row, "client_name")}</td><td>{money(row.original_contract_sum)}</td><td>{txt(row, "status")}</td><td>{["draft", "rejected"].includes(txt(row, "status")) ? <button className={styles.mini} onClick={() => void submitContract(num(row, "id"))}>Submit</button> : "—"}</td></tr>)}</tbody></table></div></section><section className={styles.panel}><div className={styles.panelHead}><div><h3>Commercial alerts</h3><p>Cost exposure, overdue client invoices and claim deadlines.</p></div></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Severity</th><th>Reference</th><th>Message</th></tr></thead><tbody>{alerts.map((row, index) => <tr key={String(row.reference ?? index)}><td>{txt(row, "severity")}</td><td>{txt(row, "reference")}</td><td>{txt(row, "message")}</td></tr>)}</tbody></table></div></section></section>
    <section className={styles.grid2}><section className={styles.panel}><div className={styles.panelHead}><div><h3>Cost history</h3><p>Posted costs are immutable; corrections use a controlled reversal.</p></div></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Date</th><th>Reference</th><th>Type</th><th>Amount</th><th>Status</th><th>Action</th></tr></thead><tbody>{costs.filter(row => !projectId || txt(row, "project_id") === projectId).slice(0, 20).map(row => <tr key={String(row.id)}><td>{txt(row, "transaction_date")}</td><td>{txt(row, "transaction_number")}</td><td>{txt(row, "cost_type")}</td><td>{money(row.amount)}</td><td>{txt(row, "status")}</td><td>{txt(row, "status") === "posted" ? <button className={styles.mini} onClick={() => void reverseCost(num(row, "id"))}>Reverse</button> : "—"}</td></tr>)}</tbody></table></div></section><section className={styles.panel}><div className={styles.panelHead}><div><h3>Claims and cash flow</h3><p>Claim deadlines and monthly cash forecasts remain visible by project.</p></div></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Record</th><th>Reference / month</th><th>Value</th><th>Status</th><th>Action</th></tr></thead><tbody>{claims.filter(row => !projectId || txt(row, "project_id") === projectId).map(row => <tr key={`claim-${String(row.id)}`}><td>Claim</td><td>{txt(row, "claim_number")}</td><td>{money(row.claimed_amount)}</td><td>{txt(row, "status")}</td><td>{["draft", "rejected"].includes(txt(row, "status")) ? <button className={styles.mini} onClick={() => void submitClaim(num(row, "id"))}>Submit</button> : "—"}</td></tr>)}{cashflows.filter(row => !projectId || txt(row, "project_id") === projectId).map(row => <tr key={`cash-${String(row.id)}`}><td>Cash flow</td><td>{txt(row, "forecast_month")}</td><td>{money(row.net_cash)}</td><td>{txt(row, "status")}</td><td>—</td></tr>)}</tbody></table></div></section></section>
  </div></main>;
}
