import { redirect } from "next/navigation";

import { ApiError, nbrosApi } from "@/lib/backend";
import { createPurchaseOrderAction, createRequisitionAction, createSupplierAction, decideApprovalAction, receiveGrnAction } from "../actions";
import OperationsNav from "../nav";

type Branch = { id: string; code: string; name: string };
type InventoryItem = { id: string; sku: string; name: string; category: string; quantity_on_hand: number; reorder_level: number; unit: string; stock_level: string };
type Inventory = { items: InventoryItem[]; recent_movements: Array<{ id: string; item_id: string; quantity_delta: number; movement_type: string; notes: string | null; created_at: string }> };
type Procurement = { requisitions: Array<{ id: string; reference: string; purpose: string; total_estimate: number; status: string; created_at: string; lines: Array<{ description: string; quantity: number; estimated_unit_cost: number }> }>; orders: Array<{ id: string; reference: string; requisition_id: string; supplier_id: string; status: string; total_amount: number; expected_at: string | null }> };
type Supplier = { id: string; name: string; supplier_type: string; contact_person: string | null; email: string | null; phone: string | null };
type Approval = { id: string; workflow_key: string; entity_type: string; status: string; amount: number; reason: string | null };
type PoDetail = { id: string; reference: string; status: string; supplier: string | null; total_amount: number; issued_at: string; expected_at: string | null; lines: Array<{ id: string; inventory_item_id: string | null; description: string; quantity: number; unit_cost: number; received_quantity: number; outstanding_quantity: number }>; grns: Array<{ id: string; reference: string; received_at: string; notes: string | null; lines: Array<{ purchase_order_item_id: string; quantity: number; unit_cost: number }> }> };
type Grn = { id: string; purchase_order_id: string; reference: string; notes: string | null; received_at: string };
function money(value: number) { return `M ${value.toLocaleString("en-ZA", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`; }

export default async function StoresPage({ searchParams }: { searchParams: Promise<{ branch?: string }> }) {
  let branches: Branch[];
  try { branches = await nbrosApi<Branch[]>("/api/v1/fleet/branches"); }
  catch (error) { if (error instanceof ApiError && error.status === 401) redirect("/api/auth/login"); throw error; }
  if (!branches.length) redirect("/fleet");
  const params = await searchParams; const selected = branches.find((branch) => branch.id === params.branch) ?? branches[0];
  const [inventory, procurement, suppliers, approvals, grns] = await Promise.all([
    nbrosApi<Inventory>(`/api/v1/fleet/inventory?branch_id=${selected.id}`),
    nbrosApi<Procurement>(`/api/v1/operations/procurement?branch_id=${selected.id}`),
    nbrosApi<Supplier[]>(`/api/v1/operations/suppliers?branch_id=${selected.id}`),
    nbrosApi<Approval[]>(`/api/v1/operations/approvals?branch_id=${selected.id}&status_filter=pending`),
    nbrosApi<Grn[]>(`/api/v1/operations/procurement/grns?branch_id=${selected.id}`),
  ]);
  const poDetails = await Promise.all(procurement.orders.map((order) => nbrosApi<PoDetail>(`/api/v1/operations/procurement/purchase-orders/${order.id}/detail?branch_id=${selected.id}`)));
  const lowStock = inventory.items.filter((item) => item.quantity_on_hand <= item.reorder_level);
  const procurementApprovals = approvals.filter((approval) => approval.entity_type === "purchase_requisition");
  const approvedRequests = procurement.requisitions.filter((row) => row.status === "approved");
  const openOrders = poDetails.filter((row) => row.status !== "received");

  return <div className="app-shell"><OperationsNav branchId={selected.id} active="stores"/><main className="workspace">
    <header className="workspace-header"><div><span className="eyebrow">Stores & Procurement</span><h1>{selected.name} supply chain</h1><p className="muted">Requisition → routed approval → purchase order → GRN → stock receipt is now one controlled workflow.</p></div><form method="get" className="branch-picker"><select name="branch" defaultValue={selected.id}>{branches.map((branch) => <option value={branch.id} key={branch.id}>{branch.name} · {branch.code}</option>)}</select><button className="ghost-button">Switch</button></form></header>
    <section className="metric-grid"><article className="metric-card"><span>Stock items</span><strong>{inventory.items.length}</strong><small>Fleet and workshop inventory</small></article><article className="metric-card danger-card"><span>Low / out</span><strong>{lowStock.length}</strong><small>at or below reorder level</small></article><article className="metric-card"><span>Approved requisitions</span><strong>{approvedRequests.length}</strong><small>ready for purchase order</small></article><article className="metric-card"><span>Open purchase orders</span><strong>{openOrders.length}</strong><small>awaiting full GRN</small></article><article className="metric-card"><span>GRNs posted</span><strong>{grns.length}</strong><small>receipt audit trail</small></article></section>

    <section className="two-column"><article className="panel"><div className="panel-heading"><div><span className="eyebrow">Inventory</span><h2>Stock position</h2></div></div>{inventory.items.length ? <div className="table-wrap"><table><thead><tr><th>SKU</th><th>Item</th><th>On hand</th><th>Reorder</th><th>Status</th></tr></thead><tbody>{inventory.items.map((item) => <tr key={item.id}><td>{item.sku}</td><td>{item.name}</td><td>{item.quantity_on_hand} {item.unit}</td><td>{item.reorder_level} {item.unit}</td><td><span className={`status-pill ${item.quantity_on_hand <= 0 ? "status-red" : item.quantity_on_hand <= item.reorder_level ? "status-orange" : "status-green"}`}>{item.stock_level}</span></td></tr>)}</tbody></table></div> : <div className="empty-state"><strong>No stock items.</strong><span>Create parts and service kits from Fleet Service-kit Stock.</span></div>}</article>
    <article className="panel"><div className="panel-heading"><div><span className="eyebrow">Purchase request</span><h2>Raise requisition</h2></div></div><form action={createRequisitionAction} className="form-grid"><input type="hidden" name="branch_id" value={selected.id}/><label className="form-span">Purpose<input name="purpose" required placeholder="Workshop parts / operational requirement"/></label><label>Existing stock item<select name="inventory_item_id"><option value="">Non-stock / new item</option>{inventory.items.map((item) => <option value={item.id} key={item.id}>{item.sku} · {item.name}</option>)}</select></label><label>Description<input name="description" required/></label><label>Quantity<input type="number" name="quantity" min="0.01" step="0.01" required/></label><label>Estimated unit cost (M)<input type="number" name="estimated_unit_cost" min="0" step="0.01"/></label><div className="form-span"><button className="primary-button">Submit for approval</button></div></form></article></section>

    <section className="panel"><div className="panel-heading"><div><span className="eyebrow">Management approvals</span><h2>Procurement decisions</h2></div><span className="count-badge">{procurementApprovals.length}</span></div>{procurementApprovals.length ? <div className="alert-list">{procurementApprovals.map((approval) => <div className="alert-row alert-orange" key={approval.id}><div><strong>{approval.workflow_key.replaceAll("_", " ")}</strong><span>{approval.reason ?? "Purchase requisition"} · {money(approval.amount)}</span></div><form action={decideApprovalAction} className="header-actions"><input type="hidden" name="branch_id" value={selected.id}/><input type="hidden" name="approval_id" value={approval.id}/><input type="hidden" name="return_path" value="/operations/stores"/><button className="ghost-button" name="decision" value="reject">Reject</button><button className="primary-button" name="decision" value="approve">Approve</button></form></div>)}</div> : <div className="empty-state"><strong>No procurement approvals waiting.</strong></div>}</section>

    <section className="two-column"><article className="panel"><div className="panel-heading"><div><span className="eyebrow">Approved requests</span><h2>Create purchase order</h2></div></div>{approvedRequests.length ? <div className="alert-list">{approvedRequests.map((row)=><div className="alert-row" key={row.id}><div><strong>{row.reference}</strong><span>{row.purpose} · {money(row.total_estimate)}</span></div><form action={createPurchaseOrderAction} className="header-actions"><input type="hidden" name="branch_id" value={selected.id}/><input type="hidden" name="requisition_id" value={row.id}/><select name="supplier_id" required defaultValue=""><option value="" disabled>Supplier</option>{suppliers.map((supplier)=><option key={supplier.id} value={supplier.id}>{supplier.name}</option>)}</select><input type="date" name="expected_at" aria-label="Expected delivery"/><button className="primary-button">Create PO</button></form></div>)}</div> : <div className="empty-state"><strong>No approved requisitions waiting for PO.</strong></div>}</article>
    <article className="panel"><div className="panel-heading"><div><span className="eyebrow">Supplier register</span><h2>Suppliers</h2></div></div><form action={createSupplierAction} className="form-grid"><input type="hidden" name="branch_id" value={selected.id}/><label>Supplier name<input name="name" required/></label><label>Type<select name="supplier_type" defaultValue="general"><option value="general">General</option><option value="parts">Parts</option><option value="workshop">External workshop</option><option value="tyres">Tyres</option><option value="fuel">Fuel</option></select></label><label>Contact person<input name="contact_person"/></label><label>Phone<input name="phone"/></label><label className="form-span">Email<input type="email" name="email"/></label><div className="form-span"><button className="primary-button">Add supplier</button></div></form>{suppliers.length ? <div className="alert-list">{suppliers.map((row) => <div className="alert-row" key={row.id}><strong>{row.name}</strong><span>{row.supplier_type} · {row.phone ?? row.email ?? "No contact recorded"}</span></div>)}</div> : null}</article></section>

    <section className="panel"><div className="panel-heading"><div><span className="eyebrow">Purchase orders & goods receipts</span><h2>PO / GRN control</h2></div><span className="count-badge">{poDetails.length}</span></div>{poDetails.length ? <div className="alert-list">{poDetails.map((order)=><details className="inline-details" key={order.id}><summary className="alert-row"><div><strong>{order.reference} · {order.supplier ?? "Supplier"}</strong><span>{money(order.total_amount)} · {order.status.replaceAll("_"," ")} · {order.expected_at ? `expected ${order.expected_at}` : "no expected date"}</span></div><span className={`status-pill ${order.status === "received" ? "status-green" : "status-orange"}`}>{order.status.toUpperCase().replaceAll("_"," ")}</span></summary><div className="panel"><div className="table-wrap"><table><thead><tr><th>Item</th><th>Ordered</th><th>Received</th><th>Outstanding</th><th>Unit cost</th><th>Post GRN</th></tr></thead><tbody>{order.lines.map((line)=><tr key={line.id}><td>{line.description}</td><td>{line.quantity}</td><td>{line.received_quantity}</td><td>{line.outstanding_quantity}</td><td>{money(line.unit_cost)}</td><td>{line.outstanding_quantity > 0 ? <form action={receiveGrnAction} className="header-actions"><input type="hidden" name="branch_id" value={selected.id}/><input type="hidden" name="purchase_order_id" value={order.id}/><input type="hidden" name="purchase_order_item_id" value={line.id}/><input name="reference" required placeholder="GRN reference"/><input type="number" name="quantity" min="0.01" max={line.outstanding_quantity} step="0.01" required placeholder="Qty"/><button className="primary-button">Receive</button></form> : <span className="status-pill status-green">RECEIVED</span>}</td></tr>)}</tbody></table></div>{order.grns.length ? <div className="alert-list">{order.grns.map((grn)=><div className="alert-row alert-green" key={grn.id}><strong>GRN {grn.reference}</strong><span>{new Date(grn.received_at).toLocaleString()} · {grn.lines.reduce((sum,line)=>sum+line.quantity,0)} units</span></div>)}</div> : null}</div></details>)}</div> : <div className="empty-state"><strong>No purchase orders yet.</strong></div>}</section>

    <section className="panel"><div className="panel-heading"><div><span className="eyebrow">Procurement register</span><h2>Requisitions</h2></div></div>{procurement.requisitions.length ? <div className="table-wrap"><table><thead><tr><th>Reference</th><th>Purpose</th><th>Estimate</th><th>Status</th><th>Lines</th></tr></thead><tbody>{procurement.requisitions.map((row) => <tr key={row.id}><td>{row.reference}</td><td>{row.purpose}</td><td>{money(row.total_estimate)}</td><td>{row.status.replaceAll("_", " ")}</td><td>{row.lines.map((line) => `${line.description} × ${line.quantity}`).join(", ")}</td></tr>)}</tbody></table></div> : <div className="empty-state"><strong>No requisitions.</strong></div>}</section>
  </main></div>;
}
