"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import styles from "../../workforce/workforce.module.css";

type Row=Record<string,unknown>;
type Policy={minimum_quotes:number;low_value_quote_waiver:string|number;po_overrun_tolerance_pct:string|number;reorder_alert_enabled:boolean};
const API="/api/v1";
function text(r:Row|null|undefined,k:string){return String(r?.[k]??"")}
function num(r:Row|null|undefined,k:string){return Number(r?.[k]??0)}
function cash(v:unknown){return `M ${Number(v??0).toLocaleString("en-LS",{minimumFractionDigits:2,maximumFractionDigits:2})}`}
async function api<T>(path:string,init?:RequestInit):Promise<T>{const response=await fetch(`${API}${path}`,{...init,credentials:"include",headers:{"Content-Type":"application/json",...(init?.headers??{})},cache:"no-store"});if(response.status===401){window.location.href=`/login?returnTo=${encodeURIComponent("/procurement/control")}`;throw new Error("Session expired")};const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(typeof payload?.detail==="string"?payload.detail:JSON.stringify(payload?.detail??payload));return payload as T}
function Btn({children,variant="",...props}:React.ButtonHTMLAttributes<HTMLButtonElement>&{variant?:"secondary"|"danger"|""}){return <button {...props} className={`${styles.button} ${variant?styles[variant]:""}`}>{children}</button>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className={styles.field}><label>{label}</label>{children}</div>}
export default function ProcurementControl(){
 const [reqs,setReqs]=useState<Row[]>([]),[pos,setPos]=useState<Row[]>([]),[stock,setStock]=useState<Row[]>([]),[locations,setLocations]=useState<Row[]>([]),[items,setItems]=useState<Row[]>([]),[moves,setMoves]=useState<Row[]>([]),[audit,setAudit]=useState<Row[]>([]),[policy,setPolicy]=useState<Policy>({minimum_quotes:3,low_value_quote_waiver:5000,po_overrun_tolerance_pct:0,reorder_alert_enabled:true}),[error,setError]=useState(""),[notice,setNotice]=useState(""),[loading,setLoading]=useState(true);
 const [adjust,setAdjust]=useState({location_id:"",stock_item_id:"",quantity_delta:"0",unit_cost:"",reason:"Physical count correction"});
 const refresh=useCallback(async()=>{setLoading(true);setError("");try{const [r,p,s,l,i,m,a,pol]=await Promise.all([api<Row[]>("/procurement/requisitions"),api<Row[]>("/procurement/purchase-orders"),api<Row[]>("/procurement/stock"),api<Row[]>("/procurement/locations"),api<Row[]>("/procurement/items"),api<Row[]>("/procurement/stock/movements?limit=150"),api<Row[]>("/procurement/audit/events?limit=200"),api<Policy>("/procurement/policy/current")]);setReqs(r);setPos(p);setStock(s);setLocations(l);setItems(i);setMoves(m);setAudit(a);setPolicy(pol)}catch(e){setError(e instanceof Error?e.message:"Could not load Procurement Control")}finally{setLoading(false)}},[]);
 useEffect(()=>{void refresh()},[refresh]);
 function success(message:string){setNotice(message);setError("");setTimeout(()=>setNotice(""),3500);void refresh()}
 async function decision(requestId:number,decision:"approve"|"reject"){try{await api(`/procurement/approvals/${requestId}/decision`,{method:"POST",body:JSON.stringify({decision,comment:decision==="approve"?"Approved in Procurement Control":"Rejected in Procurement Control"})});success(`Procurement approval ${decision}d.`)}catch(e){setError(e instanceof Error?e.message:"Approval failed")}}
 async function savePolicy(e:FormEvent){e.preventDefault();try{await api("/procurement/policy/current",{method:"PUT",body:JSON.stringify({minimum_quotes:Number(policy.minimum_quotes),low_value_quote_waiver:Number(policy.low_value_quote_waiver),po_overrun_tolerance_pct:Number(policy.po_overrun_tolerance_pct),reorder_alert_enabled:policy.reorder_alert_enabled})});success("Procurement governance policy saved.")}catch(e){setError(e instanceof Error?e.message:"Could not save policy")}}
 async function adjustStock(e:FormEvent){e.preventDefault();try{await api("/procurement/stock/adjustments",{method:"POST",body:JSON.stringify({location_id:Number(adjust.location_id),stock_item_id:Number(adjust.stock_item_id),quantity_delta:Number(adjust.quantity_delta),unit_cost:adjust.unit_cost?Number(adjust.unit_cost):null,reason:adjust.reason})});success("Controlled stock adjustment posted.")}catch(e){setError(e instanceof Error?e.message:"Stock adjustment failed")}}
 if(loading)return <main className={styles.page}><div className={styles.loading}><strong>Loading Procurement Control…</strong></div></main>;
 const pendingReq=reqs.filter(r=>text(r,"status")==="submitted"&&num(r,"approval_request_id")>0),pendingPO=pos.filter(r=>text(r,"status")==="submitted"&&num(r,"approval_request_id")>0),low=stock.filter(r=>Number(r.quantity_on_hand??0)<=Number(r.reorder_level??0)&&Number(r.reorder_level??0)>0);
 return <main className={styles.page}><header className={styles.header}><div className={styles.brand}><div className={styles.brandMark}>BT</div><div><small>Phase 8 Governance</small><h1>Procurement Control</h1><p>Approvals · purchasing policy · stock integrity · audit.</p></div></div><div className={styles.headerActions}><Link className={styles.link} href="/procurement">Procurement &amp; Stores</Link><Link className={styles.link} href="/projects">Projects</Link></div></header><div className={styles.shell}>{error&&<div className={styles.error}>{error}</div>}{notice&&<div className={styles.notice}>{notice}</div>}
 <section className={styles.metrics}><div className={styles.metric}><small>Req approvals</small><strong>{pendingReq.length}</strong><span>maker/checker queue</span></div><div className={styles.metric}><small>PO approvals</small><strong>{pendingPO.length}</strong><span>commercial commitments</span></div><div className={styles.metric}><small>Low stock</small><strong>{low.length}</strong><span>reorder threshold</span></div><div className={styles.metric}><small>Stock value</small><strong>{cash(stock.reduce((a,r)=>a+Number(r.quantity_on_hand??0)*Number(r.average_unit_cost??0),0))}</strong><span>weighted average</span></div></section>
 <section className={styles.grid2}><div className={styles.panel}><div className={styles.panelHead}><div><h3>Requisition approval queue</h3><p>Branch → Head Office maker/checker approval.</p></div></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Requisition</th><th>Title</th><th>Value</th><th>Branch</th><th>Action</th></tr></thead><tbody>{pendingReq.map(r=><tr key={String(r.id)}><td>{text(r,"requisition_number")}</td><td>{text(r,"title")}</td><td>{cash(r.estimated_total)}</td><td>{text(r,"branch_id")}</td><td><div className={styles.actions}><button className={`${styles.mini} ${styles.good}`} onClick={()=>void decision(num(r,"approval_request_id"),"approve")}>Approve</button><button className={`${styles.mini} ${styles.bad}`} onClick={()=>void decision(num(r,"approval_request_id"),"reject")}>Reject</button></div></td></tr>)}</tbody></table></div></div>
 <div className={styles.panel}><div className={styles.panelHead}><div><h3>Purchase order approval queue</h3><p>Authorise commitments only after approved requisition and selected quote.</p></div></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>PO</th><th>Total</th><th>Branch</th><th>Expected</th><th>Action</th></tr></thead><tbody>{pendingPO.map(r=><tr key={String(r.id)}><td>{text(r,"purchase_order_number")}</td><td>{cash(r.total_amount)}</td><td>{text(r,"branch_id")}</td><td>{text(r,"expected_delivery_date")}</td><td><div className={styles.actions}><button className={`${styles.mini} ${styles.good}`} onClick={()=>void decision(num(r,"approval_request_id"),"approve")}>Approve</button><button className={`${styles.mini} ${styles.bad}`} onClick={()=>void decision(num(r,"approval_request_id"),"reject")}>Reject</button></div></td></tr>)}</tbody></table></div></div></section>
 <section className={styles.grid2}><form className={styles.panel} onSubmit={savePolicy}><div className={styles.panelHead}><div><h3>Procurement governance policy</h3><p>Tax is never fabricated; quotation tax remains supplier evidence.</p></div></div><div className={styles.form}><Field label="Minimum quotations"><input type="number" min="1" max="10" value={policy.minimum_quotes} onChange={e=>setPolicy({...policy,minimum_quotes:Number(e.target.value)})}/></Field><Field label="Low-value waiver M"><input type="number" min="0" step=".01" value={String(policy.low_value_quote_waiver)} onChange={e=>setPolicy({...policy,low_value_quote_waiver:e.target.value})}/></Field><Field label="PO overrun tolerance %"><input type="number" min="0" max="100" step=".01" value={String(policy.po_overrun_tolerance_pct)} onChange={e=>setPolicy({...policy,po_overrun_tolerance_pct:e.target.value})}/></Field><Field label="Reorder alerts"><select value={policy.reorder_alert_enabled?"yes":"no"} onChange={e=>setPolicy({...policy,reorder_alert_enabled:e.target.value==="yes"})}><option value="yes">Enabled</option><option value="no">Disabled</option></select></Field><div className={styles.formActions}><Btn type="submit">Save policy</Btn></div></div></form>
 <form className={styles.panel} onSubmit={adjustStock}><div className={styles.panelHead}><div><h3>Controlled stock adjustment</h3><p>Use only for evidenced physical-count or correction movements.</p></div></div><div className={styles.form}><Field label="Store"><select required value={adjust.location_id} onChange={e=>setAdjust({...adjust,location_id:e.target.value})}><option value="">Select</option>{locations.map(r=><option key={String(r.id)} value={String(r.id)}>{text(r,"code")} · {text(r,"name")}</option>)}</select></Field><Field label="Stock item"><select required value={adjust.stock_item_id} onChange={e=>setAdjust({...adjust,stock_item_id:e.target.value})}><option value="">Select</option>{items.map(r=><option key={String(r.id)} value={String(r.id)}>{text(r,"sku")} · {text(r,"description")}</option>)}</select></Field><Field label="Quantity delta"><input required type="number" step=".001" value={adjust.quantity_delta} onChange={e=>setAdjust({...adjust,quantity_delta:e.target.value})}/></Field><Field label="Unit cost (positive only)"><input type="number" min="0" step=".0001" value={adjust.unit_cost} onChange={e=>setAdjust({...adjust,unit_cost:e.target.value})}/></Field><Field label="Reason"><input required value={adjust.reason} onChange={e=>setAdjust({...adjust,reason:e.target.value})}/></Field><div className={styles.formActions}><Btn type="submit">Post adjustment</Btn></div></div></form></section>
 <section className={styles.panel}><div className={styles.panelHead}><div><h3>Low-stock watch</h3><p>Available stock at or below configured reorder level.</p></div><div className={styles.toolbar}><a className={styles.button} href="/api/v1/procurement/exports/stock.csv">Stock CSV</a><a className={styles.button} href="/api/v1/procurement/exports/purchase-orders.csv">PO CSV</a></div></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Store</th><th>SKU</th><th>Description</th><th>On hand</th><th>Reorder</th><th>Average cost</th></tr></thead><tbody>{low.map(r=><tr key={`${String(r.location_id)}-${String(r.stock_item_id)}`}><td>{text(r,"location_code")}</td><td>{text(r,"sku")}</td><td>{text(r,"description")}</td><td>{text(r,"quantity_on_hand")}</td><td>{text(r,"reorder_level")}</td><td>{cash(r.average_unit_cost)}</td></tr>)}</tbody></table></div></section>
 <section className={styles.grid2}><div className={styles.panel}><h3>Latest immutable stock movements</h3><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Time</th><th>Type</th><th>Location</th><th>Item</th><th>Qty</th><th>Value</th></tr></thead><tbody>{moves.slice(0,50).map(r=><tr key={String(r.id)}><td>{text(r,"recorded_at")}</td><td>{text(r,"movement_type")}</td><td>{text(r,"location_id")}</td><td>{text(r,"stock_item_id")}</td><td>{text(r,"quantity")}</td><td>{cash(r.total_cost)}</td></tr>)}</tbody></table></div></div><div className={styles.panel}><h3>Procurement audit</h3><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Time</th><th>Actor</th><th>Action</th><th>Entity</th></tr></thead><tbody>{audit.slice(0,50).map(r=><tr key={String(r.id)}><td>{text(r,"occurred_at")}</td><td>{text(r,"actor")}</td><td>{text(r,"action")}</td><td>{text(r,"entity_type")} #{text(r,"entity_id")}</td></tr>)}</tbody></table></div></div></section>
 </div></main>;
}
