"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { useBuildTrackUi } from "../../components/ui";
import styles from "../../workforce/workforce.module.css";

type Row=Record<string,unknown>;
type Catalog={employees:Row[];permissions:string[]};
const API="/api/v1";
function text(r:Row|null|undefined,k:string){return String(r?.[k]??"")}
function num(r:Row|null|undefined,k:string){return Number(r?.[k]??0)}
function list(v:unknown):Row[]{return Array.isArray(v)?v as Row[]:[]}
async function api<T>(path:string,init?:RequestInit):Promise<T>{const response=await fetch(`${API}${path}`,{...init,credentials:"include",headers:{"Content-Type":"application/json",...(init?.headers??{})},cache:"no-store"});if(response.status===401){window.location.href=`/login?returnTo=${encodeURIComponent("/projects/risks")}`;throw new Error("Session expired")};const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(typeof payload?.detail==="string"?payload.detail:JSON.stringify(payload?.detail??payload));return payload as T}
function Field({label,children,wide=false}:{label:string;children:React.ReactNode;wide?:boolean}){return <div className={`${styles.field} ${wide?styles.wide:""}`}><label>{label}</label>{children}</div>}
function Btn({children,...props}:React.ButtonHTMLAttributes<HTMLButtonElement>){return <button {...props} className={styles.button}>{children}</button>}

export default function ProjectRisks(){
 const {promptText}=useBuildTrackUi();
 const [projects,setProjects]=useState<Row[]>([]),[catalog,setCatalog]=useState<Catalog>({employees:[],permissions:[]}),[selectedId,setSelectedId]=useState(""),[risks,setRisks]=useState<Row[]>([]),[selectedRisk,setSelectedRisk]=useState<Row|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const [form,setForm]=useState({category:"",title:"",description:"",likelihood:"1",impact:"1",owner_employee_id:"",mitigation:"",status:"open",target_date:""});
 const load=useCallback(async()=>{setError("");try{const [p,c]=await Promise.all([api<Row[]>("/projects"),api<Catalog>("/projects/catalog")]);setProjects(p);setCatalog(c);if(selectedId){const d=await api<Row>(`/projects/${selectedId}`);setRisks(list(d.risks));}}catch(e){setError(e instanceof Error?e.message:"Could not load project risks")}},[selectedId]);
 useEffect(()=>{void load()},[load]);
 function chooseRisk(r:Row){setSelectedRisk(r);setForm({category:text(r,"category"),title:text(r,"title"),description:text(r,"description"),likelihood:text(r,"likelihood")||"1",impact:text(r,"impact")||"1",owner_employee_id:text(r,"owner_employee_id"),mitigation:text(r,"mitigation"),status:text(r,"status")||"open",target_date:text(r,"target_date")})}
 async function save(e:FormEvent){e.preventDefault();if(!selectedRisk)return;try{await api(`/projects/risks/${num(selectedRisk,"id")}`,{method:"PUT",body:JSON.stringify({category:form.category,title:form.title,description:form.description||null,likelihood:Number(form.likelihood),impact:Number(form.impact),owner_employee_id:form.owner_employee_id?Number(form.owner_employee_id):null,mitigation:form.mitigation||null,status:form.status,target_date:form.target_date||null})});setNotice("Risk updated and readiness will recalculate from the new status/rating.");setSelectedRisk(null);setTimeout(()=>setNotice(""),3500);await load()}catch(e){setError(e instanceof Error?e.message:"Could not update risk")}}
 async function quickMitigate(r:Row){const mitigation=await promptText({title:"Record risk mitigation",description:"Enter the control evidence that supports this mitigation.",label:"Mitigation / control evidence",defaultValue:text(r,"mitigation"),multiline:true,required:true,confirmLabel:"Mark mitigated"});if(!mitigation)return;try{await api(`/projects/risks/${num(r,"id")}`,{method:"PUT",body:JSON.stringify({category:text(r,"category"),title:text(r,"title"),description:text(r,"description")||null,likelihood:num(r,"likelihood"),impact:num(r,"impact"),owner_employee_id:r.owner_employee_id?Number(r.owner_employee_id):null,mitigation,status:"mitigated",target_date:text(r,"target_date")||null})});setNotice("Risk marked mitigated.");setTimeout(()=>setNotice(""),3500);await load()}catch(e){setError(e instanceof Error?e.message:"Could not mitigate risk")}}
 return <main className={styles.page}><header className={styles.header}><div className={styles.brand}><div className={styles.brandMark}>RK</div><div><small>BuildTrack · Phase 6</small><h1>Project Risk Workbench</h1><p>Mobilisation risk treatment and readiness control</p></div></div><div className={styles.headerActions}><Link className={styles.link} href="/projects">Project Mobilisation</Link><Link className={styles.link} href="/projects/control">Project Control</Link><Link className={styles.link} href="/">Command centre</Link></div></header><div className={styles.shell}>{error&&<div className={styles.error}>{error}</div>}{notice&&<div className={styles.notice}>{notice}</div>}
 <section className={styles.panel}><div className={styles.panelHead}><div><h3>Select project</h3><p>Critical open risks block mobilisation readiness until they are treated.</p></div><select value={selectedId} onChange={e=>{setSelectedId(e.target.value);setSelectedRisk(null)}}><option value="">Select project</option>{projects.map(r=><option key={num(r,"id")} value={String(r.id)}>{text(r,"project_number")} · {text(r,"name")}</option>)}</select></div>{selectedId?<div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Risk</th><th>Category</th><th>Rating</th><th>Status</th><th>Owner</th><th>Mitigation</th><th>Action</th></tr></thead><tbody>{risks.map(r=><tr key={num(r,"id")}><td><strong>{text(r,"risk_number")}</strong><br/><small>{text(r,"title")}</small></td><td>{text(r,"category")}</td><td>{text(r,"rating")}</td><td>{text(r,"status")}</td><td>{text(r,"owner_employee_id")||"—"}</td><td>{text(r,"mitigation")||"—"}</td><td><div className={styles.actions}><button className={styles.mini} onClick={()=>chooseRisk(r)}>Edit</button>{text(r,"status")==="open"&&<button className={`${styles.mini} ${styles.good}`} onClick={()=>void quickMitigate(r)}>Mitigate</button>}</div></td></tr>)}</tbody></table></div>:<div className={styles.empty}>Select a project to manage its mobilisation risks.</div>}</section>
 {selectedRisk&&<section className={styles.panel}><div className={styles.panelHead}><div><h3>Edit {text(selectedRisk,"risk_number")}</h3><p>Likelihood × impact is recalculated by the backend; status and mitigation feed the readiness gate.</p></div></div><form className={styles.form} onSubmit={save}><Field label="Category"><input required value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></Field><Field label="Title" wide><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></Field><Field label="Likelihood"><input type="number" min="1" max="5" required value={form.likelihood} onChange={e=>setForm({...form,likelihood:e.target.value})}/></Field><Field label="Impact"><input type="number" min="1" max="5" required value={form.impact} onChange={e=>setForm({...form,impact:e.target.value})}/></Field><Field label="Owner"><select value={form.owner_employee_id} onChange={e=>setForm({...form,owner_employee_id:e.target.value})}><option value="">Unassigned</option>{catalog.employees.map(r=><option key={num(r,"id")} value={String(r.id)}>{text(r,"employee_number")} · {text(r,"name")}</option>)}</select></Field><Field label="Status"><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="open">open</option><option value="mitigated">mitigated</option><option value="closed">closed</option></select></Field><Field label="Target date"><input type="date" value={form.target_date} onChange={e=>setForm({...form,target_date:e.target.value})}/></Field><Field label="Description" wide><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field><Field label="Mitigation / control evidence" wide><textarea value={form.mitigation} onChange={e=>setForm({...form,mitigation:e.target.value})}/></Field><div className={styles.formActions}><Btn type="submit">Save risk treatment</Btn></div></form></section>}
 </div></main>;
}
