"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { useBuildTrackUi } from "../components/ui";
import styles from "../workforce/workforce.module.css";

type Row = Record<string, unknown>;
const API = "/api/v1";
const text = (row: Row | null | undefined, key: string) => String(row?.[key] ?? "");
const number = (row: Row | null | undefined, key: string) => Number(row?.[key] ?? 0);
const list = (value: unknown): Row[] => Array.isArray(value) ? value.filter((row): row is Row => Boolean(row) && typeof row === "object") : [];
const today = () => new Date().toISOString().slice(0, 10);
const monthStart = () => new Date(new Date().getFullYear(), new Date().getMonth(), 1).toISOString().slice(0, 10);
const monthEnd = () => new Date(new Date().getFullYear(), new Date().getMonth() + 1, 0).toISOString().slice(0, 10);
const money = (value: unknown) => `M ${Number(value ?? 0).toLocaleString("en-LS", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

async function api<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(`${API}${path}`, { ...init, credentials: "include", cache: "no-store", headers: { "Content-Type": "application/json", ...(init?.headers ?? {}) } });
  if (response.status === 401) { window.location.href = `/login?returnTo=${encodeURIComponent("/finance")}`; throw new Error("Session expired"); }
  const payload: unknown = await response.json().catch(() => ({}));
  if (!response.ok) { const detail = payload && typeof payload === "object" ? (payload as Row).detail : ""; throw new Error(typeof detail === "string" ? detail : "Finance action failed."); }
  return payload as T;
}

function badge(status: string) {
  if (["posted", "recorded", "paid", "approved", "open"].includes(status)) return styles.green;
  if (["submitted", "part_paid"].includes(status)) return styles.amber;
  if (["rejected", "closed"].includes(status)) return styles.red;
  return styles.blue;
}

export default function FinancePage() {
  const { confirm, promptText } = useBuildTrackUi();
  const [catalog, setCatalog] = useState<Row>({});
  const [periods, setPeriods] = useState<Row[]>([]);
  const [accounts, setAccounts] = useState<Row[]>([]);
  const [journals, setJournals] = useState<Row[]>([]);
  const [invoices, setInvoices] = useState<Row[]>([]);
  const [payments, setPayments] = useState<Row[]>([]);
  const [approvals, setApprovals] = useState<Row[]>([]);
  const [audit, setAudit] = useState<Row[]>([]);
  const [dashboard, setDashboard] = useState<Row>({});
  const [selectedJournal, setSelectedJournal] = useState<Row | null>(null);
  const [selectedInvoice, setSelectedInvoice] = useState<Row | null>(null);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [periodForm, setPeriodForm] = useState({ period_code: `${new Date().getFullYear()}-${String(new Date().getMonth() + 1).padStart(2, "0")}`, name: "Current financial period", start_date: monthStart(), end_date: monthEnd(), notes: "" });
  const [accountForm, setAccountForm] = useState({ account_code: "", name: "", account_type: "expense", parent_account_id: "", notes: "" });
  const [journalForm, setJournalForm] = useState({ branch_id: "", site_id: "", project_id: "", cost_centre_id: "", period_id: "", journal_date: today(), description: "", source_type: "manual", source_reference: "", supporting_document_id: "", notes: "" });
  const [lineForm, setLineForm] = useState({ account_id: "", description: "", debit: "", credit: "" });
  const [invoiceForm, setInvoiceForm] = useState({ branch_id: "", site_id: "", project_id: "", cost_centre_id: "", supplier_id: "", purchase_order_id: "", supplier_invoice_reference: "", invoice_date: today(), due_date: "", amount: "", invoice_document_id: "", notes: "" });
  const [paymentForm, setPaymentForm] = useState({ requested_date: today(), amount: "", payment_reference: "", notes: "" });

  const refresh = useCallback(async () => {
    try {
      const [nextCatalog, nextPeriods, nextAccounts, nextJournals, nextInvoices, nextPayments, nextApprovals, nextAudit, nextDashboard] = await Promise.all([
        api<Row>("/finance/catalog"), api<Row[]>("/finance/periods"), api<Row[]>("/finance/accounts"), api<Row[]>("/finance/journals"), api<Row[]>("/finance/supplier-invoices"), api<Row[]>("/finance/supplier-payments"), api<Row[]>("/finance/approvals"), api<Row[]>("/finance/audit?limit=120"), api<Row>("/finance/dashboard"),
      ]);
      setCatalog(nextCatalog); setPeriods(nextPeriods); setAccounts(nextAccounts); setJournals(nextJournals); setInvoices(nextInvoices); setPayments(nextPayments); setApprovals(nextApprovals); setAudit(nextAudit); setDashboard(nextDashboard); setError("");
    } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not load Finance & Cash Control. Initialise Phase 18 first."); }
  }, []);
  useEffect(() => { void refresh(); }, [refresh]);

  function done(message: string) { setNotice(message); setError(""); window.setTimeout(() => setNotice(""), 4000); void refresh(); if (selectedJournal) void chooseJournal(number(selectedJournal, "id")); }
  async function initialise() { try { await api("/finance/bootstrap", { method: "POST" }); done("Phase 18 accounts, roles, approvals, numbering and finance policy are ready."); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not initialise Phase 18"); } }
  async function chooseJournal(id: number) { try { setSelectedJournal(await api<Row>(`/finance/journals/${id}`)); setError(""); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not load journal detail"); } }
  async function createPeriod(event: FormEvent) { event.preventDefault(); try { await api("/finance/periods", { method: "POST", body: JSON.stringify({ ...periodForm, notes: periodForm.notes || null }) }); done("Financial period opened under controlled period governance."); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not create financial period"); } }
  async function createAccount(event: FormEvent) { event.preventDefault(); try { await api("/finance/accounts", { method: "POST", body: JSON.stringify({ ...accountForm, parent_account_id: accountForm.parent_account_id ? Number(accountForm.parent_account_id) : null, notes: accountForm.notes || null }) }); setAccountForm({ ...accountForm, account_code: "", name: "", parent_account_id: "", notes: "" }); done("Chart-of-account record created."); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not create chart account"); } }
  async function createJournal(event: FormEvent) { event.preventDefault(); try { const row = await api<Row>("/finance/journals", { method: "POST", body: JSON.stringify({ ...journalForm, branch_id: Number(journalForm.branch_id), site_id: journalForm.site_id ? Number(journalForm.site_id) : null, project_id: journalForm.project_id ? Number(journalForm.project_id) : null, cost_centre_id: journalForm.cost_centre_id ? Number(journalForm.cost_centre_id) : null, period_id: Number(journalForm.period_id), supporting_document_id: journalForm.supporting_document_id ? Number(journalForm.supporting_document_id) : null, notes: journalForm.notes || null }) }); await chooseJournal(number(row, "id")); done("Draft finance journal created. Add balanced debit and credit lines before submission."); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not create finance journal"); } }
  async function addLine(event: FormEvent) { event.preventDefault(); if (!selectedJournal) return; try { await api(`/finance/journals/${number(selectedJournal, "id")}/lines`, { method: "POST", body: JSON.stringify({ account_id: Number(lineForm.account_id), description: lineForm.description || null, debit: Number(lineForm.debit || 0), credit: Number(lineForm.credit || 0) }) }); setLineForm({ account_id: "", description: "", debit: "", credit: "" }); done("Journal line added. Balanced journal totals remain visible."); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not add journal line"); } }
  async function removeLine(line: Row) { if (!selectedJournal) return; const accepted = await confirm({ title: "Remove journal line?", description: "Only draft or rejected journals may be corrected. This removal is retained in the finance audit trail.", confirmLabel: "Remove line", destructive: true }); if (!accepted) return; try { await api(`/finance/journals/${number(selectedJournal, "id")}/lines/${number(line, "id")}`, { method: "DELETE" }); done("Journal line removed; balanced totals were recalculated."); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not remove journal line"); } }
  async function journalAction(path: "submit" | "post") { if (!selectedJournal) return; const accepted = await confirm({ title: path === "submit" ? "Submit balanced journal?" : "Post approved journal?", description: path === "submit" ? "This creates the controlled maker/checker approval request." : "Posting is immutable and the financial period must still be open.", confirmLabel: path === "submit" ? "Submit for approval" : "Post journal", destructive: path === "post" }); if (!accepted) return; try { await api(`/finance/journals/${number(selectedJournal, "id")}/${path}`, { method: "POST" }); done(path === "submit" ? "Journal submitted for independent approval." : "Approved journal posted to the controlled ledger."); } catch (caught) { setError(caught instanceof Error ? caught.message : "Journal action failed"); } }
  async function createInvoice(event: FormEvent) { event.preventDefault(); try { const row = await api<Row>("/finance/supplier-invoices", { method: "POST", body: JSON.stringify({ ...invoiceForm, branch_id: Number(invoiceForm.branch_id), site_id: invoiceForm.site_id ? Number(invoiceForm.site_id) : null, project_id: invoiceForm.project_id ? Number(invoiceForm.project_id) : null, cost_centre_id: invoiceForm.cost_centre_id ? Number(invoiceForm.cost_centre_id) : null, supplier_id: Number(invoiceForm.supplier_id), purchase_order_id: invoiceForm.purchase_order_id ? Number(invoiceForm.purchase_order_id) : null, amount: Number(invoiceForm.amount), due_date: invoiceForm.due_date || null, invoice_document_id: invoiceForm.invoice_document_id ? Number(invoiceForm.invoice_document_id) : null, notes: invoiceForm.notes || null }) }); setSelectedInvoice(row); done("Supplier invoice recorded in the controlled accounts-payable register."); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not create supplier invoice"); } }
  async function submitInvoice(row: Row) { const accepted = await confirm({ title: "Submit supplier invoice?", description: "The invoice evidence will enter the shared branch/HQ maker-checker approval workflow.", confirmLabel: "Submit invoice" }); if (!accepted) return; try { await api(`/finance/supplier-invoices/${number(row, "id")}/submit`, { method: "POST" }); done("Supplier invoice submitted for independent approval."); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not submit supplier invoice"); } }
  async function createPayment(event: FormEvent) { event.preventDefault(); if (!selectedInvoice) return; try { await api(`/finance/supplier-invoices/${number(selectedInvoice, "id")}/payments`, { method: "POST", body: JSON.stringify({ ...paymentForm, amount: Number(paymentForm.amount), payment_reference: paymentForm.payment_reference || null, notes: paymentForm.notes || null }) }); setPaymentForm({ ...paymentForm, amount: "", payment_reference: "", notes: "" }); done("Supplier payment request created; no money has been sent."); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not create supplier payment request"); } }
  async function submitPayment(row: Row) { const accepted = await confirm({ title: "Submit supplier payment?", description: "This requests approval only. BuildTrack does not send money or connect to a bank.", confirmLabel: "Submit payment request" }); if (!accepted) return; try { await api(`/finance/supplier-payments/${number(row, "id")}/submit`, { method: "POST" }); done("Supplier payment request submitted for independent approval."); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not submit payment request"); } }
  async function recordPayment(row: Row) { const documentId = await promptText({ title: "Record supplier payment evidence", description: "Link the controlled bank confirmation, payment voucher or other supplied evidence. This records proof; it does not send money.", label: "Controlled document ID", placeholder: "e.g. 123", required: true, confirmLabel: "Record evidence" }); if (!documentId) return; try { await api(`/finance/supplier-payments/${number(row, "id")}/record`, { method: "POST", body: JSON.stringify({ payment_document_id: Number(documentId) }) }); done("Supplier payment evidence recorded and invoice balance updated."); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not record payment evidence"); } }
  async function decide(row: Row, decision: "approve" | "reject") { const comment = await promptText({ title: decision === "approve" ? "Approve finance record" : "Reject finance record", description: "Record a decision comment in the immutable maker/checker approval trail.", label: "Decision comment", multiline: true, required: true, confirmLabel: decision === "approve" ? "Approve" : "Reject" }); if (comment === null) return; try { await api(`/finance/approvals/${number(row, "id")}/decision`, { method: "POST", body: JSON.stringify({ decision, comment }) }); done(`Finance approval ${decision}d.`); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not record finance approval decision"); } }

  const branches = list(catalog.branches); const suppliers = list(catalog.suppliers); const projects = list(catalog.projects); const purchaseOrders = list(catalog.purchase_orders); const journalLines = list(selectedJournal?.lines);
  return <main className={styles.page}>
    <header className={styles.header}><div className={styles.brand}><div className={styles.brandMark}>FC</div><div><small>BuildTrack · Phase 18</small><h1>Finance &amp; Cash Control</h1><p>Periods · balanced journals · payables · payment evidence · audit</p></div></div><div className={styles.headerActions}><Link className={styles.link} href="/commercial">Commercial Control</Link><Link className={styles.link} href="/procurement/control">Procurement Control</Link><Link className={styles.link} href="/intelligence">Management Intelligence</Link></div></header>
    <div className={styles.shell}>{error && <div className={styles.error}>{error}</div>}{notice && <div className={styles.notice}>{notice}</div>}
      <section className={styles.hero}><div className={styles.heroCard}><span className={styles.phase}>Financial control</span><h2>Evidence before posting.</h2><p>Journals must balance, approvals stay independent, closed periods reject further posting, and payments remain evidence only.</p></div><div className={styles.heroCard}><small>Accounts payable</small><h2>{money(dashboard.payables_outstanding)}</h2><p>{money(dashboard.payables_overdue)} overdue supplier balances.</p></div><div className={styles.heroCard}><small>Accounts receivable</small><h2>{money(dashboard.receivables_outstanding)}</h2><p>{money(dashboard.receivables_overdue)} overdue client invoice balances from Commercial Control.</p></div></section>
      <section className={styles.metrics}><div className={styles.metric}><small>Open periods</small><strong>{text(dashboard, "open_periods")}</strong><span>posting control</span></div><div className={styles.metric}><small>Journal approvals</small><strong>{text(dashboard, "journal_pending")}</strong><span>awaiting review</span></div><div className={styles.metric}><small>Posted journals</small><strong>{text(dashboard, "journals_posted")}</strong><span>{money(dashboard.posted_debits)} total debit evidence</span></div><div className={styles.metric}><small>Payment requests</small><strong>{text(dashboard, "payments_pending")}</strong><span>not bank transfers</span></div></section>
      <section className={styles.panel}><div className={styles.panelHead}><div><h3>Finance control setup</h3><p>Initialise the Phase 18 roles, accounts, numbering, approval workflows and policy once for the company.</p></div><button className={styles.mini} onClick={() => void initialise()}>Initialise Phase 18</button></div><div className={styles.grid2}><form className={styles.form} onSubmit={createPeriod}><div className={styles.field}><label>Period code</label><input required value={periodForm.period_code} onChange={(event) => setPeriodForm({ ...periodForm, period_code: event.target.value })}/></div><div className={styles.field}><label>Period name</label><input required value={periodForm.name} onChange={(event) => setPeriodForm({ ...periodForm, name: event.target.value })}/></div><div className={styles.field}><label>Starts</label><input required type="date" value={periodForm.start_date} onChange={(event) => setPeriodForm({ ...periodForm, start_date: event.target.value })}/></div><div className={styles.field}><label>Ends</label><input required type="date" value={periodForm.end_date} onChange={(event) => setPeriodForm({ ...periodForm, end_date: event.target.value })}/></div><div className={styles.formActions}><button className={styles.button}>Open financial period</button></div></form><form className={styles.form} onSubmit={createAccount}><div className={styles.field}><label>Account code</label><input required value={accountForm.account_code} onChange={(event) => setAccountForm({ ...accountForm, account_code: event.target.value })}/></div><div className={styles.field}><label>Account name</label><input required value={accountForm.name} onChange={(event) => setAccountForm({ ...accountForm, name: event.target.value })}/></div><div className={styles.field}><label>Account type</label><select value={accountForm.account_type} onChange={(event) => setAccountForm({ ...accountForm, account_type: event.target.value })}>{["asset", "liability", "equity", "revenue", "expense"].map((value) => <option key={value}>{value}</option>)}</select></div><div className={styles.field}><label>Parent account</label><select value={accountForm.parent_account_id} onChange={(event) => setAccountForm({ ...accountForm, parent_account_id: event.target.value })}><option value="">None</option>{accounts.filter((row) => text(row, "account_type") === accountForm.account_type).map((row) => <option key={number(row, "id")} value={number(row, "id")}>{text(row, "account_code")} · {text(row, "name")}</option>)}</select></div><div className={styles.formActions}><button className={styles.button}>Add chart account</button></div></form></div></section>
      <section className={styles.grid2}><div className={styles.panel}><div className={styles.panelHead}><div><h3>Financial periods</h3><p>Closing a period is blocked while draft, submitted, rejected or approved journals remain.</p></div></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Code</th><th>Period</th><th>Start</th><th>End</th><th>Status</th></tr></thead><tbody>{periods.map((row) => <tr key={number(row, "id")}><td>{text(row, "period_code")}</td><td>{text(row, "name")}</td><td>{text(row, "start_date")}</td><td>{text(row, "end_date")}</td><td><span className={`${styles.badge} ${badge(text(row, "status"))}`}>{text(row, "status")}</span></td></tr>)}</tbody></table></div></div><div className={styles.panel}><div className={styles.panelHead}><div><h3>Chart of accounts</h3><p>System starter accounts are generic control records; configure your accounting policy before production use.</p></div></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Code</th><th>Account</th><th>Type</th><th>System</th><th>Active</th></tr></thead><tbody>{accounts.map((row) => <tr key={number(row, "id")}><td>{text(row, "account_code")}</td><td>{text(row, "name")}</td><td>{text(row, "account_type")}</td><td>{String(Boolean(row.is_system))}</td><td>{String(Boolean(row.is_active))}</td></tr>)}</tbody></table></div></div></section>
      <section className={styles.panel}><div className={styles.panelHead}><div><h3>Prepare a balanced finance journal</h3><p>Journals stay draft until debit and credit lines balance exactly, then require independent approval before they can post.</p></div></div><form className={styles.form} onSubmit={createJournal}><div className={styles.field}><label>Branch</label><select required value={journalForm.branch_id} onChange={(event) => setJournalForm({ ...journalForm, branch_id: event.target.value })}><option value="">Select branch</option>{branches.map((row) => <option key={number(row, "id")} value={number(row, "id")}>{text(row, "code")} · {text(row, "name")}</option>)}</select></div><div className={styles.field}><label>Financial period</label><select required value={journalForm.period_id} onChange={(event) => setJournalForm({ ...journalForm, period_id: event.target.value })}><option value="">Select open period</option>{periods.filter((row) => text(row, "status") === "open").map((row) => <option key={number(row, "id")} value={number(row, "id")}>{text(row, "period_code")} · {text(row, "name")}</option>)}</select></div><div className={styles.field}><label>Journal date</label><input required type="date" value={journalForm.journal_date} onChange={(event) => setJournalForm({ ...journalForm, journal_date: event.target.value })}/></div><div className={styles.field}><label>Source type</label><input value={journalForm.source_type} onChange={(event) => setJournalForm({ ...journalForm, source_type: event.target.value })}/></div><div className={styles.field}><label>Source reference</label><input value={journalForm.source_reference} onChange={(event) => setJournalForm({ ...journalForm, source_reference: event.target.value })}/></div><div className={styles.field}><label>Supporting document ID</label><input type="number" value={journalForm.supporting_document_id} onChange={(event) => setJournalForm({ ...journalForm, supporting_document_id: event.target.value })}/></div><div className={`${styles.field} ${styles.wide}`}><label>Description</label><input required value={journalForm.description} onChange={(event) => setJournalForm({ ...journalForm, description: event.target.value })}/></div><div className={styles.formActions}><button className={styles.button}>Create draft journal</button></div></form></section>
      <section className={styles.panel}><div className={styles.panelHead}><div><h3>Finance journal register</h3><p>Select a draft journal to add its debit and credit lines, submit it and then post the approved ledger record.</p></div></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Journal</th><th>Date</th><th>Branch</th><th>Period</th><th>Debit</th><th>Credit</th><th>Status</th></tr></thead><tbody>{journals.map((row) => <tr className={styles.clickable} key={number(row, "id")} onClick={() => void chooseJournal(number(row, "id"))}><td><strong>{text(row, "journal_number")}</strong><br/><small>{text(row, "description")}</small></td><td>{text(row, "journal_date")}</td><td>{text(row, "branch_id")}</td><td>{text(row, "period_code")}</td><td>{money(row.debit_total)}</td><td>{money(row.credit_total)}</td><td><span className={`${styles.badge} ${badge(text(row, "status"))}`}>{text(row, "status")}</span></td></tr>)}</tbody></table></div></section>
      {selectedJournal && <section className={styles.grid2}><div className={styles.panel}><div className={styles.panelHead}><div><h3>{text(selectedJournal, "journal_number")} lines</h3><p>Debit {money(selectedJournal.debit_total)} · Credit {money(selectedJournal.credit_total)} · {text(selectedJournal, "line_count")} lines</p></div><div className={styles.actions}>{["draft", "rejected"].includes(text(selectedJournal, "status")) && <button className={styles.button} onClick={() => void journalAction("submit")}>Submit journal</button>}{text(selectedJournal, "status") === "approved" && <button className={`${styles.button} ${styles.good}`} onClick={() => void journalAction("post")}>Post journal</button>}</div></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Line</th><th>Account</th><th>Description</th><th>Debit</th><th>Credit</th><th>Action</th></tr></thead><tbody>{journalLines.map((row) => <tr key={number(row, "id")}><td>{text(row, "line_number")}</td><td>{text(row, "account_code")} · {text(row, "account_name")}</td><td>{text(row, "description")}</td><td>{money(row.debit)}</td><td>{money(row.credit)}</td><td>{["draft", "rejected"].includes(text(selectedJournal, "status")) && <button className={`${styles.mini} ${styles.bad}`} onClick={() => void removeLine(row)}>Remove</button>}</td></tr>)}</tbody></table></div></div><div className={styles.panel}><div className={styles.panelHead}><div><h3>Add journal line</h3><p>Enter one positive debit or one positive credit—never both.</p></div></div><form className={styles.form} onSubmit={addLine}><div className={styles.field}><label>Account</label><select required value={lineForm.account_id} onChange={(event) => setLineForm({ ...lineForm, account_id: event.target.value })}><option value="">Select account</option>{accounts.filter((row) => Boolean(row.is_active)).map((row) => <option key={number(row, "id")} value={number(row, "id")}>{text(row, "account_code")} · {text(row, "name")}</option>)}</select></div><div className={styles.field}><label>Debit</label><input type="number" min="0" step=".01" value={lineForm.debit} onChange={(event) => setLineForm({ ...lineForm, debit: event.target.value })}/></div><div className={styles.field}><label>Credit</label><input type="number" min="0" step=".01" value={lineForm.credit} onChange={(event) => setLineForm({ ...lineForm, credit: event.target.value })}/></div><div className={`${styles.field} ${styles.wide}`}><label>Line description</label><input value={lineForm.description} onChange={(event) => setLineForm({ ...lineForm, description: event.target.value })}/></div><div className={styles.formActions}><button className={styles.button}>Add journal line</button></div></form></div></section>}
      <section className={styles.panel}><div className={styles.panelHead}><div><h3>Record supplier invoice</h3><p>Invoices are accounts-payable evidence. A submitted invoice is independently approved before any payment request can exist.</p></div></div><form className={styles.form} onSubmit={createInvoice}><div className={styles.field}><label>Branch</label><select required value={invoiceForm.branch_id} onChange={(event) => setInvoiceForm({ ...invoiceForm, branch_id: event.target.value })}><option value="">Select branch</option>{branches.map((row) => <option key={number(row, "id")} value={number(row, "id")}>{text(row, "code")} · {text(row, "name")}</option>)}</select></div><div className={styles.field}><label>Supplier</label><select required value={invoiceForm.supplier_id} onChange={(event) => setInvoiceForm({ ...invoiceForm, supplier_id: event.target.value })}><option value="">Select supplier</option>{suppliers.map((row) => <option key={number(row, "id")} value={number(row, "id")}>{text(row, "supplier_code")} · {text(row, "name")}</option>)}</select></div><div className={styles.field}><label>Approved purchase order</label><select value={invoiceForm.purchase_order_id} onChange={(event) => setInvoiceForm({ ...invoiceForm, purchase_order_id: event.target.value })}><option value="">No linked purchase order</option>{purchaseOrders.filter((row) => !invoiceForm.supplier_id || number(row, "supplier_id") === Number(invoiceForm.supplier_id)).map((row) => <option key={number(row, "id")} value={number(row, "id")}>{text(row, "purchase_order_number")} · {money(row.total_amount)}</option>)}</select></div><div className={styles.field}><label>Supplier invoice reference</label><input required value={invoiceForm.supplier_invoice_reference} onChange={(event) => setInvoiceForm({ ...invoiceForm, supplier_invoice_reference: event.target.value })}/></div><div className={styles.field}><label>Invoice date</label><input required type="date" value={invoiceForm.invoice_date} onChange={(event) => setInvoiceForm({ ...invoiceForm, invoice_date: event.target.value })}/></div><div className={styles.field}><label>Due date</label><input type="date" value={invoiceForm.due_date} onChange={(event) => setInvoiceForm({ ...invoiceForm, due_date: event.target.value })}/></div><div className={styles.field}><label>Amount</label><input required type="number" min=".01" step=".01" value={invoiceForm.amount} onChange={(event) => setInvoiceForm({ ...invoiceForm, amount: event.target.value })}/></div><div className={styles.field}><label>Invoice document ID</label><input type="number" value={invoiceForm.invoice_document_id} onChange={(event) => setInvoiceForm({ ...invoiceForm, invoice_document_id: event.target.value })}/></div><div className={styles.formActions}><button className={styles.button}>Create supplier invoice</button></div></form></section>
      <section className={styles.panel}><div className={styles.panelHead}><div><h3>Accounts-payable register</h3><p>Choose an approved supplier invoice to prepare a controlled payment request. <a href="/api/v1/finance/exports/supplier-invoices.csv">Export CSV</a></p></div></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Invoice</th><th>Supplier</th><th>Supplier ref</th><th>Due</th><th>Amount</th><th>Outstanding</th><th>Status</th><th>Action</th></tr></thead><tbody>{invoices.map((row) => <tr className={styles.clickable} key={number(row, "id")} onClick={() => setSelectedInvoice(row)}><td>{text(row, "invoice_number")}</td><td>{text(row, "supplier_name")}</td><td>{text(row, "supplier_invoice_reference")}</td><td>{text(row, "due_date")}</td><td>{money(row.amount)}</td><td>{money(row.outstanding_amount)}</td><td><span className={`${styles.badge} ${badge(text(row, "status"))}`}>{text(row, "status")}</span></td><td>{["draft", "rejected"].includes(text(row, "status")) && <button className={styles.mini} onClick={(event) => { event.stopPropagation(); void submitInvoice(row); }}>Submit</button>}</td></tr>)}</tbody></table></div></section>
      {selectedInvoice && <section className={styles.grid2}><div className={styles.panel}><div className={styles.panelHead}><div><h3>Payment request for {text(selectedInvoice, "invoice_number")}</h3><p>{text(selectedInvoice, "supplier_name")} · outstanding {money(selectedInvoice.outstanding_amount)}. This only prepares a request; it cannot send money.</p></div></div><form className={styles.form} onSubmit={createPayment}><div className={styles.field}><label>Requested date</label><input required type="date" value={paymentForm.requested_date} onChange={(event) => setPaymentForm({ ...paymentForm, requested_date: event.target.value })}/></div><div className={styles.field}><label>Amount</label><input required type="number" min=".01" step=".01" value={paymentForm.amount} onChange={(event) => setPaymentForm({ ...paymentForm, amount: event.target.value })}/></div><div className={`${styles.field} ${styles.wide}`}><label>Proposed payment reference</label><input value={paymentForm.payment_reference} onChange={(event) => setPaymentForm({ ...paymentForm, payment_reference: event.target.value })}/></div><div className={styles.formActions}><button className={styles.button}>Create payment request</button></div></form></div><div className={styles.panel}><div className={styles.panelHead}><div><h3>Supplier payment register</h3><p>Approved payment requests can only be marked recorded after a controlled payment document is supplied.</p></div></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Payment</th><th>Invoice</th><th>Supplier</th><th>Requested</th><th>Amount</th><th>Status</th><th>Action</th></tr></thead><tbody>{payments.filter((row) => text(row, "supplier_invoice_id") === text(selectedInvoice, "id")).map((row) => <tr key={number(row, "id")}><td>{text(row, "payment_number")}</td><td>{text(row, "supplier_invoice_number")}</td><td>{text(row, "supplier_name")}</td><td>{text(row, "requested_date")}</td><td>{money(row.amount)}</td><td><span className={`${styles.badge} ${badge(text(row, "status"))}`}>{text(row, "status")}</span></td><td>{["draft", "rejected"].includes(text(row, "status")) && <button className={styles.mini} onClick={() => void submitPayment(row)}>Submit</button>}{text(row, "status") === "approved" && <button className={`${styles.mini} ${styles.good}`} onClick={() => void recordPayment(row)}>Record evidence</button>}</td></tr>)}</tbody></table></div></div></section>}
      <section className={styles.grid2}><div className={styles.panel}><div className={styles.panelHead}><div><h3>Finance approval queue</h3><p>Every journal, supplier invoice and payment request follows the shared maker/checker workflow.</p></div></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Reference</th><th>Type</th><th>Finance record</th><th>Amount</th><th>Step</th><th>Action</th></tr></thead><tbody>{approvals.map((row) => <tr key={number(row, "id")}><td>{text(row, "reference")}</td><td>{text(row, "entity_type")}</td><td>{text(row, "finance_reference")}</td><td>{money(row.amount)}</td><td>{text(row, "current_step_order")}</td><td><div className={styles.actions}><button className={`${styles.mini} ${styles.good}`} onClick={() => void decide(row, "approve")}>Approve</button><button className={`${styles.mini} ${styles.bad}`} onClick={() => void decide(row, "reject")}>Reject</button></div></td></tr>)}</tbody></table></div></div><div className={styles.panel}><div className={styles.panelHead}><div><h3>Finance audit</h3><p>Latest period, journal, supplier invoice, payment and approval actions.</p></div></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Time</th><th>Actor</th><th>Action</th><th>Entity</th><th>Reference</th></tr></thead><tbody>{audit.map((row, index) => <tr key={String(row.id ?? index)}><td>{text(row, "occurred_at")}</td><td>{text(row, "actor")}</td><td>{text(row, "action")}</td><td>{text(row, "entity_type")}</td><td>#{text(row, "entity_id")}</td></tr>)}</tbody></table></div></div></section>
    </div>
  </main>;
}
