"use client";
import { FormEvent, useState } from "react";
import { Building2, Plus } from "lucide-react";
import { PageHeader } from "@/components/dashboard/page-header";
import { DataTable } from "@/components/dashboard/data-table";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { useAdminMerchantsQuery, useCreateMerchantMutation } from "@/store/gateway-api";
export default function Page(){const {data=[]}=useAdminMerchantsQuery();const [create,{isLoading}]=useCreateMerchantMutation();const [form,setForm]=useState({name:"",slug:"",email:"",phone:""});async function submit(e:FormEvent){e.preventDefault();await create(form).unwrap();setForm({name:"",slug:"",email:"",phone:""});}return <><PageHeader title="Merchants" description="Organizations that consume Ithute Pay Bridge APIs. Each merchant can own multiple sandbox or live applications."/><div className="grid gap-5 xl:grid-cols-[1fr_390px]"><DataTable rows={data} columns={[{key:"name",label:"Merchant",render:(r:any)=><div><p className="font-bold text-[#082b4d]">{r.name}</p><p className="text-xs text-slate-500">{r.slug}</p></div>},{key:"contact",label:"Contact",render:(r:any)=><div><p>{r.email||"—"}</p><p className="text-xs text-slate-500">{r.phone||""}</p></div>},{key:"status",label:"Status",render:(r:any)=><span className="capitalize">{r.status}</span>},{key:"created",label:"Created",render:(r:any)=>new Date(r.created_at).toLocaleDateString()}]}/><Card className="h-fit"><CardHeader><CardTitle className="flex items-center gap-2"><Building2 className="h-4 w-4"/>Add merchant</CardTitle></CardHeader><CardContent><form className="space-y-3" onSubmit={submit}><Input required placeholder="Merchant name" value={form.name} onChange={e=>setForm({...form,name:e.target.value,slug:form.slug||e.target.value.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")})}/><Input required placeholder="merchant-slug" value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})}/><Input type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><Input placeholder="Phone" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><Button className="w-full" disabled={isLoading}><Plus className="h-4 w-4"/>{isLoading?"Creating…":"Create merchant"}</Button></form></CardContent></Card></div></>}
