"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { useBuildTrackUi } from "../../components/ui";
import styles from "../../workforce/workforce.module.css";

type Row=Record<string,unknown>;
type Policy={deadline_warning_days:number;minimum_margin_pct:string;require_commercial_approval:boolean;require_submission_approval:boolean;can_edit:boolean};
const API="/api/v1";
function text(r:Row|null|undefined,k:string){return String(r?.[k]??"")}
function num(r:Row|null|undefined,k:string){return Number(r?.[k]??0)}
function asRow(v:unknown):Row|null{return v&&typeof v==="object"&&!Array.isArray(v)?v as Row:null}
function cash(v:unknown){return `M ${Number(v??0).toLocaleString("en-LS",{minimumFractionDigits:2,maximumFractionDigits:2})}`}
async function api<T>(path:string,init?:RequestInit):Promise<T>{const response=await fetch(`${API}${path}`,{...init,credentials:"include",headers:{"Content-Type":"application/json",...(init?.headers??{})},cache:"no-store"});if(response.status===401){window.location.href=`/login?returnTo=${encodeURIComponent("/tenders/control")}`;throw new Error("Session expired")};const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(typeof payload?.detail==="string"?payload.detail:JSON.stringify(payload?.detail??payload));return payload as T}
function Field({label,children,wide=false}:{label:string;children:React.ReactNode;wide?:boolean}){return <div className={`${styles.field} ${wide?styles.wide:""}`}><label>{label}</label>{children}</div>}
function Btn({children,variant="",...props}:React.ButtonHTMLAttributes<HTMLButtonElement>&{variant?:"secondary"|"danger"|""}){return <button {...props} className={`${styles.button} ${variant?styles[variant]:""}`}>{children}</button>}

export default function TenderControl(){
 const {promptText}=useBuildTrackUi();
 const [tenders,setTenders]=useState<Row[]>([]),[selectedId,setSelectedId]=useState(""),[detail,setDetail]=useState<Row|null>(null),[policy,setPolicy]=useState<Policy>({deadline_warning_days:7,minimum_margin_pct:"0",require_commercial_approval:true,require_submission_approval:true,can_edit:false}),[error,setError]=useState(""),[notice,setNotice]=useState(""),[loading,setLoading]=useState(true);
 const [outcome,setOutcome]=useState({outcome:"awarded",decision_date:new Date().toISOString().slice(0,10),awarded_amount:"",winning_bidder:"",winning_amount:"",loss_reason:"",lessons_learned:"",award_document_id:""});
 const refresh=useCallback(async()=>{setLoading(true);setError("");try{const [t,p]=await Promise.all([api<Row[]>("/tenders"),api<Policy>("/tenders/policy/current")]);setTenders(t);setPolicy(p);if(selectedId)setDetail(await api<Row>(`/tenders/${selectedId}`));}catch(e){setError(e instanceof Error?e.message:"Could not load Tender Control")}finally{setLoading(false)}},[selectedId]);
 useEffect(()=>{void refresh()},[]);
 function success(m:string){setNotice(m);setError("");setTimeout(()=>setNotice(""),3500);void refresh()}
 async function choose(id:string){setSelectedId(id);setDetail(id?await api<Row>(`/tenders/${id}`):null)}
 async function decide(requestId:number,decision:"approve"|"reject"){const comment=await promptText({title:decision==="approve"?"Approve tender submission":"Reject tender submission",description:"Optionally record context for this controlled approval decision.",label:"Decision comment",multiline:true,confirmLabel:decision==="approve"?"Approve":"Reject"});if(comment===null)return;try{await api(`/tenders/approvals/${requestId}/decision`,{method:"POST",body:JSON.stringify({decision,comment:comment||null})});success(`Tender approval ${decision}d.`)}catch(e){setError(e instanceof Error?e.message:"Could not decide approval")}}
 async function savePolicy(e:FormEvent){e.preventDefault();try{await api("/tenders/policy/current",{method:"PUT",body:JSON.stringify({deadline_warning_days:policy.deadline_warning_days,minimum_margin_pct:Number(policy.minimum_margin_pct),require_commercial_approval:true,require_submission_approval:true})});success("Tender governance policy updated.")}catch(e){setError(e instanceof Error?e.message:"Could not save policy")}}
 async function recordOutcome(e:FormEvent){e.preventDefault();try{await api(`/tenders/${selectedId}/outcome`,{method:"POST",body:JSON.stringify({...outcome,awarded_amount:outcome.awarded_amount?Number(outcome.awarded_amount):null,winning_amount:outcome.winning_amount?Number(outcome.winning_amount):null,winning_bidder:outcome.winning_bidder||null,loss_reason:outcome.loss_reason||null,lessons_learned:outcome.lessons_learned||null,award_document_id:outcome.award_document_id?Number(outcome.award_document_id):null})});success(`Tender outcome recorded: ${outcome.outcome}.`)}catch(e){setError(e instanceof Error?e.message:"Could not record outcome")}}
 async function handoff(){try{const result=await api<Row>(`/tenders/${selectedId}/mobilisation-handoff`);const blob=new Blob([JSON.stringify(result,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`${text(detail,"tender_number")||"tender"}-phase6-handoff.json`;a.click();URL.revokeObjectURL(url);success("Phase 6 mobilisation handoff snapshot generated.")}catch(e){setError(e instanceof Error?e.message:"Tender is not ready for Phase 6 handoff")}}
 if(loading)return <main className={styles.page}><div className={styles.loading}><strong>Loading Tender Control…</strong></div></main>;
 const commercial=asRow(detail?.commercial_approval),submission=asRow(detail?.submission_approval),recorded=asRow(detail?.outcome);const selected=tenders.find(r=>String(r.id)===selectedId);
 return <main className={styles.page}><header className={styles.header}><div className={styles.brand}><span className={styles.brandMark}>BT</span><div><small>BuildTrack Construction Operations</small><h1>Tender Control</h1><p>Approvals · governance · outcomes · mobilisation handoff</p></div></div><div className={styles.headerActions}><Link className={styles.link} href="/tenders">Tender operations</Link><Link className={styles.link} href="/access">Access & Security</Link><Link className={styles.link} href="/">Core platform</Link></div></header><div className={styles.shell}>{error&&<div className={styles.error}>{error}</div>}{notice&&<div className={styles.notice}>{notice}</div>}<section className={styles.hero}><div className={styles.heroCard}><span className={styles.phase}>Phase 5 · Governance</span><h2>Separate preparation from approval.</h2><p>Commercial and submission approvals use the shared BuildTrack approval engine. The requesting user cannot approve their own request when the company no-self-approval policy is active.</p></div><div className={styles.heroCard}><small>Phase 6 boundary</small><h2>Awarded only</h2><p>Mobilisation handoff is generated only from an awarded tender with controlled submission evidence.</p></div></section>
 <div className={styles.grid2}><section className={styles.panel}><div className={styles.panelHead}><div><h3>Approval queue</h3><p>Select a tender and action its current shared approval requests.</p></div></div><div className={styles.toolbar}><select value={selectedId} onChange={e=>void choose(e.target.value)}><option value="">Select tender</option>{tenders.map(r=><option key={num(r,"id")} value={num(r,"id")}>{text(r,"tender_number")} · {text(r,"title")}</option>)}</select></div>{selected&&<><div className={styles.detail} style={{marginTop:12}}><div><small>Tender</small><strong>{text(selected,"tender_number")}</strong></div><div><small>Status</small><strong>{text(selected,"status")}</strong></div><div><small>Price</small><strong>{cash(selected.tender_price)}</strong></div><div><small>Margin</small><strong>{text(selected,"gross_margin_pct")}%</strong></div></div><ApprovalCard title="Commercial approval" row={commercial} onDecide={decide}/><ApprovalCard title="Submission approval" row={submission} onDecide={decide}/></>}</section>
 <section className={styles.panel}><div className={styles.panelHead}><div><h3>Tender policy</h3><p>Approval controls are mandatory; configure warning and commercial floor only.</p></div></div><div className={styles.warning}>Always enforced: controlled commercial approval and controlled submission approval remain enabled.</div><form className={styles.form} onSubmit={savePolicy}><Field label="Deadline warning days"><input type="number" min="1" max="90" value={policy.deadline_warning_days} onChange={e=>setPolicy({...policy,deadline_warning_days:Number(e.target.value)})}/></Field><Field label="Minimum margin %"><input type="number" min="-100" max="100" step=".001" value={policy.minimum_margin_pct} onChange={e=>setPolicy({...policy,minimum_margin_pct:e.target.value})}/></Field><div className={styles.formActions}><Btn disabled={!policy.can_edit}>Save policy</Btn></div></form></section></div>
 <div className={styles.grid2}><section className={styles.panel}><div className={styles.panelHead}><div><h3>Award / loss analysis</h3><p>Record the result only after a controlled tender submission.</p></div></div>{selected&&<form className={styles.form} onSubmit={recordOutcome}><Field label="Outcome"><select value={outcome.outcome} onChange={e=>setOutcome({...outcome,outcome:e.target.value})}>{["awarded","lost","cancelled","withdrawn"].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Decision date"><input type="date" value={outcome.decision_date} onChange={e=>setOutcome({...outcome,decision_date:e.target.value})}/></Field><Field label="Awarded amount"><input type="number" min="0" step=".01" value={outcome.awarded_amount} onChange={e=>setOutcome({...outcome,awarded_amount:e.target.value})}/></Field><Field label="Winning bidder"><input value={outcome.winning_bidder} onChange={e=>setOutcome({...outcome,winning_bidder:e.target.value})}/></Field><Field label="Winning amount"><input type="number" min="0" step=".01" value={outcome.winning_amount} onChange={e=>setOutcome({...outcome,winning_amount:e.target.value})}/></Field><Field label="Loss reason" wide><textarea value={outcome.loss_reason} onChange={e=>setOutcome({...outcome,loss_reason:e.target.value})}/></Field><Field label="Lessons learned" wide><textarea value={outcome.lessons_learned} onChange={e=>setOutcome({...outcome,lessons_learned:e.target.value})}/></Field><div className={styles.formActions}><Btn>Record outcome</Btn></div></form>}{recorded&&<div className={styles.sectionNote}>Recorded outcome: <strong>{text(recorded,"outcome")}</strong> · {text(recorded,"decision_date")}</div>}</section>
 <section className={styles.panel}><div className={styles.panelHead}><div><h3>Phase 6 mobilisation handoff</h3><p>The handoff contains tender scope, final submission, award, estimate lines, tender team and commercial totals.</p></div></div>{detail?<><div className={styles.detail}><div><small>Status</small><strong>{text(detail,"status")}</strong></div><div><small>Submission evidence</small><strong>{Array.isArray(detail.submissions)?detail.submissions.length:0}</strong></div><div><small>Outcome</small><strong>{text(recorded,"outcome")||"not recorded"}</strong></div><div><small>Commercial approval</small><strong>{text(commercial,"status")||"not requested"}</strong></div></div><div className={styles.formActions}><Btn onClick={()=>void handoff()} disabled={text(detail,"status")!=="awarded"}>Generate Phase 6 handoff</Btn></div></>:<div className={styles.empty}>Select a tender first.</div>}</section></div>
 </div></main>
}
function ApprovalCard({title,row,onDecide}:{title:string;row:Row|null;onDecide:(id:number,d:"approve"|"reject")=>void|Promise<void>}){return <div className={styles.sectionNote} style={{marginTop:12}}><strong>{title}</strong>{!row?<p>Not requested.</p>:<><p>{text(row,"reference")} · status <strong>{text(row,"status")}</strong> · step {text(row,"current_step_order")}</p>{text(row,"status")==="pending"&&<div className={styles.actions}><button className={`${styles.mini} ${styles.good}`} onClick={()=>void onDecide(num(row,"id"),"approve")}>Approve current step</button><button className={`${styles.mini} ${styles.bad}`} onClick={()=>void onDecide(num(row,"id"),"reject")}>Reject</button></div>}</>}</div>}
