"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import styles from "../../workforce/workforce.module.css";

type Row = Record<string, unknown>;
type Catalog = { branches: Row[]; sites: Row[]; employees: Row[]; permissions: string[] };
type Policy = { maintenance_due_warning_days:number; require_maintenance_approval:boolean; critical_defect_blocks_operation:boolean; can_edit:boolean };
const API="/api/v1";
function text(r:Row|null|undefined,k:string){return String(r?.[k]??"")}
function num(r:Row|null|undefined,k:string){return Number(r?.[k]??0)}
async function api<T>(path:string,init?:RequestInit):Promise<T>{const response=await fetch(`${API}${path}`,{...init,credentials:"include",headers:{"Content-Type":"application/json",...(init?.headers??{})},cache:"no-store"});if(response.status===401){window.location.href=`/login?returnTo=${encodeURIComponent("/fleet/control")}`;throw new Error("Session expired")};const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(typeof payload?.detail==="string"?payload.detail:JSON.stringify(payload?.detail??payload));return payload as T}
function Field({label,children,wide=false}:{label:string;children:React.ReactNode;wide?:boolean}){return <div className={`${styles.field} ${wide?styles.wide:""}`}><label>{label}</label>{children}</div>}
function Btn({children,variant="",...props}:React.ButtonHTMLAttributes<HTMLButtonElement>&{variant?:"secondary"|"danger"|""}){return <button {...props} className={`${styles.button} ${variant?styles[variant]:""}`}>{children}</button>}
function badge(value:string){if(["approved","active","serviceable","completed"].includes(value))return styles.green;if(["submitted","standby","restricted","maintenance"].includes(value))return styles.amber;if(["rejected","out_of_service","unserviceable","critical","blocked"].includes(value))return styles.red;return styles.blue}

export default function FleetControl(){
 const [catalog,setCatalog]=useState<Catalog>({branches:[],sites:[],employees:[],permissions:[]}),[assets,setAssets]=useState<Row[]>([]),[readiness,setReadiness]=useState<Row[]>([]),[assignments,setAssignments]=useState<Row[]>([]),[inspections,setInspections]=useState<Row[]>([]),[compliance,setCompliance]=useState<Row[]>([]),[plans,setPlans]=useState<Row[]>([]),[policy,setPolicy]=useState<Policy>({maintenance_due_warning_days:14,require_maintenance_approval:true,critical_defect_blocks_operation:true,can_edit:false}),[selectedAsset,setSelectedAsset]=useState(""),[assetStatus,setAssetStatus]=useState({status:"standby",serviceability:"serviceable",notes:""}),[meter,setMeter]=useState({odometer_km:"",engine_hours:"",notes:""}),[error,setError]=useState(""),[notice,setNotice]=useState(""),[loading,setLoading]=useState(true);
 const permissions=useMemo(()=>new Set(catalog.permissions),[catalog.permissions]);const can=(p:string)=>permissions.has(p);
 async function refresh(){setLoading(true);setError("");try{const [c,a,r,as,i,co,p,pol]=await Promise.all([api<Catalog>("/fleet/catalog"),api<Row[]>("/fleet/assets"),api<Row[]>("/fleet/control-board"),api<Row[]>("/fleet/assignments"),api<Row[]>("/fleet/inspections"),api<Row[]>("/fleet/compliance"),api<Row[]>("/fleet/maintenance-plans"),api<Policy>("/fleet/policy")]);setCatalog(c);setAssets(a);setReadiness(r);setAssignments(as);setInspections(i);setCompliance(co);setPlans(p);setPolicy(pol)}catch(e){setError(e instanceof Error?e.message:"Could not load Fleet Control")}finally{setLoading(false)}}
 useEffect(()=>{void refresh()},[]);
 function success(m:string){setNotice(m);setError("");setTimeout(()=>setNotice(""),3500);void refresh()}
 function chooseAsset(id:string){setSelectedAsset(id);const asset=assets.find(r=>String(r.id)===id);if(asset){setAssetStatus({status:text(asset,"status")||"standby",serviceability:text(asset,"serviceability")||"serviceable",notes:""});setMeter({odometer_km:text(asset,"current_odometer_km"),engine_hours:text(asset,"current_engine_hours"),notes:""})}}
 async function saveAssetStatus(e:FormEvent){e.preventDefault();try{await api(`/fleet/assets/${selectedAsset}/status`,{method:"POST",body:JSON.stringify(assetStatus)});success("Asset lifecycle/serviceability updated.")}catch(e){setError(e instanceof Error?e.message:"Could not update asset")}}
 async function saveMeter(e:FormEvent){e.preventDefault();try{await api(`/fleet/assets/${selectedAsset}/meters`,{method:"POST",body:JSON.stringify({odometer_km:meter.odometer_km?Number(meter.odometer_km):null,engine_hours:meter.engine_hours?Number(meter.engine_hours):null,notes:meter.notes||null})});success("Meter reading recorded.")}catch(e){setError(e instanceof Error?e.message:"Could not save meter")}}
 async function closeAssignment(id:number){try{await api(`/fleet/assignments/${id}/complete`,{method:"POST"});success("Assignment completed.")}catch(e){setError(e instanceof Error?e.message:"Could not complete assignment")}}
 async function decideInspection(id:number,decision:"approve"|"reject"){try{await api(`/fleet/inspections/${id}/decision`,{method:"POST",body:JSON.stringify({decision})});success(`Inspection ${decision}d.`)}catch(e){setError(e instanceof Error?e.message:"Could not decide inspection")}}
 async function savePolicy(e:FormEvent){e.preventDefault();try{await api("/fleet/policy",{method:"PUT",body:JSON.stringify({maintenance_due_warning_days:policy.maintenance_due_warning_days})});success("Fleet alert policy updated.")}catch(e){setError(e instanceof Error?e.message:"Could not update fleet policy")}}
 if(loading)return <main className={styles.page}><div className={styles.loading}><strong>Loading Fleet Control…</strong></div></main>;
 const selected=assets.find(r=>String(r.id)===selectedAsset);
 return <main className={styles.page}><header className={styles.header}><div className={styles.brand}><span className={styles.brandMark}>BT</span><div><small>BuildTrack Construction Operations</small><h1>Fleet Control</h1><p>Approvals · handovers · serviceability · meters · policy</p></div></div><div className={styles.headerActions}><Link className={styles.link} href="/fleet">Fleet operations</Link><Link className={styles.link} href="/access">Access & Security</Link><Link className={styles.link} href="/">Core platform</Link></div></header><div className={styles.shell}>{error&&<div className={styles.error}>{error}</div>}{notice&&<div className={styles.notice}>{notice}</div>}<section className={styles.hero}><div className={styles.heroCard}><span className={styles.phase}>Phase 4 · Control</span><h2>Maker/checker and lifecycle administration.</h2><p>Keep routine data capture separate from high-impact controls: approve inspections, close handovers, record verified meters and decide whether an asset may return to service.</p></div><div className={styles.heroCard}><small>Pending inspections</small><h2>{inspections.filter(r=>text(r,"status")==="submitted").length}</h2><p>{assignments.filter(r=>text(r,"status")==="active").length} active assignment(s)</p></div></section>
 <section className={styles.panel}><div className={styles.panelHead}><div><h3>Operational readiness board</h3><p>Deterministic answer before a vehicle or plant asset is assigned: document validity, inspection, mechanical condition, defects, maintenance and active handovers are checked together.</p></div></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Asset</th><th>Decision</th><th>Blocking reason</th><th>Warning / next action</th></tr></thead><tbody>{readiness.map(r=><tr key={num(r,"asset_id")}><td><strong>{text(r,"asset_number")}</strong><br/><small>{text(r,"asset")}</small></td><td><span className={`${styles.badge} ${badge(text(r,"decision"))}`}>{text(r,"decision")}</span></td><td>{Array.isArray(r.blockers)&&r.blockers.length?(r.blockers as string[]).join("; "):"—"}</td><td>{Array.isArray(r.warnings)&&r.warnings.length?(r.warnings as string[]).join("; "):"Ready to use"}</td></tr>)}{!readiness.length&&<tr><td colSpan={4} className={styles.empty}>No fleet or plant assets in your scope.</td></tr>}</tbody></table></div></section>
 <div className={styles.grid2}><section className={styles.panel}><div className={styles.panelHead}><div><h3>Asset lifecycle & meters</h3><p>Critical open defects are enforced server-side before return to active service.</p></div></div><div className={styles.toolbar}><select value={selectedAsset} onChange={e=>chooseAsset(e.target.value)}><option value="">Select asset</option>{assets.map(r=><option key={num(r,"id")} value={num(r,"id")}>{text(r,"asset_number")} · {text(r,"registration_number")||`${text(r,"make")} ${text(r,"model")}`}</option>)}</select></div>{selected&&<><div className={styles.detail} style={{marginTop:12}}><div><small>Status</small><strong>{text(selected,"status")}</strong></div><div><small>Serviceability</small><strong>{text(selected,"serviceability")}</strong></div><div><small>Odometer</small><strong>{text(selected,"current_odometer_km")} km</strong></div><div><small>Engine hours</small><strong>{text(selected,"current_engine_hours")} h</strong></div></div>{can("fleet.manage")&&<form className={styles.form} onSubmit={saveAssetStatus} style={{marginTop:12}}><Field label="Status"><select value={assetStatus.status} onChange={e=>setAssetStatus({...assetStatus,status:e.target.value})}>{["active","standby","maintenance","out_of_service","disposed"].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Serviceability"><select value={assetStatus.serviceability} onChange={e=>setAssetStatus({...assetStatus,serviceability:e.target.value})}>{["serviceable","restricted","unserviceable"].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Reason" wide><input value={assetStatus.notes} onChange={e=>setAssetStatus({...assetStatus,notes:e.target.value})}/></Field><div className={styles.formActions}><Btn>Update lifecycle</Btn></div></form>} {can("fleet.manage")&&<form className={styles.form} onSubmit={saveMeter} style={{marginTop:12}}><Field label="Odometer km"><input type="number" step=".1" min="0" value={meter.odometer_km} onChange={e=>setMeter({...meter,odometer_km:e.target.value})}/></Field><Field label="Engine hours"><input type="number" step=".1" min="0" value={meter.engine_hours} onChange={e=>setMeter({...meter,engine_hours:e.target.value})}/></Field><Field label="Evidence note" wide><input value={meter.notes} onChange={e=>setMeter({...meter,notes:e.target.value})}/></Field><div className={styles.formActions}><Btn>Record meter reading</Btn></div></form>}</>}</section>
 <section className={styles.panel}><div className={styles.panelHead}><div><h3>Fleet policy</h3><p>Configure the preventive-maintenance alert lead-time. Compliance reminder days are set on each licence, insurance or permit record.</p></div></div><div className={styles.warning}>Always enforced: maintenance maker/checker approval is mandatory, and unresolved critical defects block an asset from active service.</div><form className={styles.form} onSubmit={savePolicy}><Field label="Maintenance warning days"><input type="number" min="0" max="365" value={policy.maintenance_due_warning_days} onChange={e=>setPolicy({...policy,maintenance_due_warning_days:Number(e.target.value)})}/></Field><div className={styles.formActions}><Btn disabled={!policy.can_edit}>Save alert policy</Btn></div></form>{!policy.can_edit&&<div className={styles.sectionNote}>Company-level Fleet Manager/System Administrator authority is required to change the global warning window.</div>}</section></div>
 <div className={styles.grid2}><section className={styles.panel}><div className={styles.panelHead}><div><h3>Inspection approval queue</h3><p>Company no-self-approval policy applies.</p></div></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Date</th><th>Asset</th><th>Type</th><th>Safe</th><th>Status</th><th>Action</th></tr></thead><tbody>{inspections.map(r=><tr key={num(r,"id")}><td>{text(r,"inspection_date")}</td><td>{text(r,"asset_id")}</td><td>{text(r,"inspection_type")}</td><td>{String(r.safe_to_operate?"Yes":"No")}</td><td><span className={`${styles.badge} ${badge(text(r,"status"))}`}>{text(r,"status")}</span></td><td className={styles.actions}>{text(r,"status")==="submitted"&&can("fleet.inspect.approve")&&<><button className={`${styles.mini} ${styles.good}`} onClick={()=>void decideInspection(num(r,"id"),"approve")}>Approve</button><button className={`${styles.mini} ${styles.bad}`} onClick={()=>void decideInspection(num(r,"id"),"reject")}>Reject</button></>}</td></tr>)}</tbody></table></div></section>
 <section className={styles.panel}><div className={styles.panelHead}><div><h3>Active assignments / handover</h3><p>Close assignments when equipment returns or changes site/operator.</p></div></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Asset</th><th>Employee</th><th>Branch</th><th>Site</th><th>From</th><th>Action</th></tr></thead><tbody>{assignments.filter(r=>text(r,"status")==="active").map(r=><tr key={num(r,"id")}><td>{text(r,"asset_id")}</td><td>{text(r,"employee_id")||"—"}</td><td>{text(r,"branch_id")}</td><td>{text(r,"site_id")||"—"}</td><td>{text(r,"assigned_from")}</td><td>{can("fleet.assign")&&<button className={styles.mini} onClick={()=>void closeAssignment(num(r,"id"))}>Complete / handover</button>}</td></tr>)}</tbody></table></div></section></div>
 <div className={styles.grid2}><section className={styles.panel}><div className={styles.panelHead}><div><h3>Compliance register</h3><p>Company-wide expiry evidence within your scope.</p></div></div><SimpleTable rows={compliance} columns={["asset_number","compliance_type","reference_number","provider","expiry_date","reminder_days","cost"]}/></section><section className={styles.panel}><div className={styles.panelHead}><div><h3>Maintenance-plan register</h3><p>Next due date, kilometre and engine-hour thresholds.</p></div></div><SimpleTable rows={plans} columns={["asset_number","name","next_due_date","next_due_odometer_km","next_due_engine_hours","is_active"]}/></section></div>
 </div></main>
}
function SimpleTable({rows,columns}:{rows:Row[];columns:string[]}){return <div className={styles.tableWrap}><table className={styles.table}><thead><tr>{columns.map(c=><th key={c}>{c.replaceAll("_"," ")}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={String(r.id??i)}>{columns.map(c=><td key={c}>{text(r,c)||"—"}</td>)}</tr>)}{!rows.length&&<tr><td colSpan={columns.length} className={styles.empty}>No records yet.</td></tr>}</tbody></table></div>}
