"use client";

import { FormEvent, useEffect, useState } from "react";
import { ArrowRightLeft, Clock3, Globe2, RefreshCw, RotateCw, ShoppingCart, XCircle } from "lucide-react";
import { ControlShell } from "@/components/control-shell";

const API = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8006/api/v1";
type Membership = { tenant_id: string; tenant_name: string; role: string; status: string };
type Me = { email?: string; is_platform_owner?: boolean };
type Order = { id:string; domain_name:string; operation:string; years:number; provider:string; provider_order_id?:string|null; status:string; response?:{message?:string}|null; created_at?:string|null };

async function api(path:string, init?:RequestInit){
  return fetch(`${API}${path}`,{credentials:"include",...init,headers:{"Content-Type":"application/json",...(init?.headers||{})}});
}
async function errorText(response:Response,fallback:string){const body=await response.json().catch(()=>({}));return typeof body.detail==="string"?body.detail:fallback;}
function label(value:string){return value.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());}
function statusClass(value:string){if(value==="completed")return"bg-emerald-50 text-emerald-700";if(value==="failed"||value==="canceled")return"bg-red-50 text-red-700";if(value==="processing")return"bg-blue-50 text-blue-700";return"bg-amber-50 text-amber-700";}

export default function DomainOrdersPage(){
  const[me,setMe]=useState<Me|null>(null);const[contexts,setContexts]=useState<Membership[]>([]);const[tenant,setTenant]=useState("");const[orders,setOrders]=useState<Order[]>([]);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState("");const[message,setMessage]=useState("");const[error,setError]=useState("");
  useEffect(()=>{void(async()=>{try{const meResponse=await api("/auth/me");if(!meResponse.ok)throw new Error("Unable to load account");const current=await meResponse.json();setMe(current);let rows:Membership[]=[];if(current.is_platform_owner){const r=await api("/tenants");if(r.ok)rows=(await r.json()).map((t:{id:string;name:string;status:string})=>({tenant_id:t.id,tenant_name:t.name,role:"platform_owner",status:t.status}));}else{const r=await api("/me/memberships");if(r.ok)rows=await r.json();}rows=rows.filter(row=>row.status==="active");setContexts(rows);const remembered=localStorage.getItem("mailbox_dns_tenant");setTenant(rows.find(row=>row.tenant_id===remembered)?.tenant_id||rows[0]?.tenant_id||"");}catch(cause){setError(cause instanceof Error?cause.message:"Unable to load domain orders");}finally{setLoading(false)}})()},[]);
  useEffect(()=>{if(!tenant)return;localStorage.setItem("mailbox_dns_tenant",tenant);void load()},[tenant]);
  async function load(){setLoading(true);setError("");const response=await api(`/tenants/${tenant}/domain-orders`);if(response.ok)setOrders((await response.json()).items||[]);else setError(await errorText(response,"Unable to load domain orders"));setLoading(false);}
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!tenant)return;const form=new FormData(event.currentTarget);const domain_name=String(form.get("domain_name")||"").trim();const operation=String(form.get("operation")||"register");const years=Number(form.get("years")||1);if(!domain_name)return;setBusy("create");setError("");setMessage("");const response=await api(`/tenants/${tenant}/domain-orders`,{method:"POST",body:JSON.stringify({domain_name,operation,years})});if(response.ok){const row=await response.json();setMessage(`${row.domain_name}: ${label(row.operation)} request accepted. Registrar fulfillment is pending until Ithute's external registrar integration is configured or an owner processes it.`);event.currentTarget.reset();await load();}else setError(await errorText(response,"Unable to create domain order"));setBusy("");}
  async function cancel(order:Order){if(!window.confirm(`Cancel the pending ${label(order.operation)} request for ${order.domain_name}?`))return;setBusy(order.id);setError("");const response=await api(`/tenants/${tenant}/domain-orders/${order.id}/cancel`,{method:"POST"});if(response.ok){setMessage(`${order.domain_name} order canceled.`);await load();}else setError(await errorText(response,"Unable to cancel order"));setBusy("");}
  const selected=contexts.find(row=>row.tenant_id===tenant);const canManage=Boolean(me?.is_platform_owner||selected?.role==="tenant_admin"||selected?.role==="dns_admin");
  return <ControlShell title="Domain registration & renewals" subtitle="Commercial domain lifecycle requests with package and permission controls" userEmail={me?.email}>
    <div className="space-y-5">
      <section className="relative overflow-hidden rounded-[28px] bg-[#123a38] p-6 text-white shadow-[0_22px_60px_rgba(18,58,56,.18)] sm:p-7"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[.06] px-3 py-2 text-[9px] font-black uppercase tracking-[.13em] text-[#d8c56a]"><Globe2 size={13}/> Domain commerce</div><h1 className="mt-4 text-3xl font-black tracking-[-.045em]">Register, renew or transfer a domain.</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-white/65">Ithute validates your organization, package capacity and permissions before accepting an order. External registrar automation is not yet configured, so accepted requests stay pending until fulfillment is processed.</p></div><select value={tenant} onChange={event=>setTenant(event.target.value)} className="min-h-11 rounded-xl border border-white/15 bg-white/10 px-3 text-xs font-bold text-white">{contexts.map(item=><option className="text-black" key={item.tenant_id} value={item.tenant_id}>{item.tenant_name}</option>)}</select></div></section>
      {message?<div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-xs font-bold text-emerald-800">{message}</div>:null}{error?<div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-xs font-bold text-red-800">{error}</div>:null}
      <section className="grid gap-4 xl:grid-cols-[.72fr_1.28fr]">
        <form onSubmit={submit} className="surface-card p-5"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#edf4f1] text-[#285b55]"><ShoppingCart size={18}/></span><div><h2 className="text-lg font-black">New domain order</h2><p className="text-[10px] text-[var(--admin-muted)]">Package and commercial state are checked server-side.</p></div></div>{!canManage?<div className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-xs font-bold text-amber-800">DNS management permission is required to place domain orders.</div>:<div className="mt-5 space-y-4"><label className="block text-[10px] font-black uppercase text-[var(--admin-muted)]">Domain name<input name="domain_name" required placeholder="example.co.ls" className="input mt-1.5 w-full"/></label><label className="block text-[10px] font-black uppercase text-[var(--admin-muted)]">Operation<select name="operation" className="input mt-1.5 w-full" defaultValue="register"><option value="register">Register new domain</option><option value="renew">Renew managed domain</option><option value="transfer_in">Transfer domain into Ithute</option></select></label><label className="block text-[10px] font-black uppercase text-[var(--admin-muted)]">Years<input name="years" type="number" min={1} max={10} defaultValue={1} className="input mt-1.5 w-full"/></label><button disabled={busy==="create"} className="btn-primary w-full">{busy==="create"?"Submitting…":"Submit domain order"}</button></div>}</form>
        <div className="surface-card overflow-hidden"><div className="flex items-center justify-between border-b p-4"><div><h2 className="font-black">Order history</h2><p className="text-[10px] text-[var(--admin-muted)]">Registration, renewal and transfer requests for this organization.</p></div><button onClick={()=>void load()} className="icon-button"><RefreshCw size={14} className={loading?"animate-spin":""}/></button></div>{loading?<div className="grid min-h-48 place-items-center text-xs text-[var(--admin-muted)]">Loading orders…</div>:orders.length===0?<div className="grid min-h-48 place-items-center text-center text-xs text-[var(--admin-muted)]">No domain orders yet.</div>:<div className="divide-y">{orders.map(order=><article key={order.id} className="p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-[9px] font-black uppercase ${statusClass(order.status)}`}>{label(order.status)}</span><span className="rounded-full bg-[#edf4f1] px-2.5 py-1 text-[9px] font-black uppercase text-[#285b55]">{label(order.operation)}</span></div><h3 className="mt-2 text-sm font-black">{order.domain_name}</h3><p className="mt-1 text-[10px] text-[var(--admin-muted)]">{order.years} year{order.years===1?"":"s"} · provider: {order.provider}{order.created_at?` · ${new Date(order.created_at).toLocaleString()}`:""}</p>{order.response?.message?<p className="mt-2 max-w-2xl text-[10px] leading-5 text-[var(--admin-muted)]">{order.response.message}</p>:null}</div>{order.status==="pending"&&canManage?<button disabled={busy===order.id} onClick={()=>void cancel(order)} className="btn-secondary text-red-700"><XCircle size={13}/>Cancel</button>:order.status==="processing"?<Clock3 size={16} className="text-blue-600"/>:order.status==="completed"?<RotateCw size={16} className="text-emerald-600"/>:<ArrowRightLeft size={16} className="text-[#718078]"/>}</div></article>)}</div>}</div>
      </section>
    </div>
  </ControlShell>;
}
