from __future__ import annotations

import hashlib
import hmac
import json
import secrets
import time
from typing import Any
from uuid import UUID

import httpx

from database.config.config import settings
from database.models.company import LoanCompany
from database.session import SessionLocal


class LelefaPayGateError(RuntimeError):
    def __init__(
        self,
        detail: str,
        *,
        status_code: int | None = None,
        retryable: bool = False,
    ) -> None:
        super().__init__(detail)
        self.detail = detail
        self.status_code = status_code
        self.retryable = retryable


class LelefaPayGateWebhookError(ValueError):
    pass


def request_signature_headers(
    *,
    api_key: str,
    method: str,
    path: str,
    body: bytes,
    timestamp: int | None = None,
    nonce: str | None = None,
) -> dict[str, str]:
    stamp = str(timestamp if timestamp is not None else int(time.time()))
    nonce_value = nonce or secrets.token_urlsafe(18)
    body_hash = hashlib.sha256(body).hexdigest()
    canonical = (
        f"{stamp}\n{nonce_value}\n{method.upper()}\n{path}\n{body_hash}"
    ).encode("utf-8")
    digest = hmac.new(api_key.encode("utf-8"), canonical, hashlib.sha256).hexdigest()
    return {
        "X-IPB-Timestamp": stamp,
        "X-IPB-Nonce": nonce_value,
        "X-IPB-Signature": f"sha256={digest}",
    }


def verify_webhook_signature(
    raw_body: bytes,
    signature_header: str | None,
    signing_secret: str,
    *,
    tolerance_seconds: int,
    now: int | None = None,
) -> int:
    if not signature_header:
        raise LelefaPayGateWebhookError("Missing X-IPB-Signature")
    try:
        parts = dict(item.strip().split("=", 1) for item in signature_header.split(","))
        timestamp = int(parts["t"])
        supplied = parts["v1"]
    except (KeyError, ValueError) as exc:
        raise LelefaPayGateWebhookError("Malformed X-IPB-Signature") from exc

    current = int(time.time()) if now is None else now
    if abs(current - timestamp) > tolerance_seconds:
        raise LelefaPayGateWebhookError("Webhook timestamp is outside the allowed window")

    signed = str(timestamp).encode("ascii") + b"." + raw_body
    expected = hmac.new(
        signing_secret.encode("utf-8"),
        signed,
        hashlib.sha256,
    ).hexdigest()
    if not hmac.compare_digest(expected, supplied):
        raise LelefaPayGateWebhookError("Invalid webhook signature")
    return timestamp


def _company_business_shortcode(metadata: dict[str, Any]) -> str:
    """Load the shortcode from LoanHub's database, never from caller metadata.

    `company_id` is generated by LoanHub's server-side orchestration. Even if an
    integration context contains a fake shortcode, it is ignored here.
    """
    raw_company_id = metadata.get("company_id")
    if not raw_company_id:
        raise LelefaPayGateError(
            "A LoanHub company is required for M-Pesa money movement",
            status_code=409,
        )
    try:
        company_id = UUID(str(raw_company_id))
    except ValueError as exc:
        raise LelefaPayGateError("Invalid LoanHub company routing ID", status_code=409) from exc
    with SessionLocal() as db:
        company = db.get(LoanCompany, company_id)
        if company is None:
            raise LelefaPayGateError("LoanHub company was not found", status_code=404)
        shortcode = str(company.mpesa_shortcode or "").strip()
    if not shortcode:
        raise LelefaPayGateError(
            "This company has not configured its M-Pesa business shortcode",
            status_code=409,
        )
    if not shortcode.isdigit() or not 4 <= len(shortcode) <= 12:
        raise LelefaPayGateError(
            "This company has an invalid M-Pesa business shortcode",
            status_code=409,
        )
    return shortcode


class LelefaPayGateClient:
    def __init__(self) -> None:
        self.base_url = settings.LELEFAPAYGATE_BASE_URL.rstrip("/")
        self.api_key = (settings.LELEFAPAYGATE_API_KEY or "").strip()
        if not settings.LELEFAPAYGATE_ENABLED:
            raise LelefaPayGateError("LelefaPayGate is disabled")
        if not self.api_key:
            raise LelefaPayGateError("LelefaPayGate API key is not configured")
        if not self.api_key.startswith(("ipb_test_", "ipb_live_")):
            raise LelefaPayGateError("LelefaPayGate API key has an invalid environment prefix")

    def _request(
        self,
        method: str,
        path: str,
        *,
        payload: dict[str, Any] | None = None,
        idempotency_key: str | None = None,
    ) -> dict[str, Any]:
        raw_body = (
            json.dumps(payload, separators=(",", ":"), default=str).encode("utf-8")
            if payload is not None
            else b""
        )
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Accept": "application/json",
        }
        if payload is not None:
            headers["Content-Type"] = "application/json"
        if idempotency_key:
            headers["Idempotency-Key"] = idempotency_key
        url = f"{self.base_url}{path}"
        canonical_path = httpx.URL(url).path
        if settings.LELEFAPAYGATE_REQUEST_SIGNING_ENABLED:
            headers.update(
                request_signature_headers(
                    api_key=self.api_key,
                    method=method,
                    path=canonical_path,
                    body=raw_body,
                )
            )

        try:
            with httpx.Client(
                timeout=settings.LELEFAPAYGATE_TIMEOUT_SECONDS,
            ) as client:
                response = client.request(
                    method,
                    url,
                    content=raw_body if payload is not None else None,
                    headers=headers,
                )
        except (httpx.TimeoutException, httpx.NetworkError) as exc:
            raise LelefaPayGateError(
                "Gateway outcome is unknown; retry or refresh using the same idempotency key",
                retryable=True,
            ) from exc

        if not response.is_success:
            retryable = response.status_code >= 500 or response.status_code in {408, 429}
            try:
                body = response.json()
                detail = body.get("detail") or body.get("message")
            except ValueError:
                detail = None
            raise LelefaPayGateError(
                str(detail or f"LelefaPayGate returned HTTP {response.status_code}")[:500],
                status_code=response.status_code,
                retryable=retryable,
            )
        try:
            result = response.json()
        except ValueError as exc:
            raise LelefaPayGateError(
                "LelefaPayGate returned an invalid JSON response",
                status_code=response.status_code,
                retryable=True,
            ) from exc
        if not isinstance(result, dict):
            raise LelefaPayGateError("LelefaPayGate returned an invalid response shape")
        return result

    def create_payment_intent(
        self,
        *,
        amount: str,
        phone: str,
        reference: str,
        metadata: dict[str, Any],
        idempotency_key: str,
        provider: str | None = None,
        business_shortcode: str | None = None,
    ) -> dict[str, Any]:
        selected_provider = (provider or settings.LELEFAPAYGATE_COLLECTION_PROVIDER).strip().lower()
        if selected_provider == "mpesa":
            business_shortcode = _company_business_shortcode(metadata)
        else:
            business_shortcode = None
        return self._request(
            "POST",
            "/payment-intents",
            payload={
                "amount": amount,
                "currency": "LSL",
                "payment_method": "mobile_money",
                "provider": selected_provider,
                "customer": {"phone": phone},
                "reference": reference[:100],
                "description": "LoanHub secure collection",
                "business_shortcode": business_shortcode,
                "metadata": metadata,
                "confirm": True,
            },
            idempotency_key=idempotency_key,
        )

    def list_payment_methods(self, *, currency: str = "LSL") -> dict[str, Any]:
        normalized = currency.strip().upper()
        if len(normalized) != 3 or not normalized.isalpha():
            raise LelefaPayGateError("Invalid payment currency")
        return self._request("GET", f"/public/payment-methods?currency={normalized}")

    def create_checkout_session(
        self,
        *,
        amount: str,
        reference: str,
        description: str,
        metadata: dict[str, Any],
        idempotency_key: str,
        success_url: str,
        cancel_url: str,
        business_shortcode: str | None = None,
    ) -> dict[str, Any]:
        # LoanHub hosted checkout currently targets M-Pesa for LSL. The public
        # browser never receives or submits the shortcode; it is bound here.
        business_shortcode = _company_business_shortcode(metadata)
        return self._request(
            "POST",
            "/checkout-sessions",
            payload={
                "amount": amount,
                "currency": "LSL",
                "reference": reference[:100],
                "description": description[:255],
                "business_shortcode": business_shortcode,
                "success_url": success_url,
                "cancel_url": cancel_url,
                "expires_in_minutes": 60,
                "metadata": metadata,
            },
            idempotency_key=idempotency_key,
        )

    def create_payout(
        self,
        *,
        amount: str,
        phone: str,
        reference: str,
        metadata: dict[str, Any],
        idempotency_key: str,
        business_shortcode: str | None = None,
    ) -> dict[str, Any]:
        selected_provider = settings.LELEFAPAYGATE_PAYOUT_PROVIDER.strip().lower()
        if selected_provider == "mpesa":
            business_shortcode = _company_business_shortcode(metadata)
        else:
            business_shortcode = None
        return self._request(
            "POST",
            "/payouts",
            payload={
                "amount": amount,
                "currency": "LSL",
                "provider": selected_provider,
                "destination_phone": phone,
                "reference": reference[:100],
                "description": "LoanHub secure payout",
                "business_shortcode": business_shortcode,
                "metadata": metadata,
            },
            idempotency_key=idempotency_key,
        )

    def create_mandate(
        self,
        *,
        provider: str,
        phone: str,
        reference: str,
        first_payment_date,
        expiry_date,
        metadata: dict[str, Any],
        idempotency_key: str,
    ) -> dict[str, Any]:
        return self._request(
            "POST",
            "/mandates",
            payload={
                "provider": provider.strip().lower(),
                "customer_phone": phone,
                "reference": reference[:32],
                "agreed_terms": True,
                "frequency": "monthly",
                "first_payment_date": first_payment_date.isoformat(),
                "payment_day_from": first_payment_date.day,
                "payment_day_to": first_payment_date.day,
                "expiry_date": expiry_date.isoformat() if expiry_date else None,
                "metadata": metadata,
            },
            idempotency_key=idempotency_key,
        )

    def charge_mandate(
        self,
        mandate_id: str,
        *,
        amount: str,
        reference: str,
        idempotency_key: str,
    ) -> dict[str, Any]:
        normalized = mandate_id.strip()
        if not normalized.startswith("mand_") or not normalized.replace("_", "").isalnum():
            raise LelefaPayGateError("Invalid gateway mandate ID")
        return self._request(
            "POST",
            f"/mandates/{normalized}/charges",
            payload={
                "amount": amount,
                "currency": "LSL",
                "reference": reference[:100],
                "check_balance_first": True,
            },
            idempotency_key=idempotency_key,
        )

    def cancel_mandate(self, mandate_id: str) -> dict[str, Any]:
        normalized = mandate_id.strip()
        if not normalized.startswith("mand_") or not normalized.replace("_", "").isalnum():
            raise LelefaPayGateError("Invalid gateway mandate ID")
        return self._request("POST", f"/mandates/{normalized}/cancel")

    def get_resource(self, resource_type: str, public_id: str) -> dict[str, Any]:
        collections = {
            "payment_intent": "payment-intents",
            "payout": "payouts",
            "checkout_session": "checkout-sessions",
        }
        collection = collections.get(resource_type)
        if not collection:
            raise LelefaPayGateError("Unsupported gateway resource type")
        return self._request("GET", f"/{collection}/{public_id}")
