"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { useBuildTrackUi } from "../../components/ui";
import styles from "../../workforce/workforce.module.css";

type Row=Record<string,unknown>;
type Queue={daily_report_approvals:Row[];open_incidents:Row[];open_quality_actions:Row[];activations:Row[]};
const API="/api/v1";
function text(r:Row|null|undefined,k:string){return String(r?.[k]??"")}
function num(r:Row|null|undefined,k:string){return Number(r?.[k]??0)}
function nested(r:Row,k:string):Row{return r[k]&&typeof r[k]==="object"?r[k] as Row:{}}
function badge(v:string){if(["approved","active","closed","accepted","pass"].includes(v))return styles.green;if(["submitted","pending","investigating","conditional","action_required"].includes(v))return styles.amber;if(["rejected","fail","critical","fatal","serious","open"].includes(v))return styles.red;return styles.blue}
async function api<T>(path:string,init?:RequestInit):Promise<T>{const response=await fetch(`${API}${path}`,{...init,credentials:"include",headers:{"Content-Type":"application/json",...(init?.headers??{})},cache:"no-store"});if(response.status===401){window.location.href=`/login?returnTo=${encodeURIComponent("/site-operations/control")}`;throw new Error("Session expired")};const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(typeof payload?.detail==="string"?payload.detail:JSON.stringify(payload?.detail??payload));return payload as T}
function Btn({children,variant="",...props}:React.ButtonHTMLAttributes<HTMLButtonElement>&{variant?:"secondary"|"danger"|""}){return <button {...props} className={`${styles.button} ${variant?styles[variant]:""}`}>{children}</button>}

export default function SiteOperationsControl(){
 const {promptText}=useBuildTrackUi();
 const [queue,setQueue]=useState<Queue>({daily_report_approvals:[],open_incidents:[],open_quality_actions:[],activations:[]}),[policy,setPolicy]=useState({daily_report_lag_days:"1",require_daily_report_approval:true,serious_incident_severities:["serious","critical","fatal"],failed_quality_requires_action:true,can_edit:false}),[error,setError]=useState(""),[notice,setNotice]=useState(""),[loading,setLoading]=useState(true);
 const refresh=useCallback(async()=>{setLoading(true);setError("");try{const [q,p]=await Promise.all([api<Queue>("/site-ops/control/queue"),api<Record<string,unknown>>("/site-ops/policy/current")]);setQueue(q);setPolicy({daily_report_lag_days:String(p.daily_report_lag_days??1),require_daily_report_approval:Boolean(p.require_daily_report_approval??true),serious_incident_severities:Array.isArray(p.serious_incident_severities)?p.serious_incident_severities.map(String):["serious","critical","fatal"],failed_quality_requires_action:Boolean(p.failed_quality_requires_action??true),can_edit:Boolean(p.can_edit)});}catch(e){setError(e instanceof Error?e.message:"Could not load Site Operations Control")}finally{setLoading(false)}},[]);
 useEffect(()=>{void refresh()},[refresh]);
 function success(message:string){setNotice(message);setError("");setTimeout(()=>setNotice(""),3000);void refresh()}
 async function decide(row:Row,decision:"approve"|"reject"){const request=nested(row,"approval");const id=num(request,"id");if(!id){setError("Approval request is missing.");return}const comment=await promptText({title:decision==="approve"?"Approve daily report":"Reject daily report",description:"Record the approval context in the controlled daily-report trail.",label:"Decision comment",multiline:true,confirmLabel:decision==="approve"?"Approve":"Reject"});if(comment===null)return;try{await api(`/site-ops/approvals/${id}/decision`,{method:"POST",body:JSON.stringify({decision,comment:comment||null})});success(`Daily report ${decision} decision recorded.`)}catch(e){setError(e instanceof Error?e.message:"Could not record approval decision")}}
 async function incidentStatus(row:Row,status:string){const corrective=await promptText({title:"Update incident",description:`Set this incident to ${status} and record the corrective action or closure note.`,label:"Corrective action / closure note",defaultValue:text(row,"corrective_action"),multiline:true,required:status==="closed",confirmLabel:"Save incident"});if(corrective===null)return;try{await api(`/site-ops/incidents/${num(row,"id")}`,{method:"PUT",body:JSON.stringify({root_cause:row.root_cause||null,corrective_action:corrective||null,owner_employee_id:row.owner_employee_id?Number(row.owner_employee_id):null,due_date:row.due_date||null,status,document_id:row.document_id?Number(row.document_id):null})});success(`Incident ${status}.`)}catch(e){setError(e instanceof Error?e.message:"Could not update incident")}}
 async function qualityStatus(row:Row,status:string){const corrective=await promptText({title:"Update quality action",description:`Set this quality action to ${status} and record the corrective-action or close-out note.`,label:"Corrective action / quality close-out note",defaultValue:text(row,"corrective_action"),multiline:true,required:status==="closed",confirmLabel:"Save quality action"});if(corrective===null)return;try{await api(`/site-ops/quality/${num(row,"id")}`,{method:"PUT",body:JSON.stringify({corrective_action:corrective||null,owner_employee_id:row.owner_employee_id?Number(row.owner_employee_id):null,due_date:row.due_date||null,status,document_id:row.document_id?Number(row.document_id):null,notes:row.notes||null})});success(`Quality action ${status}.`)}catch(e){setError(e instanceof Error?e.message:"Could not update quality action")}}
 async function activationStatus(row:Row,status:string){try{await api(`/site-ops/activations/${num(row,"id")}/status`,{method:"POST",body:JSON.stringify({status,notes:row.notes||null})});success(`Site activation ${status}.`)}catch(e){setError(e instanceof Error?e.message:"Could not update site activation")}}
 async function savePolicy(e:FormEvent){e.preventDefault();try{await api("/site-ops/policy/current",{method:"PUT",body:JSON.stringify({daily_report_lag_days:Number(policy.daily_report_lag_days),require_daily_report_approval:true,serious_incident_severities:policy.serious_incident_severities,failed_quality_requires_action:policy.failed_quality_requires_action})});success("Site Operations policy saved.")}catch(e){setError(e instanceof Error?e.message:"Could not save policy")}}
 if(loading)return <main className={styles.page}><div className={styles.loading}><strong>Loading Site Operations Control…</strong></div></main>;
 return <main className={styles.page}><header className={styles.header}><div className={styles.brand}><div className={styles.brandMark}>BT</div><div><small>BUILDTRACK · PHASE 7 GOVERNANCE</small><h1>Site Operations Control</h1><p>Daily approvals · HSE incidents · quality/NCR · site lifecycle</p></div></div><div className={styles.headerActions}><Link className={styles.link} href="/site-operations">Site Operations</Link><Link className={styles.link} href="/projects/control">Project Control</Link></div></header><div className={styles.shell}>{error&&<div className={styles.error}>{error}</div>}{notice&&<div className={styles.notice}>{notice}</div>}
 <section className={styles.metrics}><div className={styles.metric}><small>Report approvals</small><strong>{queue.daily_report_approvals.length}</strong><span>maker/checker queue</span></div><div className={styles.metric}><small>Open incidents</small><strong>{queue.open_incidents.length}</strong><span>HSE / security / equipment</span></div><div className={styles.metric}><small>Quality actions</small><strong>{queue.open_quality_actions.length}</strong><span>conditional / fail / NCR</span></div><div className={styles.metric}><small>Active sites</small><strong>{queue.activations.filter(r=>text(r,"status")==="active").length}</strong><span>operational activations</span></div></section>
 <section className={styles.panel}><div className={styles.panelHead}><div><h3>Daily report maker/checker queue</h3><p>Approvals remain governed by the configured Branch → HQ workflow and no-self-approval policy.</p></div></div>{queue.daily_report_approvals.length?<div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Date</th><th>Project</th><th>Site</th><th>Submitted by</th><th>Approval</th><th>Actions</th></tr></thead><tbody>{queue.daily_report_approvals.map(r=>{const a=nested(r,"approval");return <tr key={num(r,"id")}><td>{text(r,"report_date")} · {text(r,"shift")}</td><td>{text(r,"project_id")}</td><td>{text(r,"site_id")}</td><td>{text(r,"submitted_by")}</td><td><span className={`${styles.badge} ${badge(text(a,"status"))}`}>{text(a,"status")||"missing"}</span><br/><small>step {text(a,"current_step_order")}</small></td><td><div className={styles.actions}><button className={`${styles.mini} ${styles.good}`} onClick={()=>void decide(r,"approve")}>Approve</button><button className={`${styles.mini} ${styles.bad}`} onClick={()=>void decide(r,"reject")}>Reject</button></div></td></tr>})}</tbody></table></div>:<div className={styles.empty}>No daily reports are waiting for approval.</div>}</section>
 <section className={styles.grid2}><div className={styles.panel}><div className={styles.panelHead}><div><h3>Open incidents</h3><p>Investigation and corrective-action control continues after daily-report approval.</p></div></div>{queue.open_incidents.length?<div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Incident</th><th>Severity</th><th>Status</th><th>Action</th></tr></thead><tbody>{queue.open_incidents.map(r=><tr key={num(r,"id")}><td><strong>{text(r,"incident_number")}</strong><br/><small>{text(r,"description")}</small></td><td><span className={`${styles.badge} ${badge(text(r,"severity"))}`}>{text(r,"severity")}</span></td><td>{text(r,"status")}</td><td><div className={styles.actions}><button className={styles.mini} onClick={()=>void incidentStatus(r,"investigating")}>Investigate</button><button className={styles.mini} onClick={()=>void incidentStatus(r,"action_required")}>Action required</button><button className={`${styles.mini} ${styles.good}`} onClick={()=>void incidentStatus(r,"closed")}>Close</button></div></td></tr>)}</tbody></table></div>:<div className={styles.empty}>No open incidents.</div>}</div>
 <div className={styles.panel}><div className={styles.panelHead}><div><h3>Quality / NCR actions</h3><p>Close only after corrective action has been recorded.</p></div></div>{queue.open_quality_actions.length?<div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Inspection</th><th>Result</th><th>Status</th><th>Action</th></tr></thead><tbody>{queue.open_quality_actions.map(r=><tr key={num(r,"id")}><td><strong>{text(r,"inspection_number")}</strong><br/><small>{text(r,"work_item")}</small></td><td><span className={`${styles.badge} ${badge(text(r,"result"))}`}>{text(r,"result")}</span></td><td>{text(r,"status")}</td><td><div className={styles.actions}><button className={styles.mini} onClick={()=>void qualityStatus(r,"action_required")}>Action required</button><button className={`${styles.mini} ${styles.good}`} onClick={()=>void qualityStatus(r,"accepted")}>Accept</button><button className={`${styles.mini} ${styles.good}`} onClick={()=>void qualityStatus(r,"closed")}>Close</button></div></td></tr>)}</tbody></table></div>:<div className={styles.empty}>No open quality actions.</div>}</div></section>
 <section className={styles.grid2}><div className={styles.panel}><div className={styles.panelHead}><div><h3>Site activation lifecycle</h3><p>Pause or close a project/site operating activation without deleting evidence.</p></div></div>{queue.activations.length?<div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Project / Site</th><th>Status</th><th>Actions</th></tr></thead><tbody>{queue.activations.map(r=><tr key={num(r,"id")}><td>Project {text(r,"project_id")} · Site {text(r,"site_id")}</td><td><span className={`${styles.badge} ${badge(text(r,"status"))}`}>{text(r,"status")}</span></td><td><div className={styles.actions}><button className={styles.mini} onClick={()=>void activationStatus(r,"active")}>Active</button><button className={styles.mini} onClick={()=>void activationStatus(r,"paused")}>Pause</button><button className={`${styles.mini} ${styles.bad}`} onClick={()=>void activationStatus(r,"closed")}>Close</button></div></td></tr>)}</tbody></table></div>:<div className={styles.empty}>No Site Operations activations.</div>}</div>
 <div className={styles.panel}><div className={styles.panelHead}><div><h3>Site Operations policy</h3><p>Operational controls only; no statutory HSE/quality rules are invented by BuildTrack.</p></div></div><form className={styles.form} onSubmit={savePolicy}><div className={styles.field}><label>Daily report lag days</label><input type="number" min="0" max="14" value={policy.daily_report_lag_days} onChange={e=>setPolicy({...policy,daily_report_lag_days:e.target.value})}/></div><div className={styles.field}><label>Failed quality requires action</label><select value={policy.failed_quality_requires_action?"yes":"no"} onChange={e=>setPolicy({...policy,failed_quality_requires_action:e.target.value==="yes"})}><option value="yes">Yes</option><option value="no">No</option></select></div><div className={styles.formActions}><Btn type="submit" disabled={!policy.can_edit}>Save policy</Btn></div></form><div className={styles.sectionNote}>Serious incident severities remain: {policy.serious_incident_severities.join(", ")}. Daily report approval remains mandatory through the shared approval engine.</div></div></section>
 </div></main>
}
