"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { Activity, Cloud, Gauge, Globe2, Network, Plus, RefreshCw, Server, ShieldCheck, Trash2 } from "lucide-react";
import { useRouter } from "next/navigation";
import { ControlShell } from "@/components/control-shell";
import { EmptyState, MetricCard, PageHeader, StatusBadge, Toast } from "@/components/ui-kit";

const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:8006/api/v1";
type Me={email:string;is_platform_owner:boolean};
type Membership={tenant_id:string;tenant_name:string;role:string;status:string};
type Domain={id:string;ascii_name:string;unicode_name:string;status:string;ownership_verified_at?:string|null};
type Inspection={id:string;origin_id?:string|null;checked_at:string;healthy:boolean;resolved_ip?:string|null;status_code?:number|null;latency_ms?:number|null;tls_version?:string|null;cipher?:string|null;certificate_issuer?:string|null;certificate_not_after?:string|null;certificate_days_remaining?:number|null;error?:string|null};
type Origin={id:string;name:string;url:string;enabled:boolean;weight:number;failover_priority:number;health_path:string;expected_status:number;timeout_seconds:number};
type Rule={id:string;name:string;rule_type:string;expression:string;action:string;config:Record<string,unknown>;priority:number;enabled:boolean};
type EdgeApp={id:string;domain_id:string;hostname:string;mode:string;enabled:boolean;cache_enabled:boolean;waf_enabled:boolean;bot_protection_enabled:boolean;api_shield_enabled:boolean;access_enabled:boolean;rate_limit_per_minute?:number|null;tls_mode:string;minimum_tls_version:string;health_path:string;expected_status:number;origins:Origin[];rules:Rule[];latest_inspection?:Inspection|null};
type Capability={state:"active"|"control_plane"|"planned";detail:string};
type Analytics={domain:string;live:{zone_kind?:string|null;serial?:number|null;dnssec_enabled:boolean;rrset_count:number;record_count:number;type_counts:Record<string,number>};history:Array<{captured_at:string;record_count:number;rrset_count:number;dnssec_enabled:boolean;type_counts:Record<string,number>}>};

async function api(path:string,init?:RequestInit){const options:RequestInit={credentials:"include",...init,headers:{"Content-Type":"application/json",...(init?.headers||{})}};let r=await fetch(`${API}${path}`,options);if(r.status===401){const rr=await fetch(`${API}/auth/refresh`,{method:"POST",credentials:"include"});if(rr.ok)r=await fetch(`${API}${path}`,options)}return r}
async function detail(r:Response,fallback:string){const b=await r.json().catch(()=>({}));return String(b.detail||fallback)}
const tone=(state:string)=>state==="active"?"good":state==="control_plane"?"warn":"neutral" as const;

export default function EdgePage(){
  const router=useRouter();const[me,setMe]=useState<Me|null>(null);const[contexts,setContexts]=useState<Membership[]>([]);const[tenantId,setTenantId]=useState("");const[domains,setDomains]=useState<Domain[]>([]);const[apps,setApps]=useState<EdgeApp[]>([]);const[capabilities,setCapabilities]=useState<Record<string,Capability>>({});const[selectedId,setSelectedId]=useState("");const[analyticsDomainId,setAnalyticsDomainId]=useState("");const[analytics,setAnalytics]=useState<Analytics|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[toast,setToast]=useState("");
  const[createDomainId,setCreateDomainId]=useState("");const[createHostname,setCreateHostname]=useState("");const[createMode,setCreateMode]=useState("dns_only");
  const[originName,setOriginName]=useState("");const[originUrl,setOriginUrl]=useState("");const[originPath,setOriginPath]=useState("/");
  const[ruleName,setRuleName]=useState("");const[ruleType,setRuleType]=useState("firewall");const[ruleExpression,setRuleExpression]=useState("true");const[ruleAction,setRuleAction]=useState("block");
  const selected=useMemo(()=>apps.find(x=>x.id===selectedId)||apps[0]||null,[apps,selectedId]);

  useEffect(()=>{void(async()=>{try{const m=await api("/auth/me");if(m.status===401){router.replace("/login");return}if(!m.ok)throw new Error("Unable to load account");const current:Me=await m.json();setMe(current);let rows:Membership[]=[];if(current.is_platform_owner){const r=await api("/tenants");const data=r.ok?await r.json():[];rows=data.map((x:{id:string;name:string;status:string})=>({tenant_id:x.id,tenant_name:x.name,role:"platform_owner",status:x.status}))}else{const r=await api("/me/memberships");rows=r.ok?await r.json():[]}rows=rows.filter(x=>x.status==="active");setContexts(rows);const remembered=localStorage.getItem("mailbox_dns_tenant");setTenantId(rows.find(x=>x.tenant_id===remembered)?.tenant_id||rows[0]?.tenant_id||"")}catch(e){setError(e instanceof Error?e.message:"Unable to initialize !thute Edge")}})()},[router]);
  useEffect(()=>{if(!tenantId){setDomains([]);setApps([]);return}localStorage.setItem("mailbox_dns_tenant",tenantId);void loadAll()},[tenantId]);

  async function loadAll(){if(!tenantId)return;setBusy(true);setError("");try{const[d,a,c]=await Promise.all([api(`/tenants/${tenantId}/domains`),api(`/tenants/${tenantId}/edge/applications`),api(`/tenants/${tenantId}/edge/capabilities`)]);if(!d.ok)throw new Error(await detail(d,"Unable to load domains"));if(!a.ok)throw new Error(await detail(a,"Unable to load edge applications"));if(!c.ok)throw new Error(await detail(c,"Unable to load edge capabilities"));const domainData=await d.json();const appData=await a.json();const capData=await c.json();const verified=(domainData.items||[]).filter((x:Domain)=>x.status==="verified"&&x.ownership_verified_at);setDomains(verified);setApps(appData.items||[]);setCapabilities(capData.capabilities||{});setSelectedId((cur:string)=>(appData.items||[]).some((x:EdgeApp)=>x.id===cur)?cur:(appData.items||[])[0]?.id||"");setCreateDomainId((cur:string)=>verified.some((x:Domain)=>x.id===cur)?cur:verified[0]?.id||"");setAnalyticsDomainId((cur:string)=>verified.some((x:Domain)=>x.id===cur)?cur:verified[0]?.id||"")}catch(e){setError(e instanceof Error?e.message:"Unable to load !thute Edge")}finally{setBusy(false)}}
  async function createApplication(e:FormEvent){e.preventDefault();if(!createDomainId)return;const domain=domains.find(x=>x.id===createDomainId);setBusy(true);setError("");const r=await api(`/tenants/${tenantId}/edge/applications`,{method:"POST",body:JSON.stringify({domain_id:createDomainId,hostname:createHostname.trim()||domain?.ascii_name||"",mode:createMode})});if(!r.ok){setError(await detail(r,"Unable to create edge application"));setBusy(false);return}const item:EdgeApp=await r.json();setToast(`Edge application ${item.hostname} created.`);setCreateHostname("");await loadAll();setSelectedId(item.id);setBusy(false)}
  async function patchApplication(changes:Record<string,unknown>){if(!selected)return;setBusy(true);setError("");const r=await api(`/tenants/${tenantId}/edge/applications/${selected.id}`,{method:"PATCH",body:JSON.stringify(changes)});if(!r.ok){setError(await detail(r,"Unable to update edge application"));setBusy(false);return}const updated:EdgeApp=await r.json();setApps(list=>list.map(x=>x.id===updated.id?updated:x));setToast("Edge policy saved.");setBusy(false)}
  async function addOrigin(e:FormEvent){e.preventDefault();if(!selected)return;setBusy(true);const r=await api(`/tenants/${tenantId}/edge/applications/${selected.id}/origins`,{method:"POST",body:JSON.stringify({name:originName,url:originUrl,health_path:originPath,expected_status:200,weight:100,failover_priority:(selected.origins.length+1),timeout_seconds:5})});if(!r.ok){setError(await detail(r,"Unable to add origin"));setBusy(false);return}const updated:EdgeApp=await r.json();setApps(list=>list.map(x=>x.id===updated.id?updated:x));setOriginName("");setOriginUrl("");setOriginPath("/");setToast("Origin added to the pool.");setBusy(false)}
  async function deleteOrigin(id:string){if(!selected)return;setBusy(true);const r=await api(`/tenants/${tenantId}/edge/applications/${selected.id}/origins/${id}`,{method:"DELETE"});if(!r.ok){setError(await detail(r,"Unable to delete origin"));setBusy(false);return}await loadAll();setToast("Origin removed.");setBusy(false)}
  async function addRule(e:FormEvent){e.preventDefault();if(!selected)return;setBusy(true);const r=await api(`/tenants/${tenantId}/edge/applications/${selected.id}/rules`,{method:"POST",body:JSON.stringify({name:ruleName,rule_type:ruleType,expression:ruleExpression,action:ruleAction,priority:100,config:{}})});if(!r.ok){setError(await detail(r,"Unable to add edge rule"));setBusy(false);return}const updated:EdgeApp=await r.json();setApps(list=>list.map(x=>x.id===updated.id?updated:x));setRuleName("");setRuleExpression("true");setToast("Edge rule saved to the control plane.");setBusy(false)}
  async function deleteRule(id:string){if(!selected)return;setBusy(true);const r=await api(`/tenants/${tenantId}/edge/applications/${selected.id}/rules/${id}`,{method:"DELETE"});if(!r.ok){setError(await detail(r,"Unable to delete rule"));setBusy(false);return}await loadAll();setToast("Rule removed.");setBusy(false)}
  async function inspect(){if(!selected)return;setBusy(true);setError("");const r=await api(`/tenants/${tenantId}/edge/applications/${selected.id}/inspect`,{method:"POST"});if(!r.ok){setError(await detail(r,"Inspection failed"));setBusy(false);return}await loadAll();setToast("Origin health and TLS inspection completed.");setBusy(false)}
  async function loadAnalytics(save=false){if(!analyticsDomainId)return;setBusy(true);setError("");if(save){const snap=await api(`/tenants/${tenantId}/edge/domains/${analyticsDomainId}/dns-analytics/snapshot`,{method:"POST"});if(!snap.ok){setError(await detail(snap,"Unable to capture DNS analytics snapshot"));setBusy(false);return}}const r=await api(`/tenants/${tenantId}/edge/domains/${analyticsDomainId}/dns-analytics`);if(!r.ok){setError(await detail(r,"Unable to load DNS analytics"));setBusy(false);return}setAnalytics(await r.json());if(save)setToast("DNS zone snapshot captured.");setBusy(false)}

  const inspection=selected?.latest_inspection;
  return <ControlShell title="!thute Edge & security" subtitle="DNS intelligence, origin health, TLS and edge policy control" userEmail={me?.email}><div className="space-y-4">
    <PageHeader eyebrow="!thute edge platform · phase 1" title="Edge & security control centre" description="Manage the policy layer that will protect !thute-hosted and customer applications. Health/TLS inspection and DNS-zone analytics are live now; proxy, WAF, cache and traffic-steering policies are explicitly marked as control-plane until their distributed runtime is enabled." actions={<select className="input min-w-[220px]" value={tenantId} onChange={e=>setTenantId(e.target.value)}><option value="">Select organization</option>{contexts.map(x=><option key={x.tenant_id} value={x.tenant_id}>{x.tenant_name}</option>)}</select>}/>
    {error?<div className="surface-card border-red-200 bg-red-50 p-3 text-xs font-bold text-red-700">{error}</div>:null}
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Edge applications" value={apps.length} detail="Verified hostnames registered in the control plane"/><MetricCard label="Protected policy" value={apps.filter(x=>x.mode==="protected").length} detail="Hostnames prepared for !thute protected routing" status={apps.some(x=>x.mode==="protected")?"good":"neutral"}/><MetricCard label="Healthy last probe" value={apps.filter(x=>x.latest_inspection?.healthy).length} detail="Latest persisted origin/application inspection" status="good"/><MetricCard label="DNS records" value={analytics?.live.record_count??"—"} detail="Live records in the selected PowerDNS zone"/></section>

    <section className="surface-card p-4"><div className="flex items-center justify-between gap-3"><div><p className="text-sm font-black">Capability truth table</p><p className="mt-1 text-[10px] text-[var(--admin-muted)]">!thute distinguishes working telemetry from policy that still needs distributed edge enforcement.</p></div><Cloud size={20}/></div><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{Object.entries(capabilities).map(([key,item])=><div key={key} className="rounded-xl border border-[var(--admin-line)] bg-[var(--admin-soft)] p-3"><div className="flex items-center justify-between gap-2"><p className="text-[11px] font-black capitalize">{key.replaceAll("_"," ")}</p><StatusBadge state={tone(item.state)}>{item.state.replaceAll("_"," ")}</StatusBadge></div><p className="mt-2 text-[10px] leading-4 text-[var(--admin-muted)]">{item.detail}</p></div>)}</div></section>

    <section className="grid gap-4 xl:grid-cols-[.72fr_1.28fr]"><div className="space-y-4"><form onSubmit={createApplication} className="surface-card p-4"><div className="flex items-center gap-2"><Plus size={16}/><div><p className="text-sm font-black">Add edge application</p><p className="text-[10px] text-[var(--admin-muted)]">Register a verified hostname with !thute's edge control plane.</p></div></div><label className="label mt-4">Managed domain</label><select className="input" value={createDomainId} onChange={e=>setCreateDomainId(e.target.value)} required><option value="">Select verified domain</option>{domains.map(d=><option key={d.id} value={d.id}>{d.unicode_name}</option>)}</select><label className="label mt-3">Hostname</label><input className="input" value={createHostname} onChange={e=>setCreateHostname(e.target.value)} placeholder={domains.find(x=>x.id===createDomainId)?.ascii_name||"app.example.co.ls"}/><p className="field-help">Leave blank to use the selected domain apex, or enter a hostname inside that domain.</p><label className="label mt-3">Initial mode</label><select className="input" value={createMode} onChange={e=>setCreateMode(e.target.value)}><option value="dns_only">DNS only</option><option value="protected">!thute protected policy</option></select><button className="btn-primary mt-4" disabled={busy||!createDomainId} type="submit"><Plus size={14}/>Create application</button></form>
      <section className="surface-card p-4"><p className="text-sm font-black">Applications</p><div className="mt-3 space-y-2">{apps.map(app=><button key={app.id} onClick={()=>setSelectedId(app.id)} className={`w-full rounded-xl border p-3 text-left ${selected?.id===app.id?"border-[#2b605a] bg-[#edf5f1]":"border-[var(--admin-line)] bg-white"}`}><div className="flex items-center justify-between gap-2"><span className="truncate text-[11px] font-black">{app.hostname}</span><StatusBadge state={app.mode==="protected"?"good":"neutral"}>{app.mode==="protected"?"protected policy":"DNS only"}</StatusBadge></div><p className="mt-1 text-[9px] text-[var(--admin-muted)]">{app.origins.length} origins · {app.rules.length} rules</p></button>)}{!apps.length?<EmptyState icon={<Network size={20}/>} title="No edge applications yet" description="Create the first application from a verified domain. This does not change public traffic until protected edge runtime is explicitly activated."/>:null}</div></section></div>

      <div className="space-y-4">{selected?<><section className="surface-card p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="eyebrow-label">Selected application</p><h2 className="mt-1 text-lg font-black">{selected.hostname}</h2><p className="mt-1 text-[10px] text-[var(--admin-muted)]">Policy is safely separate from runtime activation.</p></div><button className="btn-primary" disabled={busy} onClick={()=>void inspect()}><Activity size={14}/>Run health & TLS check</button></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><label className="rounded-xl border p-3 text-[11px] font-bold"><span className="block text-[9px] uppercase text-[var(--admin-muted)]">Traffic mode</span><select className="input mt-2" value={selected.mode} onChange={e=>void patchApplication({mode:e.target.value})}><option value="dns_only">DNS only</option><option value="protected">!thute protected policy</option></select></label>{[["WAF","waf_enabled",selected.waf_enabled],["Cache","cache_enabled",selected.cache_enabled],["Bot protection","bot_protection_enabled",selected.bot_protection_enabled],["API shield","api_shield_enabled",selected.api_shield_enabled],["Zero-trust policy","access_enabled",selected.access_enabled]].map(([label,key,value])=><label key={String(key)} className="flex items-center justify-between rounded-xl border p-3 text-[11px] font-bold"><span>{String(label)}</span><input type="checkbox" checked={Boolean(value)} onChange={e=>void patchApplication({[String(key)]:e.target.checked})}/></label>)}</div><div className="mt-3 grid gap-3 sm:grid-cols-3"><label><span className="label">Rate limit / minute</span><input className="input" type="number" min={1} max={1000000} value={selected.rate_limit_per_minute??""} onChange={e=>void patchApplication({rate_limit_per_minute:e.target.value?Number(e.target.value):null})}/></label><label><span className="label">Minimum TLS</span><select className="input" value={selected.minimum_tls_version} onChange={e=>void patchApplication({minimum_tls_version:e.target.value})}><option>TLSv1.2</option><option>TLSv1.3</option></select></label><label><span className="label">Expected health status</span><input className="input" type="number" min={100} max={599} value={selected.expected_status} onChange={e=>void patchApplication({expected_status:Number(e.target.value)})}/></label></div></section>

      <section className="surface-card p-4"><div className="flex items-center justify-between"><div><p className="text-sm font-black">Live health & certificate</p><p className="text-[10px] text-[var(--admin-muted)]">Stored from the last SSRF-safe public HTTP(S) inspection.</p></div><Gauge size={18}/></div>{inspection?<div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><MetricCard label="Health" value={inspection.healthy?"Healthy":"Unhealthy"} status={inspection.healthy?"good":"bad"} detail={inspection.error||`HTTP ${inspection.status_code??"—"}`}/><MetricCard label="Latency" value={inspection.latency_ms==null?"—":`${inspection.latency_ms} ms`} detail={inspection.resolved_ip||"No resolved IP"}/><MetricCard label="TLS" value={inspection.tls_version||"—"} detail={inspection.cipher||"HTTP or no TLS result"}/><MetricCard label="Certificate" value={inspection.certificate_days_remaining==null?"—":`${inspection.certificate_days_remaining} days`} status={inspection.certificate_days_remaining!=null&&inspection.certificate_days_remaining<30?"warn":"good"} detail={inspection.certificate_issuer||"Issuer unavailable"}/></div>:<EmptyState icon={<Activity size={20}/>} title="No inspection yet" description="Run the first health & TLS check. !thute connects only to globally routable public targets and refuses private/internal addresses."/>}</section>

      <section className="grid gap-4 lg:grid-cols-2"><div className="surface-card p-4"><p className="text-sm font-black">Origin pool</p><p className="mt-1 text-[10px] text-[var(--admin-muted)]">Define weighted origins and failover order for the future traffic-steering runtime.</p><div className="mt-3 space-y-2">{selected.origins.map(o=><div key={o.id} className="flex items-start gap-2 rounded-xl border p-3"><Server size={14}/><div className="min-w-0 flex-1"><p className="truncate text-[11px] font-black">{o.name}</p><p className="truncate text-[9px] text-[var(--admin-muted)]">{o.url} · priority {o.failover_priority}</p></div><button className="icon-button text-red-700" onClick={()=>void deleteOrigin(o.id)}><Trash2 size={13}/></button></div>)}</div><form onSubmit={addOrigin} className="mt-4 border-t pt-4"><label className="label">Origin name</label><input className="input" required value={originName} onChange={e=>setOriginName(e.target.value)} placeholder="primary"/><label className="label mt-2">Public origin URL</label><input className="input" required type="url" value={originUrl} onChange={e=>setOriginUrl(e.target.value)} placeholder="https://origin.example.co.ls"/><label className="label mt-2">Health path</label><input className="input" value={originPath} onChange={e=>setOriginPath(e.target.value)} placeholder="/health"/><button className="btn-secondary mt-3" disabled={busy}><Plus size={13}/>Add origin</button></form></div>
      <div className="surface-card p-4"><p className="text-sm font-black">Rules engine</p><p className="mt-1 text-[10px] text-[var(--admin-muted)]">Store firewall, rate, cache, redirect, header, access and API policies for edge enforcement.</p><div className="mt-3 space-y-2">{selected.rules.map(r=><div key={r.id} className="flex items-start gap-2 rounded-xl border p-3"><ShieldCheck size={14}/><div className="min-w-0 flex-1"><p className="truncate text-[11px] font-black">{r.name}</p><p className="truncate text-[9px] text-[var(--admin-muted)]">{r.rule_type} → {r.action} · {r.expression}</p></div><button className="icon-button text-red-700" onClick={()=>void deleteRule(r.id)}><Trash2 size={13}/></button></div>)}</div><form onSubmit={addRule} className="mt-4 grid gap-2 border-t pt-4"><input className="input" required value={ruleName} onChange={e=>setRuleName(e.target.value)} placeholder="Protect login"/><div className="grid grid-cols-2 gap-2"><select className="input" value={ruleType} onChange={e=>setRuleType(e.target.value)}><option value="firewall">Firewall</option><option value="rate_limit">Rate limit</option><option value="cache">Cache</option><option value="api_shield">API shield</option><option value="bot">Bot</option><option value="access">Access</option><option value="redirect">Redirect</option><option value="header">Header</option></select><select className="input" value={ruleAction} onChange={e=>setRuleAction(e.target.value)}><option value="block">Block</option><option value="allow">Allow</option><option value="log">Log</option><option value="challenge">Challenge</option><option value="throttle">Throttle</option><option value="cache">Cache</option><option value="bypass_cache">Bypass cache</option><option value="require_access">Require access</option><option value="redirect">Redirect</option><option value="set_header">Set header</option></select></div><textarea className="input min-h-16 font-mono text-[10px]" value={ruleExpression} onChange={e=>setRuleExpression(e.target.value)} placeholder="path starts_with /login"/><button className="btn-secondary" disabled={busy}><Plus size={13}/>Save rule</button></form></div></section></>:<EmptyState icon={<ShieldCheck size={22}/>} title="Select or create an application" description="Edge health, TLS, origins and policies will appear here."/>}</div></section>

    <section className="surface-card p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2"><Globe2 size={17}/><p className="text-sm font-black">DNS zone intelligence</p></div><p className="mt-1 text-[10px] text-[var(--admin-muted)]">Live PowerDNS inventory plus persisted snapshots. Query-volume analytics will be added when authoritative query telemetry is enabled.</p></div><div className="flex flex-wrap gap-2"><select className="input min-w-[220px]" value={analyticsDomainId} onChange={e=>{setAnalyticsDomainId(e.target.value);setAnalytics(null)}}><option value="">Select verified domain</option>{domains.map(d=><option key={d.id} value={d.id}>{d.unicode_name}</option>)}</select><button className="btn-secondary" disabled={busy||!analyticsDomainId} onClick={()=>void loadAnalytics(false)}><RefreshCw size={13}/>Read live</button><button className="btn-primary" disabled={busy||!analyticsDomainId} onClick={()=>void loadAnalytics(true)}>Capture snapshot</button></div></div>{analytics?<><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><MetricCard label="Zone kind" value={analytics.live.zone_kind||"—"}/><MetricCard label="RRsets" value={analytics.live.rrset_count}/><MetricCard label="Records" value={analytics.live.record_count}/><MetricCard label="DNSSEC" value={analytics.live.dnssec_enabled?"Enabled":"Off"} status={analytics.live.dnssec_enabled?"good":"warn"}/></div><div className="mt-4 rounded-xl border p-3"><p className="eyebrow-label">Record distribution</p><div className="mt-2 flex flex-wrap gap-2">{Object.entries(analytics.live.type_counts).map(([type,count])=><span key={type} className="rounded-full bg-[var(--admin-soft)] px-3 py-1.5 text-[10px] font-black">{type} {count}</span>)}</div><p className="mt-3 text-[10px] text-[var(--admin-muted)]">{analytics.history.length} persisted snapshot{analytics.history.length===1?"":"s"} available for change history.</p></div></>:null}</section>
    {toast?<Toast tone="success" message={toast} onClose={()=>setToast("")}/>:null}
  </div></ControlShell>
}
