"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { AlertTriangle, Archive, CheckCircle2, KeyRound, Mail, PauseCircle, Plus, RefreshCw, Trash2, UserPlus, UsersRound, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { ControlShell } from "@/components/control-shell";

const API = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8006/api/v1";
type Me={email:string;is_platform_owner:boolean};
type Membership={tenant_id:string;tenant_name:string;role:string;status:string};
type Domain={id:string;ascii_name:string;status:string;mail_enabled:boolean};
type MailboxRow={id:string;domain_id:string;address:string;display_name?:string|null;quota_bytes:number;status:"active"|"suspended"|"archived";password_changed_at:string};
type AliasRow={id:string;source_address:string;destination_address:string;active:boolean};
type GroupRow={id:string;address:string;display_name?:string|null;active:boolean;members:string[]};
type GroupMember={id:string;destination_address:string};

async function api(path:string,init?:RequestInit){const options={credentials:"include" as RequestCredentials,...init,headers:{"Content-Type":"application/json",...(init?.headers||{})}};let response=await fetch(`${API}${path}`,options);if(response.status===401){const refreshed=await fetch(`${API}/auth/refresh`,{method:"POST",credentials:"include"});if(refreshed.ok)response=await fetch(`${API}${path}`,options)}return response}
function bytes(value:number){if(value>=1024**3)return `${(value/1024**3).toFixed(value%(1024**3)?1:0)} GB`;return `${Math.round(value/1024**2)} MB`}

export default function MailboxesPage(){
 const router=useRouter();
 const[me,setMe]=useState<Me|null>(null);const[contexts,setContexts]=useState<Membership[]>([]);const[tenantId,setTenantId]=useState("");const[domains,setDomains]=useState<Domain[]>([]);const[mailboxes,setMailboxes]=useState<MailboxRow[]>([]);const[aliases,setAliases]=useState<AliasRow[]>([]);const[groups,setGroups]=useState<GroupRow[]>([]);const[groupMembers,setGroupMembers]=useState<Record<string,GroupMember[]>>({});const[tab,setTab]=useState<"mailboxes"|"aliases"|"groups">("mailboxes");const[message,setMessage]=useState("");const[error,setError]=useState("");const[loading,setLoading]=useState(true);const[passwordTarget,setPasswordTarget]=useState<MailboxRow|null>(null);const[newPassword,setNewPassword]=useState("");
 const selected=useMemo(()=>contexts.find(x=>x.tenant_id===tenantId),[contexts,tenantId]);const canManage=Boolean(me?.is_platform_owner||selected?.role==="tenant_admin"||selected?.role==="mail_admin");const readyDomains=domains.filter(d=>d.status==="verified"&&d.mail_enabled);const activeMailboxes=mailboxes.filter(m=>m.status==="active");
 useEffect(()=>{void (async()=>{try{const mr=await api("/auth/me");if(mr.status===401){router.replace("/login");return}if(!mr.ok)throw new Error("Unable to load account");const current:Me=await mr.json();setMe(current);let rows:Membership[]=[];if(current.is_platform_owner){const tr=await api("/tenants");if(!tr.ok)throw new Error("Unable to load organizations");rows=(await tr.json()).map((t:{id:string;name:string;status:string})=>({tenant_id:t.id,tenant_name:t.name,role:"platform_owner",status:t.status}))}else{const cr=await api("/me/memberships");if(!cr.ok)throw new Error("Unable to load organizations");rows=await cr.json()}const active=rows.filter(x=>x.status==="active");setContexts(active);const remembered=localStorage.getItem("mailbox_dns_tenant");setTenantId(active.find(x=>x.tenant_id===remembered)?.tenant_id||active[0]?.tenant_id||"")}catch(e){setError(e instanceof Error?e.message:"Unable to initialize mailboxes")}finally{setLoading(false)}})()},[router]);
 useEffect(()=>{if(!tenantId)return;localStorage.setItem("mailbox_dns_tenant",tenantId);void loadAll()},[tenantId]);
 async function loadAll(){if(!tenantId)return;setLoading(true);setError("");const[dr,mr,ar,gr]=await Promise.all([api(`/tenants/${tenantId}/domains`),api(`/tenants/${tenantId}/mailboxes`),api(`/tenants/${tenantId}/aliases`),api(`/tenants/${tenantId}/groups`)]);if(!dr.ok||!mr.ok||!ar.ok||!gr.ok){setError("Unable to load mailbox inventory");setLoading(false);return}setDomains((await dr.json()).items);setMailboxes((await mr.json()).items);setAliases((await ar.json()).items);setGroups((await gr.json()).items);setLoading(false)}
 async function mutate(path:string,method:"POST"|"DELETE"|"PATCH",body:object|undefined,success:string){const r=await api(path,{method,body:body===undefined?undefined:JSON.stringify(body)});if(!r.ok){const b=await r.json().catch(()=>({}));setError(b.detail||"Request failed");return false}setMessage(success);setError("");await loadAll();return true}
 async function createMailbox(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const ok=await mutate(`/tenants/${tenantId}/mailboxes`,"POST",{domain_id:f.get("domain_id"),local_part:f.get("local_part"),display_name:f.get("display_name")||null,password:f.get("password"),quota_bytes:Number(f.get("quota_gb")||5)*1024**3},"Mailbox created and available to Postfix/Dovecot immediately.");if(ok)e.currentTarget.reset()}
 async function createAlias(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const ok=await mutate(`/tenants/${tenantId}/aliases`,"POST",{domain_id:f.get("domain_id"),local_part:f.get("local_part"),destination_address:f.get("destination_address")},"Alias route created.");if(ok)e.currentTarget.reset()}
 async function createGroup(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const ok=await mutate(`/tenants/${tenantId}/groups`,"POST",{domain_id:f.get("domain_id"),local_part:f.get("local_part"),display_name:f.get("display_name")||null},"Distribution group created.");if(ok)e.currentTarget.reset()}
 async function toggleMailbox(m:MailboxRow){const action=m.status==="active"?"suspend":"restore";await mutate(`/tenants/${tenantId}/mailboxes/${m.id}/${action}`,"POST",{},`${m.address} ${action==="suspend"?"suspended":"restored"}.`)}
 async function archiveMailbox(m:MailboxRow){if(!confirm(`Archive ${m.address}? Authentication and delivery will stop immediately.`))return;await mutate(`/tenants/${tenantId}/mailboxes/${m.id}`,"DELETE",undefined,`${m.address} archived.`)}
 async function savePassword(){if(!passwordTarget)return;const ok=await mutate(`/tenants/${tenantId}/mailboxes/${passwordTarget.id}/password`,"POST",{password:newPassword},"Mailbox password changed.");if(ok){setPasswordTarget(null);setNewPassword("")}}
 async function deleteAlias(a:AliasRow){if(!confirm(`Delete alias ${a.source_address}?`))return;await mutate(`/tenants/${tenantId}/aliases/${a.id}`,"DELETE",undefined,"Alias deleted.")}
 async function loadGroupMembers(groupId:string){const r=await api(`/tenants/${tenantId}/groups/${groupId}/members`);if(!r.ok){setError("Unable to load group members");return}const payload:{items:GroupMember[]}=await r.json();setGroupMembers(x=>({...x,[groupId]:payload.items}))}
 async function addGroupMember(group:GroupRow,address:string){if(!address)return;const ok=await mutate(`/tenants/${tenantId}/groups/${group.id}/members`,"POST",{destination_address:address},`${address} added to ${group.address}.`);if(ok)await loadGroupMembers(group.id)}
 async function removeGroupMember(group:GroupRow,member:GroupMember){const ok=await mutate(`/tenants/${tenantId}/groups/${group.id}/members/${member.id}`,"DELETE",undefined,`${member.destination_address} removed from ${group.address}.`);if(ok)await loadGroupMembers(group.id)}
 async function deleteGroup(group:GroupRow){if(!confirm(`Delete distribution group ${group.address}?`))return;await mutate(`/tenants/${tenantId}/groups/${group.id}`,"DELETE",undefined,`${group.address} deleted.`)}
 return <ControlShell title="Mailboxes" subtitle="Database-backed mailbox, alias and group administration" userEmail={me?.email}><div className="space-y-4">
  <section className="rounded-2xl border border-[#e1e7e3] bg-white p-4 shadow-sm sm:p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2 text-[11px] font-black uppercase tracking-[.12em] text-[#718078]"><Mail size={14}/>Phase 7 · Mailbox management</div><h1 className="mt-2 text-2xl font-black tracking-tight text-[#21342a]">Mailbox control plane</h1><p className="mt-1 max-w-3xl text-[12px] leading-5 text-[#718078]">Mailboxes, quotas, aliases and distribution groups are controlled from PostgreSQL and consumed live by Postfix and Dovecot.</p></div><div className="flex gap-2"><select className="input min-w-[240px]" value={tenantId} onChange={e=>setTenantId(e.target.value)}><option value="">Select organization</option>{contexts.map(x=><option key={x.tenant_id} value={x.tenant_id}>{x.tenant_name} · {x.role.replaceAll("_"," ")}</option>)}</select><button className="btn-secondary px-3" onClick={()=>void loadAll()} title="Refresh"><RefreshCw size={14} className={loading?"animate-spin":""}/></button></div></div></section>
  {error?<div className="flex items-center gap-2 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-[12px] font-semibold text-red-700"><AlertTriangle size={15}/>{error}<button className="ml-auto" onClick={()=>setError("")}>×</button></div>:null}{message?<div className="flex items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-[12px] font-semibold text-emerald-700"><CheckCircle2 size={15}/>{message}<button className="ml-auto" onClick={()=>setMessage("")}>×</button></div>:null}
  <div className="flex gap-2 rounded-xl border border-[#e1e7e3] bg-white p-1.5">{(["mailboxes","aliases","groups"] as const).map(x=><button key={x} onClick={()=>setTab(x)} className={`rounded-lg px-4 py-2 text-[11px] font-black capitalize ${tab===x?"bg-[#123a38] text-white":"text-[#617269] hover:bg-[#f3f6f4]"}`}>{x}</button>)}</div>
  {tab==="mailboxes"?<section className="grid gap-4 lg:grid-cols-[1fr_2fr]">{canManage?<form onSubmit={createMailbox} className="rounded-2xl border border-[#e1e7e3] bg-white p-4 shadow-sm"><div className="flex items-center gap-2 font-black text-[#21342a]"><Plus size={15}/>Create mailbox</div><div className="mt-4 space-y-3"><select name="domain_id" className="input" required defaultValue=""><option value="" disabled>Verified mail domain</option>{readyDomains.map(d=><option key={d.id} value={d.id}>@{d.ascii_name}</option>)}</select><input name="local_part" className="input" placeholder="local part, e.g. sales" required/><input name="display_name" className="input" placeholder="Display name (optional)"/><input name="password" type="password" className="input" placeholder="Strong mailbox password" minLength={12} required/><label className="block"><span className="label">Quota (GB)</span><input name="quota_gb" type="number" min="1" max="10240" defaultValue="5" className="input"/></label><button className="btn-primary w-full" disabled={!readyDomains.length}><Plus size={14}/>Create mailbox</button></div></form>:null}<div className="rounded-2xl border border-[#e1e7e3] bg-white p-4 shadow-sm"><div className="mb-3"><p className="text-sm font-black text-[#21342a]">Mailbox inventory</p><p className="text-[10px] text-[#819087]">{mailboxes.length} mailbox{mailboxes.length===1?"":"es"}</p></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Mailbox</th><th>Status</th><th>Quota</th><th>Actions</th></tr></thead><tbody>{mailboxes.map(m=><tr key={m.id}><td><div className="font-black text-[#21342a]">{m.address}</div><div className="text-[9px] text-[#819087]">{m.display_name||"No display name"}</div></td><td><span className={`status-badge ${m.status==="active"?"status-verified":m.status==="suspended"?"status-suspended":"status-archived"}`}>{m.status}</span></td><td className="font-bold">{bytes(m.quota_bytes)}</td><td><div className="flex flex-wrap gap-2">{m.status!=="archived"&&canManage?<><button className="rounded-lg border px-2.5 py-1.5 text-[10px] font-bold" onClick={()=>void toggleMailbox(m)}><PauseCircle size={12}/>{m.status==="active"?"Suspend":"Restore"}</button><button className="rounded-lg border px-2.5 py-1.5 text-[10px] font-bold" onClick={()=>{setPasswordTarget(m);setNewPassword("")}}><KeyRound size={12}/>Password</button><button className="rounded-lg border border-red-200 px-2.5 py-1.5 text-[10px] font-bold text-red-700" onClick={()=>void archiveMailbox(m)}><Archive size={12}/>Archive</button></>:null}</div></td></tr>)}{!mailboxes.length?<tr><td colSpan={4} className="py-10 text-center text-[#819087]">No mailboxes yet.</td></tr>:null}</tbody></table></div></div></section>:null}
  {tab==="aliases"?<section className="grid gap-4 lg:grid-cols-[1fr_2fr]">{canManage?<form onSubmit={createAlias} className="rounded-2xl border border-[#e1e7e3] bg-white p-4 shadow-sm"><p className="font-black text-[#21342a]">Create alias</p><div className="mt-4 space-y-3"><select name="domain_id" className="input" required defaultValue=""><option value="" disabled>Domain</option>{readyDomains.map(d=><option key={d.id} value={d.id}>@{d.ascii_name}</option>)}</select><input name="local_part" className="input" placeholder="support" required/><select name="destination_address" className="input" required defaultValue=""><option value="" disabled>Destination mailbox/group</option>{activeMailboxes.map(m=><option key={m.id} value={m.address}>{m.address}</option>)}{groups.filter(g=>g.active).map(g=><option key={g.id} value={g.address}>{g.address} · group</option>)}</select><button className="btn-primary w-full"><Plus size={14}/>Create alias</button></div></form>:null}<div className="rounded-2xl border border-[#e1e7e3] bg-white p-4 shadow-sm"><p className="mb-3 text-sm font-black text-[#21342a]">Alias routes</p><div className="space-y-2">{aliases.map(a=><div key={a.id} className="flex items-center rounded-xl border p-3 text-[11px]"><div><span className="font-black text-[#21342a]">{a.source_address}</span><span className="mx-2 text-[#9aa59f]">→</span><span>{a.destination_address}</span></div>{canManage?<button className="ml-auto rounded-lg border border-red-200 p-2 text-red-700" onClick={()=>void deleteAlias(a)} title="Delete alias"><Trash2 size={13}/></button>:null}</div>)}{!aliases.length?<p className="py-8 text-center text-[11px] text-[#819087]">No aliases configured.</p>:null}</div></div></section>:null}
  {tab==="groups"?<section className="grid gap-4 lg:grid-cols-[1fr_2fr]">{canManage?<form onSubmit={createGroup} className="rounded-2xl border border-[#e1e7e3] bg-white p-4 shadow-sm"><div className="flex items-center gap-2 font-black text-[#21342a]"><UsersRound size={15}/>Create group</div><div className="mt-4 space-y-3"><select name="domain_id" className="input" required defaultValue=""><option value="" disabled>Domain</option>{readyDomains.map(d=><option key={d.id} value={d.id}>@{d.ascii_name}</option>)}</select><input name="local_part" className="input" placeholder="all-staff" required/><input name="display_name" className="input" placeholder="All Staff"/><button className="btn-primary w-full"><Plus size={14}/>Create group</button></div></form>:null}<div className="rounded-2xl border border-[#e1e7e3] bg-white p-4 shadow-sm"><p className="mb-3 text-sm font-black text-[#21342a]">Distribution groups</p><div className="space-y-3">{groups.map(g=><GroupCard key={g.id} group={g} members={groupMembers[g.id]} activeMailboxes={activeMailboxes} canManage={canManage} onLoad={()=>loadGroupMembers(g.id)} onAdd={address=>addGroupMember(g,address)} onRemove={member=>removeGroupMember(g,member)} onDelete={()=>deleteGroup(g)}/>)}{!groups.length?<p className="py-8 text-center text-[11px] text-[#819087]">No distribution groups configured.</p>:null}</div></div></section>:null}
  {passwordTarget?<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-5 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-sm font-black text-[#21342a]">Reset mailbox password</p><p className="mt-1 text-[11px] text-[#718078]">{passwordTarget.address}</p></div><button onClick={()=>setPasswordTarget(null)}><X size={18}/></button></div><input type="password" value={newPassword} onChange={e=>setNewPassword(e.target.value)} minLength={12} className="input mt-4" placeholder="12+ chars, 3 character classes" autoFocus/><div className="mt-4 flex justify-end gap-2"><button className="btn-secondary" onClick={()=>setPasswordTarget(null)}>Cancel</button><button className="btn-primary" disabled={newPassword.length<12} onClick={()=>void savePassword()}><KeyRound size={14}/>Change password</button></div></div></div>:null}
 </div></ControlShell>
}

function GroupCard({group,members,activeMailboxes,canManage,onLoad,onAdd,onRemove,onDelete}:{group:GroupRow;members?:GroupMember[];activeMailboxes:MailboxRow[];canManage:boolean;onLoad:()=>Promise<void>;onAdd:(address:string)=>Promise<void>;onRemove:(member:GroupMember)=>Promise<void>;onDelete:()=>Promise<void>}){const[expanded,setExpanded]=useState(false);const[selected,setSelected]=useState("");async function toggle(){const next=!expanded;setExpanded(next);if(next&&!members)await onLoad()}return <div className="rounded-xl border p-3"><div className="flex items-start gap-3"><button className="flex-1 text-left" onClick={()=>void toggle()}><div className="font-black text-[#21342a]">{group.address}</div><div className="mt-1 text-[10px] text-[#819087]">{group.display_name||"Distribution group"} · {group.members.length} member{group.members.length===1?"":"s"}</div></button>{canManage?<button className="rounded-lg border border-red-200 p-2 text-red-700" onClick={()=>void onDelete()} title="Delete group"><Trash2 size={13}/></button>:null}</div>{expanded?<div className="mt-3 border-t pt-3"><div className="space-y-2">{(members||[]).map(member=><div key={member.id} className="flex items-center rounded-lg bg-[#f7f9f8] px-3 py-2 text-[10px]"><span className="font-bold text-[#31443a]">{member.destination_address}</span>{canManage?<button className="ml-auto text-red-700" onClick={()=>void onRemove(member)}><Trash2 size={12}/></button>:null}</div>)}{members&&members.length===0?<p className="text-[10px] text-[#819087]">No members yet.</p>:null}</div>{canManage?<div className="mt-3 flex gap-2"><select className="input" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Add active mailbox</option>{activeMailboxes.filter(m=>!(members||[]).some(x=>x.destination_address===m.address)).map(m=><option key={m.id} value={m.address}>{m.address}</option>)}</select><button className="btn-secondary shrink-0 px-3" disabled={!selected} onClick={async()=>{await onAdd(selected);setSelected("")}}><UserPlus size={13}/>Add</button></div>:null}</div>:null}</div>}
