"use client";

import { Headphones, KeyRound, SearchCheck, ShieldAlert } from "lucide-react";
import { QueryCentre } from "@/components/support/query-centre";

export default function PlatformSupportPage() {
    return <div className="space-y-6"><section className="rounded-3xl border bg-card p-6 shadow-sm md:p-8"><p className="text-xs font-black uppercase tracking-[0.22em] text-primary">Controlled assistance</p><h1 className="mt-2 text-3xl font-black">Platform support procedures</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">Support users diagnose access and transaction problems without viewing provider passwords, merchant PINs, signing keys or unmasked bank accounts.</p></section><section className="grid gap-4 md:grid-cols-3"><Box icon={SearchCheck} title="Investigate" text="Use transaction references, request IDs and audit records to identify failed or pending operations." /><Box icon={KeyRound} title="Escalate credentials" text="Only the system owner changes payment credentials. Support records the issue and escalates it." /><Box icon={ShieldAlert} title="Fraud response" text="Freeze suspicious operational actions, preserve logs and follow the incident-response document." /></section><section className="rounded-3xl border bg-card p-6"><h2 className="text-xl font-black">Mandatory support checklist</h2><ol className="mt-4 space-y-3 text-sm leading-6 text-muted-foreground"><li>1. Confirm the user, company, active role and transaction reference.</li><li>2. Never request a wallet PIN, merchant PIN, API key, password or signing key.</li><li>3. Check whether the operation is pending before advising a retry.</li><li>4. Do not manually mark a financial transaction successful without provider or bank evidence.</li><li>5. Record the incident, evidence, action taken and escalation owner.</li></ol></section><section><QueryCentre platform /></section></div>;
}
function Box({ icon: Icon, title, text }: { icon: typeof Headphones; title: string; text: string }) { return <div className="rounded-3xl border bg-card p-5"><Icon className="h-8 w-8 text-primary" /><h2 className="mt-4 text-lg font-black">{title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></div>; }
