"use client";
import { useEffect, useState } from "react";
import { Gauge, Settings, ShieldCheck } from "lucide-react";
import { ControlShell } from "@/components/control-shell";
import { PageHeader, StatusBadge, Toast } from "@/components/ui-kit";
const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:8006/api/v1";
type Me={email:string};
export default function SettingsPage(){const[me,setMe]=useState<Me|null>(null);const[density,setDensity]=useState("comfortable");const[toast,setToast]=useState("");useEffect(()=>{void fetch(`${API}/auth/me`,{credentials:"include"}).then(r=>r.ok?r.json():null).then(setMe);setDensity(localStorage.getItem("mailbox_dns_density")||"comfortable")},[]);function save(){localStorage.setItem("mailbox_dns_density",density);setToast("Workspace preference saved on this device")}
return <ControlShell title="Settings" subtitle="Workspace preferences and platform information" userEmail={me?.email}><div className="space-y-4"><PageHeader eyebrow="Workspace" title="Platform settings" description="User-facing preferences live here. Infrastructure secrets and authoritative server configuration remain environment-managed and are never exposed to the browser."/><section className="grid gap-4 xl:grid-cols-2"><div className="surface-card p-4 sm:p-5"><div className="flex items-start gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#eef4f1] text-[var(--admin-pine)]"><Gauge size={18}/></div><div><p className="text-sm font-black">Interface density</p><p className="mt-1 text-[10px] leading-5 text-[var(--admin-muted)]">Choose how compact administration tables and forms should feel on this device.</p></div></div><select className="input mt-4" value={density} onChange={e=>setDensity(e.target.value)}><option value="comfortable">Comfortable</option><option value="compact">Compact</option></select><button className="btn-primary mt-3" onClick={save}>Save preference</button></div><div className="surface-card p-4 sm:p-5"><div className="flex items-start gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#eef4f1] text-[var(--admin-pine)]"><ShieldCheck size={18}/></div><div><p className="text-sm font-black">Security boundary</p><p className="mt-1 text-[10px] leading-5 text-[var(--admin-muted)]">API keys, PowerDNS credentials, database secrets and signing keys are intentionally absent from this page.</p></div></div><div className="mt-4 flex flex-wrap gap-2"><StatusBadge state="good">Secrets server-side</StatusBadge><StatusBadge state="good">HttpOnly sessions</StatusBadge><StatusBadge state="neutral">Environment managed</StatusBadge></div></div></section><section className="surface-card p-4 sm:p-5"><div className="flex items-start gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#f8f4df] text-[#806800]"><Settings size={18}/></div><div><p className="text-sm font-black">Product information</p><p className="mt-1 text-[10px] leading-5 text-[var(--admin-muted)]">Mailbox DNS control plane · multi-tenant identity, verified domains and authoritative DNS. Mail data-plane modules activate in their infrastructure release.</p></div></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-[#f8faf8] p-3"><p className="eyebrow-label">Frontend API</p><code className="mt-1 block overflow-x-auto text-[9px]">{API}</code></div><div className="rounded-xl bg-[#f8faf8] p-3"><p className="eyebrow-label">Session mode</p><p className="mt-1 text-[10px] font-bold">HttpOnly cookies</p></div><div className="rounded-xl bg-[#f8faf8] p-3"><p className="eyebrow-label">Theme foundation</p><p className="mt-1 text-[10px] font-bold">Semantic color tokens</p></div></div></section></div>{toast?<Toast tone="success" message={toast} onClose={()=>setToast("")}/>:null}</ControlShell>}
