export type PageGuide = {
  purpose: string;
  steps: string[];
  note?: string;
};

const GUIDES: Array<[string, PageGuide]> = [
  ["/dashboard/provider", { purpose: "Your home for the currently selected payment provider.", steps: ["Check provider readiness and environment.", "Choose the service you want to operate.", "Use Provider setup before sending live traffic if anything is incomplete."], note: "Switch providers from the navigation at any time; provider-specific menus change automatically." }],
  ["/dashboard/payments", { purpose: "Review money collected from customers into merchant accounts.", steps: ["Check the provider, customer and reference.", "Use the status to identify completed, failed or uncertain payments.", "Open transaction/reconciliation tools before retrying an uncertain payment."], note: "A timeout does not prove that money did not move." }],
  ["/dashboard/payouts", { purpose: "Review merchant-to-customer disbursements and open the Bulk B2C test workflow.", steps: ["Confirm the recipient and reference.", "Check the provider status and failure reason.", "Use the sandbox test before enabling a new payout integration in production."], note: "Every payout should have its own unique reference and idempotency key." }],
  ["/dashboard/transfers", { purpose: "Inspect business-to-business transfers between approved provider parties.", steps: ["Confirm the receiver party/service code.", "Review amount and provider status.", "Reconcile unknown results before creating another transfer."] }],
  ["/dashboard/authorizations", { purpose: "Manage two-stage payments where funds are reserved before final capture or release.", steps: ["Review the authorization state.", "Complete or release only the intended authorization.", "Keep provider references for audit and recovery."] }],
  ["/dashboard/mandates", { purpose: "Manage customer consent for recurring direct-debit collections.", steps: ["Confirm the customer mandate is active.", "Review mandate terms before charging.", "Keep consent and provider state auditable."] }],
  ["/dashboard/transactions", { purpose: "Trace the provider-level movement behind Pay Bridge resources.", steps: ["Search by provider/reference when investigating an issue.", "Compare gateway and provider identifiers.", "Use reconciliation for delayed or unknown states."] }],
  ["/dashboard/reconciliation", { purpose: "Match Pay Bridge records with provider outcomes and resolve uncertain transactions.", steps: ["Identify unmatched or unknown records.", "Compare amount, currency and provider identifiers.", "Resolve only when evidence supports the final state."] }],
  ["/dashboard/testing/ecocash", { purpose: "Safely validate EcoCash behavior before relying on live merchant traffic.", steps: ["Choose simulator or real sandbox.", "Select the expected provider scenario.", "Inspect provider evidence and returned JSON after each run."], note: "Sandbox credentials and test PIN behavior must never be reused as production assumptions." }],
  ["/dashboard/testing/bulk-payout", { purpose: "Run multiple controlled B2C payout tests without turning the sandbox into an uncontrolled request burst.", steps: ["Choose simulator or M-Pesa sandbox.", "Set count, amount and scenario.", "Review each payout result independently before retrying anything."], note: "Live sandbox batches are intentionally capped and processed sequentially." }],
  ["/dashboard/testing", { purpose: "Validate provider services one at a time and inspect exactly what Pay Bridge sends and receives.", steps: ["Choose execution mode.", "Select one service tab.", "Read its usage guide, run the test and inspect the evidence."], note: "The test lab refuses production provider configurations." }],
  ["/dashboard/providers", { purpose: "Configure payment providers, credentials, environments, product capabilities and callbacks.", steps: ["Choose a provider and environment.", "Enter only the credentials/products approved for that provider account.", "Review callbacks and settings before activation."], note: "Do not enable provider products that have not been approved on the provider account." }],
  ["/dashboard/merchants", { purpose: "Manage organizations that consume Ithute Pay Bridge services.", steps: ["Find or create the merchant.", "Confirm contact and status information.", "Continue to routing, applications or settlement configuration as needed."] }],
  ["/dashboard/routing", { purpose: "Control how external identifiers map requests to the correct merchant and settlement destination.", steps: ["Select the merchant.", "Review routing keys and settlement accounts.", "Avoid duplicate identifiers across merchants."] }],
  ["/dashboard/fees", { purpose: "Define fee packages and assign pricing rules to merchants.", steps: ["Create or select a package.", "Add operation/provider fee rules.", "Assign the package to the intended merchant and verify the effective pricing."] }],
  ["/dashboard/settlements", { purpose: "Track settlement obligations created from confirmed money movement.", steps: ["Review pending settlement instructions.", "Confirm destination and net amount.", "Execute or investigate only after the underlying transaction is confirmed."] }],
  ["/dashboard/finance", { purpose: "Inspect double-entry accounting, balances and financial integrity.", steps: ["Select the merchant/currency where available.", "Compare debit and credit totals.", "Investigate imbalances before further settlement activity."] }],
  ["/dashboard/operations", { purpose: "Operate risk, compliance, reconciliation and settlement controls from one place.", steps: ["Start with alerts or exceptions.", "Open the affected rule/run/batch.", "Record a clear operational resolution for audit."] }],
  ["/dashboard/applications", { purpose: "Manage merchant applications, environments and API credentials.", steps: ["Choose the merchant application.", "Keep test and live environments separate.", "Create scoped keys and rotate/revoke them when needed."] }],
  ["/dashboard/checkout", { purpose: "Manage hosted checkout sessions and shareable payment links.", steps: ["Choose the checkout or payment-link workflow.", "Confirm amount/reference and customer journey.", "Track the resulting payment rather than creating duplicate sessions on uncertainty."] }],
  ["/dashboard/webhooks", { purpose: "Monitor event delivery from Pay Bridge to connected merchant systems.", steps: ["Check endpoint and event type.", "Inspect failed delivery attempts.", "Verify signatures and retry policy before manual redelivery."] }],
  ["/dashboard/audit", { purpose: "Review security-sensitive and operational changes across the platform.", steps: ["Filter to the user/resource/action of interest.", "Read metadata for exact change context.", "Use timestamps and resource identifiers during investigations."] }],
  ["/dashboard/documentation", { purpose: "Find administrator, consumer and testing instructions for Pay Bridge.", steps: ["Choose the audience tab.", "Follow the examples for the active provider/environment.", "Return to provider setup or the test lab to verify configuration."] }],
  ["/dashboard/settings", { purpose: "Manage platform-level preferences and operational configuration.", steps: ["Change only the setting you intend to update.", "Review its effect before saving.", "Use the audit trail to confirm sensitive configuration changes."] }],
  ["/dashboard", { purpose: "Choose the payment provider you want to work with before entering an operational workspace.", steps: ["Select a provider card.", "Review the provider overview and readiness.", "Use the provider-aware navigation for only the services relevant to that rail."], note: "Platform administration remains available regardless of the selected provider." }],
];

export function getPageGuide(pathname: string): PageGuide | null {
  const match = GUIDES.find(([path]) => pathname === path || (path !== "/dashboard" && pathname.startsWith(`${path}/`)));
  return match?.[1] ?? null;
}
