protocols = imap lmtp
listen = *

mail_location = maildir:/srv/vmail/%d/%n/Maildir
mail_privileged_group = mail
first_valid_uid = 5000
last_valid_uid = 5000
mail_plugins = quota acl

ssl = required
ssl_cert = </etc/dovecot/tls/cert.pem
ssl_key = </etc/dovecot/tls/key.pem
ssl_min_protocol = TLSv1.2

disable_plaintext_auth = no
auth_mechanisms = plain login
auth_username_format = %Lu
auth_verbose = yes

passdb {
  driver = sql
  args = /etc/dovecot/dovecot-sql.conf.ext
}

userdb {
  driver = sql
  args = /etc/dovecot/dovecot-sql.conf.ext
}

namespace inbox {
  inbox = yes
  separator = /
  prefix =
}

namespace shared {
  type = shared
  separator = /
  prefix = Shared/%%u/
  location = maildir:/srv/vmail/%%d/%%n/Maildir:INDEXPVT=~/Maildir/shared/%%u
  subscriptions = no
  list = children
}

service imap-login {
  inet_listener imap {
    port = 143
  }
  inet_listener imaps {
    port = 993
    ssl = yes
  }
}

service auth {
  inet_listener auth-client {
    address = 0.0.0.0
    port = 12345
  }
}

service lmtp {
  inet_listener lmtp {
    address = 0.0.0.0
    port = 24
  }
}

protocol imap {
  mail_plugins = $mail_plugins imap_quota imap_acl
}

protocol lmtp {
  mail_plugins = $mail_plugins sieve
  postmaster_address = postmaster@localhost
}

plugin {
  quota = maildir:User quota
  acl = vfile
  sieve = file:~/sieve;active=~/.dovecot.sieve
}
