from __future__ import annotations

from dataclasses import dataclass
from uuid import UUID

from sqlalchemy.orm import Session

from app.core.config import settings
from app.models.billing import BillingPlan, SubscriptionStatus
from app.models.domains import Domain
from app.services.billing import get_subscription
from app.services.powerdns import PowerDNSClient, validate_record


@dataclass(frozen=True)
class PackageDNSProfile:
    plan_id: str
    plan_code: str
    plan_name: str
    currency: str
    monthly_price_minor: int
    included_domains: int
    included_mailboxes: int
    included_storage_mb: int
    subscription_status: str
    records: list[dict]


def _plan_for_tenant(db: Session, tenant_id: UUID) -> tuple[object, BillingPlan]:
    subscription = get_subscription(db, tenant_id)
    if subscription is None:
        raise ValueError("Organization has no hosting subscription")
    plan = db.get(BillingPlan, subscription.plan_id)
    if plan is None or not plan.is_active:
        raise ValueError("Organization hosting package is unavailable")
    if subscription.status == SubscriptionStatus.canceled:
        raise ValueError("Organization hosting subscription is canceled")
    return subscription, plan


def desired_package_records(domain: Domain, plan: BillingPlan) -> list[dict]:
    """Build conservative DNS defaults from the current hosting entitlement.

    Mail-enabled packages publish RFC 6186 service discovery in addition to
    routing/authentication records. The SRV targets use the shared canonical
    mail hostname, so clients validate the existing mail TLS certificate rather
    than a per-customer alias. DKIM remains verified-only and is generated by
    the existing mail reconciliation lifecycle after ownership is proven.
    """
    records: list[dict] = []
    if settings.bootstrap_public_ip:
        records.extend(
            [
                {
                    "name": domain.ascii_name,
                    "type": "A",
                    "values": [settings.bootstrap_public_ip],
                    "purpose": "platform-web",
                },
                {
                    "name": f"www.{domain.ascii_name}",
                    "type": "CNAME",
                    "values": [f"{domain.ascii_name}."],
                    "purpose": "www-alias",
                },
            ]
        )

    if domain.mail_enabled and plan.included_mailboxes > 0:
        records.extend(
            [
                {
                    "name": domain.ascii_name,
                    "type": "MX",
                    "values": [f"10 {settings.mail_hostname}."],
                    "purpose": "mail-routing",
                },
                {
                    "name": domain.ascii_name,
                    "type": "TXT",
                    "values": ["v=spf1 mx -all"],
                    "purpose": "spf",
                },
                {
                    "name": f"_dmarc.{domain.ascii_name}",
                    "type": "TXT",
                    "values": ["v=DMARC1; p=quarantine; adkim=s; aspf=s; pct=100"],
                    "purpose": "dmarc",
                },
                {
                    "name": f"_imaps._tcp.{domain.ascii_name}",
                    "type": "SRV",
                    "values": [f"0 1 993 {settings.mail_hostname}."],
                    "purpose": "imap-discovery",
                },
                {
                    "name": f"_submission._tcp.{domain.ascii_name}",
                    "type": "SRV",
                    "values": [f"0 1 587 {settings.mail_hostname}."],
                    "purpose": "smtp-discovery",
                },
            ]
        )
    return records


def package_dns_profile(db: Session, domain: Domain) -> PackageDNSProfile:
    subscription, plan = _plan_for_tenant(db, domain.tenant_id)
    return PackageDNSProfile(
        plan_id=str(plan.id),
        plan_code=plan.code,
        plan_name=plan.name,
        currency=plan.currency,
        monthly_price_minor=plan.monthly_price_minor,
        included_domains=plan.included_domains,
        included_mailboxes=plan.included_mailboxes,
        included_storage_mb=plan.included_storage_mb,
        subscription_status=subscription.status.value,
        records=desired_package_records(domain, plan),
    )


def _strip_txt_quotes(value: str) -> str:
    text = value.strip()
    if len(text) >= 2 and text.startswith('"') and text.endswith('"'):
        return text[1:-1]
    return text


def _zone_rrsets(zone: dict) -> list[dict]:
    rrsets = zone.get("rrsets") if isinstance(zone, dict) else None
    return rrsets if isinstance(rrsets, list) else []


def _rrset_key(name: str, rtype: str) -> tuple[str, str]:
    return name.rstrip(".").lower(), rtype.upper()


def _contents(rrset: dict) -> list[str]:
    records = rrset.get("records") if isinstance(rrset.get("records"), list) else []
    return [
        str(record.get("content", "")).strip()
        for record in records
        if isinstance(record, dict) and str(record.get("content", "")).strip()
    ]


def apply_package_dns_defaults(
    db: Session,
    domain: Domain,
    *,
    client: PowerDNSClient | None = None,
) -> dict:
    """Add missing package defaults without overwriting customer DNS.

    Existing RRsets win. SPF is the only shared RRset we extend, and even there
    unrelated TXT values are preserved. CNAME conflicts are reported and left
    untouched. This makes repeated Auto-generate clicks idempotent and safe for
    staged migrations.
    """
    profile = package_dns_profile(db, domain)
    dns = client or PowerDNSClient()
    zone = dns.get_zone(domain.ascii_name)
    rrsets = _zone_rrsets(zone)
    by_key = {_rrset_key(str(row.get("name", "")), str(row.get("type", ""))): row for row in rrsets if isinstance(row, dict)}
    owner_types: dict[str, set[str]] = {}
    for row in rrsets:
        if not isinstance(row, dict):
            continue
        owner = str(row.get("name", "")).rstrip(".").lower()
        owner_types.setdefault(owner, set()).add(str(row.get("type", "")).upper())

    generated: list[dict] = []
    skipped: list[dict] = []
    ttl = settings.powerdns_default_ttl

    for desired in profile.records:
        fqdn, rtype, values = validate_record(
            domain.ascii_name,
            desired["name"],
            desired["type"],
            desired["values"],
        )
        key = _rrset_key(fqdn, rtype)
        owner = fqdn.rstrip(".").lower()
        existing = by_key.get(key)

        if desired["purpose"] == "spf":
            existing_values = _contents(existing) if existing else []
            if any(_strip_txt_quotes(value).lower().startswith("v=spf1") for value in existing_values):
                skipped.append({**desired, "reason": "existing_spf"})
                continue
            values = existing_values + values
        elif existing is not None:
            skipped.append({**desired, "reason": "existing_rrset"})
            continue

        types_here = owner_types.get(owner, set())
        if rtype == "CNAME" and any(value not in {"CNAME", "SOA", "NS"} for value in types_here):
            skipped.append({**desired, "reason": "cname_conflict"})
            continue
        if rtype != "CNAME" and "CNAME" in types_here:
            skipped.append({**desired, "reason": "cname_conflict"})
            continue

        dns.replace_rrset(domain.ascii_name, fqdn, rtype, ttl, values)
        generated.append({"name": fqdn, "type": rtype, "values": values, "purpose": desired["purpose"]})
        by_key[key] = {
            "name": fqdn,
            "type": rtype,
            "ttl": ttl,
            "records": [{"content": value, "disabled": False} for value in values],
        }
        owner_types.setdefault(owner, set()).add(rtype)

    if generated:
        dns.rectify_zone(domain.ascii_name)

    return {
        "package": {
            "id": profile.plan_id,
            "code": profile.plan_code,
            "name": profile.plan_name,
            "currency": profile.currency,
            "monthly_price_minor": profile.monthly_price_minor,
            "included_domains": profile.included_domains,
            "included_mailboxes": profile.included_mailboxes,
            "included_storage_mb": profile.included_storage_mb,
            "subscription_status": profile.subscription_status,
        },
        "generated": generated,
        "skipped": skipped,
        "dkim": "generated after ownership verification by mail DNS reconciliation" if domain.mail_enabled and profile.included_mailboxes > 0 else "not applicable",
    }
