"use client";

import { useEffect, useState } from "react";
import { Download, FileBarChart, Search } from "lucide-react";
import { ControlShell } from "@/components/control-shell";

const API = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8006/api/v1";

type Aging = { as_of: string; buckets: Record<string, { count: number; amount_minor: number }>; items: Array<{ invoice: { invoice_number: string; client_name: string; recipient_email: string; outstanding_minor: number; due_date: string }; days_overdue: number; bucket: string }> };
type Client = { id: string; name: string; email: string };
type Statement = { client: Client; total_invoiced_minor: number; total_paid_minor: number; balance_minor: number; items: Array<{ invoice_number: string; due_date: string; total_minor: number; paid_minor: number; outstanding_minor: number; status: string }> };

async function api(path: string, init?: RequestInit) { return fetch(`${API}${path}`, { credentials: "include", ...init, headers: { "Content-Type": "application/json", ...(init?.headers || {}) } }); }
const money = (minor = 0) => `M ${(minor / 100).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

export default function FinanceReportsPage() {
  const [email, setEmail] = useState(""); const [owner, setOwner] = useState(false); const [aging, setAging] = useState<Aging | null>(null); const [clients, setClients] = useState<Client[]>([]); const [clientId, setClientId] = useState(""); const [statement, setStatement] = useState<Statement | null>(null);
  useEffect(() => { void (async () => { const me = await api("/auth/me"); if (!me.ok) return; const body = await me.json(); setEmail(body.email || ""); setOwner(Boolean(body.is_platform_owner)); if (!body.is_platform_owner) return; const [a, c] = await Promise.all([api("/finance/reports/aging"), api("/finance/clients?active=true")]); if (a.ok) setAging(await a.json()); if (c.ok) setClients((await c.json()).items || []); })(); }, []);
  async function loadStatement(id: string) { setClientId(id); setStatement(null); if (!id) return; const r = await api(`/finance/reports/clients/${id}/statement`); if (r.ok) setStatement(await r.json()); }
  async function downloadCsv() { const r = await fetch(`${API}/finance/reports/invoices.csv`, { credentials: "include" }); if (!r.ok) return; const blob = await r.blob(); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = "ithute-finance-invoices.csv"; a.click(); URL.revokeObjectURL(url); }
  const label: Record<string, string> = { current: "Current", "1_30": "1–30 days", "31_60": "31–60 days", "61_90": "61–90 days", "90_plus": "90+ days" };
  return <ControlShell title="Finance reports" subtitle="Aging, statements and accounting exports" userEmail={email}>
    {!owner ? <section className="surface-card p-6">Finance is restricted.</section> : <div className="space-y-4">
      <section className="surface-card p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><FileBarChart size={18} /><div><p className="eyebrow-label">Receivables</p><h1 className="font-black">Aging report</h1><p className="text-[10px] text-[var(--admin-muted)]">As of {aging?.as_of || "—"}</p></div></div><button className="btn-secondary" onClick={() => void downloadCsv()}><Download size={14} />Export invoices CSV</button></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{Object.entries(aging?.buckets || {}).map(([key, value]) => <div key={key} className="rounded-2xl border p-4"><p className="text-[10px] font-black uppercase">{label[key] || key}</p><p className="mt-2 text-xl font-black">{money(value.amount_minor)}</p><p className="text-[9px] text-[var(--admin-muted)]">{value.count} invoices</p></div>)}</div></section>
      <section className="surface-card overflow-hidden"><div className="border-b p-4"><h2 className="font-black">Outstanding invoices</h2></div><div className="overflow-x-auto"><table className="min-w-full text-left text-xs"><thead><tr><th className="p-3">Invoice</th><th className="p-3">Client</th><th className="p-3">Due</th><th className="p-3">Days overdue</th><th className="p-3">Bucket</th><th className="p-3">Outstanding</th></tr></thead><tbody>{(aging?.items || []).map((row) => <tr key={row.invoice.invoice_number} className="border-t"><td className="p-3 font-mono font-bold">{row.invoice.invoice_number}</td><td className="p-3 font-bold">{row.invoice.client_name}<p className="text-[9px] font-normal text-[var(--admin-muted)]">{row.invoice.recipient_email}</p></td><td className="p-3">{row.invoice.due_date}</td><td className="p-3">{row.days_overdue}</td><td className="p-3">{label[row.bucket] || row.bucket}</td><td className="p-3 font-black">{money(row.invoice.outstanding_minor)}</td></tr>)}{!aging?.items?.length ? <tr><td colSpan={6} className="p-8 text-center text-[var(--admin-muted)]">No outstanding sent invoices.</td></tr> : null}</tbody></table></div></section>
      <section className="surface-card p-4"><div className="flex items-center gap-2"><Search size={16} /><h2 className="font-black">Customer statement</h2></div><select className="input mt-3 max-w-xl" value={clientId} onChange={(e) => void loadStatement(e.target.value)}><option value="">Select a client</option>{clients.map((c) => <option key={c.id} value={c.id}>{c.name} — {c.email}</option>)}</select>{statement ? <div className="mt-4"><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border p-3"><p className="text-[10px] font-black uppercase">Invoiced</p><p className="mt-1 text-lg font-black">{money(statement.total_invoiced_minor)}</p></div><div className="rounded-2xl border p-3"><p className="text-[10px] font-black uppercase">Paid</p><p className="mt-1 text-lg font-black">{money(statement.total_paid_minor)}</p></div><div className="rounded-2xl border p-3"><p className="text-[10px] font-black uppercase">Balance</p><p className="mt-1 text-lg font-black">{money(statement.balance_minor)}</p></div></div><div className="mt-3 overflow-x-auto"><table className="min-w-full text-left text-xs"><thead><tr><th className="p-2">Invoice</th><th className="p-2">Due</th><th className="p-2">Total</th><th className="p-2">Paid</th><th className="p-2">Balance</th><th className="p-2">Status</th></tr></thead><tbody>{statement.items.map((x) => <tr key={x.invoice_number} className="border-t"><td className="p-2 font-mono font-bold">{x.invoice_number}</td><td className="p-2">{x.due_date}</td><td className="p-2">{money(x.total_minor)}</td><td className="p-2">{money(x.paid_minor)}</td><td className="p-2 font-black">{money(x.outstanding_minor)}</td><td className="p-2 uppercase">{x.status}</td></tr>)}</tbody></table></div></div> : null}</section>
    </div>}
  </ControlShell>;
}
