"use client";

import { useEffect, useMemo, useState } from "react";
import { Download, FileBarChart, Search, TrendingUp } from "lucide-react";
import { ControlShell } from "@/components/control-shell";

const API = process.env.NEXT_PUBLIC_API_URL || "/api/v1";

type Aging = { as_of: string; buckets: Record<string, { count: number; amount_minor: number }>; items: Array<{ invoice: { invoice_number: string; client_name: string; recipient_email: string; outstanding_minor: number; due_date: string }; days_overdue: number; bucket: string }> };
type Client = { id: string; name: string; email: string };
type Statement = { client: Client; total_invoiced_minor: number; total_paid_minor: number; balance_minor: number; items: Array<{ invoice_number: string; due_date: string; total_minor: number; paid_minor: number; outstanding_minor: number; status: string }> };
type Period = { period: string; invoice_count: number; gross_invoiced_minor: number; credits_minor: number; net_invoiced_minor: number; collected_minor: number; outstanding_minor: number };
type TrendRow = { period: string; label: string; invoiced_minor: number; collected_minor: number; outstanding_minor: number; invoice_count: number };

async function api(path: string, init?: RequestInit) { return fetch(`${API}${path}`, { credentials: "include", ...init, headers: { "Content-Type": "application/json", ...(init?.headers || {}) } }); }
const money = (minor = 0) => `M ${(minor / 100).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

export default function FinanceReportsPage() {
  const now = new Date();
  const [email, setEmail] = useState(""); const [owner, setOwner] = useState(false); const [aging, setAging] = useState<Aging | null>(null); const [clients, setClients] = useState<Client[]>([]); const [clientId, setClientId] = useState(""); const [statement, setStatement] = useState<Statement | null>(null);
  const [year, setYear] = useState(String(now.getFullYear())); const [month, setMonth] = useState(String(now.getMonth() + 1)); const [period, setPeriod] = useState<Period | null>(null); const [trend, setTrend] = useState<TrendRow[]>([]);

  useEffect(() => { void (async () => { const me = await api("/auth/me"); if (!me.ok) return; const body = await me.json(); setEmail(body.email || ""); setOwner(Boolean(body.is_platform_owner)); if (!body.is_platform_owner) return; const [a, c, t] = await Promise.all([api("/finance/reports/aging"), api("/finance/clients?active=true"), api("/finance/reports/trend?months=12")]); if (a.ok) setAging(await a.json()); if (c.ok) setClients((await c.json()).items || []); if (t.ok) setTrend((await t.json()).months || []); await loadPeriod(String(now.getFullYear()), String(now.getMonth() + 1)); })(); }, []);

  async function loadStatement(id: string) { setClientId(id); setStatement(null); if (!id) return; const r = await api(`/finance/reports/clients/${id}/statement`); if (r.ok) setStatement(await r.json()); }
  async function loadPeriod(y = year, m = month) { const r = await api(`/finance/reports/period?year=${encodeURIComponent(y)}&month=${encodeURIComponent(m)}`); if (r.ok) setPeriod(await r.json()); }
  async function downloadCsv() { const r = await fetch(`${API}/finance/reports/invoices.csv`, { credentials: "include" }); if (!r.ok) return; const blob = await r.blob(); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = "ithute-finance-invoices.csv"; a.click(); URL.revokeObjectURL(url); }

  const label: Record<string, string> = { current: "Current", "1_30": "1–30 days", "31_60": "31–60 days", "61_90": "61–90 days", "90_plus": "90+ days" };
  const maxTrend = useMemo(() => Math.max(1, ...trend.flatMap((x) => [x.invoiced_minor, x.collected_minor])), [trend]);

  return <ControlShell title="Finance reports" subtitle="Accounting periods, revenue trends, aging and customer statements" userEmail={email}>
    {!owner ? <section className="surface-card p-6">Finance is restricted.</section> : <div className="space-y-4">
      <section className="surface-card p-4">
        <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="eyebrow-label">Accounting period</p><h1 className="mt-1 font-black">Monthly finance summary</h1></div><div className="flex gap-2"><select className="input w-36" value={month} onChange={(e) => setMonth(e.target.value)}>{Array.from({ length: 12 }, (_, i) => <option key={i + 1} value={i + 1}>{new Date(2026, i, 1).toLocaleString(undefined, { month: "long" })}</option>)}</select><input className="input w-28" type="number" min="2000" max="2100" value={year} onChange={(e) => setYear(e.target.value)} /><button className="btn-secondary" onClick={() => void loadPeriod()}>Load</button></div></div>
        <div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><div className="rounded-2xl border p-4"><p className="text-[10px] font-black uppercase">Invoices</p><p className="mt-2 text-xl font-black">{period?.invoice_count ?? 0}</p></div><div className="rounded-2xl border p-4"><p className="text-[10px] font-black uppercase">Gross invoiced</p><p className="mt-2 text-xl font-black">{money(period?.gross_invoiced_minor)}</p></div><div className="rounded-2xl border p-4"><p className="text-[10px] font-black uppercase">Credits</p><p className="mt-2 text-xl font-black">{money(period?.credits_minor)}</p></div><div className="rounded-2xl border p-4"><p className="text-[10px] font-black uppercase">Net invoiced</p><p className="mt-2 text-xl font-black">{money(period?.net_invoiced_minor)}</p></div><div className="rounded-2xl border p-4"><p className="text-[10px] font-black uppercase">Collected</p><p className="mt-2 text-xl font-black">{money(period?.collected_minor)}</p></div><div className="rounded-2xl border p-4"><p className="text-[10px] font-black uppercase">Outstanding</p><p className="mt-2 text-xl font-black">{money(period?.outstanding_minor)}</p></div></div>
      </section>

      <section className="surface-card p-4"><div className="flex items-center gap-2"><TrendingUp size={18} /><div><p className="eyebrow-label">12-month trend</p><h2 className="font-black">Invoiced vs collected</h2></div></div><div className="mt-5 grid min-h-56 grid-cols-6 items-end gap-2 lg:grid-cols-12">{trend.map((x) => <div key={x.period} className="flex h-52 flex-col justify-end gap-1"><div className="flex flex-1 items-end justify-center gap-1"><div title={`Invoiced ${money(x.invoiced_minor)}`} className="w-3 rounded-t bg-[#174d43]" style={{ height: `${Math.max(3, (x.invoiced_minor / maxTrend) * 100)}%` }} /><div title={`Collected ${money(x.collected_minor)}`} className="w-3 rounded-t bg-[#d6ad3b]" style={{ height: `${Math.max(3, (x.collected_minor / maxTrend) * 100)}%` }} /></div><p className="text-center text-[8px] font-bold text-[var(--admin-muted)]">{x.label.replace(" 20", " '")}</p></div>)}</div><div className="mt-3 flex gap-4 text-[10px] font-bold"><span>■ Invoiced</span><span>■ Collected</span></div></section>

      <section className="surface-card p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><FileBarChart size={18} /><div><p className="eyebrow-label">Receivables</p><h2 className="font-black">Aging report</h2><p className="text-[10px] text-[var(--admin-muted)]">As of {aging?.as_of || "—"}</p></div></div><button className="btn-secondary" onClick={() => void downloadCsv()}><Download size={14} />Export invoices CSV</button></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{Object.entries(aging?.buckets || {}).map(([key, value]) => <div key={key} className="rounded-2xl border p-4"><p className="text-[10px] font-black uppercase">{label[key] || key}</p><p className="mt-2 text-xl font-black">{money(value.amount_minor)}</p><p className="text-[9px] text-[var(--admin-muted)]">{value.count} invoices</p></div>)}</div></section>

      <section className="surface-card overflow-hidden"><div className="border-b p-4"><h2 className="font-black">Outstanding invoices</h2></div><div className="overflow-x-auto"><table className="min-w-full text-left text-xs"><thead><tr><th className="p-3">Invoice</th><th className="p-3">Client</th><th className="p-3">Due</th><th className="p-3">Days overdue</th><th className="p-3">Bucket</th><th className="p-3">Outstanding</th></tr></thead><tbody>{(aging?.items || []).map((row) => <tr key={row.invoice.invoice_number} className="border-t"><td className="p-3 font-mono font-bold">{row.invoice.invoice_number}</td><td className="p-3 font-bold">{row.invoice.client_name}<p className="text-[9px] font-normal text-[var(--admin-muted)]">{row.invoice.recipient_email}</p></td><td className="p-3">{row.invoice.due_date}</td><td className="p-3">{row.days_overdue}</td><td className="p-3">{label[row.bucket] || row.bucket}</td><td className="p-3 font-black">{money(row.invoice.outstanding_minor)}</td></tr>)}{!aging?.items?.length ? <tr><td colSpan={6} className="p-8 text-center text-[var(--admin-muted)]">No outstanding sent invoices.</td></tr> : null}</tbody></table></div></section>

      <section className="surface-card p-4"><div className="flex items-center gap-2"><Search size={16} /><h2 className="font-black">Customer statement</h2></div><select className="input mt-3 max-w-xl" value={clientId} onChange={(e) => void loadStatement(e.target.value)}><option value="">Select a client</option>{clients.map((c) => <option key={c.id} value={c.id}>{c.name} — {c.email}</option>)}</select>{statement ? <div className="mt-4"><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border p-3"><p className="text-[10px] font-black uppercase">Invoiced</p><p className="mt-1 text-lg font-black">{money(statement.total_invoiced_minor)}</p></div><div className="rounded-2xl border p-3"><p className="text-[10px] font-black uppercase">Paid</p><p className="mt-1 text-lg font-black">{money(statement.total_paid_minor)}</p></div><div className="rounded-2xl border p-3"><p className="text-[10px] font-black uppercase">Balance</p><p className="mt-1 text-lg font-black">{money(statement.balance_minor)}</p></div></div><div className="mt-3 overflow-x-auto"><table className="min-w-full text-left text-xs"><thead><tr><th className="p-2">Invoice</th><th className="p-2">Due</th><th className="p-2">Total</th><th className="p-2">Paid</th><th className="p-2">Balance</th><th className="p-2">Status</th></tr></thead><tbody>{statement.items.map((x) => <tr key={x.invoice_number} className="border-t"><td className="p-2 font-mono font-bold">{x.invoice_number}</td><td className="p-2">{x.due_date}</td><td className="p-2">{money(x.total_minor)}</td><td className="p-2">{money(x.paid_minor)}</td><td className="p-2 font-black">{money(x.outstanding_minor)}</td><td className="p-2 uppercase">{x.status}</td></tr>)}</tbody></table></div></div> : null}</section>
    </div>}
  </ControlShell>;
}
