"use client";

import Link from "next/link";
import { ArrowLeft, CheckCircle2, CloudDownload, Loader2, Mail, RefreshCw, RotateCcw, ShieldCheck, TriangleAlert } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { API } from "../mail-types";

type Account = { id: string; provider: string; address: string; display_name: string; status: string; auth_type: string };
type Job = { id: string; destination: string; connected_account_id?: string | null; source_provider: string; source_username: string; status: string; folders_total: number; folders_done: number; messages_copied: number; bytes_copied: number; error?: string | null; created_at?: string | null; completed_at?: string | null };

async function api(path: string, init?: RequestInit) {
  return fetch(`${API}/webmail${path}`, { credentials: "include", ...init, headers: { "Content-Type": "application/json", ...(init?.headers || {}) } });
}
function bytes(value: number) { if (!value) return "0 B"; const u=["B","KB","MB","GB","TB"]; let n=value,i=0; while(n>=1024&&i<u.length-1){n/=1024;i++;} return `${n>=10||i===0?n.toFixed(0):n.toFixed(1)} ${u[i]}`; }
function provider(value: string) { const v=value.toLowerCase(); if(v==='google')return 'Google / Gmail'; if(v.includes('microsoft'))return 'Microsoft 365 / Outlook'; return value || 'External IMAP'; }

export default function MigrationCenterPage() {
  const [accounts,setAccounts]=useState<Account[]>([]); const [jobs,setJobs]=useState<Job[]>([]); const [destination,setDestination]=useState(""); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(""); const [error,setError]=useState(""); const [notice,setNotice]=useState("");
  const refresh=useCallback(async()=>{setLoading(true);setError("");try{const [a,j]=await Promise.all([api('/connected-accounts'),api('/migrations')]);if(a.status===401||j.status===401){window.location.assign('/webmail');return;}if(!a.ok||!j.ok)throw new Error('Unable to load Migration Center');const ap=await a.json();setAccounts(ap.items||[]);setDestination(String(ap.hosted?.address||''));setJobs((await j.json()).items||[]);}catch(cause){setError(cause instanceof Error?cause.message:'Unable to load Migration Center');}finally{setLoading(false);}},[]);
  useEffect(()=>{void refresh();},[refresh]);
  useEffect(()=>{if(!jobs.some(j=>['queued','running'].includes(j.status)))return;const timer=window.setInterval(()=>void refresh(),3000);return()=>window.clearInterval(timer);},[jobs,refresh]);
  const active=useMemo(()=>jobs.find(j=>['queued','running'].includes(j.status)),[jobs]);
  async function start(account:Account){setBusy(`start:${account.id}`);setError("");setNotice("");try{const r=await api(`/migrations/connected/${account.id}`,{method:'POST',body:'{}'});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.detail||'Unable to start migration');setNotice(p.already_running?'A migration is already running for this mailbox.':`Migration from ${account.address} has started. Source mail will not be deleted.`);await refresh();}catch(cause){setError(cause instanceof Error?cause.message:'Unable to start migration');}finally{setBusy("");}}
  async function resume(job:Job){setBusy(`resume:${job.id}`);setError("");try{const r=await api(`/migrations/${job.id}/resume`,{method:'POST',body:'{}'});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.detail||'Unable to resume migration');setNotice('Migration resumed. Already imported messages will be skipped.');await refresh();}catch(cause){setError(cause instanceof Error?cause.message:'Unable to resume migration');}finally{setBusy("");}}
  return <main className="min-h-screen bg-[#f6f8fc] text-[#202124] dark:bg-[#0f1418] dark:text-slate-100">
    <header className="sticky top-0 z-20 flex min-h-16 items-center justify-between gap-3 border-b border-slate-200 bg-white/95 px-4 backdrop-blur dark:border-white/10 dark:bg-[#111820]/95 sm:px-6"><div className="flex min-w-0 items-center gap-3"><Link href="/webmail" className="grid h-9 w-9 place-items-center rounded-full text-slate-500 hover:bg-slate-100 dark:hover:bg-white/10"><ArrowLeft size={18}/></Link><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#0c6f55] text-xs font-black text-white">iM</span><div><h1 className="text-base font-black">Migration Center</h1><p className="text-xs text-slate-500">Connected account → {destination||'Ithute business mailbox'}</p></div></div><button onClick={()=>void refresh()} className="grid h-9 w-9 place-items-center rounded-full text-slate-500 hover:bg-slate-100 dark:hover:bg-white/10"><RefreshCw size={16}/></button></header>
    <div className="mx-auto max-w-6xl space-y-5 px-4 py-5 sm:px-6">
      {error?<div className="flex gap-2 rounded-2xl border border-red-200 bg-red-50 p-3 text-sm text-red-700 dark:border-red-900/60 dark:bg-red-950/30 dark:text-red-200"><TriangleAlert size={17}/>{error}</div>:null}{notice?<div className="flex gap-2 rounded-2xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800 dark:border-emerald-900/60 dark:bg-emerald-950/30 dark:text-emerald-200"><CheckCircle2 size={17}/>{notice}</div>:null}
      <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm dark:border-white/10 dark:bg-[#141b20] sm:p-6"><div className="flex items-start gap-4"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-emerald-950 text-amber-300"><CloudDownload size={22}/></span><div><h2 className="text-xl font-black">Move old mail into your business mailbox</h2><p className="mt-1 max-w-3xl text-sm leading-6 text-slate-500">Use a persistent Google, Microsoft or IMAP account below. iMail copies folders and messages, keeps the source untouched, preserves common flags and skips duplicates when a migration is resumed.</p></div></div><div className="mt-4 flex items-start gap-2 rounded-2xl bg-emerald-50 p-3 text-xs leading-5 text-emerald-900 dark:bg-emerald-500/10 dark:text-emerald-200"><ShieldCheck size={16} className="mt-0.5 shrink-0"/>Destination is locked to the currently signed-in active Ithute mailbox. A browser request cannot choose another person's mailbox.</div></section>
      {loading?<div className="grid min-h-48 place-items-center"><Loader2 className="animate-spin text-[#0b57d0]" size={28}/></div>:<div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_380px]">
        <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm dark:border-white/10 dark:bg-[#141b20] sm:p-6"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-black">Connected sources</h2><p className="text-xs text-slate-500">OAuth accounts do not need their password entered again.</p></div><Mail size={20} className="text-[#0b57d0]"/></div><div className="space-y-3">{accounts.map(a=><div key={a.id} className="flex flex-col gap-3 rounded-2xl border border-slate-200 p-4 dark:border-white/10 sm:flex-row sm:items-center"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-slate-100 text-xs font-black dark:bg-white/10">{a.provider==='google'?'G':a.provider.includes('microsoft')?'M':'@'}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-black">{a.display_name||a.address}</p><p className="truncate text-xs text-slate-500">{a.address} · {provider(a.provider)} · {a.auth_type==='oauth'?'OAuth':'secure credential'}</p></div><button disabled={Boolean(active)||a.status!=='active'||busy===`start:${a.id}`} onClick={()=>void start(a)} className="inline-flex h-9 items-center justify-center gap-2 rounded-xl bg-[#0b57d0] px-3 text-xs font-black text-white disabled:opacity-40">{busy===`start:${a.id}`?<Loader2 size={14} className="animate-spin"/>:<CloudDownload size={14}/>} Import</button></div>)}{!accounts.length?<div className="rounded-2xl border border-dashed border-slate-200 p-6 text-center dark:border-white/10"><p className="font-black">No persistent source account yet</p><p className="mt-1 text-sm text-slate-500">Connect Google, Microsoft or another mailbox first.</p><Link href="/webmail/accounts" className="mt-3 inline-flex rounded-xl bg-[#0b57d0] px-4 py-2 text-xs font-black text-white">Connect account</Link></div>:null}</div><div className="mt-4 border-t border-slate-100 pt-4 dark:border-white/10"><p className="text-xs text-slate-500">Need a one-time App Password or custom IMAP migration?</p><Link href="/webmail/migrate" className="mt-2 inline-flex text-xs font-black text-[#0b57d0] hover:underline">Open advanced one-time migration</Link></div></section>
        <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm dark:border-white/10 dark:bg-[#141b20] sm:p-6"><h2 className="font-black">Migration history</h2><div className="mt-4 space-y-3">{jobs.map(j=>{const progress=j.folders_total?Math.round(j.folders_done/j.folders_total*100):0;return <div key={j.id} className="rounded-2xl border border-slate-200 p-3 dark:border-white/10"><div className="flex items-center justify-between gap-2"><p className="truncate text-xs font-black">{j.source_username}</p><span className={`rounded-full px-2 py-0.5 text-[9px] font-black uppercase ${j.status==='completed'?'bg-emerald-100 text-emerald-700':j.status==='failed'?'bg-red-100 text-red-700':'bg-blue-100 text-blue-700'}`}>{j.status}</span></div><p className="mt-1 text-[10px] text-slate-500">{provider(j.source_provider)} · {j.messages_copied.toLocaleString()} copied · {bytes(j.bytes_copied)}</p>{['queued','running'].includes(j.status)?<div className="mt-2 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-[#0b57d0]" style={{width:`${Math.max(4,progress)}%`}}/></div>:null}{j.error?<p className="mt-2 text-[10px] leading-4 text-red-600">{j.error}</p>:null}{j.connected_account_id&&['failed','completed'].includes(j.status)?<button onClick={()=>void resume(j)} disabled={busy===`resume:${j.id}`} className="mt-2 inline-flex items-center gap-1 text-[10px] font-black text-[#0b57d0]"><RotateCcw size={12}/> Resume safely</button>:null}</div>})}{!jobs.length?<p className="rounded-2xl border border-dashed border-slate-200 p-5 text-center text-xs text-slate-500 dark:border-white/10">No migrations yet.</p>:null}</div></section>
      </div>}
    </div>
  </main>;
}
