"""Phase 13 document, HSE and quality assurance.

Revision ID: 0014_phase13_assurance
Revises: 0013_phase11_commercial
"""
from alembic import op
import sqlalchemy as sa

revision = "0014_phase13_assurance"
down_revision = "0013_phase11_commercial"
branch_labels = None
depends_on = None

def upgrade() -> None:
    op.create_table("project_document_register", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("company_id", sa.Integer(), sa.ForeignKey("companies.id", ondelete="CASCADE"), nullable=False), sa.Column("branch_id", sa.Integer(), sa.ForeignKey("branches.id", ondelete="RESTRICT"), nullable=False), sa.Column("site_id", sa.Integer(), sa.ForeignKey("sites.id", ondelete="RESTRICT"), nullable=False), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False), sa.Column("document_id", sa.Integer(), sa.ForeignKey("documents.id", ondelete="RESTRICT"), nullable=False), sa.Column("document_number", sa.String(120), nullable=False), sa.Column("revision_code", sa.String(64), nullable=False), sa.Column("discipline", sa.String(80), nullable=False), sa.Column("title", sa.String(300), nullable=False), sa.Column("issue_date", sa.Date(), nullable=False), sa.Column("status", sa.String(24), nullable=False), sa.Column("supersedes_id", sa.Integer(), sa.ForeignKey("project_document_register.id", ondelete="SET NULL")), sa.Column("issued_to", sa.String(255)), sa.Column("notes", sa.Text()), sa.Column("registered_by", sa.String(255), nullable=False), sa.Column("registered_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("project_id", "document_number", "revision_code", name="uq_project_document_revision"))
    op.create_table("project_assurance_records", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("company_id", sa.Integer(), sa.ForeignKey("companies.id", ondelete="CASCADE"), nullable=False), sa.Column("branch_id", sa.Integer(), sa.ForeignKey("branches.id", ondelete="RESTRICT"), nullable=False), sa.Column("site_id", sa.Integer(), sa.ForeignKey("sites.id", ondelete="RESTRICT"), nullable=False), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False), sa.Column("parent_record_id", sa.Integer(), sa.ForeignKey("project_assurance_records.id", ondelete="SET NULL")), sa.Column("document_id", sa.Integer(), sa.ForeignKey("documents.id", ondelete="SET NULL")), sa.Column("record_number", sa.String(80), nullable=False), sa.Column("record_type", sa.String(48), nullable=False), sa.Column("title", sa.String(300), nullable=False), sa.Column("description", sa.Text(), nullable=False), sa.Column("priority", sa.String(24), nullable=False), sa.Column("record_date", sa.Date(), nullable=False), sa.Column("due_date", sa.Date()), sa.Column("status", sa.String(24), nullable=False), sa.Column("checklist", sa.JSON(), nullable=False), sa.Column("assigned_to", sa.String(255)), sa.Column("created_by", sa.String(255), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("submitted_at", sa.DateTime(timezone=True)), sa.Column("reviewed_by", sa.String(255)), sa.Column("reviewed_at", sa.DateTime(timezone=True)), sa.Column("review_comment", sa.Text()), sa.UniqueConstraint("company_id", "record_number", name="uq_project_assurance_number"))
    op.create_table("assurance_audit_events", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("company_id", sa.Integer(), sa.ForeignKey("companies.id", ondelete="CASCADE"), nullable=False), sa.Column("branch_id", sa.Integer(), sa.ForeignKey("branches.id", ondelete="SET NULL")), sa.Column("site_id", sa.Integer(), sa.ForeignKey("sites.id", ondelete="SET NULL")), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id", ondelete="SET NULL")), sa.Column("actor", sa.String(255), nullable=False), sa.Column("action", sa.String(100), nullable=False), sa.Column("entity_type", sa.String(80), nullable=False), sa.Column("entity_id", sa.String(100)), sa.Column("detail", sa.JSON(), nullable=False), sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False))
    for table, columns in {"project_document_register": ("company_id","branch_id","site_id","project_id","document_id","document_number","issue_date","status","supersedes_id"), "project_assurance_records": ("company_id","branch_id","site_id","project_id","parent_record_id","document_id","record_number","record_type","priority","record_date","due_date","status"), "assurance_audit_events": ("company_id","branch_id","site_id","project_id","action","entity_type","occurred_at")}.items():
        for column in columns: op.create_index(f"ix_{table}_{column}", table, [column])

def downgrade() -> None:
    for table in ("assurance_audit_events", "project_assurance_records", "project_document_register"):
        for index in [row["name"] for row in sa.inspect(op.get_bind()).get_indexes(table)]: op.drop_index(index, table_name=table)
        op.drop_table(table)
