"""Phase 15 HR development and compliance.

Revision ID: 0016_phase15_development
Revises: 0015_phase14_mobile
"""
from alembic import op
import sqlalchemy as sa
revision="0016_phase15_development";down_revision="0015_phase14_mobile";branch_labels=None;depends_on=None
def upgrade()->None:
 op.create_table("recruitment_candidates",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("company_id",sa.Integer(),sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("branch_id",sa.Integer(),sa.ForeignKey("branches.id",ondelete="SET NULL")),sa.Column("site_id",sa.Integer(),sa.ForeignKey("sites.id",ondelete="SET NULL")),sa.Column("candidate_number",sa.String(80),nullable=False),sa.Column("full_name",sa.String(240),nullable=False),sa.Column("phone",sa.String(64)),sa.Column("email",sa.String(255)),sa.Column("position",sa.String(160),nullable=False),sa.Column("status",sa.String(24),nullable=False),sa.Column("application_date",sa.Date(),nullable=False),sa.Column("cv_document_id",sa.Integer(),sa.ForeignKey("documents.id",ondelete="SET NULL")),sa.Column("notes",sa.Text()),sa.Column("created_by",sa.String(255),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("company_id","candidate_number",name="uq_recruitment_candidate_number"))
 op.create_table("employee_credentials",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("company_id",sa.Integer(),sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("employee_id",sa.Integer(),sa.ForeignKey("employees.id",ondelete="CASCADE"),nullable=False),sa.Column("credential_type",sa.String(80),nullable=False),sa.Column("reference_number",sa.String(120)),sa.Column("issuer",sa.String(180)),sa.Column("issue_date",sa.Date()),sa.Column("expiry_date",sa.Date()),sa.Column("status",sa.String(24),nullable=False),sa.Column("document_id",sa.Integer(),sa.ForeignKey("documents.id",ondelete="SET NULL")),sa.Column("notes",sa.Text()),sa.Column("recorded_by",sa.String(255),nullable=False),sa.Column("recorded_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("employee_id","credential_type","reference_number",name="uq_employee_credential_reference"))
 op.create_table("employee_training_records",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("company_id",sa.Integer(),sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("employee_id",sa.Integer(),sa.ForeignKey("employees.id",ondelete="CASCADE"),nullable=False),sa.Column("course_name",sa.String(240),nullable=False),sa.Column("provider",sa.String(180)),sa.Column("category",sa.String(80),nullable=False),sa.Column("start_date",sa.Date()),sa.Column("completion_date",sa.Date()),sa.Column("expiry_date",sa.Date()),sa.Column("cost",sa.Numeric(18,2),nullable=False),sa.Column("status",sa.String(24),nullable=False),sa.Column("certificate_document_id",sa.Integer(),sa.ForeignKey("documents.id",ondelete="SET NULL")),sa.Column("notes",sa.Text()),sa.Column("recorded_by",sa.String(255),nullable=False),sa.Column("recorded_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("employee_id","course_name","completion_date",name="uq_employee_training_completion"))
 op.create_table("employee_onboarding_items",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("company_id",sa.Integer(),sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("employee_id",sa.Integer(),sa.ForeignKey("employees.id",ondelete="CASCADE"),nullable=False),sa.Column("onboarding_type",sa.String(80),nullable=False),sa.Column("title",sa.String(240),nullable=False),sa.Column("due_date",sa.Date()),sa.Column("status",sa.String(24),nullable=False),sa.Column("document_id",sa.Integer(),sa.ForeignKey("documents.id",ondelete="SET NULL")),sa.Column("notes",sa.Text()),sa.Column("assigned_to",sa.String(255)),sa.Column("completed_by",sa.String(255)),sa.Column("completed_at",sa.DateTime(timezone=True)),sa.Column("created_by",sa.String(255),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("employee_id","title",name="uq_employee_onboarding_title"))
 op.create_table("employee_performance_reviews",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("company_id",sa.Integer(),sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("employee_id",sa.Integer(),sa.ForeignKey("employees.id",ondelete="CASCADE"),nullable=False),sa.Column("review_period_start",sa.Date(),nullable=False),sa.Column("review_period_end",sa.Date(),nullable=False),sa.Column("delivery_score",sa.Numeric(5,2),nullable=False),sa.Column("quality_score",sa.Numeric(5,2),nullable=False),sa.Column("safety_score",sa.Numeric(5,2),nullable=False),sa.Column("conduct_score",sa.Numeric(5,2),nullable=False),sa.Column("overall_score",sa.Numeric(5,2),nullable=False),sa.Column("development_plan",sa.Text()),sa.Column("status",sa.String(24),nullable=False),sa.Column("reviewed_by",sa.String(255),nullable=False),sa.Column("reviewed_at",sa.DateTime(timezone=True),nullable=False),sa.Column("acknowledged_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("employee_id","review_period_end",name="uq_employee_performance_period"))
 for table,columns in {"recruitment_candidates":("company_id","branch_id","site_id","candidate_number","position","status","application_date"),"employee_credentials":("company_id","employee_id","credential_type","expiry_date","status"),"employee_training_records":("company_id","employee_id","category","completion_date","expiry_date","status"),"employee_onboarding_items":("company_id","employee_id","onboarding_type","due_date","status"),"employee_performance_reviews":("company_id","employee_id","review_period_end","overall_score","status")}.items():
  for c in columns:op.create_index(f"ix_{table}_{c}",table,[c])
def downgrade()->None:
 for table in ("employee_performance_reviews","employee_onboarding_items","employee_training_records","employee_credentials","recruitment_candidates"):
  for index in [r["name"] for r in sa.inspect(op.get_bind()).get_indexes(table)]:op.drop_index(index,table_name=table)
  op.drop_table(table)
