"""Phase 18 finance and cash control.

Revision ID: 0019_phase18_finance
Revises: 0018_phase17_closeout
"""

from alembic import op
import sqlalchemy as sa


revision = "0019_phase18_finance"
down_revision = "0018_phase17_closeout"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table("financial_periods", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("company_id", sa.Integer(), sa.ForeignKey("companies.id", ondelete="CASCADE"), nullable=False), sa.Column("period_code", sa.String(32), nullable=False), sa.Column("name", sa.String(160), nullable=False), sa.Column("start_date", sa.Date(), nullable=False), sa.Column("end_date", sa.Date(), nullable=False), sa.Column("status", sa.String(24), nullable=False), sa.Column("closed_by", sa.String(255)), sa.Column("closed_at", sa.DateTime(timezone=True)), sa.Column("notes", sa.Text()), sa.Column("created_by", sa.String(255), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("company_id", "period_code", name="uq_financial_period_company_code"), sa.UniqueConstraint("company_id", "start_date", "end_date", name="uq_financial_period_dates"))
    op.create_table("chart_of_accounts", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("company_id", sa.Integer(), sa.ForeignKey("companies.id", ondelete="CASCADE"), nullable=False), sa.Column("account_code", sa.String(32), nullable=False), sa.Column("name", sa.String(180), nullable=False), sa.Column("account_type", sa.String(24), nullable=False), sa.Column("parent_account_id", sa.Integer(), sa.ForeignKey("chart_of_accounts.id", ondelete="SET NULL")), sa.Column("is_system", sa.Boolean(), nullable=False), sa.Column("is_active", sa.Boolean(), nullable=False), sa.Column("notes", sa.Text()), sa.Column("created_by", sa.String(255), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("company_id", "account_code", name="uq_chart_account_company_code"))
    op.create_table("finance_journals", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("company_id", sa.Integer(), sa.ForeignKey("companies.id", ondelete="CASCADE"), nullable=False), sa.Column("branch_id", sa.Integer(), sa.ForeignKey("branches.id", ondelete="RESTRICT"), nullable=False), sa.Column("site_id", sa.Integer(), sa.ForeignKey("sites.id", ondelete="SET NULL")), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id", ondelete="SET NULL")), sa.Column("cost_centre_id", sa.Integer(), sa.ForeignKey("cost_centres.id", ondelete="SET NULL")), sa.Column("period_id", sa.Integer(), sa.ForeignKey("financial_periods.id", ondelete="RESTRICT"), nullable=False), sa.Column("journal_number", sa.String(80), nullable=False), sa.Column("journal_date", sa.Date(), nullable=False), sa.Column("description", sa.String(300), nullable=False), sa.Column("source_type", sa.String(64)), sa.Column("source_reference", sa.String(160)), sa.Column("supporting_document_id", sa.Integer(), sa.ForeignKey("documents.id", ondelete="SET NULL")), sa.Column("status", sa.String(24), nullable=False), sa.Column("approval_request_id", sa.Integer(), sa.ForeignKey("approval_requests.id", ondelete="SET NULL")), sa.Column("notes", sa.Text()), sa.Column("prepared_by", sa.String(255), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("submitted_at", sa.DateTime(timezone=True)), sa.Column("approved_at", sa.DateTime(timezone=True)), sa.Column("posted_by", sa.String(255)), sa.Column("posted_at", sa.DateTime(timezone=True)), sa.UniqueConstraint("company_id", "journal_number", name="uq_finance_journal_company_number"))
    op.create_table("finance_journal_lines", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("company_id", sa.Integer(), sa.ForeignKey("companies.id", ondelete="CASCADE"), nullable=False), sa.Column("journal_id", sa.Integer(), sa.ForeignKey("finance_journals.id", ondelete="CASCADE"), nullable=False), sa.Column("line_number", sa.Integer(), nullable=False), sa.Column("account_id", sa.Integer(), sa.ForeignKey("chart_of_accounts.id", ondelete="RESTRICT"), nullable=False), sa.Column("description", sa.String(300)), sa.Column("debit", sa.Numeric(18, 2), nullable=False), sa.Column("credit", sa.Numeric(18, 2), nullable=False), sa.UniqueConstraint("journal_id", "line_number", name="uq_finance_journal_line_number"))
    op.create_table("supplier_invoices", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("company_id", sa.Integer(), sa.ForeignKey("companies.id", ondelete="CASCADE"), nullable=False), sa.Column("branch_id", sa.Integer(), sa.ForeignKey("branches.id", ondelete="RESTRICT"), nullable=False), sa.Column("site_id", sa.Integer(), sa.ForeignKey("sites.id", ondelete="SET NULL")), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id", ondelete="SET NULL")), sa.Column("cost_centre_id", sa.Integer(), sa.ForeignKey("cost_centres.id", ondelete="SET NULL")), sa.Column("supplier_id", sa.Integer(), sa.ForeignKey("suppliers.id", ondelete="RESTRICT"), nullable=False), sa.Column("purchase_order_id", sa.Integer(), sa.ForeignKey("purchase_orders.id", ondelete="SET NULL")), sa.Column("invoice_number", sa.String(80), nullable=False), sa.Column("supplier_invoice_reference", sa.String(160), nullable=False), sa.Column("invoice_date", sa.Date(), nullable=False), sa.Column("due_date", sa.Date()), sa.Column("amount", sa.Numeric(18, 2), nullable=False), sa.Column("paid_amount", sa.Numeric(18, 2), nullable=False), sa.Column("status", sa.String(24), nullable=False), sa.Column("invoice_document_id", sa.Integer(), sa.ForeignKey("documents.id", ondelete="SET NULL")), sa.Column("approval_request_id", sa.Integer(), sa.ForeignKey("approval_requests.id", ondelete="SET NULL")), sa.Column("notes", sa.Text()), sa.Column("prepared_by", sa.String(255), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("submitted_at", sa.DateTime(timezone=True)), sa.Column("approved_at", sa.DateTime(timezone=True)), sa.UniqueConstraint("company_id", "invoice_number", name="uq_supplier_invoice_company_number"), sa.UniqueConstraint("company_id", "supplier_id", "supplier_invoice_reference", name="uq_supplier_invoice_supplier_reference"))
    op.create_table("supplier_payments", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("company_id", sa.Integer(), sa.ForeignKey("companies.id", ondelete="CASCADE"), nullable=False), sa.Column("branch_id", sa.Integer(), sa.ForeignKey("branches.id", ondelete="RESTRICT"), nullable=False), sa.Column("site_id", sa.Integer(), sa.ForeignKey("sites.id", ondelete="SET NULL")), sa.Column("supplier_invoice_id", sa.Integer(), sa.ForeignKey("supplier_invoices.id", ondelete="RESTRICT"), nullable=False), sa.Column("payment_number", sa.String(80), nullable=False), sa.Column("requested_date", sa.Date(), nullable=False), sa.Column("amount", sa.Numeric(18, 2), nullable=False), sa.Column("payment_reference", sa.String(160)), sa.Column("status", sa.String(24), nullable=False), sa.Column("payment_document_id", sa.Integer(), sa.ForeignKey("documents.id", ondelete="SET NULL")), sa.Column("approval_request_id", sa.Integer(), sa.ForeignKey("approval_requests.id", ondelete="SET NULL")), sa.Column("notes", sa.Text()), sa.Column("requested_by", sa.String(255), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("submitted_at", sa.DateTime(timezone=True)), sa.Column("approved_at", sa.DateTime(timezone=True)), sa.Column("recorded_by", sa.String(255)), sa.Column("recorded_at", sa.DateTime(timezone=True)), sa.UniqueConstraint("company_id", "payment_number", name="uq_supplier_payment_company_number"))
    op.create_table("finance_audit_events", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("company_id", sa.Integer(), sa.ForeignKey("companies.id", ondelete="CASCADE"), nullable=False), sa.Column("branch_id", sa.Integer(), sa.ForeignKey("branches.id", ondelete="SET NULL")), sa.Column("site_id", sa.Integer(), sa.ForeignKey("sites.id", ondelete="SET NULL")), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id", ondelete="SET NULL")), sa.Column("actor", sa.String(255), nullable=False), sa.Column("action", sa.String(120), nullable=False), sa.Column("entity_type", sa.String(80), nullable=False), sa.Column("entity_id", sa.String(100), nullable=False), sa.Column("detail", sa.JSON(), nullable=False), sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False))
    for table, columns in {"financial_periods": ("company_id", "period_code", "start_date", "end_date", "status"), "chart_of_accounts": ("company_id", "account_code", "account_type", "parent_account_id", "is_active"), "finance_journals": ("company_id", "branch_id", "site_id", "project_id", "cost_centre_id", "period_id", "journal_number", "journal_date", "source_type", "supporting_document_id", "status", "approval_request_id"), "finance_journal_lines": ("company_id", "journal_id", "account_id"), "supplier_invoices": ("company_id", "branch_id", "site_id", "project_id", "cost_centre_id", "supplier_id", "purchase_order_id", "invoice_number", "supplier_invoice_reference", "invoice_date", "due_date", "status", "invoice_document_id", "approval_request_id"), "supplier_payments": ("company_id", "branch_id", "site_id", "supplier_invoice_id", "payment_number", "requested_date", "status", "payment_document_id", "approval_request_id"), "finance_audit_events": ("company_id", "branch_id", "site_id", "project_id", "action", "occurred_at")}.items():
        for column in columns:
            op.create_index(f"ix_{table}_{column}", table, [column])


def downgrade() -> None:
    for table in ("finance_audit_events", "supplier_payments", "supplier_invoices", "finance_journal_lines", "finance_journals", "chart_of_accounts", "financial_periods"):
        for index in [row["name"] for row in sa.inspect(op.get_bind()).get_indexes(table)]:
            op.drop_index(index, table_name=table)
        op.drop_table(table)
