"""Phase 19 programme and project controls.

Revision ID: 0020_phase19_programme
Revises: 0019_phase18_finance
"""

from alembic import op
import sqlalchemy as sa


revision = "0020_phase19_programme"
down_revision = "0019_phase18_finance"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table("programme_baselines", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("company_id", sa.Integer(), sa.ForeignKey("companies.id", ondelete="CASCADE"), nullable=False), sa.Column("branch_id", sa.Integer(), sa.ForeignKey("branches.id", ondelete="RESTRICT"), nullable=False), sa.Column("site_id", sa.Integer(), sa.ForeignKey("sites.id", ondelete="SET NULL")), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False), sa.Column("version", sa.Integer(), nullable=False), sa.Column("baseline_number", sa.String(80), nullable=False), sa.Column("name", sa.String(240), nullable=False), sa.Column("baseline_start", sa.Date(), nullable=False), sa.Column("baseline_finish", sa.Date(), nullable=False), sa.Column("status", sa.String(24), nullable=False), sa.Column("revision_reason", sa.Text()), sa.Column("supporting_document_id", sa.Integer(), sa.ForeignKey("documents.id", ondelete="SET NULL")), sa.Column("approval_request_id", sa.Integer(), sa.ForeignKey("approval_requests.id", ondelete="SET NULL")), sa.Column("prepared_by", sa.String(255), nullable=False), sa.Column("submitted_at", sa.DateTime(timezone=True)), sa.Column("approved_at", sa.DateTime(timezone=True)), sa.Column("superseded_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("project_id", "version", name="uq_programme_baseline_project_version"))
    op.create_table("programme_activities", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("company_id", sa.Integer(), sa.ForeignKey("companies.id", ondelete="CASCADE"), nullable=False), sa.Column("baseline_id", sa.Integer(), sa.ForeignKey("programme_baselines.id", ondelete="CASCADE"), nullable=False), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False), sa.Column("milestone_id", sa.Integer(), sa.ForeignKey("project_milestones.id", ondelete="SET NULL")), sa.Column("predecessor_activity_id", sa.Integer(), sa.ForeignKey("programme_activities.id", ondelete="SET NULL")), sa.Column("owner_employee_id", sa.Integer(), sa.ForeignKey("employees.id", ondelete="SET NULL")), sa.Column("wbs_code", sa.String(80), nullable=False), sa.Column("name", sa.String(300), nullable=False), sa.Column("planned_start", sa.Date(), nullable=False), sa.Column("planned_finish", sa.Date(), nullable=False), sa.Column("weight_pct", sa.Numeric(8, 3), nullable=False), sa.Column("is_milestone", sa.Boolean(), nullable=False), sa.Column("notes", sa.Text()), sa.Column("created_by", sa.String(255), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("baseline_id", "wbs_code", name="uq_programme_activity_baseline_wbs"))
    op.create_table("programme_activity_updates", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("company_id", sa.Integer(), sa.ForeignKey("companies.id", ondelete="CASCADE"), nullable=False), sa.Column("activity_id", sa.Integer(), sa.ForeignKey("programme_activities.id", ondelete="CASCADE"), nullable=False), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False), sa.Column("reporting_date", sa.Date(), nullable=False), sa.Column("progress_pct", sa.Numeric(8, 3), nullable=False), sa.Column("status", sa.String(24), nullable=False), sa.Column("actual_start", sa.Date()), sa.Column("actual_finish", sa.Date()), sa.Column("forecast_finish", sa.Date()), sa.Column("delay_reason", sa.Text()), sa.Column("evidence_document_id", sa.Integer(), sa.ForeignKey("documents.id", ondelete="SET NULL")), sa.Column("notes", sa.Text()), sa.Column("reported_by", sa.String(255), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("activity_id", "reporting_date", name="uq_programme_activity_update_date"))
    op.create_table("programme_lookahead_items", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("company_id", sa.Integer(), sa.ForeignKey("companies.id", ondelete="CASCADE"), nullable=False), sa.Column("branch_id", sa.Integer(), sa.ForeignKey("branches.id", ondelete="RESTRICT"), nullable=False), sa.Column("site_id", sa.Integer(), sa.ForeignKey("sites.id", ondelete="SET NULL")), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False), sa.Column("baseline_id", sa.Integer(), sa.ForeignKey("programme_baselines.id", ondelete="CASCADE"), nullable=False), sa.Column("activity_id", sa.Integer(), sa.ForeignKey("programme_activities.id", ondelete="SET NULL")), sa.Column("owner_employee_id", sa.Integer(), sa.ForeignKey("employees.id", ondelete="SET NULL")), sa.Column("title", sa.String(300), nullable=False), sa.Column("planned_start", sa.Date(), nullable=False), sa.Column("planned_finish", sa.Date(), nullable=False), sa.Column("status", sa.String(24), nullable=False), sa.Column("constraint", sa.Text()), sa.Column("evidence_document_id", sa.Integer(), sa.ForeignKey("documents.id", ondelete="SET NULL")), sa.Column("notes", sa.Text()), sa.Column("created_by", sa.String(255), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("programme_delay_events", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("company_id", sa.Integer(), sa.ForeignKey("companies.id", ondelete="CASCADE"), nullable=False), sa.Column("branch_id", sa.Integer(), sa.ForeignKey("branches.id", ondelete="RESTRICT"), nullable=False), sa.Column("site_id", sa.Integer(), sa.ForeignKey("sites.id", ondelete="SET NULL")), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False), sa.Column("baseline_id", sa.Integer(), sa.ForeignKey("programme_baselines.id", ondelete="SET NULL")), sa.Column("activity_id", sa.Integer(), sa.ForeignKey("programme_activities.id", ondelete="SET NULL")), sa.Column("delay_number", sa.String(80), nullable=False), sa.Column("category", sa.String(80), nullable=False), sa.Column("responsible_party", sa.String(40), nullable=False), sa.Column("title", sa.String(300), nullable=False), sa.Column("event_date", sa.Date(), nullable=False), sa.Column("expected_days", sa.Integer(), nullable=False), sa.Column("notice_due_date", sa.Date()), sa.Column("status", sa.String(24), nullable=False), sa.Column("description", sa.Text()), sa.Column("evidence_document_id", sa.Integer(), sa.ForeignKey("documents.id", ondelete="SET NULL")), sa.Column("recorded_by", sa.String(255), nullable=False), sa.Column("raised_at", sa.DateTime(timezone=True)), sa.Column("closed_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("company_id", "delay_number", name="uq_programme_delay_company_number"))
    op.create_table("planning_audit_events", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("company_id", sa.Integer(), sa.ForeignKey("companies.id", ondelete="CASCADE"), nullable=False), sa.Column("branch_id", sa.Integer(), sa.ForeignKey("branches.id", ondelete="SET NULL")), sa.Column("site_id", sa.Integer(), sa.ForeignKey("sites.id", ondelete="SET NULL")), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id", ondelete="SET NULL")), sa.Column("actor", sa.String(255), nullable=False), sa.Column("action", sa.String(120), nullable=False), sa.Column("entity_type", sa.String(80), nullable=False), sa.Column("entity_id", sa.String(100), nullable=False), sa.Column("detail", sa.JSON(), nullable=False), sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False))
    indexes = {
        "programme_baselines": ("company_id", "branch_id", "site_id", "project_id", "baseline_number", "baseline_finish", "status", "supporting_document_id", "approval_request_id"),
        "programme_activities": ("company_id", "baseline_id", "project_id", "milestone_id", "predecessor_activity_id", "owner_employee_id", "planned_start", "planned_finish"),
        "programme_activity_updates": ("company_id", "activity_id", "project_id", "reporting_date", "status", "forecast_finish", "evidence_document_id"),
        "programme_lookahead_items": ("company_id", "branch_id", "site_id", "project_id", "baseline_id", "activity_id", "owner_employee_id", "planned_start", "planned_finish", "status", "evidence_document_id"),
        "programme_delay_events": ("company_id", "branch_id", "site_id", "project_id", "baseline_id", "activity_id", "delay_number", "category", "responsible_party", "event_date", "notice_due_date", "status", "evidence_document_id"),
        "planning_audit_events": ("company_id", "branch_id", "site_id", "project_id", "action", "occurred_at"),
    }
    for table, columns in indexes.items():
        for column in columns:
            op.create_index(f"ix_{table}_{column}", table, [column])


def downgrade() -> None:
    for table in ("planning_audit_events", "programme_delay_events", "programme_lookahead_items", "programme_activity_updates", "programme_activities", "programme_baselines"):
        for index in [row["name"] for row in sa.inspect(op.get_bind()).get_indexes(table)]:
            op.drop_index(index, table_name=table)
        op.drop_table(table)
