"""Phase 20 resource planning and capacity control.

Revision ID: 0021_phase20_resources
Revises: 0020_phase19_programme
"""

from alembic import op
import sqlalchemy as sa


revision = "0021_phase20_resources"
down_revision = "0020_phase19_programme"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table("resource_plans", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("company_id", sa.Integer(), sa.ForeignKey("companies.id", ondelete="CASCADE"), nullable=False), sa.Column("branch_id", sa.Integer(), sa.ForeignKey("branches.id", ondelete="RESTRICT"), nullable=False), sa.Column("site_id", sa.Integer(), sa.ForeignKey("sites.id", ondelete="SET NULL")), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False), sa.Column("programme_baseline_id", sa.Integer(), sa.ForeignKey("programme_baselines.id", ondelete="SET NULL")), sa.Column("version", sa.Integer(), nullable=False), sa.Column("plan_number", sa.String(80), nullable=False), sa.Column("name", sa.String(240), nullable=False), sa.Column("horizon_start", sa.Date(), nullable=False), sa.Column("horizon_finish", sa.Date(), nullable=False), sa.Column("status", sa.String(24), nullable=False), sa.Column("revision_reason", sa.Text()), sa.Column("supporting_document_id", sa.Integer(), sa.ForeignKey("documents.id", ondelete="SET NULL")), sa.Column("approval_request_id", sa.Integer(), sa.ForeignKey("approval_requests.id", ondelete="SET NULL")), sa.Column("prepared_by", sa.String(255), nullable=False), sa.Column("submitted_at", sa.DateTime(timezone=True)), sa.Column("approved_at", sa.DateTime(timezone=True)), sa.Column("superseded_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("project_id", "version", name="uq_resource_plan_project_version"))
    op.create_table("resource_plan_items", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("company_id", sa.Integer(), sa.ForeignKey("companies.id", ondelete="CASCADE"), nullable=False), sa.Column("branch_id", sa.Integer(), sa.ForeignKey("branches.id", ondelete="RESTRICT"), nullable=False), sa.Column("site_id", sa.Integer(), sa.ForeignKey("sites.id", ondelete="SET NULL")), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False), sa.Column("plan_id", sa.Integer(), sa.ForeignKey("resource_plans.id", ondelete="CASCADE"), nullable=False), sa.Column("activity_id", sa.Integer(), sa.ForeignKey("programme_activities.id", ondelete="SET NULL")), sa.Column("employee_id", sa.Integer(), sa.ForeignKey("employees.id", ondelete="SET NULL")), sa.Column("asset_id", sa.Integer(), sa.ForeignKey("fleet_assets.id", ondelete="SET NULL")), sa.Column("stock_item_id", sa.Integer(), sa.ForeignKey("stock_items.id", ondelete="SET NULL")), sa.Column("line_number", sa.Integer(), nullable=False), sa.Column("resource_type", sa.String(32), nullable=False), sa.Column("description", sa.String(300), nullable=False), sa.Column("quantity", sa.Numeric(18, 3), nullable=False), sa.Column("unit", sa.String(40), nullable=False), sa.Column("allocation_pct", sa.Numeric(8, 3), nullable=False), sa.Column("planned_from", sa.Date(), nullable=False), sa.Column("planned_to", sa.Date(), nullable=False), sa.Column("is_critical", sa.Boolean(), nullable=False), sa.Column("supporting_document_id", sa.Integer(), sa.ForeignKey("documents.id", ondelete="SET NULL")), sa.Column("notes", sa.Text()), sa.Column("created_by", sa.String(255), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("plan_id", "line_number", name="uq_resource_plan_item_number"))
    op.create_table("resource_requests", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("company_id", sa.Integer(), sa.ForeignKey("companies.id", ondelete="CASCADE"), nullable=False), sa.Column("branch_id", sa.Integer(), sa.ForeignKey("branches.id", ondelete="RESTRICT"), nullable=False), sa.Column("site_id", sa.Integer(), sa.ForeignKey("sites.id", ondelete="SET NULL")), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False), sa.Column("plan_item_id", sa.Integer(), sa.ForeignKey("resource_plan_items.id", ondelete="RESTRICT"), nullable=False), sa.Column("request_number", sa.String(80), nullable=False), sa.Column("request_type", sa.String(40), nullable=False), sa.Column("needed_by", sa.Date(), nullable=False), sa.Column("quantity", sa.Numeric(18, 3), nullable=False), sa.Column("status", sa.String(24), nullable=False), sa.Column("justification", sa.Text()), sa.Column("supporting_document_id", sa.Integer(), sa.ForeignKey("documents.id", ondelete="SET NULL")), sa.Column("fulfilment_document_id", sa.Integer(), sa.ForeignKey("documents.id", ondelete="SET NULL")), sa.Column("approval_request_id", sa.Integer(), sa.ForeignKey("approval_requests.id", ondelete="SET NULL")), sa.Column("requested_by", sa.String(255), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("submitted_at", sa.DateTime(timezone=True)), sa.Column("approved_at", sa.DateTime(timezone=True)), sa.Column("fulfilled_by", sa.String(255)), sa.Column("fulfilled_at", sa.DateTime(timezone=True)), sa.UniqueConstraint("company_id", "request_number", name="uq_resource_request_company_number"))
    op.create_table("resource_audit_events", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("company_id", sa.Integer(), sa.ForeignKey("companies.id", ondelete="CASCADE"), nullable=False), sa.Column("branch_id", sa.Integer(), sa.ForeignKey("branches.id", ondelete="SET NULL")), sa.Column("site_id", sa.Integer(), sa.ForeignKey("sites.id", ondelete="SET NULL")), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id", ondelete="SET NULL")), sa.Column("actor", sa.String(255), nullable=False), sa.Column("action", sa.String(120), nullable=False), sa.Column("entity_type", sa.String(80), nullable=False), sa.Column("entity_id", sa.String(100), nullable=False), sa.Column("detail", sa.JSON(), nullable=False), sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False))
    indexes = {
        "resource_plans": ("company_id", "branch_id", "site_id", "project_id", "programme_baseline_id", "plan_number", "horizon_start", "horizon_finish", "status", "supporting_document_id", "approval_request_id"),
        "resource_plan_items": ("company_id", "branch_id", "site_id", "project_id", "plan_id", "activity_id", "employee_id", "asset_id", "stock_item_id", "resource_type", "planned_from", "planned_to", "supporting_document_id"),
        "resource_requests": ("company_id", "branch_id", "site_id", "project_id", "plan_item_id", "request_number", "request_type", "needed_by", "status", "supporting_document_id", "fulfilment_document_id", "approval_request_id"),
        "resource_audit_events": ("company_id", "branch_id", "site_id", "project_id", "action", "occurred_at"),
    }
    for table, columns in indexes.items():
        for column in columns:
            op.create_index(f"ix_{table}_{column}", table, [column])


def downgrade() -> None:
    for table in ("resource_audit_events", "resource_requests", "resource_plan_items", "resource_plans"):
        for index in [row["name"] for row in sa.inspect(op.get_bind()).get_indexes(table)]:
            op.drop_index(index, table_name=table)
        op.drop_table(table)
