"""Phase 21 project communications and stakeholder control.

Revision ID: 0022_phase21_comms
Revises: 0021_phase20_resources
"""

from alembic import op
import sqlalchemy as sa

revision = "0022_phase21_comms"
down_revision = "0021_phase20_resources"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table("project_stakeholders", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("company_id", sa.Integer(), sa.ForeignKey("companies.id", ondelete="CASCADE"), nullable=False), sa.Column("branch_id", sa.Integer(), sa.ForeignKey("branches.id", ondelete="RESTRICT"), nullable=False), sa.Column("site_id", sa.Integer(), sa.ForeignKey("sites.id", ondelete="SET NULL")), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False), sa.Column("stakeholder_number", sa.String(80), nullable=False), sa.Column("organisation", sa.String(240), nullable=False), sa.Column("contact_name", sa.String(240), nullable=False), sa.Column("stakeholder_role", sa.String(48), nullable=False), sa.Column("email", sa.String(320)), sa.Column("phone", sa.String(80)), sa.Column("notes", sa.Text()), sa.Column("is_active", sa.Boolean(), nullable=False), sa.Column("created_by", sa.String(255), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("project_id", "organisation", "contact_name", name="uq_project_stakeholder_contact"))
    op.create_table("project_correspondence", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("company_id", sa.Integer(), sa.ForeignKey("companies.id", ondelete="CASCADE"), nullable=False), sa.Column("branch_id", sa.Integer(), sa.ForeignKey("branches.id", ondelete="RESTRICT"), nullable=False), sa.Column("site_id", sa.Integer(), sa.ForeignKey("sites.id", ondelete="SET NULL")), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False), sa.Column("stakeholder_id", sa.Integer(), sa.ForeignKey("project_stakeholders.id", ondelete="SET NULL")), sa.Column("correspondence_number", sa.String(80), nullable=False), sa.Column("direction", sa.String(16), nullable=False), sa.Column("classification", sa.String(24), nullable=False), sa.Column("correspondence_type", sa.String(40), nullable=False), sa.Column("subject", sa.String(300), nullable=False), sa.Column("external_reference", sa.String(160)), sa.Column("correspondence_date", sa.Date(), nullable=False), sa.Column("response_due_date", sa.Date()), sa.Column("status", sa.String(24), nullable=False), sa.Column("correspondence_document_id", sa.Integer(), sa.ForeignKey("documents.id", ondelete="SET NULL")), sa.Column("response_document_id", sa.Integer(), sa.ForeignKey("documents.id", ondelete="SET NULL")), sa.Column("dispatch_evidence_document_id", sa.Integer(), sa.ForeignKey("documents.id", ondelete="SET NULL")), sa.Column("approval_request_id", sa.Integer(), sa.ForeignKey("approval_requests.id", ondelete="SET NULL")), sa.Column("notes", sa.Text()), sa.Column("prepared_by", sa.String(255), nullable=False), sa.Column("submitted_at", sa.DateTime(timezone=True)), sa.Column("approved_at", sa.DateTime(timezone=True)), sa.Column("recorded_at", sa.DateTime(timezone=True)), sa.Column("closed_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("company_id", "correspondence_number", name="uq_project_correspondence_number"))
    op.create_table("project_meetings", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("company_id", sa.Integer(), sa.ForeignKey("companies.id", ondelete="CASCADE"), nullable=False), sa.Column("branch_id", sa.Integer(), sa.ForeignKey("branches.id", ondelete="RESTRICT"), nullable=False), sa.Column("site_id", sa.Integer(), sa.ForeignKey("sites.id", ondelete="SET NULL")), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False), sa.Column("meeting_number", sa.String(80), nullable=False), sa.Column("meeting_type", sa.String(48), nullable=False), sa.Column("title", sa.String(300), nullable=False), sa.Column("meeting_date", sa.Date(), nullable=False), sa.Column("status", sa.String(24), nullable=False), sa.Column("minutes_document_id", sa.Integer(), sa.ForeignKey("documents.id", ondelete="SET NULL")), sa.Column("approval_request_id", sa.Integer(), sa.ForeignKey("approval_requests.id", ondelete="SET NULL")), sa.Column("notes", sa.Text()), sa.Column("prepared_by", sa.String(255), nullable=False), sa.Column("submitted_at", sa.DateTime(timezone=True)), sa.Column("approved_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("company_id", "meeting_number", name="uq_project_meeting_number"))
    op.create_table("meeting_actions", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("company_id", sa.Integer(), sa.ForeignKey("companies.id", ondelete="CASCADE"), nullable=False), sa.Column("branch_id", sa.Integer(), sa.ForeignKey("branches.id", ondelete="RESTRICT"), nullable=False), sa.Column("site_id", sa.Integer(), sa.ForeignKey("sites.id", ondelete="SET NULL")), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False), sa.Column("meeting_id", sa.Integer(), sa.ForeignKey("project_meetings.id", ondelete="CASCADE"), nullable=False), sa.Column("action_number", sa.Integer(), nullable=False), sa.Column("title", sa.String(300), nullable=False), sa.Column("owner_employee_id", sa.Integer(), sa.ForeignKey("employees.id", ondelete="SET NULL")), sa.Column("due_date", sa.Date()), sa.Column("status", sa.String(24), nullable=False), sa.Column("evidence_document_id", sa.Integer(), sa.ForeignKey("documents.id", ondelete="SET NULL")), sa.Column("completion_note", sa.Text()), sa.Column("completed_by", sa.String(255)), sa.Column("completed_at", sa.DateTime(timezone=True)), sa.Column("verified_by", sa.String(255)), sa.Column("verified_at", sa.DateTime(timezone=True)), sa.Column("created_by", sa.String(255), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("meeting_id", "action_number", name="uq_meeting_action_number"))
    op.create_table("communication_audit_events", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("company_id", sa.Integer(), sa.ForeignKey("companies.id", ondelete="CASCADE"), nullable=False), sa.Column("branch_id", sa.Integer(), sa.ForeignKey("branches.id", ondelete="SET NULL")), sa.Column("site_id", sa.Integer(), sa.ForeignKey("sites.id", ondelete="SET NULL")), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id", ondelete="SET NULL")), sa.Column("actor", sa.String(255), nullable=False), sa.Column("action", sa.String(120), nullable=False), sa.Column("entity_type", sa.String(80), nullable=False), sa.Column("entity_id", sa.String(100), nullable=False), sa.Column("detail", sa.JSON(), nullable=False), sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False))
    for table, columns in {"project_stakeholders":("company_id","branch_id","site_id","project_id","stakeholder_number","stakeholder_role","is_active"), "project_correspondence":("company_id","branch_id","site_id","project_id","stakeholder_id","correspondence_number","direction","classification","correspondence_type","correspondence_date","response_due_date","status","approval_request_id"), "project_meetings":("company_id","branch_id","site_id","project_id","meeting_number","meeting_type","meeting_date","status","approval_request_id"), "meeting_actions":("company_id","branch_id","site_id","project_id","meeting_id","owner_employee_id","due_date","status"), "communication_audit_events":("company_id","branch_id","site_id","project_id","action","occurred_at")}.items():
        for column in columns: op.create_index(f"ix_{table}_{column}", table, [column])


def downgrade() -> None:
    for table in ("communication_audit_events", "meeting_actions", "project_meetings", "project_correspondence", "project_stakeholders"):
        for index in [row["name"] for row in sa.inspect(op.get_bind()).get_indexes(table)]: op.drop_index(index, table_name=table)
        op.drop_table(table)
