"""Phase 22 integrated compliance and policy control.

Revision ID: 0023_phase22_compliance
Revises: 0022_phase21_comms
"""
from alembic import op
import sqlalchemy as sa

revision = "0023_phase22_compliance"
down_revision = "0022_phase21_comms"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table("compliance_policies",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("company_id",sa.Integer(),sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("branch_id",sa.Integer(),sa.ForeignKey("branches.id",ondelete="RESTRICT"),nullable=False),sa.Column("site_id",sa.Integer(),sa.ForeignKey("sites.id",ondelete="SET NULL")),sa.Column("project_id",sa.Integer(),sa.ForeignKey("projects.id",ondelete="CASCADE"),nullable=False),sa.Column("policy_number",sa.String(80),nullable=False),sa.Column("policy_code",sa.String(80),nullable=False),sa.Column("version",sa.Integer(),nullable=False),sa.Column("title",sa.String(300),nullable=False),sa.Column("category",sa.String(48),nullable=False),sa.Column("effective_date",sa.Date(),nullable=False),sa.Column("review_due_date",sa.Date()),sa.Column("status",sa.String(24),nullable=False),sa.Column("policy_document_id",sa.Integer(),sa.ForeignKey("documents.id",ondelete="SET NULL")),sa.Column("approval_request_id",sa.Integer(),sa.ForeignKey("approval_requests.id",ondelete="SET NULL")),sa.Column("notes",sa.Text()),sa.Column("prepared_by",sa.String(255),nullable=False),sa.Column("submitted_at",sa.DateTime(timezone=True)),sa.Column("approved_at",sa.DateTime(timezone=True)),sa.Column("superseded_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("project_id","policy_code","version",name="uq_compliance_policy_version"))
    op.create_table("compliance_obligations",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("company_id",sa.Integer(),sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("branch_id",sa.Integer(),sa.ForeignKey("branches.id",ondelete="RESTRICT"),nullable=False),sa.Column("site_id",sa.Integer(),sa.ForeignKey("sites.id",ondelete="SET NULL")),sa.Column("project_id",sa.Integer(),sa.ForeignKey("projects.id",ondelete="CASCADE"),nullable=False),sa.Column("policy_id",sa.Integer(),sa.ForeignKey("compliance_policies.id",ondelete="SET NULL")),sa.Column("obligation_number",sa.String(80),nullable=False),sa.Column("source_type",sa.String(40),nullable=False),sa.Column("source_reference",sa.String(240),nullable=False),sa.Column("title",sa.String(300),nullable=False),sa.Column("owner_employee_id",sa.Integer(),sa.ForeignKey("employees.id",ondelete="SET NULL")),sa.Column("next_due_date",sa.Date(),nullable=False),sa.Column("recurrence_days",sa.Integer()),sa.Column("status",sa.String(24),nullable=False),sa.Column("evidence_document_id",sa.Integer(),sa.ForeignKey("documents.id",ondelete="SET NULL")),sa.Column("notes",sa.Text()),sa.Column("created_by",sa.String(255),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("company_id","obligation_number",name="uq_compliance_obligation_number"))
    op.create_table("compliance_reviews",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("company_id",sa.Integer(),sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("branch_id",sa.Integer(),sa.ForeignKey("branches.id",ondelete="RESTRICT"),nullable=False),sa.Column("site_id",sa.Integer(),sa.ForeignKey("sites.id",ondelete="SET NULL")),sa.Column("project_id",sa.Integer(),sa.ForeignKey("projects.id",ondelete="CASCADE"),nullable=False),sa.Column("obligation_id",sa.Integer(),sa.ForeignKey("compliance_obligations.id",ondelete="CASCADE"),nullable=False),sa.Column("review_number",sa.String(80),nullable=False),sa.Column("review_type",sa.String(40),nullable=False),sa.Column("review_date",sa.Date(),nullable=False),sa.Column("result",sa.String(24),nullable=False),sa.Column("status",sa.String(24),nullable=False),sa.Column("evidence_document_id",sa.Integer(),sa.ForeignKey("documents.id",ondelete="SET NULL")),sa.Column("finding",sa.Text()),sa.Column("corrective_action",sa.Text()),sa.Column("approval_request_id",sa.Integer(),sa.ForeignKey("approval_requests.id",ondelete="SET NULL")),sa.Column("prepared_by",sa.String(255),nullable=False),sa.Column("submitted_at",sa.DateTime(timezone=True)),sa.Column("approved_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("obligation_id","review_date","review_type",name="uq_compliance_review_day"))
    op.create_table("compliance_audit_events",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("company_id",sa.Integer(),sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("branch_id",sa.Integer(),sa.ForeignKey("branches.id",ondelete="SET NULL")),sa.Column("site_id",sa.Integer(),sa.ForeignKey("sites.id",ondelete="SET NULL")),sa.Column("project_id",sa.Integer(),sa.ForeignKey("projects.id",ondelete="SET NULL")),sa.Column("actor",sa.String(255),nullable=False),sa.Column("action",sa.String(120),nullable=False),sa.Column("entity_type",sa.String(80),nullable=False),sa.Column("entity_id",sa.String(100),nullable=False),sa.Column("detail",sa.JSON(),nullable=False),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False))
    for table,columns in {"compliance_policies":("company_id","branch_id","site_id","project_id","policy_number","policy_code","category","effective_date","review_due_date","status","approval_request_id"),"compliance_obligations":("company_id","branch_id","site_id","project_id","policy_id","obligation_number","source_type","owner_employee_id","next_due_date","status"),"compliance_reviews":("company_id","branch_id","site_id","project_id","obligation_id","review_number","review_type","review_date","result","status","approval_request_id"),"compliance_audit_events":("company_id","branch_id","site_id","project_id","action","occurred_at")}.items():
        for column in columns: op.create_index(f"ix_{table}_{column}",table,[column])


def downgrade() -> None:
    for table in ("compliance_audit_events","compliance_reviews","compliance_obligations","compliance_policies"):
        for index in [row["name"] for row in sa.inspect(op.get_bind()).get_indexes(table)]: op.drop_index(index,table_name=table)
        op.drop_table(table)
