"""Phase 23 project data quality and readiness assurance.
Revision ID: 0024_phase23_data_quality
Revises: 0023_phase22_compliance
"""
from alembic import op
import sqlalchemy as sa
revision = "0024_phase23_data_quality"
down_revision = "0023_phase22_compliance"
branch_labels = None
depends_on = None
def upgrade()->None:
 op.create_table("data_quality_runs",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("company_id",sa.Integer(),sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("branch_id",sa.Integer(),sa.ForeignKey("branches.id",ondelete="RESTRICT"),nullable=False),sa.Column("site_id",sa.Integer(),sa.ForeignKey("sites.id",ondelete="SET NULL")),sa.Column("project_id",sa.Integer(),sa.ForeignKey("projects.id",ondelete="CASCADE"),nullable=False),sa.Column("run_number",sa.String(80),nullable=False),sa.Column("run_date",sa.Date(),nullable=False),sa.Column("sequence",sa.Integer(),nullable=False),sa.Column("score_pct",sa.Integer(),nullable=False),sa.Column("status",sa.String(24),nullable=False),sa.Column("checks",sa.JSON(),nullable=False),sa.Column("source_activity_count",sa.Integer(),nullable=False),sa.Column("run_by",sa.String(255),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("project_id","run_date","sequence",name="uq_data_quality_run_day"))
 op.create_table("data_quality_findings",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("company_id",sa.Integer(),sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("branch_id",sa.Integer(),sa.ForeignKey("branches.id",ondelete="RESTRICT"),nullable=False),sa.Column("site_id",sa.Integer(),sa.ForeignKey("sites.id",ondelete="SET NULL")),sa.Column("project_id",sa.Integer(),sa.ForeignKey("projects.id",ondelete="CASCADE"),nullable=False),sa.Column("run_id",sa.Integer(),sa.ForeignKey("data_quality_runs.id",ondelete="CASCADE"),nullable=False),sa.Column("check_code",sa.String(80),nullable=False),sa.Column("severity",sa.String(24),nullable=False),sa.Column("message",sa.Text(),nullable=False),sa.Column("status",sa.String(24),nullable=False),sa.Column("remediation_document_id",sa.Integer(),sa.ForeignKey("documents.id",ondelete="SET NULL")),sa.Column("remediation_note",sa.Text()),sa.Column("remediated_by",sa.String(255)),sa.Column("remediated_at",sa.DateTime(timezone=True)),sa.Column("verified_by",sa.String(255)),sa.Column("verified_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("run_id","check_code",name="uq_data_quality_finding_check"))
 op.create_table("data_quality_audit_events",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("company_id",sa.Integer(),sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("branch_id",sa.Integer(),sa.ForeignKey("branches.id",ondelete="SET NULL")),sa.Column("site_id",sa.Integer(),sa.ForeignKey("sites.id",ondelete="SET NULL")),sa.Column("project_id",sa.Integer(),sa.ForeignKey("projects.id",ondelete="SET NULL")),sa.Column("actor",sa.String(255),nullable=False),sa.Column("action",sa.String(120),nullable=False),sa.Column("entity_type",sa.String(80),nullable=False),sa.Column("entity_id",sa.String(100),nullable=False),sa.Column("detail",sa.JSON(),nullable=False),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False))
 for table,cols in {"data_quality_runs":("company_id","branch_id","site_id","project_id","run_number","run_date","status"),"data_quality_findings":("company_id","branch_id","site_id","project_id","run_id","check_code","severity","status"),"data_quality_audit_events":("company_id","branch_id","site_id","project_id","action","occurred_at")}.items():
  for col in cols:op.create_index(f"ix_{table}_{col}",table,[col])
def downgrade()->None:
 for table in ("data_quality_audit_events","data_quality_findings","data_quality_runs"):
  for idx in [r["name"] for r in sa.inspect(op.get_bind()).get_indexes(table)]:op.drop_index(idx,table_name=table)
  op.drop_table(table)
