"""Phase 28 environmental and sustainability control."""
from alembic import op
import sqlalchemy as sa
revision="0029_phase28_environment"
down_revision="0028_phase27_knowledge"
branch_labels=None
depends_on=None
def upgrade():
 op.create_table("environmental_plans",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("company_id",sa.Integer(),sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("project_id",sa.Integer(),sa.ForeignKey("projects.id",ondelete="CASCADE"),nullable=False),sa.Column("branch_id",sa.Integer(),sa.ForeignKey("branches.id",ondelete="RESTRICT"),nullable=False),sa.Column("site_id",sa.Integer(),sa.ForeignKey("sites.id",ondelete="RESTRICT"),nullable=False),sa.Column("plan_number",sa.String(80),nullable=False),sa.Column("title",sa.String(300),nullable=False),sa.Column("aspects",sa.Text(),nullable=False),sa.Column("controls",sa.Text(),nullable=False),sa.Column("review_due_date",sa.Date()),sa.Column("status",sa.String(24),nullable=False),sa.Column("document_id",sa.Integer(),sa.ForeignKey("documents.id",ondelete="SET NULL")),sa.Column("prepared_by",sa.String(255),nullable=False),sa.Column("submitted_at",sa.DateTime(timezone=True)),sa.Column("approved_by",sa.String(255)),sa.Column("approved_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("company_id","plan_number",name="uq_environment_plan_number"),sa.UniqueConstraint("project_id","title",name="uq_environment_project_title"))
 op.create_table("environmental_waste_records",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("company_id",sa.Integer(),sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("project_id",sa.Integer(),sa.ForeignKey("projects.id",ondelete="CASCADE"),nullable=False),sa.Column("branch_id",sa.Integer(),sa.ForeignKey("branches.id",ondelete="RESTRICT"),nullable=False),sa.Column("site_id",sa.Integer(),sa.ForeignKey("sites.id",ondelete="RESTRICT"),nullable=False),sa.Column("waste_number",sa.String(80),nullable=False),sa.Column("record_date",sa.Date(),nullable=False),sa.Column("waste_stream",sa.String(48),nullable=False),sa.Column("quantity",sa.Numeric(14,2),nullable=False),sa.Column("unit",sa.String(24),nullable=False),sa.Column("destination",sa.String(300),nullable=False),sa.Column("carrier_reference",sa.String(120)),sa.Column("hazardous",sa.Boolean(),nullable=False),sa.Column("document_id",sa.Integer(),sa.ForeignKey("documents.id",ondelete="SET NULL")),sa.Column("status",sa.String(24),nullable=False),sa.Column("recorded_by",sa.String(255),nullable=False),sa.Column("verified_by",sa.String(255)),sa.Column("verified_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("company_id","waste_number",name="uq_environment_waste_number"))
 op.create_table("environmental_inspections",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("company_id",sa.Integer(),sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("project_id",sa.Integer(),sa.ForeignKey("projects.id",ondelete="CASCADE"),nullable=False),sa.Column("branch_id",sa.Integer(),sa.ForeignKey("branches.id",ondelete="RESTRICT"),nullable=False),sa.Column("site_id",sa.Integer(),sa.ForeignKey("sites.id",ondelete="RESTRICT"),nullable=False),sa.Column("inspection_number",sa.String(80),nullable=False),sa.Column("inspection_date",sa.Date(),nullable=False),sa.Column("category",sa.String(48),nullable=False),sa.Column("severity",sa.String(24),nullable=False),sa.Column("finding",sa.Text(),nullable=False),sa.Column("corrective_action",sa.Text()),sa.Column("due_date",sa.Date()),sa.Column("document_id",sa.Integer(),sa.ForeignKey("documents.id",ondelete="SET NULL")),sa.Column("status",sa.String(24),nullable=False),sa.Column("created_by",sa.String(255),nullable=False),sa.Column("remediated_by",sa.String(255)),sa.Column("remediated_at",sa.DateTime(timezone=True)),sa.Column("verified_by",sa.String(255)),sa.Column("verified_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("company_id","inspection_number",name="uq_environment_inspection_number"))
 op.create_table("environmental_audit_events",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("company_id",sa.Integer(),sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("branch_id",sa.Integer(),sa.ForeignKey("branches.id",ondelete="SET NULL")),sa.Column("site_id",sa.Integer(),sa.ForeignKey("sites.id",ondelete="SET NULL")),sa.Column("project_id",sa.Integer(),sa.ForeignKey("projects.id",ondelete="SET NULL")),sa.Column("actor",sa.String(255),nullable=False),sa.Column("action",sa.String(120),nullable=False),sa.Column("entity_type",sa.String(80),nullable=False),sa.Column("entity_id",sa.String(100),nullable=False),sa.Column("detail",sa.JSON(),nullable=False),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False))
 for t,cs in {"environmental_plans":("company_id","project_id","branch_id","site_id","plan_number","status","review_due_date","document_id"),"environmental_waste_records":("company_id","project_id","branch_id","site_id","waste_number","record_date","waste_stream","hazardous","document_id","status"),"environmental_inspections":("company_id","project_id","branch_id","site_id","inspection_number","inspection_date","category","severity","due_date","document_id","status"),"environmental_audit_events":("company_id","branch_id","site_id","project_id","action","occurred_at")}.items():
  for c in cs:op.create_index(f"ix_{t}_{c}",t,[c])
def downgrade():
 for t in ("environmental_audit_events","environmental_inspections","environmental_waste_records","environmental_plans"):
  for r in sa.inspect(op.get_bind()).get_indexes(t):op.drop_index(r["name"],table_name=t)
  op.drop_table(t)
