"""Phase 29 tools and calibration control."""
from alembic import op
import sqlalchemy as sa
revision="0030_phase29_tools"
down_revision="0029_phase28_environment"
branch_labels=None
depends_on=None
def upgrade():
 op.create_table("tool_assets",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("company_id",sa.Integer(),sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("branch_id",sa.Integer(),sa.ForeignKey("branches.id",ondelete="RESTRICT"),nullable=False),sa.Column("site_id",sa.Integer(),sa.ForeignKey("sites.id",ondelete="SET NULL")),sa.Column("tool_number",sa.String(80),nullable=False),sa.Column("name",sa.String(240),nullable=False),sa.Column("tool_type",sa.String(48),nullable=False),sa.Column("manufacturer",sa.String(160)),sa.Column("serial_number",sa.String(160)),sa.Column("status",sa.String(24),nullable=False),sa.Column("calibration_required",sa.Boolean(),nullable=False),sa.Column("calibration_due_date",sa.Date()),sa.Column("document_id",sa.Integer(),sa.ForeignKey("documents.id",ondelete="SET NULL")),sa.Column("created_by",sa.String(255),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("company_id","tool_number",name="uq_tool_asset_number"))
 op.create_table("tool_issues",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("company_id",sa.Integer(),sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("tool_id",sa.Integer(),sa.ForeignKey("tool_assets.id",ondelete="CASCADE"),nullable=False),sa.Column("employee_id",sa.Integer(),sa.ForeignKey("employees.id",ondelete="SET NULL")),sa.Column("project_id",sa.Integer(),sa.ForeignKey("projects.id",ondelete="SET NULL")),sa.Column("branch_id",sa.Integer(),sa.ForeignKey("branches.id",ondelete="RESTRICT"),nullable=False),sa.Column("site_id",sa.Integer(),sa.ForeignKey("sites.id",ondelete="SET NULL")),sa.Column("issued_at",sa.DateTime(timezone=True),nullable=False),sa.Column("due_date",sa.Date()),sa.Column("condition_out",sa.String(48),nullable=False),sa.Column("condition_in",sa.String(48)),sa.Column("return_note",sa.Text()),sa.Column("issued_by",sa.String(255),nullable=False),sa.Column("returned_by",sa.String(255)),sa.Column("returned_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("tool_id","returned_at",name="uq_tool_open_issue"))
 op.create_table("tool_calibrations",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("company_id",sa.Integer(),sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("tool_id",sa.Integer(),sa.ForeignKey("tool_assets.id",ondelete="CASCADE"),nullable=False),sa.Column("branch_id",sa.Integer(),sa.ForeignKey("branches.id",ondelete="RESTRICT"),nullable=False),sa.Column("site_id",sa.Integer(),sa.ForeignKey("sites.id",ondelete="SET NULL")),sa.Column("calibration_date",sa.Date(),nullable=False),sa.Column("due_date",sa.Date(),nullable=False),sa.Column("provider",sa.String(200),nullable=False),sa.Column("certificate_document_id",sa.Integer(),sa.ForeignKey("documents.id",ondelete="RESTRICT"),nullable=False),sa.Column("status",sa.String(24),nullable=False),sa.Column("recorded_by",sa.String(255),nullable=False),sa.Column("verified_by",sa.String(255)),sa.Column("verified_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("tool_id","calibration_date",name="uq_tool_calibration_date"))
 op.create_table("tool_audit_events",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("company_id",sa.Integer(),sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("branch_id",sa.Integer(),sa.ForeignKey("branches.id",ondelete="SET NULL")),sa.Column("site_id",sa.Integer(),sa.ForeignKey("sites.id",ondelete="SET NULL")),sa.Column("actor",sa.String(255),nullable=False),sa.Column("action",sa.String(120),nullable=False),sa.Column("entity_type",sa.String(80),nullable=False),sa.Column("entity_id",sa.String(100),nullable=False),sa.Column("detail",sa.JSON(),nullable=False),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False))
 for t,cs in {"tool_assets":("company_id","branch_id","site_id","tool_number","tool_type","status","calibration_required","calibration_due_date","document_id"),"tool_issues":("company_id","tool_id","employee_id","project_id","branch_id","site_id","due_date"),"tool_calibrations":("company_id","tool_id","branch_id","site_id","due_date","certificate_document_id","status"),"tool_audit_events":("company_id","branch_id","site_id","action","occurred_at")}.items():
  for c in cs:op.create_index(f"ix_{t}_{c}",t,[c])
def downgrade():
 for t in ("tool_audit_events","tool_calibrations","tool_issues","tool_assets"):
  for r in sa.inspect(op.get_bind()).get_indexes(t):op.drop_index(r["name"],table_name=t)
  op.drop_table(t)
