"""Phase 31 supplier and subcontractor evidence portal."""
from alembic import op
import sqlalchemy as sa
revision="0032_phase31_vendor_portal"
down_revision="0031_phase30_client_portal"
branch_labels=None
depends_on=None
def upgrade():
 op.create_table("vendor_portal_requests",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("company_id",sa.Integer(),sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("branch_id",sa.Integer(),sa.ForeignKey("branches.id",ondelete="RESTRICT"),nullable=False),sa.Column("site_id",sa.Integer(),sa.ForeignKey("sites.id",ondelete="SET NULL")),sa.Column("target_type",sa.String(24),nullable=False),sa.Column("vendor_id",sa.Integer(),nullable=False),sa.Column("vendor_name",sa.String(240),nullable=False),sa.Column("request_number",sa.String(80),nullable=False),sa.Column("request_type",sa.String(80),nullable=False),sa.Column("title",sa.String(300),nullable=False),sa.Column("instructions",sa.Text()),sa.Column("due_date",sa.Date(),nullable=False),sa.Column("status",sa.String(24),nullable=False),sa.Column("token_hash",sa.String(64)),sa.Column("prepared_by",sa.String(255),nullable=False),sa.Column("submitted_at",sa.DateTime(timezone=True)),sa.Column("published_by",sa.String(255)),sa.Column("published_at",sa.DateTime(timezone=True)),sa.Column("received_at",sa.DateTime(timezone=True)),sa.Column("verified_by",sa.String(255)),sa.Column("verified_at",sa.DateTime(timezone=True)),sa.Column("revoked_by",sa.String(255)),sa.Column("revoked_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("company_id","request_number",name="uq_vendor_portal_request_number"),sa.UniqueConstraint("token_hash",name="uq_vendor_portal_token"))
 op.create_table("vendor_portal_evidence",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("company_id",sa.Integer(),sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("request_id",sa.Integer(),sa.ForeignKey("vendor_portal_requests.id",ondelete="CASCADE"),nullable=False),sa.Column("contact_name",sa.String(180),nullable=False),sa.Column("contact_email",sa.String(255),nullable=False),sa.Column("note",sa.Text()),sa.Column("original_filename",sa.String(255),nullable=False),sa.Column("stored_path",sa.String(500),nullable=False),sa.Column("content_type",sa.String(160)),sa.Column("file_size",sa.Integer(),nullable=False),sa.Column("sha256",sa.String(64),nullable=False),sa.Column("uploaded_at",sa.DateTime(timezone=True),nullable=False))
 op.create_table("vendor_portal_audit_events",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("company_id",sa.Integer(),sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("branch_id",sa.Integer(),sa.ForeignKey("branches.id",ondelete="SET NULL")),sa.Column("site_id",sa.Integer(),sa.ForeignKey("sites.id",ondelete="SET NULL")),sa.Column("actor",sa.String(255),nullable=False),sa.Column("action",sa.String(120),nullable=False),sa.Column("entity_type",sa.String(80),nullable=False),sa.Column("entity_id",sa.String(100),nullable=False),sa.Column("detail",sa.JSON(),nullable=False),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False))
 for t,cs in {"vendor_portal_requests":("company_id","branch_id","site_id","target_type","vendor_id","request_number","request_type","due_date","status","token_hash"),"vendor_portal_evidence":("company_id","request_id"),"vendor_portal_audit_events":("company_id","branch_id","site_id","action","occurred_at")}.items():
  for c in cs:op.create_index(f"ix_{t}_{c}",t,[c])
def downgrade():
 for t in ("vendor_portal_audit_events","vendor_portal_evidence","vendor_portal_requests"):
  for r in sa.inspect(op.get_bind()).get_indexes(t):op.drop_index(r["name"],table_name=t)
  op.drop_table(t)
