"""Phase 32 business development pipeline."""
from alembic import op
import sqlalchemy as sa
revision="0033_phase32_business_dev"
down_revision="0032_phase31_vendor_portal"
branch_labels=None
depends_on=None
def upgrade():
 op.create_table("business_opportunities",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("company_id",sa.Integer(),sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("branch_id",sa.Integer(),sa.ForeignKey("branches.id",ondelete="RESTRICT"),nullable=False),sa.Column("site_id",sa.Integer(),sa.ForeignKey("sites.id",ondelete="SET NULL")),sa.Column("opportunity_number",sa.String(80),nullable=False),sa.Column("title",sa.String(300),nullable=False),sa.Column("client_name",sa.String(240),nullable=False),sa.Column("client_contact",sa.String(240)),sa.Column("sector",sa.String(120)),sa.Column("source",sa.String(80),nullable=False),sa.Column("estimated_value",sa.Numeric(18,2)),sa.Column("probability",sa.Integer(),nullable=False),sa.Column("expected_bid_date",sa.Date()),sa.Column("scope_summary",sa.Text()),sa.Column("next_action",sa.String(300)),sa.Column("next_action_date",sa.Date()),sa.Column("status",sa.String(24),nullable=False),sa.Column("tender_id",sa.Integer(),sa.ForeignKey("tenders.id",ondelete="SET NULL")),sa.Column("prepared_by",sa.String(255),nullable=False),sa.Column("qualified_by",sa.String(255)),sa.Column("qualified_at",sa.DateTime(timezone=True)),sa.Column("closed_by",sa.String(255)),sa.Column("closed_at",sa.DateTime(timezone=True)),sa.Column("close_note",sa.Text()),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("company_id","opportunity_number",name="uq_business_opportunity_number"))
 op.create_table("business_opportunity_activities",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("company_id",sa.Integer(),sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("opportunity_id",sa.Integer(),sa.ForeignKey("business_opportunities.id",ondelete="CASCADE"),nullable=False),sa.Column("activity_date",sa.Date(),nullable=False),sa.Column("activity_type",sa.String(80),nullable=False),sa.Column("note",sa.Text(),nullable=False),sa.Column("next_action",sa.String(300)),sa.Column("next_action_date",sa.Date()),sa.Column("recorded_by",sa.String(255),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
 op.create_table("business_development_audit_events",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("company_id",sa.Integer(),sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("branch_id",sa.Integer(),sa.ForeignKey("branches.id",ondelete="SET NULL")),sa.Column("site_id",sa.Integer(),sa.ForeignKey("sites.id",ondelete="SET NULL")),sa.Column("actor",sa.String(255),nullable=False),sa.Column("action",sa.String(120),nullable=False),sa.Column("entity_type",sa.String(80),nullable=False),sa.Column("entity_id",sa.String(100),nullable=False),sa.Column("detail",sa.JSON(),nullable=False),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False))
 for t,cs in {"business_opportunities":("company_id","branch_id","site_id","opportunity_number","client_name","expected_bid_date","next_action_date","status","tender_id"),"business_opportunity_activities":("company_id","opportunity_id","activity_date"),"business_development_audit_events":("company_id","branch_id","site_id","action","occurred_at")}.items():
  for c in cs:op.create_index(f"ix_{t}_{c}",t,[c])
def downgrade():
 for t in ("business_development_audit_events","business_opportunity_activities","business_opportunities"):
  for r in sa.inspect(op.get_bind()).get_indexes(t):op.drop_index(r["name"],table_name=t)
  op.drop_table(t)
