"""Phase 33 client relationship accounts."""
from alembic import op
import sqlalchemy as sa
revision="0034_phase33_client_accounts"
down_revision="0033_phase32_business_dev"
branch_labels=None
depends_on=None
def upgrade():
 op.create_table("client_accounts",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("company_id",sa.Integer(),sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("branch_id",sa.Integer(),sa.ForeignKey("branches.id",ondelete="RESTRICT"),nullable=False),sa.Column("site_id",sa.Integer(),sa.ForeignKey("sites.id",ondelete="SET NULL")),sa.Column("account_number",sa.String(80),nullable=False),sa.Column("legal_name",sa.String(240),nullable=False),sa.Column("trading_name",sa.String(240)),sa.Column("sector",sa.String(120)),sa.Column("status",sa.String(24),nullable=False),sa.Column("account_manager",sa.String(255)),sa.Column("notes",sa.Text()),sa.Column("created_by",sa.String(255),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("company_id","account_number",name="uq_client_account_number"))
 op.create_table("client_account_contacts",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("company_id",sa.Integer(),sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("account_id",sa.Integer(),sa.ForeignKey("client_accounts.id",ondelete="CASCADE"),nullable=False),sa.Column("full_name",sa.String(240),nullable=False),sa.Column("role",sa.String(120)),sa.Column("email",sa.String(255)),sa.Column("phone",sa.String(64)),sa.Column("is_primary",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("account_id","email",name="uq_client_account_contact_email"))
 op.create_table("client_feedback",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("company_id",sa.Integer(),sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("account_id",sa.Integer(),sa.ForeignKey("client_accounts.id",ondelete="CASCADE"),nullable=False),sa.Column("feedback_date",sa.Date(),nullable=False),sa.Column("category",sa.String(80),nullable=False),sa.Column("score",sa.Integer(),nullable=False),sa.Column("comment",sa.Text(),nullable=False),sa.Column("action_plan",sa.Text()),sa.Column("status",sa.String(24),nullable=False),sa.Column("recorded_by",sa.String(255),nullable=False),sa.Column("verified_by",sa.String(255)),sa.Column("verified_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
 op.create_table("client_account_audit_events",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("company_id",sa.Integer(),sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("branch_id",sa.Integer(),sa.ForeignKey("branches.id",ondelete="SET NULL")),sa.Column("site_id",sa.Integer(),sa.ForeignKey("sites.id",ondelete="SET NULL")),sa.Column("actor",sa.String(255),nullable=False),sa.Column("action",sa.String(120),nullable=False),sa.Column("entity_type",sa.String(80),nullable=False),sa.Column("entity_id",sa.String(100),nullable=False),sa.Column("detail",sa.JSON(),nullable=False),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False))
 for t,cs in {"client_accounts":("company_id","branch_id","site_id","account_number","legal_name","status"),"client_account_contacts":("company_id","account_id"),"client_feedback":("company_id","account_id","feedback_date","status"),"client_account_audit_events":("company_id","branch_id","site_id","action","occurred_at")}.items():
  for c in cs:op.create_index(f"ix_{t}_{c}",t,[c])
def downgrade():
 for t in ("client_account_audit_events","client_feedback","client_account_contacts","client_accounts"):
  for r in sa.inspect(op.get_bind()).get_indexes(t):op.drop_index(r["name"],table_name=t)
  op.drop_table(t)
