"""Phase 34 contract administration control."""
from alembic import op
import sqlalchemy as sa
revision="0035_phase34_contract_ctrl"
down_revision="0034_phase33_client_accounts"
branch_labels=None
depends_on=None
def upgrade():
 op.create_table("contract_notices",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("company_id",sa.Integer(),sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("branch_id",sa.Integer(),sa.ForeignKey("branches.id",ondelete="RESTRICT"),nullable=False),sa.Column("site_id",sa.Integer(),sa.ForeignKey("sites.id",ondelete="SET NULL")),sa.Column("contract_id",sa.Integer(),sa.ForeignKey("client_contracts.id",ondelete="CASCADE"),nullable=False),sa.Column("notice_number",sa.String(80),nullable=False),sa.Column("notice_type",sa.String(80),nullable=False),sa.Column("subject",sa.String(300),nullable=False),sa.Column("event_date",sa.Date(),nullable=False),sa.Column("due_date",sa.Date()),sa.Column("status",sa.String(24),nullable=False),sa.Column("prepared_by",sa.String(255),nullable=False),sa.Column("issued_by",sa.String(255)),sa.Column("issued_at",sa.DateTime(timezone=True)),sa.Column("detail",sa.Text(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
 op.create_table("contract_extensions_of_time",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("company_id",sa.Integer(),sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("branch_id",sa.Integer(),sa.ForeignKey("branches.id",ondelete="RESTRICT"),nullable=False),sa.Column("site_id",sa.Integer(),sa.ForeignKey("sites.id",ondelete="SET NULL")),sa.Column("contract_id",sa.Integer(),sa.ForeignKey("client_contracts.id",ondelete="CASCADE"),nullable=False),sa.Column("notice_id",sa.Integer(),sa.ForeignKey("contract_notices.id",ondelete="SET NULL")),sa.Column("reason",sa.String(300),nullable=False),sa.Column("days_requested",sa.Integer(),nullable=False),sa.Column("impact_summary",sa.Text(),nullable=False),sa.Column("status",sa.String(24),nullable=False),sa.Column("submitted_by",sa.String(255),nullable=False),sa.Column("reviewed_by",sa.String(255)),sa.Column("reviewed_at",sa.DateTime(timezone=True)),sa.Column("review_note",sa.Text()),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
 op.create_table("contract_variation_instructions",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("company_id",sa.Integer(),sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("branch_id",sa.Integer(),sa.ForeignKey("branches.id",ondelete="RESTRICT"),nullable=False),sa.Column("site_id",sa.Integer(),sa.ForeignKey("sites.id",ondelete="SET NULL")),sa.Column("contract_id",sa.Integer(),sa.ForeignKey("client_contracts.id",ondelete="CASCADE"),nullable=False),sa.Column("instruction_number",sa.String(80),nullable=False),sa.Column("description",sa.Text(),nullable=False),sa.Column("estimated_value",sa.Numeric(18,2),nullable=False),sa.Column("status",sa.String(24),nullable=False),sa.Column("prepared_by",sa.String(255),nullable=False),sa.Column("approved_by",sa.String(255)),sa.Column("approved_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
 op.create_table("contract_control_audit_events",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("company_id",sa.Integer(),sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("branch_id",sa.Integer(),sa.ForeignKey("branches.id",ondelete="SET NULL")),sa.Column("site_id",sa.Integer(),sa.ForeignKey("sites.id",ondelete="SET NULL")),sa.Column("actor",sa.String(255),nullable=False),sa.Column("action",sa.String(120),nullable=False),sa.Column("entity_type",sa.String(80),nullable=False),sa.Column("entity_id",sa.String(100),nullable=False),sa.Column("detail",sa.JSON(),nullable=False),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False))
 for t in ("contract_notices","contract_extensions_of_time","contract_variation_instructions","contract_control_audit_events"):op.create_index(f"ix_{t}_company_id",t,["company_id"])
def downgrade():
 for t in ("contract_control_audit_events","contract_variation_instructions","contract_extensions_of_time","contract_notices"):op.drop_table(t)
