import Link from "next/link";
import { ArrowRight, BookOpen, CheckCircle2, Cpu, Database, Globe2, HardDrive, Mail, Server, ShieldCheck, TerminalSquare, TriangleAlert } from "lucide-react";

const rules = [
  ["No root or host access", "Ithute application hosting is managed shared hosting, not a customer root VPS. Customers do not receive host SSH, sudo/root access, the Docker socket, privileged containers or access to another tenant's runtime."],
  ["Resource limits are mandatory", "Every project has explicit storage, RAM, CPU and process/PID limits. A project may not disable, bypass or deliberately exhaust those limits. Package storage is an allocation, not permission to consume the whole server."],
  ["Only Ithute ingress is public", "Customer workloads must not bind arbitrary public host ports. Public HTTP/HTTPS traffic is published through the Ithute edge proxy after the hostname belongs to a verified domain in the same organization."],
  ["Build untrusted code away from the production host", "Customer source and build scripts must run through an approved isolated build pipeline. The production VPS is not a general-purpose build machine and customer builds may not receive platform, Docker-host or control-plane credentials."],
  ["Run with least privilege", "Hosted applications should run as a non-root application user wherever the runtime supports it. Writable files must stay inside project-scoped persistent storage; host paths and another project's volumes are prohibited."],
  ["Only approved workloads", "Crypto-mining, malware, credential theft, spam, phishing infrastructure, open proxy/VPN relay services, port scanning, botnet activity and deliberate denial-of-service/resource-exhaustion workloads are prohibited."],
  ["Project-scoped secrets and databases", "Applications must use project-specific database users and secrets. Ithute control-plane, mail, DNS, host or another tenant's credentials must never be embedded in a hosted application."],
  ["Email follows the mail platform", "Application hosting does not provide unrestricted direct bulk SMTP. Applications that send email must use approved Ithute transactional/professional email paths, authentication and sending limits."],
  ["Domains must be verified", "A project can receive a custom public hostname only from a verified domain owned by the same organization. DNS changes must preserve the customer's actual web origin until the project is deliberately routed to Ithute hosting."],
  ["Safety suspension", "Ithute may suspend a workload that threatens platform availability, exceeds its entitlement or violates these rules. Suspension does not by itself delete customer data; destructive deletion is a separate explicit operation."],
];

const runtimes = [
  ["Static", "HTML/CSS/JavaScript sites and compiled static frontends."],
  ["Node", "Next.js/Node.js applications prepared for a production server process."],
  ["Python", "FastAPI and similar Python web applications with an explicit production start command."],
  [".NET", "ASP.NET Core / server-side .NET applications prepared for Linux container hosting."],
];

function Card({ icon: Icon, title, children }: { icon: typeof Server; title: string; children: React.ReactNode }) {
  return <article className="rounded-2xl border border-[#dfe6e2] bg-white p-5 shadow-sm"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#edf4f1] text-[#285b55]"><Icon size={18}/></span><h3 className="mt-4 text-sm font-black text-[#21342a]">{title}</h3><div className="mt-2 text-[11px] leading-6 text-[#687970]">{children}</div></article>;
}

export default function HostingDocumentationPage() {
  return <main className="min-h-screen bg-[#f4f6f4] text-[#21342a]">
    <header className="sticky top-0 z-30 border-b border-white/10 bg-[#123a38]/95 text-white backdrop-blur-xl"><div className="mx-auto flex max-w-[1180px] items-center justify-between gap-4 px-5 py-4 sm:px-8"><Link href="/" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#d8c56a] font-black text-[#123a38]">!I</span><div><p className="text-sm font-black">Ithute Hosting</p><p className="text-[9px] font-bold uppercase tracking-[.14em] text-white/50">Hosting rules & deployment manual</p></div></Link><div className="flex gap-2"><Link href="/pricing" className="rounded-lg border border-white/15 px-4 py-2 text-xs font-bold">Pricing</Link><Link href="/login" className="rounded-lg bg-[#d8c56a] px-4 py-2 text-xs font-black text-[#123a38]">Sign in</Link></div></div></header>

    <section className="bg-[linear-gradient(135deg,#123a38_0%,#1d504a_100%)] text-white"><div className="mx-auto max-w-[1180px] px-5 py-16 sm:px-8"><div className="max-w-3xl"><span className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[.07] px-3 py-2 text-[10px] font-black uppercase tracking-[.13em] text-white/70"><BookOpen size={14}/>Rules version 2026-09-13</span><h1 className="mt-5 text-4xl font-black tracking-[-.045em] sm:text-5xl">Rules for every system hosted on Ithute.</h1><p className="mt-5 max-w-2xl text-sm leading-7 text-white/65">Ithute sells managed application hosting on shared infrastructure. These rules define the isolation, capacity, domain, build and security contract that protects the platform owner and every customer sharing the servers.</p></div></div></section>

    <div className="mx-auto max-w-[1180px] space-y-8 px-5 py-10 sm:px-8">
      <section className="grid gap-4 md:grid-cols-3"><Card icon={Server} title="Managed hosting, not root VPS"><p>Customers deploy applications through Ithute. They do not administer the shared operating system or Docker host.</p></Card><Card icon={HardDrive} title="1–10 GB commercial app storage"><p>Packages may sell from 1 GB to 10 GB of application storage. Mail storage remains a separate quota so a website cannot consume mailbox capacity.</p></Card><Card icon={Cpu} title="CPU + RAM + PID enforcement"><p>Every project receives a resource ceiling. The system owner also registers only the safe portion of the VPS as sellable capacity.</p></Card></section>

      <section className="rounded-3xl border border-[#dfe6e2] bg-white p-6 shadow-sm sm:p-8"><div className="flex items-start gap-3"><ShieldCheck className="mt-1 shrink-0 text-[#285b55]"/><div><p className="text-[10px] font-black uppercase tracking-[.12em] text-[#718078]">Mandatory policy</p><h2 className="mt-1 text-2xl font-black tracking-[-.03em]">Application hosting rules</h2><p className="mt-2 text-sm leading-6 text-[#687970]">The API requires explicit acceptance of the current rules version when a hosted project is created. Acceptance is stored with the project and the user who accepted it.</p></div></div><div className="mt-6 grid gap-3 lg:grid-cols-2">{rules.map(([title,copy], index) => <div key={title} className="flex gap-3 rounded-2xl border border-[#e3e9e6] bg-[#f8faf9] p-4"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-[#123a38] text-[10px] font-black text-white">{index+1}</span><div><h3 className="text-xs font-black text-[#21342a]">{title}</h3><p className="mt-1 text-[10px] leading-5 text-[#687970]">{copy}</p></div></div>)}</div></section>

      <section className="grid gap-4 lg:grid-cols-2"><div className="rounded-3xl border border-[#dfe6e2] bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><TerminalSquare className="text-[#285b55]"/><h2 className="text-xl font-black">Supported application types</h2></div><div className="mt-5 space-y-3">{runtimes.map(([title,copy]) => <div key={title} className="rounded-xl bg-[#f6f9f7] p-4"><p className="text-xs font-black">{title}</p><p className="mt-1 text-[10px] leading-5 text-[#687970]">{copy}</p></div>)}</div><div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-4 text-[10px] leading-5 text-amber-900"><b>Runtime support is not permission to run arbitrary host commands.</b> The project still follows the same container, resource, ingress and build restrictions.</div></div><div className="rounded-3xl border border-[#dfe6e2] bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><Globe2 className="text-[#285b55]"/><h2 className="text-xl font-black">Domain and HTTPS flow</h2></div><div className="mt-5 space-y-3 text-xs leading-6 text-[#687970]"><p><b>1.</b> Add or transfer the domain to the correct organization.</p><p><b>2.</b> Complete domain ownership verification. Ithute-managed authoritative DNS uses nameserver delegation; external DNS follows its external verification path.</p><p><b>3.</b> Create the hosted project and select the verified domain/hostname.</p><p><b>4.</b> Route public traffic through Ithute edge/Caddy only when the workload is actually ready. Never replace a working customer's A/CNAME records merely because a domain was added to DNS management.</p><p><b>5.</b> HTTPS certificates and public health checks must pass before the project is considered publicly available.</p></div></div></section>

      <section className="rounded-3xl border border-[#dfe6e2] bg-white p-6 shadow-sm sm:p-8"><h2 className="text-2xl font-black tracking-[-.03em]">Package and server-capacity rules</h2><p className="mt-3 max-w-3xl text-sm leading-7 text-[#687970]">There are two independent safety gates. A customer package limits what the organization is entitled to buy/use; the hosting-node ledger limits what the physical/shared server is allowed to allocate. A project must fit both gates.</p><div className="mt-6 grid gap-4 md:grid-cols-2"><Card icon={HardDrive} title="Customer package gate"><p>Checks project count, total app storage, per-project RAM, per-project CPU and PID limit. Package creation currently supports 1–10 GB app-storage pools when application hosting is enabled.</p></Card><Card icon={Server} title="Hosting-node gate"><p>The system owner manually declares sellable storage, memory and CPU. This should always be less than the server's physical capacity, leaving headroom for Ithute, DNS, mail, databases, the OS and traffic spikes.</p></Card></div><div className="mt-5 rounded-2xl bg-[#123a38] p-5 text-xs leading-6 text-white/70"><b className="text-white">Do not oversell the control-plane VPS.</b> If the VPS has 16 GB RAM, for example, do not mark all 16 GB as sellable. Reserve enough RAM/CPU/disk for platform services and failure recovery before registering node capacity.</div></section>

      <section className="grid gap-4 md:grid-cols-3"><Card icon={Database} title="Databases"><p>Each hosted system must use project-scoped database credentials. Do not share PostgreSQL superuser credentials or the control-plane application's database account with customer workloads.</p></Card><Card icon={Mail} title="Application email"><p>Use Ithute transactional/professional email for approved sending. A hosted project must not turn the shared VPS into an unrestricted outbound SMTP relay.</p></Card><Card icon={DatabaseBackup} title="Backups"><p>Live project allocation and backup retention are different resources. A backup policy must never be treated as permission for the running application to exceed its storage quota.</p></Card></section>

      <section className="rounded-3xl border border-amber-200 bg-amber-50 p-6"><div className="flex gap-3"><TriangleAlert className="shrink-0 text-amber-700"/><div><h2 className="text-lg font-black text-amber-950">Deployment boundary</h2><p className="mt-2 text-xs leading-6 text-amber-900">The control plane can allocate a project only after package and node capacity checks pass. Application source must then move through the approved isolated build/deployment pipeline. Do not work around this by giving customers VPS SSH access or by mounting the host Docker socket into customer-facing services.</p></div></div></section>

      <section className="rounded-3xl bg-[#123a38] p-7 text-white"><div className="flex items-start gap-4"><CheckCircle2 className="mt-1 shrink-0 text-[#f1de8b]"/><div><h2 className="text-xl font-black">Ready to configure hosting?</h2><p className="mt-2 max-w-2xl text-xs leading-6 text-white/65">The system owner first creates a commercial package and registers sellable node capacity. Organization administrators can then allocate hosted projects within those limits and accept this rules version for each project.</p><div className="mt-4 flex flex-wrap gap-3"><Link href="/login" className="inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3 text-xs font-black text-[#123a38]">Open control panel <ArrowRight size={14}/></Link><Link href="/pricing" className="inline-flex items-center gap-2 rounded-xl border border-white/15 px-5 py-3 text-xs font-black">View packages</Link></div></div></div></section>
    </div>
  </main>;
}
