import { redirect } from "next/navigation";

import { ApiError, nbrosApi } from "@/lib/backend";
import { createApprovalPolicyAction, decideApprovalAction, toggleApprovalPolicyAction } from "../actions";
import OperationsNav from "../nav";

type Branch = { id: string; code: string; name: string };
type Governance = {
  policies: Array<{ id: string; workflow_key: string; display_name: string; min_amount: number; required_role: string; priority: number; is_active: boolean }>;
  approvals: Array<{ id: string; workflow_key: string; entity_type: string; entity_id: string; status: string; amount: number; reason: string | null; requested_at: string; required_role: string }>;
};
function money(value: number) { return `M ${value.toLocaleString("en-ZA", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`; }

export default async function GovernancePage({ searchParams }: { searchParams: Promise<{ branch?: string }> }) {
  let branches: Branch[];
  try { branches = await nbrosApi<Branch[]>("/api/v1/fleet/branches"); }
  catch (error) { if (error instanceof ApiError && error.status === 401) redirect("/api/auth/login"); throw error; }
  if (!branches.length) redirect("/fleet");
  const params = await searchParams;
  const selected = branches.find((branch) => branch.id === params.branch) ?? branches[0];
  const governance = await nbrosApi<Governance>(`/api/v1/operations/governance?branch_id=${selected.id}`);
  const pending = governance.approvals.filter((row) => row.status === "pending");

  return <div className="app-shell"><OperationsNav branchId={selected.id} active="governance"/><main className="workspace">
    <header className="workspace-header"><div><span className="eyebrow">Approvals & Governance</span><h1>{selected.name} control framework</h1><p className="muted">Approval tiers route workshop and procurement decisions to the required operational role while preserving a traceable decision record.</p></div><form method="get" className="branch-picker"><select name="branch" defaultValue={selected.id}>{branches.map((branch)=><option key={branch.id} value={branch.id}>{branch.name} · {branch.code}</option>)}</select><button className="ghost-button">Switch</button></form></header>
    <section className="metric-grid"><article className="metric-card"><span>Approval policies</span><strong>{governance.policies.length}</strong><small>{governance.policies.filter((row)=>row.is_active).length} active routing tiers</small></article><article className={`metric-card ${pending.length ? "danger-card" : ""}`}><span>Pending decisions</span><strong>{pending.length}</strong><small>management actions waiting</small></article><article className="metric-card"><span>Approved</span><strong>{governance.approvals.filter((row)=>row.status === "approved").length}</strong><small>recorded decisions</small></article><article className="metric-card"><span>Rejected</span><strong>{governance.approvals.filter((row)=>row.status === "rejected").length}</strong><small>recorded decisions</small></article></section>

    <section className="two-column"><article className="panel"><div className="panel-heading"><div><span className="eyebrow">Routing policy</span><h2>Add approval tier</h2></div></div><form action={createApprovalPolicyAction} className="form-grid"><input type="hidden" name="branch_id" value={selected.id}/><label>Workflow<select name="workflow_key" defaultValue="procurement_high_value"><option value="procurement_standard">Procurement standard</option><option value="procurement_high_value">Procurement high value</option><option value="workshop_high_value">Workshop high value</option></select></label><label>Display name<input name="display_name" required placeholder="Executive approval"/></label><label>Minimum amount (M)<input name="min_amount" type="number" min="0" step="0.01" defaultValue="0" required/></label><label>Required role<select name="required_role" defaultValue="manager"><option value="manager">Manager</option><option value="fleet_manager">Fleet manager</option><option value="admin">Administrator</option><option value="fleet_admin">Fleet administrator</option></select></label><label>Priority<input name="priority" type="number" min="1" max="10000" defaultValue="100" required/></label><div className="form-span"><button className="primary-button">Create routing tier</button></div></form></article>
    <article className="panel"><div className="panel-heading"><div><span className="eyebrow">Active policy set</span><h2>Approval tiers</h2></div></div>{governance.policies.length ? <div className="alert-list">{governance.policies.map((row)=><div className={`alert-row ${row.is_active ? "alert-green" : ""}`} key={row.id}><div><strong>{row.display_name}</strong><span>{row.workflow_key.replaceAll("_"," ")} · from {money(row.min_amount)} · role {row.required_role}</span></div><form action={toggleApprovalPolicyAction}><input type="hidden" name="branch_id" value={selected.id}/><input type="hidden" name="policy_id" value={row.id}/><button className="ghost-button">{row.is_active ? "Disable" : "Enable"}</button></form></div>)}</div> : <div className="empty-state"><strong>No approval policies.</strong><span>Existing workflows default to manager approval until a branch routing tier is configured.</span></div>}</article></section>

    <section className="panel"><div className="panel-heading"><div><span className="eyebrow">Decision queue</span><h2>Pending approvals</h2></div><span className="count-badge">{pending.length}</span></div>{pending.length ? <div className="table-wrap"><table><thead><tr><th>Workflow</th><th>Entity</th><th>Amount</th><th>Required role</th><th>Reason</th><th>Decision</th></tr></thead><tbody>{pending.map((row)=><tr key={row.id}><td>{row.workflow_key.replaceAll("_"," ")}</td><td>{row.entity_type.replaceAll("_"," ")}</td><td>{money(row.amount)}</td><td><span className="status-pill status-orange">{row.required_role}</span></td><td>{row.reason ?? "—"}</td><td><form action={decideApprovalAction} className="header-actions"><input type="hidden" name="branch_id" value={selected.id}/><input type="hidden" name="approval_id" value={row.id}/><input type="hidden" name="return_path" value="/operations/governance"/><button className="ghost-button" name="decision" value="reject">Reject</button><button className="primary-button" name="decision" value="approve">Approve</button></form></td></tr>)}</tbody></table></div> : <div className="empty-state"><strong>No pending decisions.</strong><span>Workshop and procurement approvals will appear here automatically.</span></div>}</section>

    <section className="panel"><div className="panel-heading"><div><span className="eyebrow">Decision history</span><h2>Latest approval records</h2></div></div>{governance.approvals.length ? <div className="table-wrap"><table><thead><tr><th>Requested</th><th>Workflow</th><th>Entity</th><th>Amount</th><th>Status</th><th>Role</th></tr></thead><tbody>{governance.approvals.slice(0,100).map((row)=><tr key={row.id}><td>{new Date(row.requested_at).toLocaleString()}</td><td>{row.workflow_key.replaceAll("_"," ")}</td><td>{row.entity_type.replaceAll("_"," ")}</td><td>{money(row.amount)}</td><td><span className={`status-pill ${row.status === "approved" ? "status-green" : row.status === "rejected" ? "status-red" : "status-orange"}`}>{row.status.toUpperCase()}</span></td><td>{row.required_role}</td></tr>)}</tbody></table></div> : <div className="empty-state"><strong>No approval history yet.</strong></div>}</section>
  </main></div>;
}
