options {
    directory "/var/cache/bind";
    listen-on port 53 { any; };
    listen-on-v6 { none; };
    recursion no;
    allow-query { any; };
    allow-recursion { none; };
    allow-transfer { none; };
    minimal-responses yes;
    version "not disclosed";
    dnssec-validation no;
};

zone "ithute.co.ls" IN {
    type primary;
    file "/etc/bind/zones/db.ithute.co.ls";
    allow-query { any; };
    allow-transfer { none; };
    notify no;
};
