#!/usr/bin/env sh
set -eu

STORAGE_ROOT="${ITHUTE_HOSTING_STORAGE_ROOT:-/srv/ithute-hosting-build-plane}"
BUILDER_ETC="${ITHUTE_HOSTING_BUILDER_ETC_ROOT:-/etc/ithute-hosting-builder}"
SERVICE_UID="${ITHUTE_HOSTING_SERVICE_UID:-10001}"
SERVICE_GID="${ITHUTE_HOSTING_SERVICE_GID:-10001}"

if ! command -v docker >/dev/null 2>&1; then
  echo "docker is required" >&2
  exit 1
fi

# The builder controls the Docker daemon on this host. Refuse installation on a
# host that visibly runs Ithute/LoanHub production workloads unless an operator
# explicitly overrides the guard for a reviewed topology.
if [ "${ITHUTE_ALLOW_BUILD_PLANE_ON_APPLICATION_HOST:-false}" != "true" ]; then
  if docker ps --format '{{.Names}}' 2>/dev/null | grep -Eiq '(^|[-_])(ithute-web|ithute-auth|ithute-push|ithute-realtime|ithute-mail|loanhub|khanya)([-_]|$)'; then
    echo "refusing to bootstrap the hosting build plane on an application/production host" >&2
    echo "use a dedicated build host; override only after an explicit security review" >&2
    exit 1
  fi
fi

mkdir -p \
  "$STORAGE_ROOT/quarantine" \
  "$STORAGE_ROOT/verified" \
  "$STORAGE_ROOT/builder-work" \
  "$BUILDER_ETC/docker"

chown -R "$SERVICE_UID:$SERVICE_GID" "$STORAGE_ROOT"
chmod 0700 "$STORAGE_ROOT/quarantine" "$STORAGE_ROOT/builder-work"
chmod 0750 "$STORAGE_ROOT/verified"

if [ ! -f "$BUILDER_ETC/known_hosts" ]; then
  : > "$BUILDER_ETC/known_hosts"
fi
chown "$SERVICE_UID:$SERVICE_GID" "$BUILDER_ETC/known_hosts"
chmod 0444 "$BUILDER_ETC/known_hosts"

chown -R "$SERVICE_UID:$SERVICE_GID" "$BUILDER_ETC/docker"
chmod 0700 "$BUILDER_ETC/docker"

SOCKET_GID="$(stat -c '%g' /var/run/docker.sock 2>/dev/null || true)"
if [ -z "$SOCKET_GID" ]; then
  echo "cannot determine /var/run/docker.sock group id" >&2
  exit 1
fi

cat <<EOF
Build-plane directories prepared.

Set these values in the private runtime .env file:
ITHUTE_HOSTING_STORAGE_ROOT=$STORAGE_ROOT
ITHUTE_HOSTING_BUILDER_KNOWN_HOSTS_FILE=$BUILDER_ETC/known_hosts
ITHUTE_HOSTING_DOCKER_CONFIG_ROOT=$BUILDER_ETC/docker
ITHUTE_HOSTING_DOCKER_GID=$SOCKET_GID

Before starting services:
1. populate known_hosts only with reviewed Git host keys;
2. authenticate the Docker CLI config to the approved ghcr.io namespace;
3. add the upload-service and builder tokens generated by Ithute;
4. point the dedicated upload hostname at this host;
5. apply outbound firewall rules for the build host.
EOF
