Host 204.12.205.224
  ServerAliveInterval 20
  ServerAliveCountMax 90
  TCPKeepAlive yes
  ConnectTimeout 20
  ConnectionAttempts 10
  ControlMaster auto
  ControlPersist 10m
  ControlPath ~/.ssh/ithute-%C
  IPQoS none
