"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Building2, UsersRound } from "lucide-react";
import { ControlShell } from "@/components/control-shell";
import { EmptyState, LoadingPanel, PageHeader, StatusBadge } from "@/components/ui-kit";
const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:8006/api/v1";
type Membership={membership_id:string;tenant_id:string;tenant_name:string;tenant_slug:string;tenant_status:string;role:string;status:string};type Me={email:string;is_platform_owner:boolean};
export default function OrganizationsPage(){const router=useRouter();const[rows,setRows]=useState<Membership[]>([]);const[me,setMe]=useState<Me|null>(null);const[loading,setLoading]=useState(true);useEffect(()=>{void(async()=>{try{const m=await fetch(`${API}/auth/me`,{credentials:"include"});if(m.status===401){router.replace("/login");return}if(m.ok)setMe(await m.json());const r=await fetch(`${API}/me/memberships`,{credentials:"include"});if(r.ok)setRows(await r.json())}finally{setLoading(false)}})()},[router]);function choose(id:string){localStorage.setItem("mailbox_dns_tenant",id);router.push("/domains")}
return <ControlShell title="Organizations" subtitle="Company contexts, memberships and team access" userEmail={me?.email}><div className="space-y-4"><PageHeader eyebrow="Multi-tenant control" title="Your organizations" description="Your identity is global while access, domains and operational permissions remain isolated per organization."/>{loading?<LoadingPanel label="Loading organizations"/>:rows.length?<section className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{rows.map(m=><article key={m.membership_id} className="surface-card p-4"><div className="flex items-start justify-between gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#eef4f1] text-[var(--admin-pine)]"><Building2 size={18}/></div><StatusBadge state={m.status==="active"?"good":"warn"}>{m.status}</StatusBadge></div><h2 className="mt-4 text-base font-black text-[var(--admin-ink)]">{m.tenant_name}</h2><p className="mt-1 font-mono text-[9px] text-[var(--admin-muted)]">{m.tenant_slug}</p><div className="mt-4 grid grid-cols-2 gap-2 rounded-xl bg-[#f8faf8] p-3"><div><p className="eyebrow-label">Role</p><p className="mt-1 text-[11px] font-bold capitalize">{m.role.replaceAll("_"," ")}</p></div><div><p className="eyebrow-label">Tenant</p><p className="mt-1 text-[11px] font-bold capitalize">{m.tenant_status}</p></div></div><div className="mt-4 flex flex-wrap gap-2"><button className="btn-primary" onClick={()=>choose(m.tenant_id)}>Use organization</button>{m.role==="tenant_admin"?<Link className="btn-secondary" href={`/tenants/${m.tenant_id}/members`}><UsersRound size={14}/>Manage team</Link>:null}</div></article>)}</section>:<EmptyState icon={<Building2 size={20}/>} title="No organization memberships" description="Ask a platform owner or tenant administrator to invite this account to an organization."/>}</div></ControlShell>}
