"""Enterprise operations modules connected to Fleet.

Revision ID: 0006_enterprise_operations
Revises: 0005_align_metadata
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0006_enterprise_operations"
down_revision = "0005_align_metadata"
branch_labels = None
depends_on = None

UUID = postgresql.UUID(as_uuid=True)


def upgrade() -> None:
    op.create_table("operations_settings", sa.Column("branch_id", UUID, nullable=False), sa.Column("workshop_approval_threshold", sa.Numeric(14, 2), nullable=False), sa.Column("procurement_approval_threshold", sa.Numeric(14, 2), nullable=False), sa.Column("vehicle_replacement_age_years", sa.Integer(), nullable=False), sa.Column("vehicle_replacement_mileage", sa.Integer(), nullable=False), sa.ForeignKeyConstraint(["branch_id"], ["branches.id"], ondelete="CASCADE"), sa.PrimaryKeyConstraint("branch_id"))
    op.create_table("operations_suppliers", sa.Column("id", UUID, nullable=False), sa.Column("branch_id", UUID, nullable=False), sa.Column("name", sa.String(180), nullable=False), sa.Column("supplier_type", sa.String(60), nullable=False), sa.Column("contact_person", sa.String(160), nullable=True), sa.Column("email", sa.String(320), nullable=True), sa.Column("phone", sa.String(80), nullable=True), sa.Column("is_active", sa.Boolean(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["branch_id"], ["branches.id"], ondelete="CASCADE"), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("branch_id", "name", name="uq_operations_supplier_branch_name"))
    op.create_table("workshop_technicians", sa.Column("id", UUID, nullable=False), sa.Column("branch_id", UUID, nullable=False), sa.Column("employee_number", sa.String(80), nullable=True), sa.Column("full_name", sa.String(160), nullable=False), sa.Column("specialty", sa.String(160), nullable=True), sa.Column("hourly_rate", sa.Numeric(12, 2), nullable=True), sa.Column("is_active", sa.Boolean(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["branch_id"], ["branches.id"], ondelete="CASCADE"), sa.PrimaryKeyConstraint("id"))
    op.create_table("workshop_bays", sa.Column("id", UUID, nullable=False), sa.Column("branch_id", UUID, nullable=False), sa.Column("code", sa.String(50), nullable=False), sa.Column("name", sa.String(120), nullable=False), sa.Column("is_active", sa.Boolean(), nullable=False), sa.ForeignKeyConstraint(["branch_id"], ["branches.id"], ondelete="CASCADE"), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("branch_id", "code", name="uq_workshop_bay_branch_code"))
    op.create_table("purchase_requisitions", sa.Column("id", UUID, nullable=False), sa.Column("branch_id", UUID, nullable=False), sa.Column("reference", sa.String(80), nullable=False), sa.Column("requested_by_profile_id", UUID, nullable=True), sa.Column("purpose", sa.Text(), nullable=False), sa.Column("total_estimate", sa.Numeric(14, 2), nullable=False), sa.Column("status", sa.String(40), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["branch_id"], ["branches.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["requested_by_profile_id"], ["profiles.id"], ondelete="SET NULL"), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("branch_id", "reference", name="uq_purchase_requisition_branch_reference"))
    op.create_table("tyre_assets", sa.Column("id", UUID, nullable=False), sa.Column("branch_id", UUID, nullable=False), sa.Column("serial_number", sa.String(120), nullable=False), sa.Column("brand", sa.String(100), nullable=True), sa.Column("size", sa.String(80), nullable=True), sa.Column("purchase_date", sa.Date(), nullable=True), sa.Column("purchase_cost", sa.Numeric(14, 2), nullable=True), sa.Column("status", sa.String(40), nullable=False), sa.Column("vehicle_id", UUID, nullable=True), sa.Column("wheel_position", sa.String(80), nullable=True), sa.Column("fitted_at_mileage", sa.Integer(), nullable=True), sa.Column("current_tread_mm", sa.Numeric(6, 2), nullable=True), sa.Column("fitted_at", sa.DateTime(timezone=True), nullable=True), sa.Column("removed_at", sa.DateTime(timezone=True), nullable=True), sa.ForeignKeyConstraint(["branch_id"], ["branches.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["vehicle_id"], ["vehicles.id"], ondelete="SET NULL"), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("branch_id", "serial_number", name="uq_tyre_branch_serial"))
    op.create_table("driver_credentials", sa.Column("id", UUID, nullable=False), sa.Column("branch_id", UUID, nullable=False), sa.Column("driver_id", UUID, nullable=False), sa.Column("credential_type", sa.String(100), nullable=False), sa.Column("reference", sa.String(160), nullable=True), sa.Column("issue_date", sa.Date(), nullable=True), sa.Column("expiry_date", sa.Date(), nullable=True), sa.Column("notes", sa.Text(), nullable=True), sa.ForeignKeyConstraint(["branch_id"], ["branches.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["driver_id"], ["drivers.id"], ondelete="CASCADE"), sa.PrimaryKeyConstraint("id"))
    op.create_table("insurance_claims", sa.Column("id", UUID, nullable=False), sa.Column("branch_id", UUID, nullable=False), sa.Column("vehicle_id", UUID, nullable=False), sa.Column("accident_id", UUID, nullable=True), sa.Column("insurer", sa.String(160), nullable=True), sa.Column("claim_number", sa.String(160), nullable=True), sa.Column("police_reference", sa.String(160), nullable=True), sa.Column("claim_amount", sa.Numeric(14, 2), nullable=True), sa.Column("excess_amount", sa.Numeric(14, 2), nullable=True), sa.Column("status", sa.String(40), nullable=False), sa.Column("notes", sa.Text(), nullable=True), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True), sa.ForeignKeyConstraint(["branch_id"], ["branches.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["vehicle_id"], ["vehicles.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["accident_id"], ["accident_records.id"], ondelete="SET NULL"), sa.PrimaryKeyConstraint("id"))
    op.create_table("telematics_events", sa.Column("id", UUID, nullable=False), sa.Column("branch_id", UUID, nullable=False), sa.Column("vehicle_id", UUID, nullable=False), sa.Column("provider", sa.String(100), nullable=False), sa.Column("event_type", sa.String(80), nullable=False), sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False), sa.Column("latitude", sa.Numeric(10, 7), nullable=True), sa.Column("longitude", sa.Numeric(10, 7), nullable=True), sa.Column("odometer_km", sa.Integer(), nullable=True), sa.Column("speed_kph", sa.Numeric(8, 2), nullable=True), sa.Column("payload_json", sa.Text(), nullable=True), sa.ForeignKeyConstraint(["branch_id"], ["branches.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["vehicle_id"], ["vehicles.id"], ondelete="CASCADE"), sa.PrimaryKeyConstraint("id"))
    op.create_table("approval_requests", sa.Column("id", UUID, nullable=False), sa.Column("branch_id", UUID, nullable=False), sa.Column("workflow_key", sa.String(100), nullable=False), sa.Column("entity_type", sa.String(100), nullable=False), sa.Column("entity_id", UUID, nullable=False), sa.Column("requested_by_profile_id", UUID, nullable=True), sa.Column("status", sa.String(40), nullable=False), sa.Column("amount", sa.Numeric(14, 2), nullable=True), sa.Column("reason", sa.Text(), nullable=True), sa.Column("decided_by_profile_id", UUID, nullable=True), sa.Column("decision_note", sa.Text(), nullable=True), sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False), sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True), sa.ForeignKeyConstraint(["branch_id"], ["branches.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["requested_by_profile_id"], ["profiles.id"], ondelete="SET NULL"), sa.ForeignKeyConstraint(["decided_by_profile_id"], ["profiles.id"], ondelete="SET NULL"), sa.PrimaryKeyConstraint("id"))
    op.create_table("audit_events", sa.Column("id", UUID, nullable=False), sa.Column("branch_id", UUID, nullable=True), sa.Column("actor_profile_id", UUID, nullable=True), sa.Column("action", sa.String(120), nullable=False), sa.Column("entity_type", sa.String(100), nullable=False), sa.Column("entity_id", sa.String(120), nullable=True), sa.Column("detail_json", sa.Text(), nullable=True), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["branch_id"], ["branches.id"], ondelete="SET NULL"), sa.ForeignKeyConstraint(["actor_profile_id"], ["profiles.id"], ondelete="SET NULL"), sa.PrimaryKeyConstraint("id"))
    op.create_table("branch_fleet_budgets", sa.Column("id", UUID, nullable=False), sa.Column("branch_id", UUID, nullable=False), sa.Column("year", sa.Integer(), nullable=False), sa.Column("month", sa.Integer(), nullable=False), sa.Column("budget_amount", sa.Numeric(14, 2), nullable=False), sa.Column("notes", sa.Text(), nullable=True), sa.ForeignKeyConstraint(["branch_id"], ["branches.id"], ondelete="CASCADE"), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("branch_id", "year", "month", name="uq_branch_fleet_budget_period"))
    op.create_table("workshop_job_cards", sa.Column("id", UUID, nullable=False), sa.Column("branch_id", UUID, nullable=False), sa.Column("vehicle_id", UUID, nullable=False), sa.Column("maintenance_work_order_id", UUID, nullable=True), sa.Column("technician_id", UUID, nullable=True), sa.Column("bay_id", UUID, nullable=True), sa.Column("external_supplier_id", UUID, nullable=True), sa.Column("status", sa.String(40), nullable=False), sa.Column("priority", sa.String(30), nullable=False), sa.Column("complaint", sa.Text(), nullable=False), sa.Column("diagnosis", sa.Text(), nullable=True), sa.Column("work_performed", sa.Text(), nullable=True), sa.Column("expected_release_at", sa.DateTime(timezone=True), nullable=True), sa.Column("labour_hours", sa.Numeric(10, 2), nullable=True), sa.Column("labour_cost", sa.Numeric(14, 2), nullable=True), sa.Column("external_quote", sa.Numeric(14, 2), nullable=True), sa.Column("external_cost", sa.Numeric(14, 2), nullable=True), sa.Column("service_type", sa.String(100), nullable=True), sa.Column("service_mileage", sa.Integer(), nullable=True), sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False), sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True), sa.ForeignKeyConstraint(["branch_id"], ["branches.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["vehicle_id"], ["vehicles.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["maintenance_work_order_id"], ["maintenance_work_orders.id"], ondelete="SET NULL"), sa.ForeignKeyConstraint(["technician_id"], ["workshop_technicians.id"], ondelete="SET NULL"), sa.ForeignKeyConstraint(["bay_id"], ["workshop_bays.id"], ondelete="SET NULL"), sa.ForeignKeyConstraint(["external_supplier_id"], ["operations_suppliers.id"], ondelete="SET NULL"), sa.PrimaryKeyConstraint("id"))
    op.create_table("workshop_job_parts", sa.Column("id", UUID, nullable=False), sa.Column("branch_id", UUID, nullable=False), sa.Column("job_id", UUID, nullable=False), sa.Column("inventory_item_id", UUID, nullable=False), sa.Column("quantity", sa.Numeric(12, 2), nullable=False), sa.Column("unit_cost", sa.Numeric(14, 2), nullable=True), sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["branch_id"], ["branches.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["job_id"], ["workshop_job_cards.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["inventory_item_id"], ["fleet_inventory_items.id"], ondelete="RESTRICT"), sa.PrimaryKeyConstraint("id"))
    op.create_table("purchase_requisition_items", sa.Column("id", UUID, nullable=False), sa.Column("requisition_id", UUID, nullable=False), sa.Column("inventory_item_id", UUID, nullable=True), sa.Column("description", sa.String(255), nullable=False), sa.Column("quantity", sa.Numeric(12, 2), nullable=False), sa.Column("estimated_unit_cost", sa.Numeric(14, 2), nullable=True), sa.ForeignKeyConstraint(["requisition_id"], ["purchase_requisitions.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["inventory_item_id"], ["fleet_inventory_items.id"], ondelete="SET NULL"), sa.PrimaryKeyConstraint("id"))
    op.create_table("purchase_orders", sa.Column("id", UUID, nullable=False), sa.Column("branch_id", UUID, nullable=False), sa.Column("requisition_id", UUID, nullable=False), sa.Column("supplier_id", UUID, nullable=False), sa.Column("reference", sa.String(80), nullable=False), sa.Column("status", sa.String(40), nullable=False), sa.Column("total_amount", sa.Numeric(14, 2), nullable=False), sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False), sa.Column("expected_at", sa.Date(), nullable=True), sa.ForeignKeyConstraint(["branch_id"], ["branches.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["requisition_id"], ["purchase_requisitions.id"], ondelete="RESTRICT"), sa.ForeignKeyConstraint(["supplier_id"], ["operations_suppliers.id"], ondelete="RESTRICT"), sa.PrimaryKeyConstraint("id"), sa.UniqueConstraint("branch_id", "reference", name="uq_purchase_order_branch_reference"))
    op.create_table("purchase_order_items", sa.Column("id", UUID, nullable=False), sa.Column("purchase_order_id", UUID, nullable=False), sa.Column("inventory_item_id", UUID, nullable=True), sa.Column("description", sa.String(255), nullable=False), sa.Column("quantity", sa.Numeric(12, 2), nullable=False), sa.Column("unit_cost", sa.Numeric(14, 2), nullable=False), sa.Column("received_quantity", sa.Numeric(12, 2), nullable=False), sa.ForeignKeyConstraint(["purchase_order_id"], ["purchase_orders.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["inventory_item_id"], ["fleet_inventory_items.id"], ondelete="SET NULL"), sa.PrimaryKeyConstraint("id"))
    op.create_table("goods_receipts", sa.Column("id", UUID, nullable=False), sa.Column("branch_id", UUID, nullable=False), sa.Column("purchase_order_id", UUID, nullable=False), sa.Column("reference", sa.String(100), nullable=False), sa.Column("received_by_profile_id", UUID, nullable=True), sa.Column("notes", sa.Text(), nullable=True), sa.Column("received_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["branch_id"], ["branches.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["purchase_order_id"], ["purchase_orders.id"], ondelete="RESTRICT"), sa.ForeignKeyConstraint(["received_by_profile_id"], ["profiles.id"], ondelete="SET NULL"), sa.PrimaryKeyConstraint("id"))
    op.create_table("dispatch_requests", sa.Column("id", UUID, nullable=False), sa.Column("branch_id", UUID, nullable=False), sa.Column("requested_by_profile_id", UUID, nullable=True), sa.Column("vehicle_type", sa.String(100), nullable=False), sa.Column("driver_id", UUID, nullable=True), sa.Column("assigned_vehicle_id", UUID, nullable=True), sa.Column("reservation_id", UUID, nullable=True), sa.Column("trip_id", UUID, nullable=True), sa.Column("destination", sa.String(255), nullable=False), sa.Column("purpose", sa.String(255), nullable=False), sa.Column("passenger_count", sa.Integer(), nullable=False), sa.Column("load_description", sa.Text(), nullable=True), sa.Column("start_at", sa.DateTime(timezone=True), nullable=False), sa.Column("end_at", sa.DateTime(timezone=True), nullable=False), sa.Column("status", sa.String(40), nullable=False), sa.Column("approved_by_profile_id", UUID, nullable=True), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.ForeignKeyConstraint(["branch_id"], ["branches.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["requested_by_profile_id"], ["profiles.id"], ondelete="SET NULL"), sa.ForeignKeyConstraint(["driver_id"], ["drivers.id"], ondelete="SET NULL"), sa.ForeignKeyConstraint(["assigned_vehicle_id"], ["vehicles.id"], ondelete="SET NULL"), sa.ForeignKeyConstraint(["reservation_id"], ["vehicle_reservations.id"], ondelete="SET NULL"), sa.ForeignKeyConstraint(["trip_id"], ["trips.id"], ondelete="SET NULL"), sa.ForeignKeyConstraint(["approved_by_profile_id"], ["profiles.id"], ondelete="SET NULL"), sa.PrimaryKeyConstraint("id"))


def downgrade() -> None:
    for table in ["dispatch_requests", "goods_receipts", "purchase_order_items", "purchase_orders", "purchase_requisition_items", "workshop_job_parts", "workshop_job_cards", "branch_fleet_budgets", "audit_events", "approval_requests", "telematics_events", "insurance_claims", "driver_credentials", "tyre_assets", "purchase_requisitions", "workshop_bays", "workshop_technicians", "operations_suppliers", "operations_settings"]:
        op.drop_table(table)
