"use client";

import { useEffect, useMemo, useState } from "react";
import { Activity, Search } from "lucide-react";
import { ControlShell } from "@/components/control-shell";
import { EmptyState, LoadingPanel, PageHeader, StatusBadge } from "@/components/ui-kit";

const API = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8006/api/v1";
type Me={email:string;is_platform_owner:boolean}; type Membership={tenant_id:string;tenant_name:string;status:string}; type Audit={id:string;tenant_id?:string|null;actor_user_id?:string|null;action:string;resource_type?:string|null;resource_id?:string|null;metadata?:Record<string,unknown>|null;created_at:string};
async function api(path:string){let r=await fetch(`${API}${path}`,{credentials:"include"});if(r.status===401){const rr=await fetch(`${API}/auth/refresh`,{method:"POST",credentials:"include"});if(rr.ok)r=await fetch(`${API}${path}`,{credentials:"include"})}return r}
export default function AuditPage(){const[me,setMe]=useState<Me|null>(null);const[tenants,setTenants]=useState<Membership[]>([]);const[tenant,setTenant]=useState("");const[rows,setRows]=useState<Audit[]>([]);const[loading,setLoading]=useState(true);const[query,setQuery]=useState("");const[action,setAction]=useState("");const[error,setError]=useState("");
useEffect(()=>{void(async()=>{try{const m=await api("/auth/me");if(!m.ok)throw new Error("Please sign in again");const user=await m.json();setMe(user);if(user.is_platform_owner){const t=await api("/tenants");const data=t.ok?await t.json():[];setTenants(data.map((x:{id:string;name:string;status:string})=>({tenant_id:x.id,tenant_name:x.name,status:x.status})));}else{const t=await api("/me/memberships");setTenants(t.ok?await t.json():[])} }catch(e){setError(e instanceof Error?e.message:"Unable to load audit context")}finally{setLoading(false)}})()},[]);
useEffect(()=>{void(async()=>{if(!me)return;setLoading(true);try{const path=me.is_platform_owner&&!tenant?"/audit/platform?limit=300":tenant?`/tenants/${tenant}/audit?limit=300`:"";if(!path){setRows([]);return}const r=await api(path);if(!r.ok)throw new Error("Audit log unavailable");setRows(await r.json())}catch(e){setError(e instanceof Error?e.message:"Unable to load audit log")}finally{setLoading(false)}})()},[me,tenant]);
const actions=useMemo(()=>Array.from(new Set(rows.map(r=>r.action))).sort(),[rows]);const filtered=useMemo(()=>rows.filter(r=>(!action||r.action===action)&&(!query||JSON.stringify(r).toLowerCase().includes(query.toLowerCase()))),[rows,query,action]);
return <ControlShell title="Audit & activity" subtitle="Searchable operational history" userEmail={me?.email}><div className="space-y-4"><PageHeader eyebrow="Governance" title="Activity timeline" description="Review who changed what, when it happened and which resource was affected." actions={<><select className="input min-w-[210px]" value={tenant} onChange={e=>setTenant(e.target.value)}><option value="">{me?.is_platform_owner?"All platform activity":"Select organization"}</option>{tenants.filter(t=>t.status==="active").map(t=><option key={t.tenant_id} value={t.tenant_id}>{t.tenant_name}</option>)}</select></>}/>{error?<div className="surface-card border-red-200 bg-red-50 p-3 text-xs font-bold text-red-700">{error}</div>:null}<section className="surface-card p-4"><div className="grid gap-3 md:grid-cols-[1fr_260px]"><div className="relative"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-[var(--admin-muted)]"/><input className="input pl-9" placeholder="Search action, resource, actor or metadata" value={query} onChange={e=>setQuery(e.target.value)}/></div><select className="input" value={action} onChange={e=>setAction(e.target.value)}><option value="">All actions</option>{actions.map(a=><option key={a}>{a}</option>)}</select></div></section>{loading?<LoadingPanel label="Loading activity"/>:filtered.length?<section className="surface-card overflow-hidden"><div className="table-wrap"><table><thead><tr><th>Time</th><th>Action</th><th>Resource</th><th>Actor</th><th>Details</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td className="whitespace-nowrap text-[10px] text-[var(--admin-muted)]">{new Date(r.created_at).toLocaleString()}</td><td><StatusBadge state={r.action.includes("delete")||r.action.includes("revoke")?"warn":"neutral"}>{r.action}</StatusBadge></td><td><div className="text-[11px] font-bold">{r.resource_type||"—"}</div><div className="max-w-[220px] truncate font-mono text-[9px] text-[var(--admin-muted)]">{r.resource_id||"—"}</div></td><td className="max-w-[180px] truncate font-mono text-[9px]">{r.actor_user_id||"system"}</td><td><details className="text-[10px]"><summary className="cursor-pointer font-bold text-[var(--admin-pine)]">View metadata</summary><pre className="mt-2 max-w-[420px] overflow-auto rounded-lg bg-[#f5f7f5] p-2 text-[9px]">{JSON.stringify(r.metadata||{},null,2)}</pre></details></td></tr>)}</tbody></table></div></section>:<EmptyState icon={<Activity size={19}/>} title="No matching activity" description="Change your organization, action filter or search phrase to see more events."/>}</div></ControlShell>}
