import Link from "next/link";
import { redirect } from "next/navigation";
import { ApiError, nbrosApi } from "@/lib/backend";

type VehicleRow = { vehicle: { id: string; registration_plate: string; make: string; model: string; vehicle_type: string } };
type Dashboard = { vehicles: VehicleRow[] };
type AdvisorResponse = { mode: "ai" | "deterministic"; question: string; deterministic_actions: string[]; ai_advice: string | null; ai_error: string | null; provider_configured: boolean; guardrail: string; evidence: { branch_summary: { fleet: { readiness: { green: number; orange: number; red: number } }; alerts: { active: number; red: number; orange: number }; service_kit_stock: { available: number; reorder: number; stock_required: number; unknown: number } } } };

export default async function AdvisorPage({ searchParams }: { searchParams: Promise<{ branch?: string; vehicle?: string; question?: string }> }) {
  const params = await searchParams; if (!params.branch) redirect("/fleet");
  const question = params.question?.trim() || "What should Fleet management prioritize now?";
  let dashboard: Dashboard; let advice: AdvisorResponse;
  try { [dashboard, advice] = await Promise.all([nbrosApi<Dashboard>(`/api/v1/fleet/dashboard?branch_id=${params.branch}`), nbrosApi<AdvisorResponse>("/api/v1/fleet/advisor", { method: "POST", body: JSON.stringify({ branch_id: params.branch, vehicle_id: params.vehicle || null, question }) })]); }
  catch (error) { if (error instanceof ApiError && error.status === 401) redirect("/api/auth/login"); throw error; }
  const summary = advice.evidence.branch_summary;
  return <div className="app-shell">
    <aside className="sidebar"><div className="sidebar-brand"><span className="mini-mark">NB</span><strong>NBros</strong></div><nav><span className="nav-section">Fleet</span><Link className="nav-item" href={`/fleet?branch=${params.branch}`}>Dashboard</Link><Link className="nav-item" href={`/fleet/drivers?branch=${params.branch}`}>Drivers</Link><Link className="nav-item" href={`/fleet/requests?branch=${params.branch}`}>Vehicle requests</Link><Link className="nav-item" href={`/fleet/operations?branch=${params.branch}`}>Operations</Link><Link className="nav-item" href={`/fleet/inventory?branch=${params.branch}`}>Service-kit stock</Link><Link className="nav-item" href={`/fleet/reports?branch=${params.branch}`}>Reports</Link><Link className="nav-item active" href={`/fleet/advisor?branch=${params.branch}`}>Fleet advisor</Link><Link className="nav-item" href={`/fleet/settings?branch=${params.branch}`}>Settings</Link></nav></aside>
    <main className="workspace">
      <header className="workspace-header"><div><span className="eyebrow">Decision support</span><h1>Fleet advisor</h1><p className="muted">AI may explain and prioritize evidence, but it cannot override deterministic Fleet rules.</p></div><Link className="ghost-button" href={`/fleet?branch=${params.branch}`}>Back to fleet</Link></header>
      <section className="panel"><form method="get" className="form-grid compact-form"><input type="hidden" name="branch" value={params.branch}/><label>Vehicle scope<select name="vehicle" defaultValue={params.vehicle ?? ""}><option value="">Whole branch</option>{dashboard.vehicles.map((row) => <option key={row.vehicle.id} value={row.vehicle.id}>{row.vehicle.registration_plate} · {row.vehicle.make} {row.vehicle.model}</option>)}</select></label><label className="form-span">Question<textarea name="question" rows={3} defaultValue={question}/></label><div className="form-span"><button className="primary-button">Evaluate Fleet evidence</button></div></form></section>
      <section className="metric-grid"><article className="metric-card"><span>Ready</span><strong>{summary.fleet.readiness.green}</strong><small>deterministic GREEN</small></article><article className="metric-card"><span>Attention</span><strong>{summary.fleet.readiness.orange}</strong><small>deterministic ORANGE</small></article><article className="metric-card danger-card"><span>Blocked</span><strong>{summary.fleet.readiness.red}</strong><small>deterministic RED</small></article><article className="metric-card"><span>Active alerts</span><strong>{summary.alerts.active}</strong><small>{summary.alerts.red} red · {summary.alerts.orange} orange</small></article><article className="metric-card"><span>Kits available</span><strong>{summary.service_kit_stock.available}</strong><small>{summary.service_kit_stock.reorder} need reorder</small></article><article className="metric-card danger-card"><span>Stock required</span><strong>{summary.service_kit_stock.stock_required}</strong><small>service-kit exceptions</small></article></section>
      <section className="two-column"><article className="panel"><div className="panel-heading"><div><span className="eyebrow">Authoritative actions</span><h2>Deterministic priorities</h2></div><span className="count-badge">{advice.deterministic_actions.length}</span></div><div className="history-list">{advice.deterministic_actions.map((action, index) => <div key={index}><strong>Priority {index + 1}</strong><span>{action}</span></div>)}</div></article><article className="panel"><div className="panel-heading"><div><span className="eyebrow">AI advisory</span><h2>{advice.mode === "ai" ? "Model analysis" : "Provider not active"}</h2></div><span className={`status-pill status-${advice.mode === "ai" ? "green" : "orange"}`}>{advice.mode.toUpperCase()}</span></div>{advice.ai_advice ? <p style={{ whiteSpace: "pre-wrap", lineHeight: 1.65 }}>{advice.ai_advice}</p> : <p className="muted">{advice.provider_configured ? advice.ai_error || "The AI provider did not return advice." : "No runtime AI provider is configured. The page still provides deterministic Fleet priorities without inventing AI output."}</p>}<p className="muted"><strong>Guardrail:</strong> {advice.guardrail}</p></article></section>
    </main>
  </div>;
}
