"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { useBuildTrackUi } from "../components/ui";
import styles from "../workforce/workforce.module.css";

type Row = Record<string, unknown>;
type Catalog = { branches: Row[]; sites: Row[]; employees: Row[]; assets: Row[]; awarded_tenders: Row[]; documents: Row[]; permissions: string[] };
type Summary = { total:number; mobilising:number; readiness_pending:number; ready:number; contract_value:string; approved_baseline_budget:string; awarded_tenders_waiting:number };
type Tab = "dashboard"|"convert"|"mobilisation"|"budget"|"programme"|"team"|"assets"|"handover"|"risks"|"audit";
const API="/api/v1";
const tabs:Array<[Tab,string]>=[["dashboard","Dashboard"],["convert","Award → Project"],["mobilisation","Mobilisation"],["budget","Budget baseline"],["programme","Programme"],["team","Team"],["assets","Plant allocation"],["handover","Handover docs"],["risks","Risks"],["audit","Audit"]];
function text(r:Row|null|undefined,k:string){return String(r?.[k]??"")}
function num(r:Row|null|undefined,k:string){return Number(r?.[k]??0)}
function list(v:unknown):Row[]{return Array.isArray(v)?v as Row[]:[]}
function cash(v:unknown){return `M ${Number(v??0).toLocaleString("en-LS",{minimumFractionDigits:2,maximumFractionDigits:2})}`}
function addDays(days:number){const d=new Date();d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)}
function badge(v:string){if(["ready","approved","confirmed","verified","closed","mitigated"].includes(v))return styles.green;if(["mobilising","pending","planned","received","in_progress","draft"].includes(v))return styles.amber;if(["rejected","missing","released","open"].includes(v))return styles.red;return styles.blue}
async function api<T>(path:string,init?:RequestInit):Promise<T>{const response=await fetch(`${API}${path}`,{...init,credentials:"include",headers:{"Content-Type":"application/json",...(init?.headers??{})},cache:"no-store"});if(response.status===401){window.location.href=`/login?returnTo=${encodeURIComponent("/projects")}`;throw new Error("Session expired")};const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(typeof payload?.detail==="string"?payload.detail:JSON.stringify(payload?.detail??payload));return payload as T}
function Field({label,children,wide=false}:{label:string;children:React.ReactNode;wide?:boolean}){return <div className={`${styles.field} ${wide?styles.wide:""}`}><label>{label}</label>{children}</div>}
function Btn({children,variant="",...props}:React.ButtonHTMLAttributes<HTMLButtonElement>&{variant?:"secondary"|"danger"|""}){return <button {...props} className={`${styles.button} ${variant?styles[variant]:""}`}>{children}</button>}
function Data({rows,cols}:{rows:Row[];cols:string[]}){return rows.length?<div className={styles.tableWrap}><table className={styles.table}><thead><tr>{cols.map(c=><th key={c}>{c.replaceAll("_"," ")}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={String(r.id??i)}>{cols.map(c=><td key={c}>{c.includes("amount")||c.includes("budget")||c.includes("cost")?cash(r[c]):String(r[c]??"")}</td>)}</tr>)}</tbody></table></div>:<div className={styles.empty}>No records yet.</div>}

export default function ProjectsPage(){
 const {promptText}=useBuildTrackUi();
 const [initialized,setInitialized]=useState<boolean|null>(null),[catalog,setCatalog]=useState<Catalog>({branches:[],sites:[],employees:[],assets:[],awarded_tenders:[],documents:[],permissions:[]}),[summary,setSummary]=useState<Summary|null>(null),[projects,setProjects]=useState<Row[]>([]),[alerts,setAlerts]=useState<Row[]>([]),[audit,setAudit]=useState<Row[]>([]),[selectedId,setSelectedId]=useState(""),[detail,setDetail]=useState<Row|null>(null),[tab,setTab]=useState<Tab>("dashboard"),[error,setError]=useState(""),[notice,setNotice]=useState(""),[loading,setLoading]=useState(true);
 const [convert,setConvert]=useState({tender_id:"",site_code:"",site_name:"",district:"Maseru",site_location:"",project_manager_employee_id:"",mobilisation_date:addDays(1),contract_start_date:addDays(7),contract_completion_date:addDays(372),contract_reference:"",project_type:"",contingency_budget:"0",contract_document_id:"",notes:""});
 const [budget,setBudget]=useState({cost_code:"",cost_type:"material",description:"",amount:"0",notes:""});
 const [milestone,setMilestone]=useState({code:"",name:"",planned_start:addDays(7),planned_finish:addDays(30),weight_pct:"0",notes:""});
 const [team,setTeam]=useState({employee_id:"",role:"site_manager",allocation_pct:"100",start_date:addDays(1),end_date:"",status:"planned",notes:""});
 const [asset,setAsset]=useState({asset_id:"",site_id:"",planned_from:addDays(1),planned_to:"",purpose:""});
 const [risk,setRisk]=useState({category:"delivery",title:"",description:"",likelihood:"3",impact:"3",owner_employee_id:"",mitigation:"",status:"open",target_date:""});
 const permissions=useMemo(()=>new Set(catalog.permissions),[catalog.permissions]);const can=(p:string)=>permissions.has(p);
 const refresh=useCallback(async()=>{setLoading(true);setError("");try{const s=await api<{initialized:boolean}>("/projects/status");setInitialized(s.initialized);if(!s.initialized)return;const [c,p,sm,a,au]=await Promise.all([api<Catalog>("/projects/catalog"),api<Row[]>("/projects"),api<Summary>("/projects/dashboard/summary"),api<Row[]>("/projects/dashboard/alerts"),api<Row[]>("/projects/audit/events?limit=150")]);setCatalog(c);setProjects(p);setSummary(sm);setAlerts(a);setAudit(au);if(selectedId)setDetail(await api<Row>(`/projects/${selectedId}`).catch(()=>null));}catch(e){setError(e instanceof Error?e.message:"Could not load Project Mobilisation")}finally{setLoading(false)}},[selectedId]);
 useEffect(()=>{void refresh()},[]);
 function success(message:string){setNotice(message);setError("");setTimeout(()=>setNotice(""),3500);void refresh()}
 async function initialize(){try{await api("/projects/bootstrap",{method:"POST"});setInitialized(true);success("Phase 6 Project Mobilisation initialised.")}catch(e){setError(e instanceof Error?e.message:"Could not initialise Phase 6")}}
 async function choose(id:string){setSelectedId(id);setDetail(id?await api<Row>(`/projects/${id}`):null)}
 async function convertTender(e:FormEvent){e.preventDefault();try{await api(`/projects/from-tender/${convert.tender_id}`,{method:"POST",body:JSON.stringify({site_code:convert.site_code||null,site_name:convert.site_name||null,district:convert.district||null,site_location:convert.site_location||null,project_manager_employee_id:convert.project_manager_employee_id?Number(convert.project_manager_employee_id):null,mobilisation_date:convert.mobilisation_date,contract_start_date:convert.contract_start_date,contract_completion_date:convert.contract_completion_date,contract_reference:convert.contract_reference||null,project_type:convert.project_type||null,contingency_budget:Number(convert.contingency_budget),contract_document_id:convert.contract_document_id?Number(convert.contract_document_id):null,notes:convert.notes||null})});success("Awarded tender converted to a controlled project mobilisation baseline.")}catch(e){setError(e instanceof Error?e.message:"Could not mobilise awarded tender")}}
 async function checklist(row:Row,status:string){try{await api(`/projects/mobilisation-items/${num(row,"id")}`,{method:"PUT",body:JSON.stringify({status,owner_employee_id:row.owner_employee_id?Number(row.owner_employee_id):null,due_date:row.due_date||null,document_id:row.document_id?Number(row.document_id):null,notes:row.notes||null})});success("Mobilisation checklist updated.")}catch(e){setError(e instanceof Error?e.message:"Could not update checklist")}}
 async function addBudget(e:FormEvent){e.preventDefault();try{await api(`/projects/${selectedId}/budget-lines`,{method:"POST",body:JSON.stringify({...budget,amount:Number(budget.amount),cost_code:budget.cost_code||null,notes:budget.notes||null})});setBudget({...budget,description:"",amount:"0"});success("Budget line added.")}catch(e){setError(e instanceof Error?e.message:"Could not add budget line")}}
 async function submitBudget(){try{await api(`/projects/${selectedId}/budget/submit`,{method:"POST"});success("Budget baseline submitted for maker/checker approval.")}catch(e){setError(e instanceof Error?e.message:"Could not submit budget baseline")}}
 async function reviseBudget(){try{await api(`/projects/${selectedId}/budget/revise`,{method:"POST"});success("New budget revision created from the approved baseline.")}catch(e){setError(e instanceof Error?e.message:"Could not revise budget")}}
 async function addMilestone(e:FormEvent){e.preventDefault();try{await api(`/projects/${selectedId}/milestones`,{method:"POST",body:JSON.stringify({...milestone,code:milestone.code||null,weight_pct:Number(milestone.weight_pct),notes:milestone.notes||null,predecessor_id:null})});setMilestone({...milestone,name:"",weight_pct:"0"});success("Programme milestone added.")}catch(e){setError(e instanceof Error?e.message:"Could not add milestone")}}
 async function addTeam(e:FormEvent){e.preventDefault();try{await api(`/projects/${selectedId}/team`,{method:"POST",body:JSON.stringify({...team,employee_id:Number(team.employee_id),allocation_pct:Number(team.allocation_pct),end_date:team.end_date||null,notes:team.notes||null})});success("Project team member added.")}catch(e){setError(e instanceof Error?e.message:"Could not add team member")}}
 async function teamStatus(id:number,status:string){try{await api(`/projects/team/${id}/status`,{method:"POST",body:JSON.stringify({status})});success(`Team assignment ${status}.`)}catch(e){setError(e instanceof Error?e.message:"Could not update team")}}
 async function addAsset(e:FormEvent){e.preventDefault();try{await api(`/projects/${selectedId}/assets`,{method:"POST",body:JSON.stringify({asset_id:Number(asset.asset_id),site_id:Number(asset.site_id),planned_from:asset.planned_from,planned_to:asset.planned_to||null,purpose:asset.purpose||null})});success("Fleet/plant allocation planned.")}catch(e){setError(e instanceof Error?e.message:"Could not allocate asset")}}
 async function assetStatus(id:number,status:string){try{await api(`/projects/assets/${id}/status`,{method:"POST",body:JSON.stringify({status})});success(`Fleet/plant allocation ${status}.`)}catch(e){setError(e instanceof Error?e.message:"Could not update asset allocation")}}
 async function verifyDoc(row:Row){const value=await promptText({title:"Verify handover document",description:"Link the controlled document before marking this handover requirement verified.",label:"Controlled document ID",defaultValue:String(row.document_id??""),placeholder:"e.g. 123",required:true,confirmLabel:"Verify document"});if(!value)return;try{await api(`/projects/handover-documents/${num(row,"id")}`,{method:"PUT",body:JSON.stringify({document_id:Number(value),status:"verified",notes:row.notes||null})});success("Handover document verified.")}catch(e){setError(e instanceof Error?e.message:"Could not verify handover document")}}
 async function addRisk(e:FormEvent){e.preventDefault();try{await api(`/projects/${selectedId}/risks`,{method:"POST",body:JSON.stringify({...risk,likelihood:Number(risk.likelihood),impact:Number(risk.impact),owner_employee_id:risk.owner_employee_id?Number(risk.owner_employee_id):null,target_date:risk.target_date||null,description:risk.description||null,mitigation:risk.mitigation||null})});setRisk({...risk,title:"",description:"",mitigation:""});success("Mobilisation risk recorded.")}catch(e){setError(e instanceof Error?e.message:"Could not add risk")}}
 async function requestReadiness(){try{await api(`/projects/${selectedId}/readiness-approval`,{method:"POST"});success("Project readiness submitted for maker/checker approval.")}catch(e){setError(e instanceof Error?e.message:"Project is not ready for approval")}}
 if(loading&&initialized===null)return <main className={styles.page}><div className={styles.loading}><strong>Loading Project Mobilisation…</strong></div></main>;
 if(initialized===false)return <main className={styles.page}><Header/><div className={styles.shell}><section className={styles.initialise}><span className={styles.phase}>Phase 6 · Project Mobilisation</span><h2>Activate the awarded-tender mobilisation control plane.</h2><p>Initialisation adds project permissions and roles, project budget/risk controls, maker/checker workflows and mobilisation governance.</p>{error&&<div className={styles.error}>{error}</div>}<Btn onClick={()=>void initialize()}>Initialise Phase 6</Btn></section></div></main>;
 const mobilisation=list(detail?.mobilisation_items),budgets=list(detail?.budgets),latestBudget=budgets[0],budgetLines=list(latestBudget?.lines),milestones=list(detail?.milestones),teamRows=list(detail?.team),assets=list(detail?.assets),handover=list(detail?.handover_documents),risks=list(detail?.risks),readiness=(detail?.readiness??{}) as Row;
 return <main className={styles.page}><Header/><div className={styles.shell}>{error&&<div className={styles.error}>{error}</div>}{notice&&<div className={styles.notice}>{notice}</div>}<div className={styles.tabs}>{tabs.map(([id,label])=><button key={id} className={tab===id?styles.active:""} onClick={()=>setTab(id)}>{label}</button>)}</div>
 {summary&&<section className={styles.metrics}><div className={styles.metric}><small>Projects</small><strong>{summary.total}</strong><span>{summary.mobilising} mobilising</span></div><div className={styles.metric}><small>Contract value</small><strong>{cash(summary.contract_value)}</strong><span>awarded portfolio</span></div><div className={styles.metric}><small>Approved budget</small><strong>{cash(summary.approved_baseline_budget)}</strong><span>mobilisation baseline</span></div><div className={styles.metric}><small>Ready</small><strong>{summary.ready}</strong><span>{summary.readiness_pending} under approval</span></div><div className={styles.metric}><small>Awards waiting</small><strong>{summary.awarded_tenders_waiting}</strong><span>not yet mobilised</span></div></section>}
 {tab==="dashboard"&&<><section className={styles.hero}><div className={styles.heroCard}><span className={styles.phase}>Phase 6 · Project Mobilisation</span><h2>Awarded work becomes an approved operating baseline.</h2><p>Project site, cost centre, budget, programme, people, plant, risk and controlled handover are completed before Site Operations is opened.</p></div><div className={styles.heroCard}><small>Readiness alerts</small><h2>{alerts.length}</h2><p>mobilisation · checklist · documents · risks</p></div></section><section className={styles.panel}><div className={styles.panelHead}><div><h3>Project mobilisation portfolio</h3><p>Select a project to work across the operational tabs.</p></div><a className={styles.button} href="/api/v1/projects/exports/projects.csv">Export CSV</a></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Project</th><th>Client</th><th>Site</th><th>Status</th><th>Contract</th><th>Budget</th><th>Completion</th></tr></thead><tbody>{projects.map(r=><tr key={num(r,"id")} className={styles.clickable} onClick={()=>void choose(String(r.id))}><td><strong>{text(r,"project_number")}</strong><br/><small>{text(r,"name")}</small></td><td>{text(r,"client_name")}</td><td>{text(r,"primary_site_id")}</td><td><span className={`${styles.badge} ${badge(text(r,"status"))}`}>{text(r,"status")}</span></td><td>{cash(r.contract_amount)}</td><td>{cash(r.baseline_budget)}</td><td>{text(r,"contract_completion_date")}</td></tr>)}</tbody></table></div></section><section className={styles.panel}><div className={styles.panelHead}><div><h3>Mobilisation alerts</h3><p>Resolve blockers before readiness approval.</p></div></div><Data rows={alerts} cols={["severity","project_number","type","message"]}/></section></>}
 {tab==="convert"&&<section className={styles.panel}><div className={styles.panelHead}><div><h3>Awarded tender → project</h3><p>Creates the primary site, project cost centre and draft budget directly from controlled Phase 5 evidence.</p></div></div>{can("projects.mobilise")&&<form className={styles.form} onSubmit={convertTender}><Field label="Awarded tender"><select required value={convert.tender_id} onChange={e=>setConvert({...convert,tender_id:e.target.value})}><option value="">Select award</option>{catalog.awarded_tenders.map(r=><option key={num(r,"id")} value={String(r.id)}>{text(r,"tender_number")} · {text(r,"title")}</option>)}</select></Field><Field label="Project manager"><select value={convert.project_manager_employee_id} onChange={e=>setConvert({...convert,project_manager_employee_id:e.target.value})}><option value="">Tender lead / assign later</option>{catalog.employees.map(r=><option key={num(r,"id")} value={String(r.id)}>{text(r,"employee_number")} · {text(r,"name")}</option>)}</select></Field><Field label="Site code"><input value={convert.site_code} onChange={e=>setConvert({...convert,site_code:e.target.value})} placeholder="Auto from project number"/></Field><Field label="Site name"><input value={convert.site_name} onChange={e=>setConvert({...convert,site_name:e.target.value})} placeholder="Tender title if blank"/></Field><Field label="District"><input value={convert.district} onChange={e=>setConvert({...convert,district:e.target.value})}/></Field><Field label="Location"><input value={convert.site_location} onChange={e=>setConvert({...convert,site_location:e.target.value})}/></Field><Field label="Mobilisation"><input type="date" required value={convert.mobilisation_date} onChange={e=>setConvert({...convert,mobilisation_date:e.target.value})}/></Field><Field label="Contract start"><input type="date" required value={convert.contract_start_date} onChange={e=>setConvert({...convert,contract_start_date:e.target.value})}/></Field><Field label="Completion"><input type="date" required value={convert.contract_completion_date} onChange={e=>setConvert({...convert,contract_completion_date:e.target.value})}/></Field><Field label="Contingency"><input type="number" min="0" step="0.01" value={convert.contingency_budget} onChange={e=>setConvert({...convert,contingency_budget:e.target.value})}/></Field><Field label="Contract reference"><input value={convert.contract_reference} onChange={e=>setConvert({...convert,contract_reference:e.target.value})}/></Field><Field label="Contract document ID"><input type="number" value={convert.contract_document_id} onChange={e=>setConvert({...convert,contract_document_id:e.target.value})}/></Field><Field label="Notes" wide><textarea value={convert.notes} onChange={e=>setConvert({...convert,notes:e.target.value})}/></Field><div className={styles.formActions}><Btn type="submit">Create mobilisation baseline</Btn></div></form>}</section>}
 {tab==="mobilisation"&&<Selected selectedId={selectedId}>{detail&&<><section className={styles.panel}><div className={styles.panelHead}><div><h3>{text(detail,"project_number")} · Readiness</h3><p>{text(detail,"name")}</p></div><Btn onClick={()=>void requestReadiness()} disabled={!can("projects.mobilise")}>Request readiness approval</Btn></div>{list(readiness.blockers).length>0?<div className={styles.warning}>{list(readiness.blockers).map((b,i)=><div key={i}>{String(b)}</div>)}</div>:<div className={styles.notice}>All current readiness gates are satisfied.</div>}<div className={styles.detail}><div><small>Status</small><strong>{text(detail,"status")}</strong></div><div><small>Readiness</small><strong>{text(detail,"readiness_status")}</strong></div><div><small>Manager employee</small><strong>{text(detail,"project_manager_employee_id")||"Unassigned"}</strong></div><div><small>Primary site</small><strong>{text(detail,"primary_site_id")}</strong></div></div></section><section className={styles.panel}><div className={styles.panelHead}><div><h3>Mobilisation checklist</h3><p>Required items must be ready before approval.</p></div></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Category</th><th>Requirement</th><th>Required</th><th>Status</th><th>Action</th></tr></thead><tbody>{mobilisation.map(r=><tr key={num(r,"id")}><td>{text(r,"category")}</td><td>{text(r,"name")}</td><td>{String(Boolean(r.required))}</td><td><span className={`${styles.badge} ${badge(text(r,"status"))}`}>{text(r,"status")}</span></td><td><div className={styles.actions}><button className={`${styles.mini} ${styles.good}`} onClick={()=>void checklist(r,"ready")}>Ready</button>{!Boolean(r.required)&&<button className={styles.mini} onClick={()=>void checklist(r,"not_applicable")}>N/A</button>}<button className={styles.mini} onClick={()=>void checklist(r,"in_progress")}>In progress</button></div></td></tr>)}</tbody></table></div></section></>}</Selected>}
 {tab==="budget"&&<Selected selectedId={selectedId}><section className={styles.panel}><div className={styles.panelHead}><div><h3>Versioned project budget baseline</h3><p>Tender direct costs are imported into v1; any later revision remains auditable.</p></div><div className={styles.actions}><Btn onClick={()=>void submitBudget()} disabled={!can("projects.budget")}>Submit baseline</Btn><Btn variant="secondary" onClick={()=>void reviseBudget()} disabled={!can("projects.budget")}>Create revision</Btn></div></div>{latestBudget&&<div className={styles.detail}><div><small>Version</small><strong>v{text(latestBudget,"version")}</strong></div><div><small>Status</small><strong>{text(latestBudget,"status")}</strong></div><div><small>Total</small><strong>{cash(latestBudget.total_amount)}</strong></div><div><small>Approval</small><strong>{text(latestBudget,"approval_request_id")||"Not submitted"}</strong></div></div>}<Data rows={budgetLines} cols={["cost_code","cost_type","description","amount"]}/></section>{can("projects.budget")&&<section className={styles.panel}><div className={styles.panelHead}><div><h3>Add baseline cost</h3><p>Only the current draft baseline is editable.</p></div></div><form className={styles.form} onSubmit={addBudget}><Field label="Cost code"><input value={budget.cost_code} onChange={e=>setBudget({...budget,cost_code:e.target.value})}/></Field><Field label="Cost type"><select value={budget.cost_type} onChange={e=>setBudget({...budget,cost_type:e.target.value})}>{["material","labour","plant","subcontract","other","overhead","contingency"].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Description" wide><input required value={budget.description} onChange={e=>setBudget({...budget,description:e.target.value})}/></Field><Field label="Amount"><input type="number" min="0.01" step="0.01" required value={budget.amount} onChange={e=>setBudget({...budget,amount:e.target.value})}/></Field><div className={styles.formActions}><Btn type="submit">Add budget line</Btn></div></form></section>}</Selected>}
 {tab==="programme"&&<Selected selectedId={selectedId}><section className={styles.panel}><div className={styles.panelHead}><div><h3>Baseline programme</h3><p>Milestone weights must total 100% before readiness approval.</p></div></div><Data rows={milestones} cols={["code","name","planned_start","planned_finish","weight_pct","status"]}/></section>{can("projects.programme")&&<section className={styles.panel}><form className={styles.form} onSubmit={addMilestone}><Field label="Code"><input value={milestone.code} onChange={e=>setMilestone({...milestone,code:e.target.value})}/></Field><Field label="Milestone" wide><input required value={milestone.name} onChange={e=>setMilestone({...milestone,name:e.target.value})}/></Field><Field label="Weight %"><input type="number" min="0" max="100" step="0.001" value={milestone.weight_pct} onChange={e=>setMilestone({...milestone,weight_pct:e.target.value})}/></Field><Field label="Start"><input type="date" value={milestone.planned_start} onChange={e=>setMilestone({...milestone,planned_start:e.target.value})}/></Field><Field label="Finish"><input type="date" value={milestone.planned_finish} onChange={e=>setMilestone({...milestone,planned_finish:e.target.value})}/></Field><div className={styles.formActions}><Btn type="submit">Add milestone</Btn></div></form></section>}</Selected>}
 {tab==="team"&&<Selected selectedId={selectedId}><section className={styles.panel}><div className={styles.panelHead}><div><h3>Mobilisation team</h3><p>Phase 3 employees are assigned without duplicating employee records.</p></div></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Employee</th><th>Role</th><th>Allocation</th><th>Status</th><th>Action</th></tr></thead><tbody>{teamRows.map(r=><tr key={num(r,"id")}><td>{text(r,"employee_id")}</td><td>{text(r,"role")}</td><td>{text(r,"allocation_pct")}%</td><td>{text(r,"status")}</td><td><div className={styles.actions}><button className={`${styles.mini} ${styles.good}`} onClick={()=>void teamStatus(num(r,"id"),"confirmed")}>Confirm</button><button className={styles.mini} onClick={()=>void teamStatus(num(r,"id"),"released")}>Release</button></div></td></tr>)}</tbody></table></div></section>{can("projects.team")&&<section className={styles.panel}><form className={styles.form} onSubmit={addTeam}><Field label="Employee"><select required value={team.employee_id} onChange={e=>setTeam({...team,employee_id:e.target.value})}><option value="">Select employee</option>{catalog.employees.map(r=><option key={num(r,"id")} value={String(r.id)}>{text(r,"employee_number")} · {text(r,"name")}</option>)}</select></Field><Field label="Role"><input required value={team.role} onChange={e=>setTeam({...team,role:e.target.value})}/></Field><Field label="Allocation %"><input type="number" min="1" max="100" value={team.allocation_pct} onChange={e=>setTeam({...team,allocation_pct:e.target.value})}/></Field><Field label="Status"><select value={team.status} onChange={e=>setTeam({...team,status:e.target.value})}><option>planned</option><option>confirmed</option></select></Field><div className={styles.formActions}><Btn type="submit">Add team member</Btn></div></form></section>}</Selected>}
 {tab==="assets"&&<Selected selectedId={selectedId}><section className={styles.panel}><div className={styles.panelHead}><div><h3>Fleet & plant project allocation</h3><p>Overlapping allocations and unserviceable confirmation are blocked server-side.</p></div></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Asset</th><th>Site</th><th>From</th><th>To</th><th>Status</th><th>Action</th></tr></thead><tbody>{assets.map(r=><tr key={num(r,"id")}><td>{text(r,"asset_id")}</td><td>{text(r,"site_id")}</td><td>{text(r,"planned_from")}</td><td>{text(r,"planned_to")}</td><td>{text(r,"status")}</td><td><div className={styles.actions}><button className={`${styles.mini} ${styles.good}`} onClick={()=>void assetStatus(num(r,"id"),"confirmed")}>Confirm</button><button className={styles.mini} onClick={()=>void assetStatus(num(r,"id"),"released")}>Release</button></div></td></tr>)}</tbody></table></div></section>{can("projects.assets")&&<section className={styles.panel}><form className={styles.form} onSubmit={addAsset}><Field label="Asset"><select required value={asset.asset_id} onChange={e=>setAsset({...asset,asset_id:e.target.value})}><option value="">Select fleet/plant</option>{catalog.assets.map(r=><option key={num(r,"id")} value={String(r.id)}>{text(r,"asset_number")} · {text(r,"name")} · {text(r,"serviceability")}</option>)}</select></Field><Field label="Project site"><select required value={asset.site_id} onChange={e=>setAsset({...asset,site_id:e.target.value})}><option value="">Select site</option>{list(detail?.sites).map(r=><option key={num(r,"site_id")} value={String(r.site_id)}>{String(r.site_id)} · {text(r,"site_role")}</option>)}</select></Field><Field label="From"><input type="date" value={asset.planned_from} onChange={e=>setAsset({...asset,planned_from:e.target.value})}/></Field><Field label="To"><input type="date" value={asset.planned_to} onChange={e=>setAsset({...asset,planned_to:e.target.value})}/></Field><Field label="Purpose" wide><input value={asset.purpose} onChange={e=>setAsset({...asset,purpose:e.target.value})}/></Field><div className={styles.formActions}><Btn type="submit">Plan allocation</Btn></div></form></section>}</Selected>}
 {tab==="handover"&&<Selected selectedId={selectedId}><section className={styles.panel}><div className={styles.panelHead}><div><h3>Controlled project handover documents</h3><p>Required documents must be linked to Phase 1 document control and explicitly verified.</p></div></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Type</th><th>Document</th><th>Required</th><th>Status</th><th>Action</th></tr></thead><tbody>{handover.map(r=><tr key={num(r,"id")}><td>{text(r,"title")}</td><td>{text(r,"document_id")||"—"}</td><td>{String(Boolean(r.required))}</td><td><span className={`${styles.badge} ${badge(text(r,"status"))}`}>{text(r,"status")}</span></td><td><button className={`${styles.mini} ${styles.good}`} onClick={()=>void verifyDoc(r)}>Link & verify</button></td></tr>)}</tbody></table></div></section></Selected>}
 {tab==="risks"&&<Selected selectedId={selectedId}><section className={styles.panel}><div className={styles.panelHead}><div><h3>Mobilisation risk register</h3><p>Likelihood × impact drives the readiness risk gate.</p></div></div><Data rows={risks} cols={["risk_number","category","title","likelihood","impact","rating","status","target_date"]}/></section>{can("projects.manage")&&<section className={styles.panel}><form className={styles.form} onSubmit={addRisk}><Field label="Category"><input value={risk.category} onChange={e=>setRisk({...risk,category:e.target.value})}/></Field><Field label="Risk" wide><input required value={risk.title} onChange={e=>setRisk({...risk,title:e.target.value})}/></Field><Field label="Likelihood"><input type="number" min="1" max="5" value={risk.likelihood} onChange={e=>setRisk({...risk,likelihood:e.target.value})}/></Field><Field label="Impact"><input type="number" min="1" max="5" value={risk.impact} onChange={e=>setRisk({...risk,impact:e.target.value})}/></Field><Field label="Owner"><select value={risk.owner_employee_id} onChange={e=>setRisk({...risk,owner_employee_id:e.target.value})}><option value="">Unassigned</option>{catalog.employees.map(r=><option key={num(r,"id")} value={String(r.id)}>{text(r,"name")}</option>)}</select></Field><Field label="Mitigation" wide><textarea value={risk.mitigation} onChange={e=>setRisk({...risk,mitigation:e.target.value})}/></Field><div className={styles.formActions}><Btn type="submit">Add risk</Btn></div></form></section>}</Selected>}
 {tab==="audit"&&<section className={styles.panel}><div className={styles.panelHead}><div><h3>Project mobilisation audit</h3><p>Authenticated actor, scope, entity and event history.</p></div></div><Data rows={audit} cols={["occurred_at","actor_name","action","entity_type","entity_id","project_id"]}/></section>}
 </div></main>;
}

function Selected({selectedId,children}:{selectedId:string;children:React.ReactNode}){return selectedId?<>{children}</>:<section className={styles.panel}><div className={styles.empty}>Select a project from Dashboard first.</div></section>}
function Header(){return <header className={styles.header}><div className={styles.brand}><div className={styles.brandMark}>P6</div><div><small>BuildTrack Construction Operations</small><h1>Project Mobilisation</h1><p>Award → approved project baseline → Phase 7 Site Operations</p></div></div><div className={styles.headerActions}><Link className={styles.link} href="/projects/control">Project Control</Link><Link className={styles.link} href="/tenders">Tenders</Link><Link className={styles.link} href="/fleet">Fleet & Plant</Link><Link className={styles.link} href="/">Command centre</Link></div></header>}
