from fastapi import APIRouter
from app.api.v1 import security_operations
from app.api.v1 import security_approvals
from app.api.v1 import (
    account_verification,
    application_hosting,
    audit,
    auth,
    backups,
    billing,
    business,
    canonical_pricing,
    commercial_ops_v2,
    corporate_quotations,
    customer_applications,
    deliverability,
    dns,
    dns_phase5,
    domain_onboarding,
    domain_orders,
    domain_mail_health,
    domains,
    edge,
    edge_routes,
    external_webmail,
    external_webmail_counts,
    external_webmail_events,
    external_webmail_known,
    external_webmail_preferences,
    external_webmail_register,
    external_webmail_rich,
    external_webmail_rich_alias,
    external_webmail_smart,
    finance,
    finance_accounting,
    finance_completion,
    finance_control,
    finance_documents,
    finance_governance,
    finance_ops,
    finance_preferences,
    finance_reports,
    hosting,
    hosting_build_logs,
    hosting_build_settings,
    hosting_builds,
    hosting_catalog,
    hosting_database_backups,
    hosting_git_webhooks,
    hosting_metering,
    hosting_operations,
    hosting_project_operations,
    hosting_source_credentials,
    hosting_uploads,
    identity,
    ithute_auth,
    ithute_operating,
    ithute_platform,
    mail_intelligence,
    mail_node_agent,
    mail_node_operations,
    mail_node_provisioning,
    mail_operations,
    mail_routing,
    mailboxes,
    operations,
    payments,
    plan_admin,
    platform_mail,
    platform_mail_attachments,
    platform_mail_forwarding,
    platform_setup,
    professional_email,
    public_hosting,
    reseller_contexts,
    shared_hosting,
    system_owner,
    system_owner_telemetry,
    tenants,
    transactional,
    webmail,
    webmail_compose_tools,
    webmail_connected_accounts,
    webmail_content,
    webmail_drafts_plus,
    webmail_events,
    webmail_migration_center,
    webmail_productivity,
)

api_router = APIRouter()
api_router.include_router(auth.router)
api_router.include_router(ithute_auth.router)
api_router.include_router(ithute_platform.router)
api_router.include_router(ithute_operating.router)
api_router.include_router(system_owner.router)
api_router.include_router(system_owner_telemetry.router)
api_router.include_router(account_verification.router)
api_router.include_router(identity.router)
api_router.include_router(reseller_contexts.router)
api_router.include_router(audit.router)
api_router.include_router(tenants.router)
api_router.include_router(domain_onboarding.router)
api_router.include_router(domains.router)
api_router.include_router(domain_orders.router)
api_router.include_router(domain_mail_health.router)
api_router.include_router(dns.router)
api_router.include_router(dns_phase5.router)
api_router.include_router(edge.router)
api_router.include_router(edge_routes.router)
api_router.include_router(mailboxes.router)
api_router.include_router(mail_node_agent.router)
api_router.include_router(mail_node_operations.router)
api_router.include_router(mail_node_provisioning.router)
api_router.include_router(mail_routing.router)
api_router.include_router(platform_mail.router)
api_router.include_router(platform_mail_attachments.router)
api_router.include_router(platform_mail_forwarding.router)
api_router.include_router(professional_email.router)
api_router.include_router(deliverability.router)
api_router.include_router(mail_intelligence.router)
api_router.include_router(mail_operations.router)
api_router.include_router(backups.router)
api_router.include_router(operations.router)
# Canonical pricing is registered before historical catalogue handlers so
# lifecycle_state is authoritative for public signup/package discovery.
api_router.include_router(canonical_pricing.router)
# Keep one authoritative package-admin contract. It preserves the historical
# commercial/creative fields while adding annual/setup pricing, visibility,
# sorting and large hosting quotas. The hosting catalogue remains authoritative
# for add-on lifecycle endpoints.
api_router.include_router(plan_admin.router)
api_router.include_router(hosting_catalog.router)
api_router.include_router(billing.router)
api_router.include_router(commercial_ops_v2.router)
api_router.include_router(finance.router)
api_router.include_router(finance_documents.router)
api_router.include_router(corporate_quotations.router)
api_router.include_router(finance_ops.router)
api_router.include_router(finance_preferences.router)
api_router.include_router(finance_reports.router)
api_router.include_router(finance_accounting.router)
api_router.include_router(finance_control.router)
api_router.include_router(finance_governance.router)
api_router.include_router(finance_completion.router)
api_router.include_router(finance_completion.portal_router)
api_router.include_router(payments.router)
api_router.include_router(customer_applications.router)
api_router.include_router(business.router)
api_router.include_router(hosting.router)
api_router.include_router(application_hosting.router)
api_router.include_router(hosting_operations.router)
api_router.include_router(hosting_project_operations.router)
api_router.include_router(hosting_database_backups.router)
api_router.include_router(hosting_build_settings.router)
api_router.include_router(hosting_builds.router)
api_router.include_router(hosting_build_logs.router)
api_router.include_router(hosting_git_webhooks.router)
api_router.include_router(hosting_metering.router)
api_router.include_router(shared_hosting.router)
api_router.include_router(hosting_source_credentials.router)
api_router.include_router(hosting_uploads.router)
api_router.include_router(public_hosting.router)
api_router.include_router(platform_setup.router)
api_router.include_router(transactional.router)
api_router.include_router(webmail.router)
api_router.include_router(webmail_connected_accounts.router)
api_router.include_router(webmail_productivity.router)
api_router.include_router(webmail_compose_tools.router)
api_router.include_router(webmail_migration_center.router)
# Exact counts, smart provider setup and rich compose aliases are registered
# before the legacy external router so the newer behavior wins for identical
# paths while the established session/message contract remains unchanged.
api_router.include_router(external_webmail_counts.router)
api_router.include_router(external_webmail_rich_alias.router)
api_router.include_router(external_webmail_smart.router)
api_router.include_router(external_webmail.router)
api_router.include_router(external_webmail_rich.router)
api_router.include_router(external_webmail_known.router)
api_router.include_router(external_webmail_register.router)
api_router.include_router(external_webmail_preferences.router)
api_router.include_router(webmail_drafts_plus.router)
api_router.include_router(webmail_content.router)
api_router.include_router(external_webmail_events.router)
api_router.include_router(webmail_events.router)
api_router.include_router(security_approvals.router)

api_router.include_router(security_operations.router)
