"use client";

import { useCallback, useEffect, useState, type FormEvent, type ReactNode } from "react";
import { AlertTriangle, BookLock, Landmark, RefreshCw, RotateCcw, ShieldCheck, Webhook } from "lucide-react";

import { governanceControlsApi, type ControlRecord, type ControlSummary } from "@/api/governanceControls";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { NativeSelect } from "@/components/ui/native-select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { formatDateTime, titleCase } from "@/lib/format";
import { toast } from "@/utils/toast";

const emptySummary: ControlSummary = {pending_approvals:0,payment_adjustments_attention:0,webhook_dead_letters:0,unmatched_bank_lines:0,open_complaints:0};
const today = () => new Date().toISOString().slice(0,10);

export default function ControlCentrePage(){
  const [summary,setSummary]=useState(emptySummary); const [audit,setAudit]=useState<{valid:boolean;sealed_events:number;broken_event_id:string|null}|null>(null);
  const [adjustments,setAdjustments]=useState<ControlRecord[]>([]); const [periods,setPeriods]=useState<ControlRecord[]>([]); const [lines,setLines]=useState<ControlRecord[]>([]); const [webhooks,setWebhooks]=useState<ControlRecord[]>([]); const [complaints,setComplaints]=useState<ControlRecord[]>([]); const [busy,setBusy]=useState(false);
  const [adjustment,setAdjustment]=useState({payment_id:"",adjustment_type:"refund",amount:"",reason:"",idempotency_key:""});
  const [period,setPeriod]=useState({period_start:today().slice(0,8)+"01",period_end:today()});
  const [line,setLine]=useState({transaction_date:today(),description:"",reference:"",amount:"",currency:"LSL"});
  const load=useCallback(async()=>{setBusy(true);try{const [s,a,p,bs,w,c,integrity]=await Promise.all([governanceControlsApi.summary(),governanceControlsApi.paymentAdjustments(),governanceControlsApi.accountingPeriods(),governanceControlsApi.bankLines(),governanceControlsApi.webhookOutbox(),governanceControlsApi.complaints(),governanceControlsApi.auditIntegrity()]);setSummary(s);setAdjustments(a);setPeriods(p);setLines(bs);setWebhooks(w);setComplaints(c);setAudit(integrity);}catch(error){toast.error(error,{description:"The control centre could not be loaded for this role."});}finally{setBusy(false);}},[]);
  useEffect(()=>{void load();},[load]);
  async function createAdjustment(event:FormEvent){event.preventDefault();setBusy(true);try{await governanceControlsApi.requestPaymentAdjustment({...adjustment,amount:Number(adjustment.amount),idempotency_key:adjustment.idempotency_key||crypto.randomUUID()});toast.success("Adjustment sent for independent approval");setAdjustment({payment_id:"",adjustment_type:"refund",amount:"",reason:"",idempotency_key:""});await load();}catch(error){toast.error(error);}finally{setBusy(false);}}
  async function decide(id:string,action:"approve"|"reject"){const reason=window.prompt(`Reason to ${action} this adjustment`);if(!reason||reason.trim().length<5)return;setBusy(true);try{await governanceControlsApi.decidePaymentAdjustment(id,action,reason.trim());toast.success(`Adjustment ${action}d`);await load();}catch(error){toast.error(error);}finally{setBusy(false);}}
  async function createPeriod(event:FormEvent){event.preventDefault();setBusy(true);try{await governanceControlsApi.createAccountingPeriod(period.period_start,period.period_end);toast.success("Accounting period opened");await load();}catch(error){toast.error(error);}finally{setBusy(false);}}
  async function periodAction(id:string,action:"lock"|"close"){const note=window.prompt(`${titleCase(action)} note`);if(!note||note.trim().length<5)return;setBusy(true);try{await governanceControlsApi.periodAction(id,action,note.trim());toast.success(`Accounting period ${action}ed`);await load();}catch(error){toast.error(error);}finally{setBusy(false);}}
  async function addLine(event:FormEvent){event.preventDefault();setBusy(true);try{await governanceControlsApi.createBankLine({...line,amount:Number(line.amount)});toast.success("Statement line imported");setLine({transaction_date:today(),description:"",reference:"",amount:"",currency:"LSL"});await load();}catch(error){toast.error(error);}finally{setBusy(false);}}
  async function matchLine(id:string){const payment=window.prompt("LoanHub payment ID to match");if(!payment)return;setBusy(true);try{await governanceControlsApi.matchBankLine(id,payment.trim());toast.success("Bank line reconciled");await load();}catch(error){toast.error(error);}finally{setBusy(false);}}
  return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.16em] text-primary">Financial governance</p><h1 className="mt-2 text-3xl font-black">Control & assurance centre</h1><p className="mt-2 max-w-3xl text-sm text-muted-foreground">Independent approvals, locked accounting periods, bank reconciliation, complaint oversight, signed webhook delivery and tamper-evident audit verification.</p></div><Button variant="outline" disabled={busy} onClick={()=>void load()}><RefreshCw className={busy?"h-4 w-4 animate-spin":"h-4 w-4"}/>Refresh</Button></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6">{[["Approvals",summary.pending_approvals],["Adjustments",summary.payment_adjustments_attention],["Unmatched bank",summary.unmatched_bank_lines],["Webhook dead letters",summary.webhook_dead_letters],["Open complaints",summary.open_complaints],[audit?.valid?"Audit chain valid":"Audit attention",audit?.sealed_events??0]].map(([label,value],i)=><Card key={String(label)} className={i===5&&audit&&!audit.valid?"border-destructive":""}><CardContent className="p-5"><p className="text-xs font-bold uppercase text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-black">{value}</p></CardContent></Card>)}</div>
    <Tabs defaultValue="adjustments" className="space-y-5"><TabsList className="grid h-auto grid-cols-2 gap-1 rounded-2xl p-1 md:grid-cols-5"><TabsTrigger value="adjustments">Payments</TabsTrigger><TabsTrigger value="periods">Periods</TabsTrigger><TabsTrigger value="reconciliation">Reconciliation</TabsTrigger><TabsTrigger value="webhooks">Webhooks</TabsTrigger><TabsTrigger value="complaints">Complaints</TabsTrigger></TabsList>
      <TabsContent value="adjustments" className="grid gap-5 xl:grid-cols-[380px_1fr]"><Card><CardHeader><CardTitle>Request an adjustment</CardTitle><CardDescription>The maker can never approve the same request. LoanHub only reverses full allocations to protect the ledger.</CardDescription></CardHeader><CardContent><form className="space-y-3" onSubmit={createAdjustment}><Field label="Payment ID"><Input required value={adjustment.payment_id} onChange={e=>setAdjustment(v=>({...v,payment_id:e.target.value}))}/></Field><Field label="Type"><NativeSelect value={adjustment.adjustment_type} onChange={e=>setAdjustment(v=>({...v,adjustment_type:e.target.value}))}><option value="refund">Refund</option><option value="reversal">Reversal</option><option value="chargeback">Chargeback investigation</option></NativeSelect></Field><Field label="Amount"><Input required type="number" min="0.01" step="0.01" value={adjustment.amount} onChange={e=>setAdjustment(v=>({...v,amount:e.target.value}))}/></Field><Field label="Reason"><Textarea required minLength={10} value={adjustment.reason} onChange={e=>setAdjustment(v=>({...v,reason:e.target.value}))}/></Field><Button className="w-full" disabled={busy}>Send for approval</Button></form></CardContent></Card><RecordList title="Adjustment queue" records={adjustments} actions={item=>item.status==="pending_approval"?<div className="flex gap-2"><Button size="sm" onClick={()=>void decide(item.id,"approve")}>Approve</Button><Button size="sm" variant="outline" onClick={()=>void decide(item.id,"reject")}>Reject</Button></div>:null}/></TabsContent>
      <TabsContent value="periods" className="grid gap-5 xl:grid-cols-[380px_1fr]"><Card><CardHeader><CardTitle>Open accounting period</CardTitle><CardDescription>Once periods exist, postings outside an open period are blocked.</CardDescription></CardHeader><CardContent><form className="space-y-3" onSubmit={createPeriod}><Field label="Start"><Input type="date" required value={period.period_start} onChange={e=>setPeriod(v=>({...v,period_start:e.target.value}))}/></Field><Field label="End"><Input type="date" required value={period.period_end} onChange={e=>setPeriod(v=>({...v,period_end:e.target.value}))}/></Field><Button className="w-full" disabled={busy}><BookLock className="h-4 w-4"/>Open period</Button></form></CardContent></Card><RecordList title="Accounting periods" records={periods} actions={item=><>{item.status==="open"?<Button size="sm" onClick={()=>void periodAction(item.id,"lock")}>Lock</Button>:null}{item.status==="locked"?<Button size="sm" onClick={()=>void periodAction(item.id,"close")}>Close</Button>:null}</>}/></TabsContent>
      <TabsContent value="reconciliation" className="grid gap-5 xl:grid-cols-[380px_1fr]"><Card><CardHeader><CardTitle>Import statement line</CardTitle><CardDescription>Fingerprinting rejects duplicate imports before matching.</CardDescription></CardHeader><CardContent><form className="space-y-3" onSubmit={addLine}><Field label="Date"><Input required type="date" value={line.transaction_date} onChange={e=>setLine(v=>({...v,transaction_date:e.target.value}))}/></Field><Field label="Description"><Input required value={line.description} onChange={e=>setLine(v=>({...v,description:e.target.value}))}/></Field><Field label="Reference"><Input value={line.reference} onChange={e=>setLine(v=>({...v,reference:e.target.value}))}/></Field><Field label="Amount"><Input required type="number" step="0.01" value={line.amount} onChange={e=>setLine(v=>({...v,amount:e.target.value}))}/></Field><Button className="w-full" disabled={busy}><Landmark className="h-4 w-4"/>Import line</Button></form></CardContent></Card><RecordList title="Statement lines" records={lines} actions={item=>item.status==="unmatched"?<Button size="sm" onClick={()=>void matchLine(item.id)}>Match payment</Button>:null}/></TabsContent>
      <TabsContent value="webhooks"><RecordList title="Delivery outbox" records={webhooks} actions={item=>item.status==="dead_letter"||item.status==="delivered"?<Button size="sm" variant="outline" onClick={async()=>{setBusy(true);try{await governanceControlsApi.replayWebhook(item.id);toast.success("Webhook queued for replay");await load();}catch(error){toast.error(error);}finally{setBusy(false);}}}><RotateCcw className="h-4 w-4"/>Replay</Button>:null} emptyIcon={Webhook}/></TabsContent>
      <TabsContent value="complaints"><RecordList title="Complaint service-level queue" records={complaints} emptyIcon={AlertTriangle}/></TabsContent>
    </Tabs></div>;
}

function Field({label,children}:{label:string;children:ReactNode}){return <label className="block space-y-2"><Label>{label}</Label>{children}</label>}
function RecordList({title,records,actions,emptyIcon:Empty=ShieldCheck}:{title:string;records:ControlRecord[];actions?:(item:ControlRecord)=>ReactNode;emptyIcon?:typeof ShieldCheck}){return <Card><CardHeader><CardTitle>{title}</CardTitle><CardDescription>{records.length} current record(s)</CardDescription></CardHeader><CardContent className="space-y-3">{records.length?records.map(item=><div key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border p-4"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><b className="font-mono text-xs">{String(item.reference??item.id)}</b><Badge variant={item.status==="dead_letter"?"destructive":item.status==="completed"||item.status==="delivered"||item.status==="closed"?"default":"outline"}>{titleCase(item.status)}</Badge></div><p className="mt-2 text-sm text-muted-foreground">{String(item.reason??item.description??item.event_type??item.period_start??item.adjustment_type??"")}</p>{item.created_at?<p className="mt-1 text-xs text-muted-foreground">{formatDateTime(item.created_at)}</p>:null}</div>{actions?.(item)}</div>):<div className="rounded-2xl border border-dashed p-10 text-center"><Empty className="mx-auto h-8 w-8 text-muted-foreground"/><p className="mt-3 font-bold">No records require attention</p></div>}</CardContent></Card>}
