import { redirect } from "next/navigation";

import { ApiError, nbrosApi } from "@/lib/backend";
import { createClaimAction, createTelematicsAction, createTyreAction } from "../actions";
import OperationsNav from "../nav";

type Branch = { id: string; code: string; name: string };
type FleetDashboard = { vehicles: Array<{ vehicle: { id: string; registration_plate: string; make: string; model: string; current_mileage: number } }> };
type Tyre = { id: string; serial_number: string; brand: string | null; size: string | null; status: string; vehicle_id: string | null; wheel_position: string | null; current_tread_mm: number | null; purchase_cost: number };
type Claim = { id: string; vehicle_id: string; insurer: string | null; claim_number: string | null; police_reference: string | null; claim_amount: number; excess_amount: number; status: string; created_at: string };
type Event = { id: string; vehicle_id: string; provider: string; event_type: string; occurred_at: string; odometer_km: number | null; speed_kph: number | null; latitude: number | null; longitude: number | null };
type Tco = { total_known_cost: number; vehicles: Array<{ vehicle_id: string; registration_plate: string; known_cost: number; cost_per_recorded_km: number | null; fuel: number; service: number; workshop_labour: number; external_repairs: number; tyres: number; insurance_excess: number }> };
function money(value: number) { return `M ${value.toLocaleString("en-ZA", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`; }

export default async function AssetsPage({ searchParams }: { searchParams: Promise<{ branch?: string }> }) {
  let branches: Branch[];
  try { branches = await nbrosApi<Branch[]>("/api/v1/fleet/branches"); }
  catch (error) { if (error instanceof ApiError && error.status === 401) redirect("/api/auth/login"); throw error; }
  if (!branches.length) redirect("/fleet");
  const params = await searchParams; const selected = branches.find((branch) => branch.id === params.branch) ?? branches[0];
  const [fleet, tyres, claims, events, tco] = await Promise.all([
    nbrosApi<FleetDashboard>(`/api/v1/fleet/dashboard?branch_id=${selected.id}`),
    nbrosApi<Tyre[]>(`/api/v1/operations/tyres?branch_id=${selected.id}`),
    nbrosApi<Claim[]>(`/api/v1/operations/insurance/claims?branch_id=${selected.id}`),
    nbrosApi<Event[]>(`/api/v1/operations/telematics/events?branch_id=${selected.id}`),
    nbrosApi<Tco>(`/api/v1/operations/finance/tco?branch_id=${selected.id}`),
  ]);
  const vehicleNames = new Map(fleet.vehicles.map((row) => [row.vehicle.id, row.vehicle.registration_plate]));

  return <div className="app-shell"><OperationsNav branchId={selected.id} active="assets"/><main className="workspace">
    <header className="workspace-header"><div><span className="eyebrow">Asset Risk & Intelligence</span><h1>{selected.name} lifecycle control</h1></div><form method="get" className="branch-picker"><select name="branch" defaultValue={selected.id}>{branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.name} · {branch.code}</option>)}</select><button className="ghost-button">Switch</button></form></header>
    <section className="metric-grid"><article className="metric-card"><span>Tyres</span><strong>{tyres.length}</strong><small>{tyres.filter((row) => row.status === "fitted").length} fitted to vehicles</small></article><article className="metric-card danger-card"><span>Open claims</span><strong>{claims.filter((row) => !["paid", "closed", "rejected"].includes(row.status)).length}</strong><small>insurance cases in progress</small></article><article className="metric-card"><span>Telematics events</span><strong>{events.length}</strong><small>latest 500 branch events</small></article><article className="metric-card"><span>Known TCO</span><strong>{money(tco.total_known_cost)}</strong><small>recorded operating cost</small></article></section>

    <section className="two-column"><article className="panel"><div className="panel-heading"><div><span className="eyebrow">Tyre lifecycle</span><h2>Register tyre asset</h2></div></div><form action={createTyreAction} className="form-grid"><input type="hidden" name="branch_id" value={selected.id}/><label>Serial number<input name="serial_number" required/></label><label>Brand<input name="brand"/></label><label>Size<input name="size" placeholder="265/65R17"/></label><label>Purchase date<input type="date" name="purchase_date"/></label><label>Purchase cost (M)<input type="number" name="purchase_cost" min="0" step="0.01"/></label><label>Tread depth (mm)<input type="number" name="current_tread_mm" min="0" step="0.1"/></label><div className="form-span"><button className="primary-button">Register tyre</button></div></form></article>
    <article className="panel"><div className="panel-heading"><div><span className="eyebrow">Insurance & claims</span><h2>Open claim</h2></div></div><form action={createClaimAction} className="form-grid"><input type="hidden" name="branch_id" value={selected.id}/><label>Vehicle<select name="vehicle_id" required><option value="">Select vehicle</option>{fleet.vehicles.map((row) => <option key={row.vehicle.id} value={row.vehicle.id}>{row.vehicle.registration_plate} · {row.vehicle.make} {row.vehicle.model}</option>)}</select></label><label>Insurer<input name="insurer"/></label><label>Claim number<input name="claim_number"/></label><label>Police reference<input name="police_reference"/></label><label>Claim amount (M)<input type="number" name="claim_amount" min="0" step="0.01"/></label><label>Excess (M)<input type="number" name="excess_amount" min="0" step="0.01"/></label><label className="form-span">Notes<textarea name="notes" rows={2}/></label><div className="form-span"><button className="primary-button">Open insurance claim</button></div></form></article></section>

    <section className="panel"><div className="panel-heading"><div><span className="eyebrow">Tyre register</span><h2>Tyre assets</h2></div></div>{tyres.length ? <div className="table-wrap"><table><thead><tr><th>Serial</th><th>Brand / size</th><th>Status</th><th>Vehicle</th><th>Position</th><th>Tread</th><th>Cost</th></tr></thead><tbody>{tyres.map((row) => <tr key={row.id}><td><strong>{row.serial_number}</strong></td><td>{row.brand ?? "—"} · {row.size ?? "—"}</td><td>{row.status.replaceAll("_", " ")}</td><td>{row.vehicle_id ? vehicleNames.get(row.vehicle_id) ?? row.vehicle_id : "Stock"}</td><td>{row.wheel_position ?? "—"}</td><td>{row.current_tread_mm == null ? "—" : `${row.current_tread_mm} mm`}</td><td>{money(row.purchase_cost)}</td></tr>)}</tbody></table></div> : <div className="empty-state"><strong>No tyre assets registered.</strong></div>}</section>

    <section className="two-column"><article className="panel"><div className="panel-heading"><div><span className="eyebrow">Vendor-neutral telematics</span><h2>Record / ingest event</h2></div></div><form action={createTelematicsAction} className="form-grid"><input type="hidden" name="branch_id" value={selected.id}/><label>Vehicle<select name="vehicle_id" required><option value="">Select vehicle</option>{fleet.vehicles.map((row) => <option key={row.vehicle.id} value={row.vehicle.id}>{row.vehicle.registration_plate}</option>)}</select></label><label>Provider<input name="provider" defaultValue="manual"/></label><label>Event type<input name="event_type" required placeholder="odometer / speeding / ignition"/></label><label>Occurred at<input type="datetime-local" name="occurred_at" required/></label><label>Odometer km<input type="number" name="odometer_km" min="0"/></label><label>Speed km/h<input type="number" name="speed_kph" min="0" step="0.1"/></label><label>Latitude<input type="number" name="latitude" min="-90" max="90" step="0.000001"/></label><label>Longitude<input type="number" name="longitude" min="-180" max="180" step="0.000001"/></label><div className="form-span"><button className="primary-button">Record event</button></div></form>{events.length ? <div className="alert-list">{events.slice(0,8).map((row) => <div className="alert-row" key={row.id}><strong>{vehicleNames.get(row.vehicle_id) ?? row.vehicle_id} · {row.event_type}</strong><span>{row.provider} · {new Date(row.occurred_at).toLocaleString()}{row.odometer_km == null ? "" : ` · ${row.odometer_km.toLocaleString()} km`}</span></div>)}</div> : null}</article>
    <article className="panel"><div className="panel-heading"><div><span className="eyebrow">Insurance workflow</span><h2>Claims</h2></div></div>{claims.length ? <div className="alert-list">{claims.slice(0,12).map((row) => <div className={`alert-row ${["paid","closed"].includes(row.status) ? "alert-green" : "alert-orange"}`} key={row.id}><strong>{vehicleNames.get(row.vehicle_id) ?? row.vehicle_id} · {row.status.toUpperCase()}</strong><span>{row.insurer ?? "Insurer not recorded"} · Claim {money(row.claim_amount)} · Excess {money(row.excess_amount)}</span></div>)}</div> : <div className="empty-state"><strong>No insurance claims.</strong></div>}</article></section>

    <section className="panel"><div className="panel-heading"><div><span className="eyebrow">Total cost of ownership</span><h2>Vehicle cost intelligence</h2></div></div>{tco.vehicles.length ? <div className="table-wrap"><table><thead><tr><th>Vehicle</th><th>Total</th><th>Fuel</th><th>Service</th><th>Workshop</th><th>External</th><th>Tyres</th><th>Insurance excess</th></tr></thead><tbody>{tco.vehicles.slice().sort((a,b) => b.known_cost-a.known_cost).map((row) => <tr key={row.vehicle_id}><td><strong>{row.registration_plate}</strong></td><td>{money(row.known_cost)}</td><td>{money(row.fuel)}</td><td>{money(row.service)}</td><td>{money(row.workshop_labour)}</td><td>{money(row.external_repairs)}</td><td>{money(row.tyres)}</td><td>{money(row.insurance_excess)}</td></tr>)}</tbody></table></div> : <div className="empty-state"><strong>No Fleet cost data yet.</strong></div>}</section>
  </main></div>;
}
