"use client";

import { useEffect, useState } from "react";
import { CalendarClock, Download, FileSignature, Loader2, RefreshCcw } from "lucide-react";

import { loanPaymentOperationsApi, type LoanPaymentOperationsSummary, type RestructureRequest } from "@/api/loanPaymentOperations";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { formatMoney, titleCase } from "@/lib/format";
import { toast } from "@/utils/toast";

function monthBounds() { const now=new Date(); const start=new Date(now.getFullYear(),now.getMonth(),1); const end=new Date(now.getFullYear(),now.getMonth()+1,0); return {period_start:start.toISOString().slice(0,10),period_end:end.toISOString().slice(0,10)}; }

export default function PaymentOperationsPage() {
  const [summary,setSummary]=useState<LoanPaymentOperationsSummary|null>(null);
  const [requests,setRequests]=useState<RestructureRequest[]>([]);
  const [reminders,setReminders]=useState<any[]>([]);
  const [exports,setExports]=useState<any[]>([]);
  const [busy,setBusy]=useState(false);
  const [selected,setSelected]=useState<RestructureRequest|null>(null);
  const [rate,setRate]=useState("");
  const [agreement,setAgreement]=useState("");

  async function load(){ setBusy(true); try { const [s,r,m,e]=await Promise.all([loanPaymentOperationsApi.summary(),loanPaymentOperationsApi.restructures(),loanPaymentOperationsApi.reminders(),loanPaymentOperationsApi.accountingExports()]); setSummary(s);setRequests(r);setReminders(m);setExports(e); } catch(error){toast.error(error,{description:"Payment operations could not be loaded."});} finally{setBusy(false);} }
  useEffect(()=>{void load();},[]);
  async function runReminders(){setBusy(true);try{const result=await loanPaymentOperationsApi.runReminders();toast.success(`${result.created} repayment reminders prepared`,{description:result.configuration_required?`${result.configuration_required} external messages await approved connector configuration.`:undefined});await load();}catch(error){toast.error(error);}finally{setBusy(false);}}
  async function runMandates(){setBusy(true);try{const result=await loanPaymentOperationsApi.runDueMandates();toast.success(`${result.created} due mandate charges created`,{description:`${result.succeeded} confirmed · ${result.processing} processing · ${result.failed} failed`});await load();}catch(error){toast.error(error,{description:"Automatic collections could not be run."});}finally{setBusy(false);}}
  async function exportAccounting(){setBusy(true);try{await loanPaymentOperationsApi.createAccountingExport({...monthBounds(),format:"json",destination:"manual"});toast.success("Balanced accounting export prepared");await load();}catch(error){toast.error(error);}finally{setBusy(false);}}
  async function approve(){if(!selected||agreement.trim().length<4)return toast.warning("Enter the replacement agreement reference.");setBusy(true);try{await loanPaymentOperationsApi.approveRestructure(selected.id,{approved_rate_percent:rate?Number(rate):null,agreement_reference:agreement.trim()});toast.success("Replacement schedule approved and applied");setSelected(null);setAgreement("");setRate("");await load();}catch(error){toast.error(error,{description:"The loan may have changed; issue a fresh request if necessary."});}finally{setBusy(false);}}

  return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.16em] text-primary">Financial operations</p><h1 className="mt-2 text-3xl font-black">Payment automation & servicing</h1><p className="mt-2 max-w-3xl text-sm text-muted-foreground">Monitor recurring mandates, reminder delivery, controlled restructuring and balanced accounting exports. External transports remain disabled until their approved adapters are configured.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>void runMandates()} disabled={busy}><RefreshCcw className="h-4 w-4"/>Run due mandates</Button><Button variant="outline" onClick={()=>void runReminders()} disabled={busy}><CalendarClock className="h-4 w-4"/>Run reminders</Button><Button onClick={()=>void exportAccounting()} disabled={busy}><Download className="h-4 w-4"/>Export this month</Button></div></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[["Active mandates",summary?.active_mandates??0],["Mandates due",summary?.mandates_due??0],["Reminder attention",summary?.reminders_attention??0],["Restructures pending",summary?.restructures_pending??0],["Accounting exports",summary?.accounting_exports??0]].map(([label,value])=><Card key={String(label)}><CardContent className="p-5"><p className="text-xs font-bold uppercase text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-black">{value}</p></CardContent></Card>)}</div>
    <div className="grid gap-5 xl:grid-cols-[1fr_380px]"><Card><CardHeader><CardTitle>Restructure requests</CardTitle><CardDescription>A balance change invalidates an old preview; LoanHub refuses stale approval automatically.</CardDescription></CardHeader><CardContent className="space-y-3">{requests.length?requests.map(item=><button key={item.id} type="button" onClick={()=>{setSelected(item);setAgreement(`RESTRUCT-${item.id.slice(0,8).toUpperCase()}`);}} className="w-full rounded-2xl border p-4 text-left transition hover:border-primary"><div className="flex flex-wrap justify-between gap-3"><div><b>{item.loan_id}</b><p className="mt-1 text-sm text-muted-foreground">{item.reason}</p></div><Badge variant={item.status==="requested"?"secondary":"outline"}>{titleCase(item.status)}</Badge></div><div className="mt-3 flex gap-4 text-xs"><span>{item.requested_term_months} months</span><span>Proposed {formatMoney(Number(item.preview?.monthly_installment??0))}</span></div></button>):<div className="rounded-2xl border border-dashed p-8 text-center"><FileSignature className="mx-auto h-8 w-8 text-muted-foreground"/><p className="mt-3 font-bold">No restructure requests</p><p className="mt-1 text-sm text-muted-foreground">Borrower requests will appear here with a calculator preview.</p></div>}</CardContent></Card>
      <Card><CardHeader><CardTitle>Approve replacement agreement</CardTitle><CardDescription>Approval supersedes only unpaid instalments and retains the complete original snapshot.</CardDescription></CardHeader><CardContent className="space-y-3">{selected?<><div className="rounded-xl bg-muted p-3 text-sm"><b>{selected.loan_id}</b><p>{selected.requested_term_months} remaining months</p></div><div className="space-y-2"><Label>Approved rate % (blank keeps current)</Label><Input type="number" min="0" max="100" step="0.001" value={rate} onChange={e=>setRate(e.target.value)}/></div><div className="space-y-2"><Label>Replacement agreement reference</Label><Input value={agreement} onChange={e=>setAgreement(e.target.value)}/></div><Button className="w-full" disabled={busy||selected.status!=="requested"} onClick={()=>void approve()}>{busy?<Loader2 className="h-4 w-4 animate-spin"/>:<FileSignature className="h-4 w-4"/>}Approve and apply schedule</Button></>:<p className="text-sm text-muted-foreground">Select a pending request.</p>}</CardContent></Card></div>
    <div className="grid gap-5 xl:grid-cols-2"><Card><CardHeader><CardTitle>Repayment reminders</CardTitle></CardHeader><CardContent className="space-y-2">{reminders.slice(0,12).map(item=><div key={item.id} className="flex justify-between gap-3 rounded-xl border p-3 text-sm"><div><b>{item.reminder_type}</b><p className="text-xs text-muted-foreground">{item.channel} · {item.message}</p></div><Badge variant="outline">{titleCase(item.status)}</Badge></div>)}{!reminders.length?<p className="text-sm text-muted-foreground">No reminder run has produced records yet.</p>:null}</CardContent></Card><Card><CardHeader><CardTitle>Accounting exports</CardTitle></CardHeader><CardContent className="space-y-2">{exports.slice(0,12).map(item=><div key={item.id} className="flex justify-between gap-3 rounded-xl border p-3 text-sm"><div><b>{item.period_start} – {item.period_end}</b><p className="text-xs text-muted-foreground">{item.entry_count} entries · Debit {item.total_debit} · Credit {item.total_credit}</p></div><Badge variant="outline">{titleCase(item.status)}</Badge></div>)}{!exports.length?<p className="text-sm text-muted-foreground">No accounting export has been generated.</p>:null}</CardContent></Card></div>
    {busy?<div className="flex items-center gap-2 text-sm text-muted-foreground"><RefreshCcw className="h-4 w-4 animate-spin"/>Updating operations…</div>:null}
  </div>;
}
