import Link from "next/link";
import { redirect } from "next/navigation";
import { ApiError, nbrosApi } from "@/lib/backend";

type Summary = { window: { from: string; to: string }; fleet: { vehicles: number; drivers: number; available_now: number; readiness: { green: number; orange: number; red: number } }; operations: { active_assignments: number; active_trips: number; active_reservations: number; open_maintenance: number; trips_in_window: number; accidents_in_window: number }; costs: { service_total: number; fuel_total: number; fuel_litres: number; maintenance_jobs_in_window: number }; alerts: { active: number; red: number; orange: number }; service_kit_stock: { available: number; reorder: number; stock_required: number; unknown: number }; vehicle_costs: Array<{ vehicle_id: string; registration_plate: string; service_cost: number; fuel_cost: number; total_cost: number }> };
function money(value: number) { return `M ${value.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`; }

export default async function ReportsPage({ searchParams }: { searchParams: Promise<{ branch?: string; from?: string; to?: string }> }) {
  const params = await searchParams; if (!params.branch) redirect("/fleet");
  const query = new URLSearchParams({ branch_id: params.branch }); if (params.from) query.set("from_date", params.from); if (params.to) query.set("to_date", params.to);
  let summary: Summary;
  try { summary = await nbrosApi<Summary>(`/api/v1/fleet/reports/summary?${query.toString()}`); }
  catch (error) { if (error instanceof ApiError && error.status === 401) redirect("/api/auth/login"); throw error; }
  return <div className="app-shell">
    <aside className="sidebar"><div className="sidebar-brand"><span className="mini-mark">NB</span><strong>NBros</strong></div><nav><span className="nav-section">Fleet</span><Link className="nav-item" href={`/fleet?branch=${params.branch}`}>Dashboard</Link><Link className="nav-item" href={`/fleet/drivers?branch=${params.branch}`}>Drivers</Link><Link className="nav-item" href={`/fleet/requests?branch=${params.branch}`}>Vehicle requests</Link><Link className="nav-item" href={`/fleet/operations?branch=${params.branch}`}>Operations</Link><Link className="nav-item" href={`/fleet/inventory?branch=${params.branch}`}>Service-kit stock</Link><Link className="nav-item active" href={`/fleet/reports?branch=${params.branch}`}>Reports</Link><Link className="nav-item" href={`/fleet/advisor?branch=${params.branch}`}>Fleet advisor</Link><Link className="nav-item" href={`/fleet/settings?branch=${params.branch}`}>Settings</Link></nav></aside>
    <main className="workspace">
      <header className="workspace-header"><div><span className="eyebrow">Fleet Management</span><h1>Fleet reporting</h1><p className="muted">Operational, readiness and cost reporting for this company branch.</p></div><Link className="ghost-button" href={`/fleet?branch=${params.branch}`}>Back to fleet</Link></header>
      <section className="panel"><form method="get" className="form-grid compact-form"><input type="hidden" name="branch" value={params.branch}/><label>From<input name="from" type="date" defaultValue={summary.window.from}/></label><label>To<input name="to" type="date" defaultValue={summary.window.to}/></label><div className="form-span"><button className="primary-button">Apply reporting period</button></div></form></section>
      <section className="metric-grid"><article className="metric-card"><span>Vehicles</span><strong>{summary.fleet.vehicles}</strong><small>{summary.fleet.available_now} available now</small></article><article className="metric-card"><span>Drivers</span><strong>{summary.fleet.drivers}</strong><small>active branch drivers</small></article><article className="metric-card"><span>Trips</span><strong>{summary.operations.trips_in_window}</strong><small>{summary.window.from} → {summary.window.to}</small></article><article className="metric-card"><span>Service cost</span><strong>{money(summary.costs.service_total)}</strong><small>{summary.costs.maintenance_jobs_in_window} maintenance jobs</small></article><article className="metric-card"><span>Fuel cost</span><strong>{money(summary.costs.fuel_total)}</strong><small>{summary.costs.fuel_litres.toFixed(2)} litres</small></article><article className="metric-card danger-card"><span>Accidents</span><strong>{summary.operations.accidents_in_window}</strong><small>recorded in period</small></article></section>
      <section className="two-column"><article className="panel"><div className="panel-heading"><div><span className="eyebrow">Readiness</span><h2>Decision-engine status</h2></div></div><div className="readiness-row"><div><span className="readiness-dot green-dot"/><strong>{summary.fleet.readiness.green}</strong><span>Ready</span></div><div><span className="readiness-dot orange-dot"/><strong>{summary.fleet.readiness.orange}</strong><span>Attention</span></div><div><span className="readiness-dot red-dot"/><strong>{summary.fleet.readiness.red}</strong><span>Blocked</span></div></div></article><article className="panel"><div className="panel-heading"><div><span className="eyebrow">Active alerts</span><h2>{summary.alerts.active}</h2></div></div><p><span className="status-pill status-red">{summary.alerts.red} RED</span> <span className="status-pill status-orange">{summary.alerts.orange} ORANGE</span></p><p className="muted">Persistent alerts remain traceable to the underlying Fleet record.</p></article></section>
      <section className="two-column"><article className="panel"><div className="panel-heading"><div><span className="eyebrow">Current operations</span><h2>Commitments</h2></div></div><div className="readiness-row"><div><strong>{summary.operations.active_assignments}</strong><span>Assignments</span></div><div><strong>{summary.operations.active_trips}</strong><span>Trips</span></div><div><strong>{summary.operations.active_reservations}</strong><span>Reservations</span></div><div><strong>{summary.operations.open_maintenance}</strong><span>Maintenance</span></div></div></article><article className="panel"><div className="panel-heading"><div><span className="eyebrow">Service kits</span><h2>Stock readiness</h2></div></div><p><span className="status-pill status-green">{summary.service_kit_stock.available} AVAILABLE</span> <span className="status-pill status-orange">{summary.service_kit_stock.reorder} REORDER</span> <span className="status-pill status-red">{summary.service_kit_stock.stock_required} STOCK REQUIRED</span></p><Link className="ghost-button" href={`/fleet/inventory?branch=${params.branch}`}>Open service-kit inventory</Link></article></section>
      <section className="panel"><div className="panel-heading"><div><span className="eyebrow">Cost traceability</span><h2>Vehicle operating costs in period</h2></div></div>{summary.vehicle_costs.length === 0 ? <div className="empty-state"><strong>No vehicles.</strong><span>Register branch vehicles to begin Fleet reporting.</span></div> : <div className="table-wrap"><table><thead><tr><th>Vehicle</th><th>Service</th><th>Fuel</th><th>Total</th><th>History</th></tr></thead><tbody>{summary.vehicle_costs.map((row) => <tr key={row.vehicle_id}><td><strong>{row.registration_plate}</strong></td><td>{money(row.service_cost)}</td><td>{money(row.fuel_cost)}</td><td><strong>{money(row.total_cost)}</strong></td><td><Link className="vehicle-link" href={`/fleet/reports/history?branch=${params.branch}&vehicle=${row.vehicle_id}`}>Full history</Link></td></tr>)}</tbody></table></div>}</section>
    </main>
  </div>;
}
