"""add loan company client

Revision ID: 056d9353ae4b
Revises: cdb7c1666d74
Create Date: 2026-06-30 14:51:20.603248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '056d9353ae4b'
down_revision: Union[str, Sequence[str], None] = 'cdb7c1666d74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_company_loan',
    sa.Column('loan_request_id', sa.UUID(), nullable=False),
    sa.Column('loan_offer_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('borrower_id', sa.UUID(), nullable=False),
    sa.Column('loan_reference', sa.String(length=50), nullable=True),
    sa.Column('principal_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total_repayable', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('repayment_period', sa.Integer(), nullable=False),
    sa.Column('installment_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('disbursed_at', sa.DateTime(), nullable=True),
    sa.Column('first_payment_due', sa.Date(), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('amount_paid', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', name='risklevel'), nullable=True),
    sa.Column('is_overdue', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['borrower_id'], ['borrowers.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['loan_companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['loan_offer_id'], ['loan_offers.id'], ),
    sa.ForeignKeyConstraint(['loan_request_id'], ['loan_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_company_loan_loan_reference'), 'client_company_loan', ['loan_reference'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_company_loan_loan_reference'), table_name='client_company_loan')
    op.drop_table('client_company_loan')
    # ### end Alembic commands ###
