"""c


Revision ID: 15c00a058229
Revises: 790ed6fd651d
Create Date: 2026-06-10 20:48:10.036504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15c00a058229'
down_revision: Union[str, Sequence[str], None] = '790ed6fd651d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan_products',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('min_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('min_term_months', sa.Integer(), nullable=False),
    sa.Column('max_term_months', sa.Integer(), nullable=False),
    sa.Column('interest_rate_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('processing_fee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['loan_companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loan_products')
    # ### end Alembic commands ###
