"""initial loan marketplace schema

Revision ID: 4ffb06dcde89
Revises: 3057a2cdb0ea
Create Date: 2026-06-10 20:43:19.514927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ffb06dcde89'
down_revision: Union[str, Sequence[str], None] = '3057a2cdb0ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('borrowers',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('national_id', sa.String(length=50), nullable=True),
    sa.Column('passport_number', sa.String(length=50), nullable=True),
    sa.Column('marital_status', sa.Enum('SINGLE', 'MARRIED', 'DIVORCED', 'WIDOWED', name='maritalstatus'), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('town_or_village', sa.String(length=150), nullable=True),
    sa.Column('physical_address', sa.Text(), nullable=True),
    sa.Column('employment_status', sa.Enum('EMPLOYED', 'SELF_EMPLOYED', 'UNEMPLOYED', 'STUDENT', 'PENSIONER', name='employmentstatus'), nullable=False),
    sa.Column('employer_name', sa.String(length=200), nullable=True),
    sa.Column('job_title', sa.String(length=150), nullable=True),
    sa.Column('monthly_income', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_date', sa.String(length=20), nullable=True),
    sa.Column('has_existing_loans', sa.Boolean(), nullable=True),
    sa.Column('existing_loan_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('consent_to_share_profile', sa.Boolean(), nullable=True),
    sa.Column('consent_to_credit_checks', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('national_id'),
    sa.UniqueConstraint('passport_number'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('borrowers')
    # ### end Alembic commands ###
