"""realtime transparency, employees, performance and system errors

Revision ID: 6c1f9a7e2d40
Revises: 274950a4cd45
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = "6c1f9a7e2d40"
down_revision: Union[str, Sequence[str], None] = "274950a4cd45"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Serialize Alembic executions and fail clearly instead of allowing two
    # migration runners to deadlock each other. Application/worker processes
    # must still be stopped while this schema migration runs.
    op.execute("SELECT pg_advisory_xact_lock(62106420260715)")
    op.execute("SET LOCAL lock_timeout = '60s'")
    op.execute("SET LOCAL statement_timeout = '20min'")
    # Defensive schema hardening. Earlier local migration attempts may have
    # recorded empty or over-broad revisions. These statements are safe when
    # the desired types/constraints already exist and make the upgrade reliable
    # from either database state.
    op.execute(
        "ALTER TABLE payment_transactions "
        "ALTER COLUMN idempotency_key TYPE VARCHAR(255)"
    )
    op.execute(
        "ALTER TABLE payment_transactions "
        "ALTER COLUMN provider_payload TYPE JSONB "
        "USING provider_payload::jsonb"
    )
    op.execute(
        "ALTER TABLE subscription_plans "
        "ALTER COLUMN features TYPE JSONB USING features::jsonb"
    )
    op.execute(
        "ALTER TABLE subscription_plans "
        "ALTER COLUMN limits TYPE JSONB USING limits::jsonb"
    )
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM pg_index i
                JOIN pg_class t ON t.oid = i.indrelid
                JOIN pg_namespace n ON n.oid = t.relnamespace
                WHERE n.nspname = current_schema()
                  AND t.relname = 'subscription_plans'
                  AND i.indisunique
                  AND pg_get_indexdef(i.indexrelid)
                      ~ '\\(\\s*code\\s*\\)'
            ) THEN
                CREATE UNIQUE INDEX uq_subscription_plans_code_realtime
                ON subscription_plans (code);
            END IF;
        END $$;
        """
    )

    op.execute(
        "UPDATE notifications SET notification_type = 'SYSTEM' "
        "WHERE notification_type IS NULL"
    )
    op.execute(
        "UPDATE notifications SET is_read = FALSE WHERE is_read IS NULL"
    )
    op.alter_column(
        "notifications",
        "notification_type",
        existing_type=postgresql.ENUM(
            "LOAN_REQUEST",
            "ACCESS_REQUEST",
            "OFFER",
            "SYSTEM",
            name="notificationtype",
            create_type=False,
        ),
        nullable=False,
    )
    op.alter_column(
        "notifications",
        "is_read",
        existing_type=sa.Boolean(),
        nullable=False,
    )

    # Stable cascade semantics for tenant membership and durable notification
    # references. DROP IF EXISTS also supports databases that applied the old
    # autogenerated migration before this corrected package.
    op.execute(
        "ALTER TABLE company_staff DROP CONSTRAINT IF EXISTS "
        "company_staff_company_id_fkey"
    )
    op.execute(
        "ALTER TABLE company_staff DROP CONSTRAINT IF EXISTS "
        "fk_company_staff_company"
    )
    op.create_foreign_key(
        "fk_company_staff_company",
        "company_staff",
        "loan_companies",
        ["company_id"],
        ["id"],
        ondelete="CASCADE",
    )

    op.execute(
        "ALTER TABLE notifications DROP CONSTRAINT IF EXISTS "
        "notifications_user_id_fkey"
    )
    op.execute(
        "ALTER TABLE notifications DROP CONSTRAINT IF EXISTS "
        "fk_notifications_user"
    )
    op.create_foreign_key(
        "fk_notifications_user",
        "notifications",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )

    for constraint_name, column_name, target_table in [
        (
            "notifications_related_loan_request_id_fkey",
            "related_loan_request_id",
            "loan_requests",
        ),
        (
            "notifications_related_offer_id_fkey",
            "related_offer_id",
            "loan_offers",
        ),
    ]:
        op.execute(
            f"ALTER TABLE notifications DROP CONSTRAINT IF EXISTS {constraint_name}"
        )
        op.create_foreign_key(
            constraint_name,
            "notifications",
            target_table,
            [column_name],
            ["id"],
            ondelete="SET NULL",
        )

    # PostgreSQL 16 supports ADD VALUE inside a transaction. Keeping these
    # statements in the Alembic transaction makes the whole revision atomic.
    # The new values are not used until after the migration commits.
    op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'HR_MANAGER'")
    op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'PERFORMANCE_MANAGER'")
    op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'RISK_MANAGER'")
    op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'IT_SUPPORT'")
    op.execute("ALTER TYPE notificationtype ADD VALUE IF NOT EXISTS 'PAYMENT'")
    op.execute("ALTER TYPE notificationtype ADD VALUE IF NOT EXISTS 'SUBSCRIPTION'")

    for column in [
        sa.Column("actor_user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("company_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("branch_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("event_type", sa.String(length=150), server_default="system.event", nullable=False),
        sa.Column("action", sa.String(length=40), server_default="view", nullable=False),
        sa.Column("entity_type", sa.String(length=120), nullable=True),
        sa.Column("entity_id", sa.String(length=120), nullable=True),
        sa.Column("action_url", sa.String(length=500), nullable=True),
        sa.Column("icon", sa.String(length=80), nullable=True),
        sa.Column("priority", sa.String(length=30), server_default="normal", nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column("deduplication_key", sa.String(length=255), nullable=True),
        sa.Column("read_at", sa.DateTime(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("archived_at", sa.DateTime(), nullable=True),
    ]:
        op.add_column("notifications", column)

    op.create_foreign_key("fk_notifications_actor_user", "notifications", "users", ["actor_user_id"], ["id"], ondelete="SET NULL")
    op.create_foreign_key("fk_notifications_company", "notifications", "loan_companies", ["company_id"], ["id"], ondelete="SET NULL")
    op.create_foreign_key("fk_notifications_branch", "notifications", "company_branches", ["branch_id"], ["id"], ondelete="SET NULL")
    for name, columns in [
        ("ix_notifications_user_id", ["user_id"]),
        ("ix_notifications_notification_type", ["notification_type"]),
        ("ix_notifications_actor_user_id", ["actor_user_id"]),
        ("ix_notifications_company_id", ["company_id"]),
        ("ix_notifications_branch_id", ["branch_id"]),
        ("ix_notifications_event_type", ["event_type"]),
        ("ix_notifications_entity_type", ["entity_type"]),
        ("ix_notifications_entity_id", ["entity_id"]),
        ("ix_notifications_priority", ["priority"]),
        ("ix_notifications_is_read", ["is_read"]),
        ("ix_notifications_is_archived", ["is_archived"]),
        ("ix_notifications_deduplication_key", ["deduplication_key"]),
    ]:
        op.create_index(name, "notifications", columns, unique=False)

    for column in [
        sa.Column("company_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("branch_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("entity_type", sa.String(length=150), nullable=True),
        sa.Column("actor_role", sa.String(length=80), nullable=True),
        sa.Column("severity", sa.String(length=30), server_default="info", nullable=False),
        sa.Column("status", sa.String(length=30), server_default="success", nullable=False),
        sa.Column("before_data", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column("after_data", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column("changed_fields", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
        sa.Column("event_data", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column("request_id", sa.String(length=100), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
    ]:
        op.add_column("audit_logs", column)
    op.drop_constraint(op.f("audit_logs_user_id_fkey"), "audit_logs", type_="foreignkey")
    op.create_foreign_key("fk_audit_logs_user", "audit_logs", "users", ["user_id"], ["id"], ondelete="SET NULL")
    op.create_foreign_key("fk_audit_logs_company", "audit_logs", "loan_companies", ["company_id"], ["id"], ondelete="SET NULL")
    op.create_foreign_key("fk_audit_logs_branch", "audit_logs", "company_branches", ["branch_id"], ["id"], ondelete="SET NULL")
    for name, columns in [
        ("ix_audit_logs_user_id", ["user_id"]),
        ("ix_audit_logs_table_name", ["table_name"]),
        ("ix_audit_logs_company_id", ["company_id"]),
        ("ix_audit_logs_branch_id", ["branch_id"]),
        ("ix_audit_logs_entity_type", ["entity_type"]),
        ("ix_audit_logs_action", ["action"]),
        ("ix_audit_logs_record_id", ["record_id"]),
        ("ix_audit_logs_severity", ["severity"]),
        ("ix_audit_logs_status", ["status"]),
        ("ix_audit_logs_request_id", ["request_id"]),
    ]:
        op.create_index(name, "audit_logs", columns, unique=False)

    op.create_table(
        "employee_profiles",
        sa.Column("staff_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("company_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("branch_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("reports_to_staff_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("employee_number", sa.String(length=80), nullable=False),
        sa.Column("job_title", sa.String(length=150), nullable=True),
        sa.Column("department", sa.String(length=120), nullable=True),
        sa.Column("employment_type", sa.String(length=50), server_default="full_time", nullable=False),
        sa.Column("employment_status", sa.String(length=50), server_default="active", nullable=False),
        sa.Column("hire_date", sa.Date(), nullable=True),
        sa.Column("probation_end_date", sa.Date(), nullable=True),
        sa.Column("termination_date", sa.Date(), nullable=True),
        sa.Column("base_salary", sa.Numeric(15, 2), nullable=True),
        sa.Column("currency", sa.String(length=8), server_default="LSL", nullable=False),
        sa.Column("skills", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
        sa.Column("target_config", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_manager", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(["staff_id"], ["company_staff.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["company_id"], ["loan_companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["branch_id"], ["company_branches.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["reports_to_staff_id"], ["company_staff.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "employee_number", name="uq_employee_company_number"),
        sa.UniqueConstraint("staff_id", name="uq_employee_staff"),
    )
    for column in ["staff_id", "company_id", "branch_id", "reports_to_staff_id", "department", "employment_status"]:
        op.create_index(f"ix_employee_profiles_{column}", "employee_profiles", [column], unique=False)

    op.create_table(
        "performance_goals",
        sa.Column("employee_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("company_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("branch_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_by_user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=100), server_default="general", nullable=False),
        sa.Column("target_value", sa.Numeric(15, 3), server_default="100", nullable=False),
        sa.Column("current_value", sa.Numeric(15, 3), server_default="0", nullable=False),
        sa.Column("unit", sa.String(length=50), server_default="percent", nullable=False),
        sa.Column("weight", sa.Numeric(6, 3), server_default="1", nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=40), server_default="active", nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(["employee_id"], ["employee_profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["company_id"], ["loan_companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["branch_id"], ["company_branches.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    for column in ["employee_id", "company_id", "branch_id", "category", "status"]:
        op.create_index(f"ix_performance_goals_{column}", "performance_goals", [column], unique=False)

    op.create_table(
        "performance_reviews",
        sa.Column("employee_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("reviewer_staff_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("company_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("branch_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("overall_score", sa.Numeric(6, 2), nullable=False),
        sa.Column("rating", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=40), server_default="completed", nullable=False),
        sa.Column("strengths", sa.Text(), nullable=True),
        sa.Column("improvements", sa.Text(), nullable=True),
        sa.Column("comments", sa.Text(), nullable=True),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column("employee_acknowledged_at", sa.DateTime(), nullable=True),
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(["employee_id"], ["employee_profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["reviewer_staff_id"], ["company_staff.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["company_id"], ["loan_companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["branch_id"], ["company_branches.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    for column in ["employee_id", "reviewer_staff_id", "company_id", "branch_id", "rating", "status"]:
        op.create_index(f"ix_performance_reviews_{column}", "performance_reviews", [column], unique=False)

    op.create_table(
        "system_error_logs",
        sa.Column("request_id", sa.String(length=100), nullable=True),
        sa.Column("fingerprint", sa.String(length=128), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("company_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("branch_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("method", sa.String(length=20), nullable=True),
        sa.Column("path", sa.String(length=500), nullable=False),
        sa.Column("status_code", sa.Integer(), server_default="500", nullable=False),
        sa.Column("error_type", sa.String(length=200), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("stack_trace", sa.Text(), nullable=True),
        sa.Column("severity", sa.String(length=30), server_default="error", nullable=False),
        sa.Column("environment", sa.String(length=50), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
        sa.Column("occurrence_count", sa.Integer(), server_default="1", nullable=False),
        sa.Column("first_seen_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.Column("is_resolved", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("resolved_by_user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("resolution_notes", sa.Text(), nullable=True),
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["company_id"], ["loan_companies.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["branch_id"], ["company_branches.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["resolved_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fingerprint"),
    )
    for column in ["request_id", "fingerprint", "user_id", "company_id", "branch_id", "path", "status_code", "error_type", "severity", "is_resolved"]:
        op.create_index(f"ix_system_error_logs_{column}", "system_error_logs", [column], unique=False)


def downgrade() -> None:
    op.drop_table("system_error_logs")
    op.drop_table("performance_reviews")
    op.drop_table("performance_goals")
    op.drop_table("employee_profiles")

    for name in [
        "ix_audit_logs_request_id", "ix_audit_logs_status", "ix_audit_logs_severity",
        "ix_audit_logs_table_name", "ix_audit_logs_user_id",
        "ix_audit_logs_record_id", "ix_audit_logs_action", "ix_audit_logs_entity_type",
        "ix_audit_logs_branch_id", "ix_audit_logs_company_id",
    ]:
        op.drop_index(name, table_name="audit_logs")
    op.drop_constraint("fk_audit_logs_branch", "audit_logs", type_="foreignkey")
    op.drop_constraint("fk_audit_logs_company", "audit_logs", type_="foreignkey")
    op.drop_constraint("fk_audit_logs_user", "audit_logs", type_="foreignkey")
    op.create_foreign_key(op.f("audit_logs_user_id_fkey"), "audit_logs", "users", ["user_id"], ["id"])
    for column in ["duration_ms", "user_agent", "request_id", "event_data", "changed_fields", "after_data", "before_data", "status", "severity", "actor_role", "entity_type", "branch_id", "company_id"]:
        op.drop_column("audit_logs", column)

    for name in [
        "ix_notifications_deduplication_key", "ix_notifications_is_archived", "ix_notifications_is_read",
        "ix_notifications_notification_type", "ix_notifications_user_id",
        "ix_notifications_priority", "ix_notifications_entity_id", "ix_notifications_entity_type",
        "ix_notifications_event_type", "ix_notifications_branch_id", "ix_notifications_company_id",
        "ix_notifications_actor_user_id",
    ]:
        op.drop_index(name, table_name="notifications")
    op.drop_constraint("fk_notifications_branch", "notifications", type_="foreignkey")
    op.drop_constraint("fk_notifications_company", "notifications", type_="foreignkey")
    op.drop_constraint("fk_notifications_actor_user", "notifications", type_="foreignkey")
    op.drop_constraint("fk_notifications_user", "notifications", type_="foreignkey")
    op.create_foreign_key(
        "notifications_user_id_fkey",
        "notifications",
        "users",
        ["user_id"],
        ["id"],
    )
    op.drop_constraint(
        "notifications_related_loan_request_id_fkey",
        "notifications",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "notifications_related_loan_request_id_fkey",
        "notifications",
        "loan_requests",
        ["related_loan_request_id"],
        ["id"],
    )
    op.drop_constraint(
        "notifications_related_offer_id_fkey",
        "notifications",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "notifications_related_offer_id_fkey",
        "notifications",
        "loan_offers",
        ["related_offer_id"],
        ["id"],
    )
    op.alter_column(
        "notifications",
        "notification_type",
        existing_type=postgresql.ENUM(
            "LOAN_REQUEST",
            "ACCESS_REQUEST",
            "OFFER",
            "SYSTEM",
            name="notificationtype",
            create_type=False,
        ),
        nullable=True,
    )
    op.alter_column(
        "notifications",
        "is_read",
        existing_type=sa.Boolean(),
        nullable=True,
    )
    for column in ["archived_at", "is_archived", "read_at", "deduplication_key", "data", "priority", "icon", "action_url", "entity_id", "entity_type", "action", "event_type", "branch_id", "company_id", "actor_user_id"]:
        op.drop_column("notifications", column)
