"""c


Revision ID: 77031f1f0be4
Revises: db8c1b7032c2
Create Date: 2026-06-10 20:51:05.784860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77031f1f0be4'
down_revision: Union[str, Sequence[str], None] = 'db8c1b7032c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.Enum('LOAN_REQUEST', 'ACCESS_REQUEST', 'OFFER', 'SYSTEM', name='notificationtype'), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('related_loan_request_id', sa.UUID(), nullable=True),
    sa.Column('related_offer_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['related_loan_request_id'], ['loan_requests.id'], ),
    sa.ForeignKeyConstraint(['related_offer_id'], ['loan_offers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    # ### end Alembic commands ###
