"""c


Revision ID: 790ed6fd651d
Revises: 96e6e94f2ba7
Create Date: 2026-06-10 20:47:38.351434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '790ed6fd651d'
down_revision: Union[str, Sequence[str], None] = '96e6e94f2ba7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_staff', sa.Column('role', sa.Enum('SUPERADMIN', 'BORROWER', 'COMPANY_ADMIN', 'BRANCH_MANAGER', 'LOAN_OFFICER', name='userrole'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_staff', 'role')
    # ### end Alembic commands ###
