"""c


Revision ID: 8563cd58deb9
Revises: d09fde6cd60e
Create Date: 2026-06-10 20:50:05.729746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8563cd58deb9'
down_revision: Union[str, Sequence[str], None] = 'd09fde6cd60e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('borrower_documents',
    sa.Column('borrower_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('NATIONAL_ID', 'PASSPORT', 'PAYSLIP', 'BANK_STATEMENT', 'PROOF_OF_RESIDENCE', 'EMPLOYMENT_LETTER', 'OTHER', name='documenttype'), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['borrower_id'], ['borrowers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loan_request_documents',
    sa.Column('loan_request_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('NATIONAL_ID', 'PASSPORT', 'PAYSLIP', 'BANK_STATEMENT', 'PROOF_OF_RESIDENCE', 'EMPLOYMENT_LETTER', 'OTHER', name='documenttype'), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['loan_request_id'], ['loan_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loan_request_documents')
    op.drop_table('borrower_documents')
    # ### end Alembic commands ###
