"""c


Revision ID: 920a67b52323
Revises: 464f4729f8a7
Create Date: 2026-06-10 20:50:33.573975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '920a67b52323'
down_revision: Union[str, Sequence[str], None] = '464f4729f8a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan_offers',
    sa.Column('loan_request_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('offered_by_user_id', sa.UUID(), nullable=False),
    sa.Column('approved_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('term_months', sa.Integer(), nullable=False),
    sa.Column('interest_rate_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('processing_fee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('monthly_repayment', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_repayment', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', name='offerstatus'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['company_branches.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['loan_companies.id'], ),
    sa.ForeignKeyConstraint(['loan_request_id'], ['loan_requests.id'], ),
    sa.ForeignKeyConstraint(['offered_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loan_offers')
    # ### end Alembic commands ###
