"""add loan company client

Revision ID: a56c9061c634
Revises: 80d0284b8cd6
Create Date: 2026-06-30 14:39:52.352501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a56c9061c634'
down_revision: Union[str, Sequence[str], None] = '80d0284b8cd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_company_loan', sa.Column('loan_request_id', sa.UUID(), nullable=False))
    op.add_column('client_company_loan', sa.Column('loan_offer_id', sa.UUID(), nullable=False))
    op.alter_column('client_company_loan', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('client_company_loan', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key('client_company_loan_loan_request_id_fkey', 'client_company_loan', 'loan_requests', ['loan_request_id'], ['id'])
    op.create_foreign_key('client_company_loan_loan_offer_id_fkey', 'client_company_loan', 'loan_offers', ['loan_offer_id'], ['id'])
    op.alter_column('loan_offers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('loan_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('loan_requests_selected_offer_id_fkey'), 'loan_requests', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('loan_requests_selected_offer_id_fkey'), 'loan_requests', 'loan_offers', ['selected_offer_id'], ['id'])
    op.alter_column('loan_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('loan_offers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('client_company_loan_loan_offer_id_fkey', 'client_company_loan', type_='foreignkey')
    op.drop_constraint('client_company_loan_loan_request_id_fkey', 'client_company_loan', type_='foreignkey')
    op.alter_column('client_company_loan', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('client_company_loan', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('client_company_loan', 'loan_offer_id')
    op.drop_column('client_company_loan', 'loan_request_id')
    # ### end Alembic commands ###
