"""professional lending v1.1
Revision ID: a7c91d2e4f10
Revises: f1a9c4e7b620
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision='a7c91d2e4f10'; down_revision='f1a9c4e7b620'; branch_labels=None; depends_on=None

def upgrade():
    op.alter_column('client_company_loan','loan_request_id',existing_type=postgresql.UUID(),nullable=True)
    op.alter_column('client_company_loan','loan_offer_id',existing_type=postgresql.UUID(),nullable=True)
    op.add_column('client_company_loan',sa.Column('origination_channel',sa.String(30),nullable=False,server_default='marketplace'))
    op.create_index('ix_client_company_loan_origination_channel','client_company_loan',['origination_channel'])
    op.create_table('direct_loan_applications',sa.Column('id',postgresql.UUID(),primary_key=True),sa.Column('company_id',postgresql.UUID(),sa.ForeignKey('loan_companies.id',ondelete='CASCADE'),nullable=False),sa.Column('branch_id',postgresql.UUID(),sa.ForeignKey('company_branches.id',ondelete='SET NULL')),sa.Column('borrower_id',postgresql.UUID(),sa.ForeignKey('borrowers.id',ondelete='RESTRICT'),nullable=False),sa.Column('product_id',postgresql.UUID(),sa.ForeignKey('loan_products.id',ondelete='SET NULL')),sa.Column('application_reference',sa.String(60),nullable=False,unique=True),sa.Column('channel',sa.String(30),nullable=False,server_default='branch_walk_in'),sa.Column('requested_amount',sa.Numeric(15,2),nullable=False),sa.Column('approved_amount',sa.Numeric(15,2)),sa.Column('interest_rate',sa.Numeric(8,3)),sa.Column('term_count',sa.Integer(),nullable=False),sa.Column('repayment_type',sa.String(30),nullable=False,server_default='monthly'),sa.Column('purpose',sa.Text()),sa.Column('status',sa.String(30),nullable=False,server_default='draft'),sa.Column('affordability_snapshot',postgresql.JSONB(),nullable=False,server_default='{}'),sa.Column('credit_warning',postgresql.JSONB(),nullable=False,server_default='{}'),sa.Column('submitted_at',sa.DateTime()),sa.Column('approved_at',sa.DateTime()),sa.Column('approved_by_user_id',postgresql.UUID(),sa.ForeignKey('users.id',ondelete='SET NULL')),sa.Column('loan_id',postgresql.UUID()),sa.Column('created_at',sa.DateTime(),server_default=sa.func.now(),nullable=False),sa.Column('updated_at',sa.DateTime(),server_default=sa.func.now(),nullable=False),sa.Column('created_by',sa.String(36)),sa.Column('updated_by',sa.String(36)))
    op.add_column('client_company_loan',sa.Column('direct_application_id',postgresql.UUID(),sa.ForeignKey('direct_loan_applications.id',ondelete='SET NULL'),unique=True))
    op.create_foreign_key('fk_direct_application_loan','direct_loan_applications','client_company_loan',['loan_id'],['id'],ondelete='SET NULL')
    def common():
        return [sa.Column('id',postgresql.UUID(),primary_key=True),sa.Column('created_at',sa.DateTime(),server_default=sa.func.now(),nullable=False),sa.Column('updated_at',sa.DateTime(),server_default=sa.func.now(),nullable=False),sa.Column('created_by',sa.String(36)),sa.Column('updated_by',sa.String(36))]
    op.create_table('credit_blacklist',sa.Column('borrower_id',postgresql.UUID(),sa.ForeignKey('borrowers.id',ondelete='CASCADE'),nullable=False,unique=True),sa.Column('reason',sa.Text(),nullable=False),sa.Column('source',sa.String(50),nullable=False),sa.Column('is_active',sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column('blacklisted_at',sa.DateTime(),nullable=False),sa.Column('review_due_at',sa.DateTime()),sa.Column('cleared_at',sa.DateTime()),sa.Column('cleared_by_user_id',postgresql.UUID(),sa.ForeignKey('users.id',ondelete='SET NULL')),*common())
    op.create_table('platform_suggestions',sa.Column('company_id',postgresql.UUID(),sa.ForeignKey('loan_companies.id',ondelete='SET NULL')),sa.Column('branch_id',postgresql.UUID(),sa.ForeignKey('company_branches.id',ondelete='SET NULL')),sa.Column('submitted_by_user_id',postgresql.UUID(),sa.ForeignKey('users.id',ondelete='SET NULL')),sa.Column('reference',sa.String(60),nullable=False,unique=True),sa.Column('title',sa.String(200),nullable=False),sa.Column('category',sa.String(80),nullable=False),sa.Column('description',sa.Text(),nullable=False),sa.Column('priority',sa.String(30),nullable=False),sa.Column('status',sa.String(30),nullable=False),sa.Column('platform_response',sa.Text()),*common())
    op.create_table('offer_wall_posts',sa.Column('company_id',postgresql.UUID(),sa.ForeignKey('loan_companies.id',ondelete='CASCADE'),nullable=False),sa.Column('branch_id',postgresql.UUID(),sa.ForeignKey('company_branches.id',ondelete='SET NULL')),sa.Column('product_id',postgresql.UUID(),sa.ForeignKey('loan_products.id',ondelete='SET NULL')),sa.Column('title',sa.String(200),nullable=False),sa.Column('summary',sa.Text(),nullable=False),sa.Column('terms',postgresql.JSONB(),nullable=False,server_default='{}'),sa.Column('image_file_id',postgresql.UUID(),sa.ForeignKey('managed_files.id',ondelete='SET NULL')),sa.Column('status',sa.String(30),nullable=False),sa.Column('published_at',sa.DateTime()),sa.Column('expires_at',sa.DateTime()),sa.Column('created_by_user_id',postgresql.UUID(),sa.ForeignKey('users.id',ondelete='SET NULL')),*common())
    op.create_table('offer_wall_interests',sa.Column('post_id',postgresql.UUID(),sa.ForeignKey('offer_wall_posts.id',ondelete='CASCADE'),nullable=False),sa.Column('borrower_id',postgresql.UUID(),sa.ForeignKey('borrowers.id',ondelete='CASCADE'),nullable=False),sa.Column('status',sa.String(30),nullable=False),sa.UniqueConstraint('post_id','borrower_id',name='uq_offer_interest_borrower'),*common())
    op.create_table('payment_receipts',sa.Column('payment_id',postgresql.UUID(),sa.ForeignKey('payment_transactions.id',ondelete='CASCADE'),nullable=False,unique=True),sa.Column('company_id',postgresql.UUID(),sa.ForeignKey('loan_companies.id',ondelete='SET NULL')),sa.Column('borrower_id',postgresql.UUID(),sa.ForeignKey('borrowers.id',ondelete='SET NULL')),sa.Column('loan_id',postgresql.UUID(),sa.ForeignKey('client_company_loan.id',ondelete='SET NULL')),sa.Column('receipt_number',sa.String(60),nullable=False,unique=True),sa.Column('balance_before',sa.Numeric(15,2),nullable=False),sa.Column('amount_received',sa.Numeric(15,2),nullable=False),sa.Column('principal_amount',sa.Numeric(15,2),nullable=False),sa.Column('interest_amount',sa.Numeric(15,2),nullable=False),sa.Column('fee_amount',sa.Numeric(15,2),nullable=False),sa.Column('penalty_amount',sa.Numeric(15,2),nullable=False),sa.Column('balance_after',sa.Numeric(15,2),nullable=False),sa.Column('payment_method',sa.String(30),nullable=False),sa.Column('provider_reference',sa.String(180)),sa.Column('pdf_file_id',postgresql.UUID(),sa.ForeignKey('managed_files.id',ondelete='SET NULL')),sa.Column('verification_code',sa.String(80),nullable=False,unique=True),*common())
    op.create_table('print_agents',sa.Column('user_id',postgresql.UUID(),sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False),sa.Column('company_id',postgresql.UUID(),sa.ForeignKey('loan_companies.id',ondelete='CASCADE'),nullable=False),sa.Column('name',sa.String(120),nullable=False),sa.Column('secret_hash',sa.String(255),nullable=False),sa.Column('is_active',sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column('last_seen_at',sa.DateTime()),*common())
    op.create_table('print_jobs',sa.Column('agent_id',postgresql.UUID(),sa.ForeignKey('print_agents.id',ondelete='CASCADE'),nullable=False),sa.Column('requested_by_user_id',postgresql.UUID(),sa.ForeignKey('users.id',ondelete='SET NULL')),sa.Column('file_id',postgresql.UUID(),sa.ForeignKey('managed_files.id',ondelete='RESTRICT'),nullable=False),sa.Column('printer_name',sa.String(200)),sa.Column('copies',sa.Integer(),nullable=False,server_default='1'),sa.Column('status',sa.String(30),nullable=False,server_default='queued'),sa.Column('error_message',sa.Text()),sa.Column('completed_at',sa.DateTime()),*common())

def downgrade():
    for t in ['print_jobs','print_agents','payment_receipts','offer_wall_interests','offer_wall_posts','platform_suggestions','credit_blacklist'] : op.drop_table(t)
    op.drop_constraint('fk_direct_application_loan','direct_loan_applications',type_='foreignkey')
    op.drop_column('client_company_loan','direct_application_id');op.drop_table('direct_loan_applications');op.drop_index('ix_client_company_loan_origination_channel',table_name='client_company_loan');op.drop_column('client_company_loan','origination_channel')
