"""add loan company client

Revision ID: af6a1575fb01
Revises: 056d9353ae4b
Create Date: 2026-06-30 15:06:36.168668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af6a1575fb01'
down_revision: Union[str, Sequence[str], None] = '056d9353ae4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add repayment type and status to the existing company-loan table.

    ``risk_level`` is intentionally not added here: revision 056d9353ae4b
    creates that column together with ``client_company_loan``.  The original
    autogenerated revision attempted to add it a second time, which made a
    clean ``alembic upgrade head`` fail with DuplicateColumn.
    """
    op.add_column(
        'client_company_loan',
        sa.Column(
            'repayment_type',
            sa.Enum('daily', 'weekly', 'monthly', 'custom', name='repaymenttype'),
            nullable=False,
        ),
    )
    op.add_column(
        'client_company_loan',
        sa.Column(
            'status',
            sa.Enum(
                'pending',
                'approved',
                'active',
                'completed',
                'defaulted',
                'rejected',
                name='loanstatus',
            ),
            nullable=True,
        ),
    )


def downgrade() -> None:
    """Return to revision 056d9353ae4b without dropping its risk_level column."""
    op.drop_column('client_company_loan', 'status')
    op.drop_column('client_company_loan', 'repayment_type')
