"""add loan company client

Revision ID: cdb7c1666d74
Revises: a56c9061c634
Create Date: 2026-06-30 14:49:56.085743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cdb7c1666d74'
down_revision: Union[str, Sequence[str], None] = 'a56c9061c634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_company_loan_loan_reference'), table_name='client_company_loan')
    op.drop_table('client_company_loan')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_company_loan',
    sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('borrower_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('loan_reference', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('principal_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('interest_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('total_repayable', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('repayment_type', postgresql.ENUM('daily', 'weekly', 'monthly', 'custom', name='repaymenttype'), autoincrement=False, nullable=False),
    sa.Column('repayment_period', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('installment_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('disbursed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('first_payment_due', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('maturity_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('amount_paid', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('balance', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'approved', 'active', 'completed', 'defaulted', 'rejected', name='loanstatus'), autoincrement=False, nullable=True),
    sa.Column('risk_level', postgresql.ENUM('low', 'medium', 'high', name='risklevel'), autoincrement=False, nullable=True),
    sa.Column('is_overdue', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('approved_by', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('loan_request_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('loan_offer_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['borrower_id'], ['borrowers.id'], name=op.f('client_company_loan_borrower_id_fkey')),
    sa.ForeignKeyConstraint(['company_id'], ['loan_companies.id'], name=op.f('client_company_loan_company_id_fkey')),
    sa.ForeignKeyConstraint(['loan_offer_id'], ['loan_offers.id'], name=op.f('client_company_loan_loan_offer_id_fkey')),
    sa.ForeignKeyConstraint(['loan_request_id'], ['loan_requests.id'], name=op.f('client_company_loan_loan_request_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('client_company_loan_pkey'))
    )
    op.create_index(op.f('ix_client_company_loan_loan_reference'), 'client_company_loan', ['loan_reference'], unique=True)
    # ### end Alembic commands ###
