"""c


Revision ID: db8c1b7032c2
Revises: 920a67b52323
Create Date: 2026-06-10 20:50:50.757460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db8c1b7032c2'
down_revision: Union[str, Sequence[str], None] = '920a67b52323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan_requests', sa.Column('selected_offer_id', sa.UUID(), nullable=True))
    op.create_foreign_key('loan_requests_selected_offer_id_fkey', 'loan_requests', 'loan_offers', ['selected_offer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('loan_requests_selected_offer_id_fkey', 'loan_requests', type_='foreignkey')
    op.drop_column('loan_requests', 'selected_offer_id')
    # ### end Alembic commands ###
